-- FurniScope PostgreSQL Database Schema V2.1
-- Generated from the reviewed MySQL V1 business schema and extended for API/Data Dictionary V2.
-- Target: PostgreSQL 16+; all timestamps are stored as timestamptz in UTC.

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS furniscope;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_code VARCHAR(32) NOT NULL,
  tenant_name VARCHAR(200) NOT NULL,
  display_name VARCHAR(100) DEFAULT NULL,
  industry VARCHAR(64) NOT NULL DEFAULT 'furniture_manufacturing',
  default_timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  default_currency CHAR(3) NOT NULL DEFAULT 'CNY',
  status SMALLINT NOT NULL DEFAULT 1,
  data_retention_days INTEGER NOT NULL DEFAULT 365,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_tenants_code UNIQUE (tenant_code)
);
COMMENT ON TABLE tenants IS 'Enterprise tenants';

CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  user_name VARCHAR(100) NOT NULL,
  phone VARCHAR(32) DEFAULT NULL,
  department VARCHAR(100) DEFAULT NULL,
  job_title VARCHAR(100) DEFAULT NULL,
  role_code VARCHAR(32) NOT NULL DEFAULT 'market_ops',
  locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  timezone VARCHAR(64) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  last_login_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_users_tenant_email UNIQUE (tenant_id, email),
  CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);
COMMENT ON TABLE users IS 'System users';

CREATE TABLE IF NOT EXISTS enterprise_profiles (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  business_models JSONB NOT NULL,
  primary_categories JSONB NOT NULL,
  export_markets JSONB DEFAULT NULL,
  sales_channels JSONB DEFAULT NULL,
  annual_capacity_note VARCHAR(1000) DEFAULT NULL,
  profile_completeness DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  confirmed_by BIGINT DEFAULT NULL,
  confirmed_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_enterprise_profiles_tenant UNIQUE (tenant_id),
  CONSTRAINT fk_enterprise_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_enterprise_profiles_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id)
);
COMMENT ON TABLE enterprise_profiles IS 'Enterprise business profile';

CREATE TABLE IF NOT EXISTS manufacturing_capabilities (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  capability_type VARCHAR(32) NOT NULL,
  capability_code VARCHAR(100) NOT NULL,
  capability_name VARCHAR(200) NOT NULL,
  availability SMALLINT NOT NULL DEFAULT 2,
  min_value DECIMAL(18,4) DEFAULT NULL,
  max_value DECIMAL(18,4) DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  valid_from DATE DEFAULT NULL,
  valid_until DATE DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'confirmed_user',
  confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
  evidence_url VARCHAR(1000) DEFAULT NULL,
  notes VARCHAR(1000) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_capability_tenant_type_code UNIQUE (tenant_id, capability_type, capability_code),
  CONSTRAINT fk_capability_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_capability_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_capability_range CHECK (max_value IS NULL OR min_value IS NULL OR max_value >= min_value),
  CONSTRAINT chk_capability_confidence CHECK (confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE manufacturing_capabilities IS 'Enterprise manufacturing capabilities';

CREATE TABLE IF NOT EXISTS products (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  sku VARCHAR(100) NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  category_code VARCHAR(100) NOT NULL DEFAULT 'sofa',
  sofa_type VARCHAR(32) DEFAULT NULL,
  lifecycle_status VARCHAR(24) NOT NULL DEFAULT 'active',
  analysis_status VARCHAR(24) NOT NULL DEFAULT 'draft',
  description TEXT DEFAULT NULL,
  primary_image_url VARCHAR(1000) DEFAULT NULL,
  image_urls JSONB DEFAULT NULL,
  source_files JSONB DEFAULT NULL,
  factory_price DECIMAL(18,4) DEFAULT NULL,
  factory_price_currency CHAR(3) DEFAULT NULL,
  price_term VARCHAR(16) DEFAULT NULL,
  moq INTEGER DEFAULT NULL,
  moq_unit VARCHAR(32) DEFAULT 'piece',
  lead_time_days INTEGER DEFAULT NULL,
  profile_version INTEGER NOT NULL DEFAULT 1,
  profile_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
  profile_completeness DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  profile_confirmed_by BIGINT DEFAULT NULL,
  profile_confirmed_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_products_tenant_sku UNIQUE (tenant_id, sku),
  CONSTRAINT fk_products_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_products_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_products_confirmer FOREIGN KEY (profile_confirmed_by) REFERENCES users (id),
  CONSTRAINT chk_products_profile_complete CHECK (profile_completeness BETWEEN 0 AND 1)
);
COMMENT ON TABLE products IS 'Enterprise product master';

CREATE TABLE IF NOT EXISTS product_attributes (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  profile_version INTEGER NOT NULL,
  attribute_code VARCHAR(100) NOT NULL,
  attribute_name VARCHAR(100) NOT NULL,
  value_type VARCHAR(16) NOT NULL,
  attribute_value JSONB DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  raw_value VARCHAR(1000) DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_locator JSONB DEFAULT NULL,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  confirmation_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
  is_sensitive BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_product_attr_version_code UNIQUE (product_id, profile_version, attribute_code),
  CONSTRAINT fk_product_attr_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_product_attr_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT chk_product_attr_confidence CHECK (confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE product_attributes IS 'Versioned normalized product attributes';

CREATE TABLE IF NOT EXISTS market_datasets (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  dataset_name VARCHAR(200) NOT NULL,
  version_no INTEGER NOT NULL DEFAULT 1,
  platform VARCHAR(32) NOT NULL,
  market_country CHAR(2) NOT NULL,
  marketplace_code VARCHAR(50) DEFAULT NULL,
  category_code VARCHAR(100) NOT NULL,
  data_start_date DATE DEFAULT NULL,
  data_end_date DATE NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_name VARCHAR(200) NOT NULL,
  authorization_reference VARCHAR(1000) DEFAULT NULL,
  import_file_url VARCHAR(1000) DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'uploaded',
  listing_count INTEGER NOT NULL DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  valid_review_count INTEGER NOT NULL DEFAULT 0,
  quality_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  quality_report JSONB DEFAULT NULL,
  limitations JSONB DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_dataset_tenant_name_version UNIQUE (tenant_id, dataset_name, version_no),
  CONSTRAINT fk_dataset_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_dataset_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_dataset_quality CHECK (quality_score BETWEEN 0 AND 100),
  CONSTRAINT chk_dataset_counts CHECK (valid_review_count <= review_count)
);
COMMENT ON TABLE market_datasets IS 'Versioned market data imports';

CREATE TABLE IF NOT EXISTS competitor_listings (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  dataset_id BIGINT NOT NULL,
  platform_listing_id VARCHAR(200) NOT NULL,
  listing_url VARCHAR(1000) DEFAULT NULL,
  brand VARCHAR(200) DEFAULT NULL,
  seller_name VARCHAR(200) DEFAULT NULL,
  title TEXT NOT NULL,
  description TEXT DEFAULT NULL,
  bullet_points JSONB DEFAULT NULL,
  category_raw VARCHAR(300) DEFAULT NULL,
  category_code VARCHAR(100) NOT NULL,
  image_urls JSONB DEFAULT NULL,
  normalized_attributes JSONB DEFAULT NULL,
  feature_codes JSONB DEFAULT NULL,
  currency CHAR(3) NOT NULL,
  list_price DECIMAL(18,4) DEFAULT NULL,
  sale_price DECIMAL(18,4) NOT NULL,
  coupon_info JSONB DEFAULT NULL,
  rating DECIMAL(3,2) DEFAULT NULL,
  rating_count INTEGER DEFAULT NULL,
  review_count INTEGER DEFAULT NULL,
  rank_value INTEGER DEFAULT NULL,
  rank_category VARCHAR(300) DEFAULT NULL,
  sales_value DECIMAL(18,4) DEFAULT NULL,
  sales_value_type VARCHAR(16) DEFAULT NULL,
  sales_period VARCHAR(16) DEFAULT NULL,
  first_available_at TIMESTAMPTZ(3) DEFAULT NULL,
  availability_status VARCHAR(24) DEFAULT 'unknown',
  observed_at TIMESTAMPTZ(3) NOT NULL,
  raw_payload JSONB DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_listing_dataset_platform_observed UNIQUE (dataset_id, platform_listing_id, observed_at),
  CONSTRAINT fk_listing_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_listing_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT chk_listing_price CHECK (sale_price >= 0),
  CONSTRAINT chk_listing_rating CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
);
COMMENT ON TABLE competitor_listings IS 'Competitor platform listing snapshots';

CREATE TABLE IF NOT EXISTS competitor_reviews (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  dataset_id BIGINT NOT NULL,
  listing_id BIGINT NOT NULL,
  platform_review_id VARCHAR(200) DEFAULT NULL,
  rating DECIMAL(3,2) NOT NULL,
  review_title TEXT DEFAULT NULL,
  body_original TEXT NOT NULL,
  language VARCHAR(16) NOT NULL DEFAULT 'und',
  body_translated_zh TEXT DEFAULT NULL,
  reviewed_at TIMESTAMPTZ(3) DEFAULT NULL,
  verified_purchase SMALLINT NOT NULL DEFAULT 2,
  helpful_votes INTEGER DEFAULT NULL,
  variant_info JSONB DEFAULT NULL,
  is_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
  is_spam BOOLEAN NOT NULL DEFAULT FALSE,
  is_valid BOOLEAN NOT NULL DEFAULT TRUE,
  invalid_reason VARCHAR(64) DEFAULT NULL,
  content_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_review_dataset_hash UNIQUE (dataset_id, content_hash),
  CONSTRAINT fk_review_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_review_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT fk_review_listing FOREIGN KEY (listing_id) REFERENCES competitor_listings (id),
  CONSTRAINT chk_review_rating CHECK (rating BETWEEN 0 AND 5)
);
COMMENT ON TABLE competitor_reviews IS 'Competitor customer reviews';

CREATE TABLE IF NOT EXISTS analysis_tasks (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id BIGINT NOT NULL,
  task_name VARCHAR(200) NOT NULL,
  task_type VARCHAR(32) NOT NULL DEFAULT 'product_market_fit',
  product_id BIGINT NOT NULL,
  product_profile_version INTEGER NOT NULL,
  dataset_id BIGINT NOT NULL,
  target_country CHAR(2) NOT NULL,
  target_platform VARCHAR(32) NOT NULL,
  analysis_currency CHAR(3) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  current_stage VARCHAR(32) NOT NULL DEFAULT 'draft',
  progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  ontology_version VARCHAR(64) NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  prompt_bundle_version VARCHAR(64) NOT NULL,
  analysis_config JSONB DEFAULT NULL,
  sample_listing_count INTEGER NOT NULL DEFAULT 0,
  sample_review_count INTEGER NOT NULL DEFAULT 0,
  started_at TIMESTAMPTZ(3) DEFAULT NULL,
  completed_at TIMESTAMPTZ(3) DEFAULT NULL,
  failure_code VARCHAR(100) DEFAULT NULL,
  failure_message VARCHAR(1000) DEFAULT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_analysis_tasks_uuid UNIQUE (task_uuid),
  CONSTRAINT fk_task_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_task_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_task_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT fk_task_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_task_progress CHECK (progress_percent BETWEEN 0 AND 100)
);
COMMENT ON TABLE analysis_tasks IS 'Market AI analysis tasks';

CREATE TABLE IF NOT EXISTS task_stage_runs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  stage_code VARCHAR(32) NOT NULL,
  attempt_no INTEGER NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  input_ref JSONB NOT NULL,
  output_ref JSONB DEFAULT NULL,
  started_at TIMESTAMPTZ(3) DEFAULT NULL,
  ended_at TIMESTAMPTZ(3) DEFAULT NULL,
  error_code VARCHAR(100) DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  retryable BOOLEAN DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_stage_idempotency UNIQUE (idempotency_key),
  CONSTRAINT uk_stage_task_code_attempt UNIQUE (task_id, stage_code, attempt_no),
  CONSTRAINT fk_stage_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id)
);
COMMENT ON TABLE task_stage_runs IS 'Analysis task workflow stage runs';

CREATE TABLE IF NOT EXISTS ai_model_runs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  stage_run_id BIGINT DEFAULT NULL,
  provider VARCHAR(100) NOT NULL DEFAULT 'aliyun_model_router',
  model_id VARCHAR(200) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  prompt_code VARCHAR(100) DEFAULT NULL,
  prompt_version VARCHAR(64) DEFAULT NULL,
  input_hash CHAR(64) NOT NULL,
  output_schema_version VARCHAR(64) DEFAULT NULL,
  input_tokens INTEGER DEFAULT NULL,
  output_tokens INTEGER DEFAULT NULL,
  image_count INTEGER NOT NULL DEFAULT 0,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  estimated_cost DECIMAL(18,8) DEFAULT NULL,
  cost_unit VARCHAR(16) DEFAULT NULL,
  status VARCHAR(24) NOT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  schema_valid BOOLEAN DEFAULT NULL,
  error_code VARCHAR(100) DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_model_run_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_model_run_stage FOREIGN KEY (stage_run_id) REFERENCES task_stage_runs (id)
);
COMMENT ON TABLE ai_model_runs IS 'AI model invocation logs and cost metrics';

CREATE TABLE IF NOT EXISTS competitor_matches (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  listing_id BIGINT NOT NULL,
  competitor_type VARCHAR(16) NOT NULL DEFAULT 'direct',
  category_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  function_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  style_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  price_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  material_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  scenario_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  overall_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  rerank_score DECIMAL(10,8) DEFAULT NULL,
  match_reasons JSONB NOT NULL,
  review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  review_note VARCHAR(1000) DEFAULT NULL,
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_match_task_listing UNIQUE (task_id, listing_id),
  CONSTRAINT fk_match_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_match_listing FOREIGN KEY (listing_id) REFERENCES competitor_listings (id),
  CONSTRAINT fk_match_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
);
COMMENT ON TABLE competitor_matches IS 'Task-specific competitor matching and human review';

CREATE TABLE IF NOT EXISTS review_aspects (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  review_id BIGINT NOT NULL,
  aspect_index INTEGER NOT NULL,
  taxonomy_code VARCHAR(150) NOT NULL,
  product_attribute_code VARCHAR(100) DEFAULT NULL,
  opinion_text VARCHAR(1000) NOT NULL,
  sentiment VARCHAR(16) NOT NULL,
  severity SMALLINT DEFAULT NULL,
  user_profile_codes JSONB DEFAULT NULL,
  usage_scenario_codes JSONB DEFAULT NULL,
  purchase_driver BOOLEAN NOT NULL DEFAULT FALSE,
  evidence_start INTEGER NOT NULL,
  evidence_end INTEGER NOT NULL,
  evidence_quote VARCHAR(2000) NOT NULL,
  extraction_confidence DECIMAL(5,4) NOT NULL,
  embedding JSONB DEFAULT NULL,
  model_run_id BIGINT NOT NULL,
  validation_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_aspect_task_review_index UNIQUE (task_id, review_id, aspect_index),
  CONSTRAINT fk_aspect_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_aspect_review FOREIGN KEY (review_id) REFERENCES competitor_reviews (id),
  CONSTRAINT fk_aspect_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT chk_aspect_confidence CHECK (extraction_confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_aspect_severity CHECK (severity IS NULL OR severity BETWEEN 1 AND 5),
  CONSTRAINT chk_aspect_span CHECK (evidence_end > evidence_start)
);
COMMENT ON TABLE review_aspects IS 'Aspect-level AI extraction from competitor reviews';

CREATE TABLE IF NOT EXISTS insight_clusters (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  cluster_no INTEGER NOT NULL,
  cluster_name VARCHAR(200) NOT NULL,
  taxonomy_code VARCHAR(150) NOT NULL,
  sentiment VARCHAR(16) NOT NULL,
  aspect_count INTEGER NOT NULL,
  review_count INTEGER NOT NULL,
  listing_count INTEGER NOT NULL,
  mention_rate DECIMAL(7,6) NOT NULL,
  mention_denominator_type VARCHAR(32) NOT NULL,
  cross_listing_rate DECIMAL(7,6) NOT NULL,
  avg_severity DECIMAL(4,2) DEFAULT NULL,
  freshness_score DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  importance_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  cluster_confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  representative_aspect_ids JSONB DEFAULT NULL,
  algorithm_version VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_cluster_task_no UNIQUE (task_id, cluster_no),
  CONSTRAINT fk_cluster_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_cluster_mention_rate CHECK (mention_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_cluster_cross_rate CHECK (cross_listing_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_cluster_confidence CHECK (cluster_confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE insight_clusters IS 'Aggregated user need and pain-point clusters';

CREATE TABLE IF NOT EXISTS cluster_members (
  cluster_id BIGINT NOT NULL,
  aspect_id BIGINT NOT NULL,
  distance DECIMAL(12,10) NOT NULL DEFAULT 0.0000000000,
  is_representative BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (cluster_id, aspect_id),
  CONSTRAINT fk_cluster_member_cluster FOREIGN KEY (cluster_id) REFERENCES insight_clusters (id),
  CONSTRAINT fk_cluster_member_aspect FOREIGN KEY (aspect_id) REFERENCES review_aspects (id)
);
COMMENT ON TABLE cluster_members IS 'Membership between insight clusters and review aspects';

CREATE TABLE IF NOT EXISTS market_opportunities (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  opportunity_code VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  target_country CHAR(2) NOT NULL,
  target_platform VARCHAR(32) NOT NULL,
  target_user_codes JSONB DEFAULT NULL,
  usage_scenario_codes JSONB DEFAULT NULL,
  primary_cluster_ids JSONB NOT NULL,
  price_band_min DECIMAL(18,4) DEFAULT NULL,
  price_band_max DECIMAL(18,4) DEFAULT NULL,
  price_currency CHAR(3) DEFAULT NULL,
  demand_heat_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  demand_growth_score DECIMAL(5,2) DEFAULT NULL,
  unmet_need_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  competition_space_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  profit_space_score DECIMAL(5,2) DEFAULT NULL,
  enterprise_fit_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  overall_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  recommendation_level VARCHAR(32) NOT NULL,
  capability_gaps JSONB DEFAULT NULL,
  weight_config JSONB NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'generated',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_opportunity_task_code UNIQUE (task_id, opportunity_code),
  CONSTRAINT fk_opportunity_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_opportunity_score CHECK (overall_score BETWEEN 0 AND 100),
  CONSTRAINT chk_opportunity_confidence CHECK (confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE market_opportunities IS 'Market opportunities with denormalized six-dimension scores';

CREATE TABLE IF NOT EXISTS product_recommendations (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  opportunity_id BIGINT NOT NULL,
  recommendation_type VARCHAR(24) NOT NULL,
  problem_statement TEXT NOT NULL,
  root_cause_hypotheses JSONB NOT NULL,
  recommended_action TEXT NOT NULL,
  target_attribute_code VARCHAR(100) DEFAULT NULL,
  target_value JSONB DEFAULT NULL,
  expected_benefit TEXT NOT NULL,
  impact_dimensions JSONB NOT NULL,
  cost_impact_min DECIMAL(18,4) DEFAULT NULL,
  cost_impact_max DECIMAL(18,4) DEFAULT NULL,
  cost_currency CHAR(3) DEFAULT NULL,
  priority VARCHAR(16) NOT NULL,
  confidence DECIMAL(5,4) NOT NULL,
  validation_method TEXT NOT NULL,
  evidence_cluster_ids JSONB NOT NULL,
  expert_review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  expert_review_note VARCHAR(2000) DEFAULT NULL,
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMPTZ(3) DEFAULT NULL,
  model_run_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_recommendation_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_recommendation_opportunity FOREIGN KEY (opportunity_id) REFERENCES market_opportunities (id),
  CONSTRAINT fk_recommendation_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id),
  CONSTRAINT fk_recommendation_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT chk_recommendation_confidence CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_recommendation_cost CHECK (cost_impact_max IS NULL OR cost_impact_min IS NULL OR cost_impact_max >= cost_impact_min)
);
COMMENT ON TABLE product_recommendations IS 'AI product improvement recommendations with expert review';

CREATE TABLE IF NOT EXISTS evidence_links (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id BIGINT NOT NULL,
  claim_type VARCHAR(32) NOT NULL,
  claim_id BIGINT NOT NULL,
  claim_category VARCHAR(24) NOT NULL,
  evidence_type VARCHAR(32) NOT NULL,
  evidence_id BIGINT NOT NULL,
  support_type VARCHAR(16) NOT NULL DEFAULT 'supports',
  relevance_score DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_evidence_claim_item UNIQUE (claim_type, claim_id, evidence_type, evidence_id),
  CONSTRAINT fk_evidence_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_evidence_relevance CHECK (relevance_score BETWEEN 0 AND 1)
);
COMMENT ON TABLE evidence_links IS 'Polymorphic evidence chain for all AI conclusions';

CREATE TABLE IF NOT EXISTS analysis_reports (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  report_uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  report_version INTEGER NOT NULL DEFAULT 1,
  title VARCHAR(300) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  executive_summary TEXT NOT NULL,
  decision_recommendation VARCHAR(32) NOT NULL,
  overall_opportunity_score DECIMAL(5,2) NOT NULL,
  overall_confidence DECIMAL(5,4) NOT NULL,
  data_scope_summary JSONB NOT NULL,
  product_profile_snapshot JSONB NOT NULL,
  competitor_summary JSONB DEFAULT NULL,
  user_need_summary JSONB DEFAULT NULL,
  price_summary JSONB DEFAULT NULL,
  opportunity_summary JSONB NOT NULL,
  recommendation_summary JSONB NOT NULL,
  risk_summary JSONB NOT NULL,
  pending_validation_items JSONB NOT NULL,
  generated_model_run_id BIGINT NOT NULL,
  published_by BIGINT DEFAULT NULL,
  published_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_reports_uuid UNIQUE (report_uuid),
  CONSTRAINT uk_reports_task_version UNIQUE (task_id, report_version),
  CONSTRAINT fk_report_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_report_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_report_model_run FOREIGN KEY (generated_model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT fk_report_publisher FOREIGN KEY (published_by) REFERENCES users (id),
  CONSTRAINT chk_report_score CHECK (overall_opportunity_score BETWEEN 0 AND 100),
  CONSTRAINT chk_report_confidence CHECK (overall_confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE analysis_reports IS 'Versioned market opportunity reports';

CREATE TABLE IF NOT EXISTS listing_generation_records (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  source_task_id BIGINT DEFAULT NULL,
  target_platform VARCHAR(32) NOT NULL,
  target_country CHAR(2) NOT NULL,
  language VARCHAR(16) NOT NULL,
  generation_type VARCHAR(32) NOT NULL,
  input_snapshot JSONB NOT NULL,
  generated_title TEXT DEFAULT NULL,
  generated_bullets JSONB DEFAULT NULL,
  generated_description TEXT DEFAULT NULL,
  generated_keywords JSONB DEFAULT NULL,
  compliance_warnings JSONB DEFAULT NULL,
  model_run_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'generated',
  reviewed_by BIGINT DEFAULT NULL,
  reviewed_at TIMESTAMPTZ(3) DEFAULT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_listing_gen_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_listing_gen_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_listing_gen_task FOREIGN KEY (source_task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_listing_gen_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT fk_listing_gen_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
);
COMMENT ON TABLE listing_generation_records IS 'Optional generated listing records; post-MVP extension';

CREATE TABLE IF NOT EXISTS report_exports (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  report_id BIGINT NOT NULL,
  export_format VARCHAR(16) NOT NULL,
  file_url VARCHAR(1000) DEFAULT NULL,
  file_size_bytes BIGINT DEFAULT NULL,
  file_hash CHAR(64) DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  error_message VARCHAR(1000) DEFAULT NULL,
  requested_by BIGINT NOT NULL,
  requested_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ(3) DEFAULT NULL,
  expires_at TIMESTAMPTZ(3) DEFAULT NULL,
  download_count INTEGER NOT NULL DEFAULT 0,
  last_downloaded_at TIMESTAMPTZ(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_export_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_export_report FOREIGN KEY (report_id) REFERENCES analysis_reports (id),
  CONSTRAINT fk_export_requester FOREIGN KEY (requested_by) REFERENCES users (id)
);
COMMENT ON TABLE report_exports IS 'Asynchronous report export records';

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT DEFAULT NULL,
  actor_id BIGINT DEFAULT NULL,
  action VARCHAR(32) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT DEFAULT NULL,
  before_snapshot JSONB DEFAULT NULL,
  after_snapshot JSONB DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(512) DEFAULT NULL,
  occurred_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);
COMMENT ON TABLE audit_logs IS 'Sensitive operation audit trail';

CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants (status);
CREATE INDEX IF NOT EXISTS idx_users_tenant_role_status ON users (tenant_id, role_code, status);
CREATE INDEX IF NOT EXISTS idx_capability_tenant_available ON manufacturing_capabilities (tenant_id, availability, capability_type);
CREATE INDEX IF NOT EXISTS idx_capability_valid_until ON manufacturing_capabilities (tenant_id, valid_until);
CREATE INDEX IF NOT EXISTS idx_products_tenant_category_status ON products (tenant_id, category_code, lifecycle_status);
CREATE INDEX IF NOT EXISTS idx_products_tenant_analysis_status ON products (tenant_id, analysis_status, updated_at);
CREATE INDEX IF NOT EXISTS idx_product_attr_tenant_code ON product_attributes (tenant_id, attribute_code);
CREATE INDEX IF NOT EXISTS idx_product_attr_product_status ON product_attributes (product_id, confirmation_status);
CREATE INDEX IF NOT EXISTS idx_dataset_tenant_market_status ON market_datasets (tenant_id, platform, market_country, status);
CREATE INDEX IF NOT EXISTS idx_dataset_category_date ON market_datasets (tenant_id, category_code, data_end_date);
CREATE INDEX IF NOT EXISTS idx_listing_dataset_price ON competitor_listings (dataset_id, sale_price);
CREATE INDEX IF NOT EXISTS idx_listing_dataset_brand ON competitor_listings (dataset_id, brand);
CREATE INDEX IF NOT EXISTS idx_listing_dataset_rating ON competitor_listings (dataset_id, rating, review_count);
CREATE INDEX IF NOT EXISTS idx_listing_tenant_category_time ON competitor_listings (tenant_id, category_code, observed_at);
CREATE INDEX IF NOT EXISTS idx_review_listing_valid_time ON competitor_reviews (listing_id, is_valid, reviewed_at);
CREATE INDEX IF NOT EXISTS idx_review_dataset_rating_valid ON competitor_reviews (dataset_id, rating, is_valid);
CREATE INDEX IF NOT EXISTS idx_review_tenant_language ON competitor_reviews (tenant_id, language);
CREATE INDEX IF NOT EXISTS idx_task_tenant_status_created ON analysis_tasks (tenant_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_task_product_created ON analysis_tasks (tenant_id, product_id, created_at);
CREATE INDEX IF NOT EXISTS idx_task_dataset_status ON analysis_tasks (dataset_id, status);
CREATE INDEX IF NOT EXISTS idx_stage_task_status ON task_stage_runs (task_id, status, stage_code);
CREATE INDEX IF NOT EXISTS idx_model_run_task_type ON ai_model_runs (task_id, task_type, status);
CREATE INDEX IF NOT EXISTS idx_model_run_model_time ON ai_model_runs (model_id, created_at);
CREATE INDEX IF NOT EXISTS idx_model_run_stage ON ai_model_runs (stage_run_id);
CREATE INDEX IF NOT EXISTS idx_match_task_type_score ON competitor_matches (task_id, competitor_type, overall_score);
CREATE INDEX IF NOT EXISTS idx_match_task_review ON competitor_matches (task_id, review_status);
CREATE INDEX IF NOT EXISTS idx_aspect_task_taxonomy_sentiment ON review_aspects (task_id, taxonomy_code, sentiment);
CREATE INDEX IF NOT EXISTS idx_aspect_task_severity ON review_aspects (task_id, sentiment, severity);
CREATE INDEX IF NOT EXISTS idx_aspect_review ON review_aspects (review_id);
CREATE INDEX IF NOT EXISTS idx_cluster_task_importance ON insight_clusters (task_id, importance_score);
CREATE INDEX IF NOT EXISTS idx_cluster_task_taxonomy ON insight_clusters (task_id, taxonomy_code, sentiment);
CREATE INDEX IF NOT EXISTS idx_cluster_members_aspect ON cluster_members (aspect_id);
CREATE INDEX IF NOT EXISTS idx_opportunity_task_score ON market_opportunities (task_id, overall_score, confidence);
CREATE INDEX IF NOT EXISTS idx_opportunity_task_status ON market_opportunities (task_id, status);
CREATE INDEX IF NOT EXISTS idx_recommendation_task_priority ON product_recommendations (task_id, priority, expert_review_status);
CREATE INDEX IF NOT EXISTS idx_recommendation_opportunity ON product_recommendations (opportunity_id);
CREATE INDEX IF NOT EXISTS idx_evidence_task_claim ON evidence_links (task_id, claim_type, claim_id, display_order);
CREATE INDEX IF NOT EXISTS idx_evidence_reverse ON evidence_links (evidence_type, evidence_id);
CREATE INDEX IF NOT EXISTS idx_reports_tenant_status_time ON analysis_reports (tenant_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_reports_task_status ON analysis_reports (task_id, status);
CREATE INDEX IF NOT EXISTS idx_listing_gen_product_time ON listing_generation_records (tenant_id, product_id, created_at);
CREATE INDEX IF NOT EXISTS idx_listing_gen_task ON listing_generation_records (source_task_id);
CREATE INDEX IF NOT EXISTS idx_listing_gen_status ON listing_generation_records (tenant_id, status, target_platform);
CREATE INDEX IF NOT EXISTS idx_export_report_status ON report_exports (report_id, status, requested_at);
CREATE INDEX IF NOT EXISTS idx_export_tenant_time ON report_exports (tenant_id, requested_at);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON audit_logs (tenant_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON audit_logs (resource_type, resource_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_actor_time ON audit_logs (actor_id, occurred_at);

COMMENT ON COLUMN tenants.id IS 'Tenant primary key';
COMMENT ON COLUMN tenants.tenant_code IS 'Globally unique tenant code';
COMMENT ON COLUMN tenants.tenant_name IS 'Enterprise legal/display name';
COMMENT ON COLUMN tenants.display_name IS 'Enterprise short name';
COMMENT ON COLUMN tenants.industry IS 'Industry code';
COMMENT ON COLUMN tenants.default_timezone IS 'IANA timezone';
COMMENT ON COLUMN tenants.default_currency IS 'ISO 4217 currency';
COMMENT ON COLUMN tenants.status IS '0 disabled, 1 active, 2 suspended';
COMMENT ON COLUMN tenants.data_retention_days IS 'Default data retention days';
COMMENT ON COLUMN users.id IS 'User primary key';
COMMENT ON COLUMN users.tenant_id IS 'Tenant ID';
COMMENT ON COLUMN users.email IS 'Login email, normalized lowercase';
COMMENT ON COLUMN users.password_hash IS 'Password hash; never plaintext';
COMMENT ON COLUMN users.user_name IS 'User display name';
COMMENT ON COLUMN users.phone IS 'Phone in E.164 format';
COMMENT ON COLUMN users.department IS 'Department';
COMMENT ON COLUMN users.job_title IS 'Job title';
COMMENT ON COLUMN users.role_code IS 'owner/product_rd/market_ops/sales/admin';
COMMENT ON COLUMN users.locale IS 'BCP 47 locale';
COMMENT ON COLUMN users.timezone IS 'IANA timezone; null inherits tenant';
COMMENT ON COLUMN users.status IS '0 disabled, 1 active, 2 invited, 3 locked';
COMMENT ON COLUMN enterprise_profiles.business_models IS 'B2B/B2C/OEM/ODM/brand array';
COMMENT ON COLUMN enterprise_profiles.primary_categories IS 'Primary category code array';
COMMENT ON COLUMN enterprise_profiles.export_markets IS 'ISO country code array';
COMMENT ON COLUMN enterprise_profiles.sales_channels IS 'Existing sales channels';
COMMENT ON COLUMN enterprise_profiles.profile_completeness IS '0-1';
COMMENT ON COLUMN manufacturing_capabilities.capability_type IS 'category/material/process/customization/packaging/certification/delivery/equipment';
COMMENT ON COLUMN manufacturing_capabilities.availability IS '0 no, 1 yes, 2 unknown';
COMMENT ON COLUMN manufacturing_capabilities.confidence IS '0-1';
COMMENT ON COLUMN manufacturing_capabilities.evidence_url IS 'Authorized evidence object URL/key';
COMMENT ON COLUMN products.sku IS 'Enterprise SKU';
COMMENT ON COLUMN products.sofa_type IS 'standard/sectional/modular/sleeper/loveseat/recliner/other';
COMMENT ON COLUMN products.lifecycle_status IS 'concept/sample/active/discontinued';
COMMENT ON COLUMN products.analysis_status IS 'draft/profile_pending/ready/archived';
COMMENT ON COLUMN products.source_files IS 'Authorized object keys for PDF/XLSX/images';
COMMENT ON COLUMN products.factory_price IS 'Sensitive factory quotation';
COMMENT ON COLUMN products.price_term IS 'EXW/FOB/CIF/DDP/other';
COMMENT ON COLUMN products.profile_status IS 'unreviewed/confirmed/needs_fix';
COMMENT ON COLUMN product_attributes.value_type IS 'string/number/boolean/enum/array/range';
COMMENT ON COLUMN product_attributes.source_type IS 'structured_file/user_input/pdf/vision/model_inference';
COMMENT ON COLUMN market_datasets.platform IS 'amazon/wayfair/walmart/other';
COMMENT ON COLUMN market_datasets.source_type IS 'enterprise_export/licensed_provider/public_authorized/demo_synthetic';
COMMENT ON COLUMN market_datasets.status IS 'uploaded/validating/ready/rejected/archived';
COMMENT ON COLUMN competitor_listings.platform_listing_id IS 'ASIN or platform item ID';
COMMENT ON COLUMN competitor_listings.normalized_attributes IS 'Denormalized attributes for Demo queries';
COMMENT ON COLUMN competitor_listings.feature_codes IS 'Normalized selling point codes';
COMMENT ON COLUMN competitor_listings.sales_value_type IS 'actual/estimated/proxy';
COMMENT ON COLUMN competitor_reviews.verified_purchase IS '0 no, 1 yes, 2 unknown';
COMMENT ON COLUMN analysis_tasks.task_uuid IS 'Externally exposed task UUID';
COMMENT ON COLUMN analysis_tasks.analysis_config IS 'Frozen thresholds and filters';
COMMENT ON COLUMN ai_model_runs.task_type IS 'vision_extract/text_extract/translate/embed/rerank/reason/report';
COMMENT ON COLUMN ai_model_runs.cost_unit IS 'CNY/USD/credit';
COMMENT ON COLUMN competitor_matches.competitor_type IS 'direct/benchmark/substitute/excluded';
COMMENT ON COLUMN review_aspects.sentiment IS 'positive/negative/neutral/mixed';
COMMENT ON COLUMN review_aspects.severity IS '1-5 for negative aspects';
COMMENT ON COLUMN review_aspects.embedding IS 'Demo storage; production may use vector DB';
COMMENT ON COLUMN insight_clusters.mention_denominator_type IS 'valid_reviews/negative_aspects/all_aspects';
COMMENT ON COLUMN product_recommendations.priority IS 'high/medium/low';
COMMENT ON COLUMN evidence_links.claim_type IS 'opportunity/recommendation/report/score';
COMMENT ON COLUMN evidence_links.claim_category IS 'observation/inference/recommendation/validation_required';
COMMENT ON COLUMN evidence_links.evidence_type IS 'review_aspect/listing/cluster/metric/product_attribute/capability/expert_feedback';
COMMENT ON COLUMN evidence_links.support_type IS 'supports/contradicts/context/limitation';
COMMENT ON COLUMN analysis_reports.status IS 'draft/human_review/published/superseded';
COMMENT ON COLUMN listing_generation_records.source_task_id IS 'Optional market insight task source';
COMMENT ON COLUMN listing_generation_records.generation_type IS 'title/bullets/description/keywords/full_listing';
COMMENT ON COLUMN listing_generation_records.status IS 'generated/reviewed/approved/rejected';
COMMENT ON COLUMN report_exports.export_format IS 'pdf/docx/xlsx/json';
COMMENT ON COLUMN report_exports.file_url IS 'Authorized object key or URL';
COMMENT ON COLUMN report_exports.status IS 'queued/generating/succeeded/failed/expired';

-- =========================================================
-- V2 workflow persistence required by Data Dictionary/API V2
-- =========================================================

ALTER TABLE analysis_tasks
  ADD COLUMN IF NOT EXISTS checkpoint_stage VARCHAR(32),
  ADD COLUMN IF NOT EXISTS cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cancel_reason_code VARCHAR(32),
  ADD COLUMN IF NOT EXISTS cancel_reason_note VARCHAR(1000),
  ADD COLUMN IF NOT EXISTS cancel_requested_by BIGINT REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS cancel_requested_at TIMESTAMPTZ(3),
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ(3);

ALTER TABLE task_stage_runs
  ADD COLUMN IF NOT EXISTS retry_parent_run_id BIGINT REFERENCES task_stage_runs(id),
  ADD COLUMN IF NOT EXISTS retry_reason VARCHAR(500),
  ADD COLUMN IF NOT EXISTS retry_requested_by BIGINT REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS retry_requested_at TIMESTAMPTZ(3),
  ADD COLUMN IF NOT EXISTS retry_scope JSONB;

ALTER TABLE analysis_tasks
  ADD CONSTRAINT chk_analysis_task_status CHECK(status IN ('draft','queued','running','waiting_human','partial_succeeded','succeeded','failed','cancelled')),
  ADD CONSTRAINT chk_analysis_task_cancel_reason CHECK(cancel_reason_code IS NULL OR cancel_reason_code IN ('user_cancelled','data_issue','scope_changed','cost_control','other')),
  ADD CONSTRAINT chk_analysis_task_cancel_fields CHECK(
    cancel_requested = FALSE OR (cancel_requested_by IS NOT NULL AND cancel_requested_at IS NOT NULL)
  );

ALTER TABLE task_stage_runs
  ADD CONSTRAINT chk_stage_run_status CHECK(status IN ('queued','running','waiting_human','retry_scheduled','succeeded','partial_succeeded','failed','skipped','cancelled')),
  ADD CONSTRAINT chk_stage_run_attempt CHECK(attempt_no >= 1),
  ADD CONSTRAINT chk_stage_run_time CHECK(ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at);

CREATE TABLE IF NOT EXISTS file_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  owner_type VARCHAR(32) NOT NULL,
  owner_id BIGINT NOT NULL,
  asset_type VARCHAR(32) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  storage_key VARCHAR(512) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT NOT NULL,
  sha256 CHAR(64) NOT NULL,
  security_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  parse_status VARCHAR(24) NOT NULL DEFAULT 'not_started',
  retention_until TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_file_assets_storage_key UNIQUE(storage_key),
  CONSTRAINT chk_file_assets_size CHECK(size_bytes > 0),
  CONSTRAINT chk_file_assets_security CHECK(security_status IN ('pending','clean','rejected','quarantined')),
  CONSTRAINT chk_file_assets_parse CHECK(parse_status IN ('not_started','processing','succeeded','partial','failed'))
);
COMMENT ON TABLE file_assets IS 'Authorized object-storage file metadata; binary content is not stored in PostgreSQL';

CREATE TABLE IF NOT EXISTS product_parse_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parse_job_id VARCHAR(32) NOT NULL,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  current_stage VARCHAR(32) NOT NULL DEFAULT 'security_scan',
  progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  profile_version INTEGER,
  file_count INTEGER NOT NULL,
  succeeded_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  extracted_attribute_count INTEGER NOT NULL DEFAULT 0,
  conflict_count INTEGER NOT NULL DEFAULT 0,
  retryable BOOLEAN NOT NULL DEFAULT FALSE,
  failure_code VARCHAR(100),
  failure_message VARCHAR(1000),
  idempotency_key VARCHAR(128) NOT NULL,
  requested_by BIGINT NOT NULL REFERENCES users(id),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_parse_jobs_external UNIQUE(parse_job_id),
  CONSTRAINT uk_parse_jobs_tenant_idempotency UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_parse_jobs_status CHECK(status IN ('queued','processing','succeeded','partial','failed','cancelled')),
  CONSTRAINT chk_parse_jobs_stage CHECK(current_stage IN ('security_scan','text_extract','vision_extract','schema_mapping','conflict_detection','completed')),
  CONSTRAINT chk_parse_jobs_progress CHECK(progress_percent BETWEEN 0 AND 100),
  CONSTRAINT chk_parse_jobs_counts CHECK(file_count >= 1 AND succeeded_count >= 0 AND failed_count >= 0 AND succeeded_count + failed_count <= file_count)
);
COMMENT ON TABLE product_parse_jobs IS 'Asynchronous product document parse jobs for API-PRD-05/07';

CREATE TABLE IF NOT EXISTS product_parse_job_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parse_job_id BIGINT NOT NULL REFERENCES product_parse_jobs(id) ON DELETE CASCADE,
  file_asset_id BIGINT NOT NULL REFERENCES file_assets(id),
  security_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  parse_status VARCHAR(24) NOT NULL DEFAULT 'queued',
  current_stage VARCHAR(32),
  extracted_attribute_count INTEGER NOT NULL DEFAULT 0,
  error_code VARCHAR(100),
  error_message VARCHAR(1000),
  output_ref JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_parse_job_file UNIQUE(parse_job_id,file_asset_id),
  CONSTRAINT chk_parse_job_file_security CHECK(security_status IN ('pending','clean','rejected','quarantined')),
  CONSTRAINT chk_parse_job_file_status CHECK(parse_status IN ('queued','processing','succeeded','partial','failed','skipped')),
  CONSTRAINT chk_parse_job_file_count CHECK(extracted_attribute_count >= 0)
);
COMMENT ON TABLE product_parse_job_files IS 'File-level status and output references for a product parse job';

CREATE TABLE IF NOT EXISTS workflow_checkpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkpoint_id VARCHAR(128) NOT NULL,
  thread_id VARCHAR(128) NOT NULL,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_code VARCHAR(32) NOT NULL,
  checkpoint_version BIGINT NOT NULL,
  state_snapshot JSONB NOT NULL,
  state_hash CHAR(64) NOT NULL,
  is_safe_resume BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consumed_at TIMESTAMPTZ(3),
  CONSTRAINT uk_workflow_checkpoint_id UNIQUE(checkpoint_id),
  CONSTRAINT uk_workflow_checkpoint_version UNIQUE(task_id,checkpoint_version),
  CONSTRAINT chk_workflow_checkpoint_status CHECK(status IN ('active','consumed','superseded','corrupted'))
);
COMMENT ON TABLE workflow_checkpoints IS 'Business projection of safe LangGraph checkpoints; official saver owns its internal checkpoint tables';

CREATE TABLE IF NOT EXISTS workflow_partial_failures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_run_id BIGINT NOT NULL REFERENCES task_stage_runs(id),
  stage_code VARCHAR(32) NOT NULL,
  unit_type VARCHAR(32) NOT NULL,
  failed_unit_ids JSONB NOT NULL,
  failed_count INTEGER NOT NULL,
  total_count INTEGER NOT NULL,
  impact VARCHAR(1000) NOT NULL,
  confidence_cap NUMERIC(5,4),
  retryable BOOLEAN NOT NULL,
  resolved_status VARCHAR(24) NOT NULL DEFAULT 'open',
  resolved_stage_run_id BIGINT REFERENCES task_stage_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ(3),
  CONSTRAINT chk_partial_failure_unit CHECK(unit_type IN ('review_batch','opportunity','model_call','file','branch','other')),
  CONSTRAINT chk_partial_failure_counts CHECK(failed_count > 0 AND total_count >= failed_count),
  CONSTRAINT chk_partial_failure_confidence CHECK(confidence_cap IS NULL OR confidence_cap BETWEEN 0 AND 1),
  CONSTRAINT chk_partial_failure_status CHECK(resolved_status IN ('open','retry_scheduled','resolved','accepted_limit'))
);
COMMENT ON TABLE workflow_partial_failures IS 'Persistent projection of non-blocking Agent branch and batch failures';

CREATE TABLE IF NOT EXISTS workflow_control_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_uuid UUID NOT NULL DEFAULT gen_random_uuid(),
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  event_type VARCHAR(32) NOT NULL,
  expected_checkpoint_stage VARCHAR(32),
  checkpoint_id VARCHAR(128),
  stage_code VARCHAR(32),
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  requested_by BIGINT NOT NULL REFERENCES users(id),
  requested_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consumed_at TIMESTAMPTZ(3),
  error_code VARCHAR(100),
  CONSTRAINT uk_control_event_uuid UNIQUE(event_uuid),
  CONSTRAINT uk_control_event_idempotency UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_control_event_type CHECK(event_type IN ('resume_competitors','resume_expert_review','retry_stage','cancel_task')),
  CONSTRAINT chk_control_event_status CHECK(status IN ('pending','enqueued','consumed','failed','cancelled'))
);
COMMENT ON TABLE workflow_control_events IS 'Transactional Outbox for resume, retry, and cooperative cancellation commands';

CREATE TABLE IF NOT EXISTS competitor_set_confirmations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  version_no INTEGER NOT NULL,
  checkpoint_stage VARCHAR(32) NOT NULL,
  confirmed_listing_ids JSONB NOT NULL,
  direct_count INTEGER NOT NULL DEFAULT 0,
  benchmark_count INTEGER NOT NULL DEFAULT 0,
  substitute_count INTEGER NOT NULL DEFAULT 0,
  excluded_count INTEGER NOT NULL DEFAULT 0,
  confirm_sample_scope BOOLEAN NOT NULL DEFAULT FALSE,
  confirmation_note VARCHAR(1000),
  idempotency_key VARCHAR(128) NOT NULL,
  resume_command_id VARCHAR(64),
  resume_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  confirmed_by BIGINT NOT NULL REFERENCES users(id),
  confirmed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_competitor_confirmation_version UNIQUE(task_id,version_no),
  CONSTRAINT uk_competitor_confirmation_idempotency UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_competitor_confirmation_stage CHECK(checkpoint_stage = 'competitor_review'),
  CONSTRAINT chk_competitor_confirmation_resume CHECK(resume_status IN ('pending','enqueued','consumed','failed'))
);
COMMENT ON TABLE competitor_set_confirmations IS 'Versioned human confirmation snapshot used to resume competitor_review checkpoint';

-- =========================================================
-- Data Dictionary V2 full-domain entities
-- =========================================================

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) NOT NULL,
  name VARCHAR(64) NOT NULL,
  permissions JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_roles_code UNIQUE(code),
  CONSTRAINT chk_roles_code CHECK(code IN ('owner','product_rd','market_ops','sales','admin')),
  CONSTRAINT chk_roles_permissions_array CHECK(jsonb_typeof(permissions) = 'array')
);
COMMENT ON TABLE roles IS 'Registered RBAC roles and permission-code sets';

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_id BIGINT NOT NULL REFERENCES roles(id),
  granted_by BIGINT NOT NULL REFERENCES users(id),
  granted_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id,role_id)
);
COMMENT ON TABLE user_roles IS 'Audited many-to-many assignments between users and roles';

CREATE TABLE IF NOT EXISTS enterprise_constraints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  constraint_type VARCHAR(32) NOT NULL,
  operator VARCHAR(16) NOT NULL,
  value JSONB NOT NULL,
  unit VARCHAR(32),
  hardness VARCHAR(16) NOT NULL,
  effective_at TIMESTAMPTZ(3) NOT NULL,
  expires_at TIMESTAMPTZ(3),
  sensitivity_level VARCHAR(24) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_enterprise_constraint_type CHECK(constraint_type IN ('cost','moq','lead_time','package_volume','certification','material','process','market')),
  CONSTRAINT chk_enterprise_constraint_operator CHECK(operator IN ('eq','ne','lt','lte','gt','gte','between','in','not_in')),
  CONSTRAINT chk_enterprise_constraint_hardness CHECK(hardness IN ('hard','soft')),
  CONSTRAINT chk_enterprise_constraint_sensitivity CHECK(sensitivity_level IN ('internal','confidential','restricted')),
  CONSTRAINT chk_enterprise_constraint_time CHECK(expires_at IS NULL OR expires_at >= effective_at)
);
COMMENT ON TABLE enterprise_constraints IS 'Versioned enterprise cost, delivery, certification and market constraints';

CREATE TABLE IF NOT EXISTS product_profile_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  version_no INTEGER NOT NULL,
  schema_version VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  completeness_score NUMERIC(5,4) NOT NULL DEFAULT 0,
  conflict_count INTEGER NOT NULL DEFAULT 0,
  confirmed_by BIGINT REFERENCES users(id),
  confirmed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_product_profile_version UNIQUE(product_id,version_no),
  CONSTRAINT chk_product_profile_status CHECK(status IN ('draft','needs_confirmation','confirmed','superseded')),
  CONSTRAINT chk_product_profile_completeness CHECK(completeness_score BETWEEN 0 AND 1),
  CONSTRAINT chk_product_profile_conflicts CHECK(conflict_count >= 0),
  CONSTRAINT chk_product_profile_confirmation CHECK(status <> 'confirmed' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL))
);
COMMENT ON TABLE product_profile_versions IS 'Immutable versions of normalized product profiles used by analysis tasks';

CREATE TABLE IF NOT EXISTS dataset_field_mappings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataset_id BIGINT NOT NULL REFERENCES market_datasets(id) ON DELETE CASCADE,
  source_field VARCHAR(200) NOT NULL,
  target_entity VARCHAR(32) NOT NULL,
  target_field VARCHAR(100) NOT NULL,
  transform_rule JSONB,
  mapping_status VARCHAR(24) NOT NULL DEFAULT 'auto_suggested',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_dataset_field_mapping UNIQUE(dataset_id,source_field,target_entity,target_field),
  CONSTRAINT chk_dataset_mapping_entity CHECK(target_entity IN ('listing','review','market_metric')),
  CONSTRAINT chk_dataset_mapping_status CHECK(mapping_status IN ('auto_suggested','confirmed','ignored','error'))
);
COMMENT ON TABLE dataset_field_mappings IS 'Whitelisted mappings from imported source fields to registered target fields';

CREATE TABLE IF NOT EXISTS listing_attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL REFERENCES competitor_listings(id) ON DELETE CASCADE,
  attribute_code VARCHAR(100) NOT NULL,
  value JSONB,
  unit VARCHAR(32),
  source_locator JSONB,
  confidence NUMERIC(5,4) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_listing_attribute UNIQUE(listing_id,attribute_code),
  CONSTRAINT chk_listing_attribute_confidence CHECK(confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE listing_attributes IS 'Normalized competitor listing attributes aligned with the product schema';

CREATE TABLE IF NOT EXISTS market_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  metric_code VARCHAR(100) NOT NULL,
  metric_name VARCHAR(200) NOT NULL,
  dimension_type VARCHAR(24) NOT NULL,
  dimension_value JSONB NOT NULL,
  metric_value NUMERIC(24,8) NOT NULL,
  metric_unit VARCHAR(32) NOT NULL,
  numerator NUMERIC(24,8),
  denominator NUMERIC(24,8),
  value_type VARCHAR(24) NOT NULL,
  period_start DATE,
  period_end DATE,
  sample_size INTEGER NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  formula_version VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_market_metric_dimension CHECK(dimension_type IN ('market','price_band','brand','feature','cluster','time','product')),
  CONSTRAINT chk_market_metric_value_type CHECK(value_type IN ('observed','calculated','estimated','proxy')),
  CONSTRAINT chk_market_metric_period CHECK(period_end IS NULL OR period_start IS NULL OR period_end >= period_start),
  CONSTRAINT chk_market_metric_sample CHECK(sample_size >= 0),
  CONSTRAINT chk_market_metric_confidence CHECK(confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_market_metric_denominator CHECK(denominator IS NULL OR denominator > 0)
);
COMMENT ON TABLE market_metrics IS 'Deterministically calculated market, price, brand, feature and time metrics';

CREATE TABLE IF NOT EXISTS price_bands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  currency CHAR(3) NOT NULL,
  lower_bound NUMERIC(18,4) NOT NULL,
  upper_bound NUMERIC(18,4),
  listing_count INTEGER NOT NULL,
  median_rating NUMERIC(3,2),
  review_share NUMERIC(7,6),
  feature_codes JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_price_band UNIQUE(task_id,currency,lower_bound),
  CONSTRAINT chk_price_band_bounds CHECK(lower_bound >= 0 AND (upper_bound IS NULL OR upper_bound > lower_bound)),
  CONSTRAINT chk_price_band_listing_count CHECK(listing_count >= 0),
  CONSTRAINT chk_price_band_rating CHECK(median_rating IS NULL OR median_rating BETWEEN 0 AND 5),
  CONSTRAINT chk_price_band_review_share CHECK(review_share IS NULL OR review_share BETWEEN 0 AND 1)
);
COMMENT ON TABLE price_bands IS 'Task-scoped price distribution buckets and observed feature penetration';

CREATE TABLE IF NOT EXISTS prompt_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  version VARCHAR(64) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  template_content TEXT NOT NULL,
  output_schema JSONB,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  evaluation_set_version VARCHAR(64),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_prompt_template_version UNIQUE(code,version),
  CONSTRAINT chk_prompt_template_status CHECK(status IN ('draft','testing','active','retired')),
  CONSTRAINT chk_prompt_template_active_eval CHECK(status <> 'active' OR evaluation_set_version IS NOT NULL)
);
COMMENT ON TABLE prompt_templates IS 'Immutable versioned prompts and optional structured-output JSON Schemas';

CREATE TABLE IF NOT EXISTS opportunity_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL REFERENCES market_opportunities(id) ON DELETE CASCADE,
  demand_heat_score NUMERIC(5,2) NOT NULL,
  demand_growth_score NUMERIC(5,2),
  unmet_need_score NUMERIC(5,2) NOT NULL,
  competition_space_score NUMERIC(5,2) NOT NULL,
  profit_space_score NUMERIC(5,2),
  enterprise_fit_score NUMERIC(5,2) NOT NULL,
  base_score NUMERIC(5,2) NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  recommendation_level VARCHAR(32) NOT NULL,
  weight_config JSONB NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  calculated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_opportunity_score_version UNIQUE(opportunity_id,scoring_version),
  CONSTRAINT chk_opportunity_scores_range CHECK(
    demand_heat_score BETWEEN 0 AND 100 AND
    (demand_growth_score IS NULL OR demand_growth_score BETWEEN 0 AND 100) AND
    unmet_need_score BETWEEN 0 AND 100 AND competition_space_score BETWEEN 0 AND 100 AND
    (profit_space_score IS NULL OR profit_space_score BETWEEN 0 AND 100) AND
    enterprise_fit_score BETWEEN 0 AND 100 AND base_score BETWEEN 0 AND 100
  ),
  CONSTRAINT chk_opportunity_score_confidence CHECK(confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_opportunity_recommendation CHECK(recommendation_level IN ('prioritize_validate','collect_more_data','capability_gap','limited_opportunity'))
);
COMMENT ON TABLE opportunity_scores IS 'Versioned six-dimension opportunity scores with independent confidence';

CREATE TABLE IF NOT EXISTS manufacturing_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL REFERENCES market_opportunities(id) ON DELETE CASCADE,
  requirement_type VARCHAR(32) NOT NULL,
  requirement_code VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  target_value JSONB,
  unit VARCHAR(32),
  priority VARCHAR(16) NOT NULL,
  evidence_cluster_ids JSONB NOT NULL,
  validation_required BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_manufacturing_requirement UNIQUE(opportunity_id,requirement_code),
  CONSTRAINT chk_manufacturing_requirement_type CHECK(requirement_type IN ('attribute','material','process','equipment','packaging','cost','moq','certification','delivery','test')),
  CONSTRAINT chk_manufacturing_requirement_priority CHECK(priority IN ('must','should','could')),
  CONSTRAINT chk_manufacturing_requirement_evidence CHECK(jsonb_typeof(evidence_cluster_ids)='array' AND jsonb_array_length(evidence_cluster_ids)>=1)
);
COMMENT ON TABLE manufacturing_requirements IS 'Evidence-backed manufacturing requirements derived from an opportunity';

CREATE TABLE IF NOT EXISTS enterprise_fit_details (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id BIGINT NOT NULL REFERENCES market_opportunities(id) ON DELETE CASCADE,
  requirement_id BIGINT NOT NULL REFERENCES manufacturing_requirements(id) ON DELETE CASCADE,
  capability_id BIGINT REFERENCES manufacturing_capabilities(id),
  fit_status VARCHAR(24) NOT NULL,
  fit_score NUMERIC(5,2),
  hard_constraint_breached BOOLEAN NOT NULL DEFAULT FALSE,
  explanation TEXT NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_enterprise_fit_requirement UNIQUE(opportunity_id,requirement_id),
  CONSTRAINT chk_enterprise_fit_status CHECK(fit_status IN ('matched','partial','gap','unknown','not_applicable')),
  CONSTRAINT chk_enterprise_fit_score CHECK((fit_status='unknown' AND fit_score IS NULL) OR (fit_status<>'unknown' AND fit_score BETWEEN 0 AND 100)),
  CONSTRAINT chk_enterprise_fit_confidence CHECK(confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE enterprise_fit_details IS 'Requirement-level fit, gap and hard-constraint evaluation against enterprise capabilities';

CREATE TABLE IF NOT EXISTS validation_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recommendation_id BIGINT NOT NULL REFERENCES product_recommendations(id) ON DELETE CASCADE,
  validation_type VARCHAR(24) NOT NULL,
  owner_id BIGINT NOT NULL REFERENCES users(id),
  due_date DATE,
  status VARCHAR(24) NOT NULL DEFAULT 'planned',
  result_summary TEXT,
  result_metrics JSONB,
  evidence_asset_ids JSONB,
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_validation_task_type CHECK(validation_type IN ('expert_review','prototype','lab_test','user_test','market_test','cost_quote')),
  CONSTRAINT chk_validation_task_status CHECK(status IN ('planned','in_progress','passed','failed','cancelled')),
  CONSTRAINT chk_validation_task_result CHECK(status NOT IN ('passed','failed') OR result_summary IS NOT NULL),
  CONSTRAINT chk_validation_task_completed CHECK(status NOT IN ('passed','failed','cancelled') OR completed_at IS NOT NULL)
);
COMMENT ON TABLE validation_tasks IS 'P1 recommendation validation tasks for expert, prototype, laboratory and market feedback';

CREATE TABLE IF NOT EXISTS report_sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES analysis_reports(id) ON DELETE CASCADE,
  section_code VARCHAR(32) NOT NULL,
  title VARCHAR(200) NOT NULL,
  sort_order INTEGER NOT NULL,
  content_type VARCHAR(16) NOT NULL,
  structured_content JSONB,
  narrative_text TEXT,
  chart_config JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_report_section_code UNIQUE(report_id,section_code),
  CONSTRAINT uk_report_section_order UNIQUE(report_id,sort_order),
  CONSTRAINT chk_report_section_code CHECK(section_code IN ('scope','product','competitor','user_need','price','opportunity','fit','recommendation','risk','evidence')),
  CONSTRAINT chk_report_section_order CHECK(sort_order>=1),
  CONSTRAINT chk_report_section_content_type CHECK(content_type IN ('structured','text','chart','mixed')),
  CONSTRAINT chk_report_section_content CHECK(
    (content_type NOT IN ('structured','mixed') OR structured_content IS NOT NULL) AND
    (content_type NOT IN ('text','mixed') OR narrative_text IS NOT NULL)
  )
);
COMMENT ON TABLE report_sections IS 'Ordered structured and narrative sections of a versioned analysis report';

CREATE TABLE IF NOT EXISTS report_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES analysis_reports(id) ON DELETE CASCADE,
  reviewer_id BIGINT NOT NULL REFERENCES users(id),
  decision VARCHAR(16) NOT NULL,
  usability_score INTEGER NOT NULL,
  accuracy_score INTEGER NOT NULL,
  actionability_score INTEGER NOT NULL,
  comment TEXT,
  reviewed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_report_review_decision CHECK(decision IN ('approve','revise','reject','hold')),
  CONSTRAINT chk_report_review_scores CHECK(usability_score BETWEEN 1 AND 5 AND accuracy_score BETWEEN 1 AND 5 AND actionability_score BETWEEN 1 AND 5),
  CONSTRAINT chk_report_review_comment CHECK(decision='approve' OR comment IS NOT NULL)
);
COMMENT ON TABLE report_reviews IS 'Audited human review decisions and usability, accuracy and actionability scores';

CREATE TABLE IF NOT EXISTS model_route_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(32) NOT NULL,
  primary_model_id VARCHAR(200) NOT NULL,
  fallback_model_ids JSONB,
  timeout_ms INTEGER NOT NULL,
  max_retries INTEGER NOT NULL,
  batch_size INTEGER,
  concurrency_limit INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_model_route_timeout CHECK(timeout_ms>0),
  CONSTRAINT chk_model_route_retries CHECK(max_retries BETWEEN 0 AND 5),
  CONSTRAINT chk_model_route_batch CHECK(batch_size IS NULL OR batch_size>=1),
  CONSTRAINT chk_model_route_concurrency CHECK(concurrency_limit>=1)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_model_route_active_task ON model_route_configs(task_type) WHERE active=TRUE;
COMMENT ON TABLE model_route_configs IS 'Versioned runtime routing, fallback, timeout, retry and concurrency settings without credentials';

CREATE TABLE IF NOT EXISTS compute_quotas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  period_start TIMESTAMPTZ(3) NOT NULL,
  period_end TIMESTAMPTZ(3) NOT NULL,
  quota_unit VARCHAR(16) NOT NULL,
  quota_total NUMERIC(24,8) NOT NULL,
  quota_used NUMERIC(24,8) NOT NULL DEFAULT 0,
  warning_threshold NUMERIC(5,4) NOT NULL DEFAULT 0.8,
  hard_limit BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_compute_quota_period UNIQUE(tenant_id,period_start,period_end,quota_unit),
  CONSTRAINT chk_compute_quota_period CHECK(period_end>period_start),
  CONSTRAINT chk_compute_quota_unit CHECK(quota_unit IN ('credit','token','currency','job')),
  CONSTRAINT chk_compute_quota_values CHECK(quota_total>=0 AND quota_used BETWEEN 0 AND quota_total),
  CONSTRAINT chk_compute_quota_threshold CHECK(warning_threshold BETWEEN 0 AND 1)
);
COMMENT ON TABLE compute_quotas IS 'Tenant compute quota periods and idempotently aggregated usage';

CREATE TABLE IF NOT EXISTS product_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  user_id BIGINT REFERENCES users(id),
  event_name VARCHAR(100) NOT NULL,
  entity_type VARCHAR(64),
  entity_id BIGINT,
  properties JSONB,
  occurred_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE product_events IS 'Privacy-safe registered product and quality events for funnel and usage analysis';

ALTER TABLE manufacturing_capabilities
  ADD COLUMN IF NOT EXISTS evidence_asset_id BIGINT REFERENCES file_assets(id);

ALTER TABLE product_attributes
  ADD COLUMN IF NOT EXISTS profile_version_id BIGINT REFERENCES product_profile_versions(id),
  ADD COLUMN IF NOT EXISTS source_asset_id BIGINT REFERENCES file_assets(id);

ALTER TABLE competitor_matches
  ADD COLUMN IF NOT EXISTS product_profile_version_id BIGINT REFERENCES product_profile_versions(id);

ALTER TABLE market_opportunities
  ADD COLUMN IF NOT EXISTS price_band_id BIGINT REFERENCES price_bands(id);

ALTER TABLE ai_model_runs
  ADD COLUMN IF NOT EXISTS prompt_template_id BIGINT REFERENCES prompt_templates(id);

CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles(role_id,user_id);
CREATE INDEX IF NOT EXISTS idx_enterprise_constraints_active ON enterprise_constraints(tenant_id,constraint_type,effective_at,expires_at);
CREATE INDEX IF NOT EXISTS idx_product_profile_versions_status ON product_profile_versions(product_id,status,version_no DESC);
CREATE INDEX IF NOT EXISTS idx_dataset_mappings_status ON dataset_field_mappings(dataset_id,mapping_status);
CREATE INDEX IF NOT EXISTS idx_listing_attributes_code ON listing_attributes(attribute_code,listing_id);
CREATE INDEX IF NOT EXISTS idx_market_metrics_task_dimension ON market_metrics(task_id,metric_code,dimension_type);
CREATE INDEX IF NOT EXISTS idx_market_metrics_period ON market_metrics(task_id,period_start,period_end);
CREATE INDEX IF NOT EXISTS idx_price_bands_task ON price_bands(task_id,currency,lower_bound);
CREATE INDEX IF NOT EXISTS idx_prompt_templates_active ON prompt_templates(task_type,status,code);
CREATE INDEX IF NOT EXISTS idx_opportunity_scores_rank ON opportunity_scores(recommendation_level,base_score DESC,confidence DESC);
CREATE INDEX IF NOT EXISTS idx_manufacturing_requirements_opportunity ON manufacturing_requirements(opportunity_id,priority);
CREATE INDEX IF NOT EXISTS idx_enterprise_fit_status ON enterprise_fit_details(opportunity_id,fit_status,hard_constraint_breached);
CREATE INDEX IF NOT EXISTS idx_validation_tasks_owner ON validation_tasks(owner_id,status,due_date);
CREATE INDEX IF NOT EXISTS idx_report_reviews_report ON report_reviews(report_id,reviewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_compute_quotas_tenant_period ON compute_quotas(tenant_id,period_start,period_end);
CREATE INDEX IF NOT EXISTS idx_product_events_tenant_name_time ON product_events(tenant_id,event_name,occurred_at DESC);

INSERT INTO roles(code,name,permissions) VALUES
  ('owner','企业负责人','[]'::jsonb),
  ('product_rd','产品研发','[]'::jsonb),
  ('market_ops','市场运营','[]'::jsonb),
  ('sales','外贸销售','[]'::jsonb),
  ('admin','系统管理员','[]'::jsonb)
ON CONFLICT(code) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_file_assets_owner ON file_assets(tenant_id,owner_type,owner_id);
CREATE INDEX IF NOT EXISTS idx_parse_jobs_product_status ON product_parse_jobs(tenant_id,product_id,status,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_parse_job_files_status ON product_parse_job_files(parse_job_id,parse_status);
CREATE INDEX IF NOT EXISTS idx_workflow_checkpoints_safe ON workflow_checkpoints(task_id,is_safe_resume,status,checkpoint_version DESC);
CREATE INDEX IF NOT EXISTS idx_partial_failures_open ON workflow_partial_failures(task_id,resolved_status,retryable,stage_code);
CREATE INDEX IF NOT EXISTS idx_control_events_outbox ON workflow_control_events(status,requested_at);
CREATE INDEX IF NOT EXISTS idx_control_events_task ON workflow_control_events(task_id,event_type,status);
CREATE INDEX IF NOT EXISTS idx_competitor_confirmations_task ON competitor_set_confirmations(task_id,version_no DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_tasks_checkpoint ON analysis_tasks(tenant_id,status,checkpoint_stage);
CREATE INDEX IF NOT EXISTS idx_analysis_tasks_cancel ON analysis_tasks(cancel_requested,status) WHERE cancel_requested = TRUE;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'tenants','users','enterprise_profiles','manufacturing_capabilities','products',
    'product_attributes','market_datasets','competitor_listings','competitor_matches',
    'analysis_tasks','product_recommendations','analysis_reports','listing_generation_records',
    'file_assets','product_parse_jobs','product_parse_job_files','roles','enterprise_constraints',
    'product_profile_versions','dataset_field_mappings','listing_attributes','prompt_templates',
    'manufacturing_requirements','validation_tasks','report_sections','model_route_configs','compute_quotas'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON %I', table_name, table_name);
    EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', table_name, table_name);
  END LOOP;
END;
$$;

COMMIT;
