-- FurniScope PostgreSQL Database Schema V3.0
-- Product: Cross-border Furniture Super AI Employee
-- Target: PostgreSQL 16+
-- Security: no default password, API key, model credential or secret is inserted.

BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS furniscope;
SET search_path TO furniscope, public;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION jsonb_option_has_code(items JSONB, expected_code TEXT) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT EXISTS (SELECT 1 FROM jsonb_array_elements(items) item WHERE item->>'code'=expected_code)
$$;

CREATE TABLE tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_code VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  display_name VARCHAR(100),
  industry VARCHAR(64) NOT NULL DEFAULT 'furniture_manufacturing',
  default_timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  default_currency CHAR(3) NOT NULL DEFAULT 'CNY',
  status VARCHAR(16) NOT NULL DEFAULT 'trial',
  data_retention_days INTEGER NOT NULL DEFAULT 365,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_tenant_code CHECK (tenant_code ~ '^[A-Z0-9_]+$'),
  CONSTRAINT chk_tenant_status CHECK (status IN ('trial','active','suspended','closed')),
  CONSTRAINT chk_tenant_retention CHECK (data_retention_days > 0)
);
COMMENT ON TABLE tenants IS 'V3 tenant isolation boundary; every business object belongs to one tenant.';
COMMENT ON COLUMN tenants.tenant_code IS 'Globally unique operational tenant code.';

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(32),
  name VARCHAR(100) NOT NULL,
  department VARCHAR(100),
  job_title VARCHAR(100),
  role_code VARCHAR(16) NOT NULL DEFAULT 'user',
  locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
  timezone VARCHAR(64),
  status VARCHAR(16) NOT NULL DEFAULT 'invited',
  last_login_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_users_email UNIQUE (email),
  CONSTRAINT chk_users_role CHECK (role_code IN ('user','admin')),
  CONSTRAINT chk_users_status CHECK (status IN ('invited','active','disabled','locked')),
  CONSTRAINT chk_users_email_lower CHECK (email = lower(email))
);
COMMENT ON TABLE users IS 'System users with exactly one static role: user or admin.';
COMMENT ON COLUMN users.role_code IS 'Only user/admin; job_title and department never affect authorization.';
COMMENT ON COLUMN users.email IS 'Globally unique login identity; tenant_id is resolved by the server after email lookup.';
COMMENT ON COLUMN users.password_hash IS 'Hash produced by the authentication subsystem; never plaintext and no SQL default.';
CREATE INDEX idx_users_tenant_role_status ON users(tenant_id,role_code,status);

CREATE TABLE auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash CHAR(64) NOT NULL UNIQUE,
  token_family_uuid UUID NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  last_used_at TIMESTAMPTZ(3),
  revoked_at TIMESTAMPTZ(3),
  revoke_reason VARCHAR(64),
  replaced_by_session_uuid UUID,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_auth_token_hash CHECK(refresh_token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_auth_expiry CHECK(expires_at>created_at),
  CONSTRAINT chk_auth_revoke CHECK((revoked_at IS NULL)=(revoke_reason IS NULL))
);
COMMENT ON TABLE auth_sessions IS 'Rotating refresh-token sessions; only SHA-256 token hashes are persisted.';
COMMENT ON COLUMN auth_sessions.refresh_token_hash IS 'One-way hash only; access and refresh token plaintext is never stored.';
CREATE INDEX idx_auth_sessions_user_active ON auth_sessions(tenant_id,user_id,expires_at DESC) WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_sessions_family ON auth_sessions(token_family_uuid,created_at);

CREATE TABLE password_reset_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  email VARCHAR(254) NOT NULL,
  code_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  consumed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_password_reset_hash CHECK (code_hash ~ '^[0-9a-f]{64}$')
);
COMMENT ON TABLE password_reset_requests IS 'One-time password reset codes stored as SHA-256 hashes; plaintext codes are never persisted.';
CREATE INDEX idx_password_reset_user_active ON password_reset_requests(user_id, created_at DESC);

CREATE TABLE api_idempotency_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  actor_user_id BIGINT NOT NULL REFERENCES users(id),
  route_code VARCHAR(32) NOT NULL,
  http_method VARCHAR(8) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'processing',
  resource_type VARCHAR(64),
  resource_public_id VARCHAR(128),
  response_status INTEGER,
  response_body JSONB,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_api_idempotency_scope UNIQUE(tenant_id,route_code,idempotency_key),
  CONSTRAINT chk_api_idempotency_method CHECK(http_method IN ('POST','PUT','PATCH','DELETE')),
  CONSTRAINT chk_api_idempotency_hash CHECK(request_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_api_idempotency_status CHECK(status IN ('processing','completed','failed')),
  CONSTRAINT chk_api_idempotency_response CHECK(
    (status='processing' AND response_status IS NULL AND response_body IS NULL)
    OR (status IN ('completed','failed') AND response_status BETWEEN 200 AND 599 AND response_body IS NOT NULL)
  ),
  CONSTRAINT chk_api_idempotency_expiry CHECK(expires_at>created_at)
);
COMMENT ON TABLE api_idempotency_records IS 'Tenant-scoped durable HTTP idempotency ledger; never stores credentials, tokens, file bytes or review text.';
COMMENT ON COLUMN api_idempotency_records.response_body IS 'Sanitized API Envelope only; authentication endpoints are excluded.';
CREATE INDEX idx_api_idempotency_expiry ON api_idempotency_records(expires_at);
CREATE INDEX idx_api_idempotency_resource ON api_idempotency_records(tenant_id,resource_type,resource_public_id);

CREATE TABLE enterprise_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL UNIQUE REFERENCES tenants(id),
  business_model JSONB NOT NULL DEFAULT '[]'::jsonb,
  primary_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  export_markets JSONB NOT NULL DEFAULT '[]'::jsonb,
  sales_channels JSONB NOT NULL DEFAULT '[]'::jsonb,
  annual_capacity_note TEXT,
  constraints JSONB NOT NULL DEFAULT '[]'::jsonb,
  profile_completeness NUMERIC(5,4) NOT NULL DEFAULT 0,
  profile_version INTEGER NOT NULL DEFAULT 1,
  confirmed_by BIGINT REFERENCES users(id),
  confirmed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_enterprise_json_arrays CHECK (
    jsonb_typeof(business_model)='array' AND jsonb_typeof(primary_categories)='array' AND
    jsonb_typeof(export_markets)='array' AND jsonb_typeof(sales_channels)='array' AND
    jsonb_typeof(constraints)='array'
  ),
  CONSTRAINT chk_enterprise_completeness CHECK (profile_completeness BETWEEN 0 AND 1),
  CONSTRAINT chk_enterprise_profile_version CHECK (profile_version>=1),
  CONSTRAINT chk_enterprise_confirmation CHECK ((confirmed_by IS NULL)=(confirmed_at IS NULL))
);
COMMENT ON TABLE enterprise_profiles IS 'One enterprise profile per tenant; V2 enterprise_constraints are merged into constraints JSONB.';
COMMENT ON COLUMN enterprise_profiles.constraints IS 'Array schema: constraint_type, operator, value, unit, hardness, effective_at, expires_at, sensitivity_level.';

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  sku VARCHAR(100) NOT NULL,
  name VARCHAR(200) NOT NULL,
  category_code VARCHAR(100) NOT NULL DEFAULT 'sofa',
  lifecycle_status VARCHAR(24) NOT NULL DEFAULT 'active',
  analysis_status VARCHAR(24) NOT NULL DEFAULT 'draft',
  primary_image_id BIGINT,
  current_profile_version_id BIGINT,
  description TEXT,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3),
  CONSTRAINT uk_products_tenant_sku UNIQUE (tenant_id,sku),
  CONSTRAINT chk_product_lifecycle CHECK (lifecycle_status IN ('concept','sample','active','discontinued')),
  CONSTRAINT chk_product_analysis CHECK (analysis_status IN ('draft','profile_pending','ready','archived'))
);
COMMENT ON TABLE products IS 'Tenant product master; P0 category is sofa.';

CREATE TABLE file_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  owner_type VARCHAR(24) NOT NULL,
  owner_id BIGINT NOT NULL,
  asset_type VARCHAR(24) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  storage_key VARCHAR(512) NOT NULL UNIQUE,
  mime_type VARCHAR(100) NOT NULL,
  size_bytes BIGINT NOT NULL,
  sha256 CHAR(64) NOT NULL,
  security_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  parse_status VARCHAR(24) NOT NULL DEFAULT 'not_started',
  retention_until TIMESTAMPTZ(3),
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_asset_owner_type CHECK (owner_type IN ('product','capability','dataset','other')),
  CONSTRAINT chk_asset_type CHECK (asset_type IN ('image','pdf','spreadsheet','csv','json','cad','other')),
  CONSTRAINT chk_asset_size CHECK (size_bytes > 0),
  CONSTRAINT chk_asset_sha CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_asset_security CHECK (security_status IN ('pending','clean','rejected','quarantined')),
  CONSTRAINT chk_asset_parse CHECK (parse_status IN ('not_started','processing','succeeded','partial','failed'))
);
COMMENT ON TABLE file_assets IS 'Object-storage metadata; file bytes never reside in PostgreSQL.';
COMMENT ON COLUMN file_assets.storage_key IS 'Internal tenant-prefixed key; API returns only short-lived signed URLs.';
CREATE INDEX idx_file_assets_owner ON file_assets(tenant_id,owner_type,owner_id);
CREATE INDEX idx_file_assets_hash ON file_assets(tenant_id,sha256);

ALTER TABLE products ADD CONSTRAINT fk_products_primary_image FOREIGN KEY(primary_image_id) REFERENCES file_assets(id);

CREATE TABLE manufacturing_capabilities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  capability_type VARCHAR(32) NOT NULL,
  capability_code VARCHAR(100) NOT NULL,
  capability_name VARCHAR(200) NOT NULL,
  availability VARCHAR(16) NOT NULL DEFAULT 'unknown',
  min_value NUMERIC(18,4),
  max_value NUMERIC(18,4),
  unit VARCHAR(32),
  valid_from DATE,
  valid_until DATE,
  evidence_asset_id BIGINT REFERENCES file_assets(id),
  source_type VARCHAR(32) NOT NULL DEFAULT 'confirmed_user',
  confidence NUMERIC(5,4) NOT NULL DEFAULT 1,
  notes TEXT,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_capability_tenant_type_code UNIQUE(tenant_id,capability_type,capability_code),
  CONSTRAINT chk_capability_type CHECK (capability_type IN ('category','material','process','customization','packaging','certification','delivery','equipment')),
  CONSTRAINT chk_capability_availability CHECK (availability IN ('yes','no','unknown')),
  CONSTRAINT chk_capability_range CHECK (max_value IS NULL OR min_value IS NULL OR max_value>=min_value),
  CONSTRAINT chk_capability_dates CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until>=valid_from),
  CONSTRAINT chk_capability_confidence CHECK (confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE manufacturing_capabilities IS 'Versioned evidence-backed manufacturing capabilities; unknown is distinct from no.';

CREATE TABLE product_parse_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parse_job_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  current_stage VARCHAR(64) NOT NULL DEFAULT 'queued',
  progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  file_count INTEGER NOT NULL,
  succeeded_file_count INTEGER NOT NULL DEFAULT 0,
  failed_file_count INTEGER NOT NULL DEFAULT 0,
  retryable BOOLEAN NOT NULL DEFAULT FALSE,
  failure_code VARCHAR(100),
  failure_message VARCHAR(1000),
  idempotency_key VARCHAR(128) NOT NULL,
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_parse_job_tenant_idem UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_parse_status CHECK (status IN ('queued','running','partial_succeeded','succeeded','failed')),
  CONSTRAINT chk_parse_progress CHECK (progress_percent BETWEEN 0 AND 100),
  CONSTRAINT chk_parse_counts CHECK (file_count>0 AND succeeded_file_count>=0 AND failed_file_count>=0 AND succeeded_file_count+failed_file_count<=file_count)
);
COMMENT ON TABLE product_parse_jobs IS 'Persisted asynchronous product-document parsing job.';

CREATE TABLE product_parse_job_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  parse_job_id BIGINT NOT NULL REFERENCES product_parse_jobs(id) ON DELETE CASCADE,
  file_asset_id BIGINT NOT NULL REFERENCES file_assets(id),
  security_status VARCHAR(24) NOT NULL,
  parse_status VARCHAR(24) NOT NULL,
  output_ref JSONB,
  error_code VARCHAR(100),
  error_message VARCHAR(1000),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_parse_job_file UNIQUE(parse_job_id,file_asset_id),
  CONSTRAINT chk_parse_file_output CHECK (output_ref IS NULL OR jsonb_typeof(output_ref)='object')
);
COMMENT ON TABLE product_parse_job_files IS 'File-level secure parsing result and lightweight output reference.';

CREATE TABLE product_profile_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  product_id BIGINT NOT NULL REFERENCES products(id),
  version_no INTEGER NOT NULL,
  schema_version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  completeness_score NUMERIC(5,4) NOT NULL DEFAULT 0,
  conflict_count INTEGER NOT NULL DEFAULT 0,
  source_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  confirmed_by BIGINT REFERENCES users(id),
  confirmed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_profile_product_version UNIQUE(product_id,version_no),
  CONSTRAINT chk_profile_status CHECK (status IN ('draft','parsed','confirmed','superseded')),
  CONSTRAINT chk_profile_complete CHECK (completeness_score BETWEEN 0 AND 1),
  CONSTRAINT chk_profile_conflicts CHECK (conflict_count>=0),
  CONSTRAINT chk_profile_source CHECK (jsonb_typeof(source_summary)='object'),
  CONSTRAINT chk_profile_confirmation CHECK (status<>'confirmed' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL))
);
COMMENT ON TABLE product_profile_versions IS 'Immutable product profile versions frozen into analysis tasks.';
ALTER TABLE products ADD CONSTRAINT fk_products_profile FOREIGN KEY(current_profile_version_id) REFERENCES product_profile_versions(id);

CREATE TABLE product_attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  profile_version_id BIGINT NOT NULL REFERENCES product_profile_versions(id) ON DELETE CASCADE,
  attribute_code VARCHAR(100) NOT NULL,
  value JSONB NOT NULL,
  unit VARCHAR(32),
  source_type VARCHAR(32) NOT NULL,
  source_asset_id BIGINT REFERENCES file_assets(id),
  source_locator JSONB,
  confidence NUMERIC(5,4) NOT NULL,
  confirmation_status VARCHAR(24) NOT NULL DEFAULT 'unconfirmed',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_product_attribute UNIQUE(profile_version_id,attribute_code),
  CONSTRAINT chk_product_attr_source CHECK (source_type IN ('confirmed_structured','user_input','document','image','inferred')),
  CONSTRAINT chk_product_attr_conf CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_product_attr_confirmation CHECK (confirmation_status IN ('unconfirmed','confirmed','conflicted','unknown'))
);
COMMENT ON TABLE product_attributes IS 'Normalized product attributes with source, confidence and confirmation state.';

CREATE TABLE market_datasets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(200) NOT NULL,
  version_no INTEGER NOT NULL DEFAULT 1,
  platform VARCHAR(32) NOT NULL,
  market_country CHAR(2) NOT NULL,
  marketplace_code VARCHAR(50),
  category_code VARCHAR(100) NOT NULL,
  data_start_date DATE,
  data_end_date DATE NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_name VARCHAR(200) NOT NULL,
  authorization_reference TEXT,
  import_asset_id BIGINT REFERENCES file_assets(id),
  field_mapping JSONB NOT NULL DEFAULT '[]'::jsonb,
  status VARCHAR(24) NOT NULL DEFAULT 'uploaded',
  listing_count INTEGER NOT NULL DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  valid_review_count INTEGER NOT NULL DEFAULT 0,
  quality_score NUMERIC(5,2) NOT NULL DEFAULT 0,
  quality_report JSONB NOT NULL DEFAULT '{}'::jsonb,
  limitations JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3),
  CONSTRAINT uk_dataset_tenant_name_version UNIQUE(tenant_id,name,version_no),
  CONSTRAINT chk_dataset_dates CHECK (data_start_date IS NULL OR data_end_date>=data_start_date),
  CONSTRAINT chk_dataset_source CHECK (source_type IN ('enterprise_export','licensed_provider','public_authorized','demo_synthetic')),
  CONSTRAINT chk_dataset_status CHECK (status IN ('uploaded','validating','ready','rejected','archived')),
  CONSTRAINT chk_dataset_counts CHECK (listing_count>=0 AND review_count>=0 AND valid_review_count BETWEEN 0 AND review_count),
  CONSTRAINT chk_dataset_quality CHECK (quality_score BETWEEN 0 AND 100),
  CONSTRAINT chk_dataset_json CHECK (jsonb_typeof(field_mapping)='array' AND jsonb_typeof(quality_report)='object' AND jsonb_typeof(limitations)='array')
);
COMMENT ON TABLE market_datasets IS 'Authorized versioned market dataset; V2 field mappings are merged into field_mapping.';
COMMENT ON COLUMN market_datasets.field_mapping IS 'Array of source_field,target_entity,target_field,transform_rule,mapping_status; transformations are whitelist-only.';
CREATE INDEX idx_dataset_tenant_market_status ON market_datasets(tenant_id,platform,market_country,status);

CREATE TABLE market_listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  dataset_id BIGINT NOT NULL REFERENCES market_datasets(id) ON DELETE CASCADE,
  platform_listing_id VARCHAR(200) NOT NULL,
  listing_url VARCHAR(1000),
  brand VARCHAR(200), seller_name VARCHAR(200),
  title TEXT NOT NULL, description TEXT,
  bullet_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  category_raw VARCHAR(300), category_code VARCHAR(100) NOT NULL,
  image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  currency CHAR(3) NOT NULL,
  list_price NUMERIC(18,4), sale_price NUMERIC(18,4) NOT NULL,
  coupon_value JSONB,
  rating NUMERIC(3,2), rating_count INTEGER, review_count INTEGER,
  rank_value INTEGER, rank_category VARCHAR(300),
  captured_at TIMESTAMPTZ(3) NOT NULL,
  first_available_date DATE,
  normalized_attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
  raw_payload JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_listing_dataset_platform_capture UNIQUE(dataset_id,platform_listing_id,captured_at),
  CONSTRAINT chk_listing_price CHECK (sale_price>=0 AND (list_price IS NULL OR list_price>=0)),
  CONSTRAINT chk_listing_rating CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
  CONSTRAINT chk_listing_counts CHECK ((rating_count IS NULL OR rating_count>=0) AND (review_count IS NULL OR review_count>=0)),
  CONSTRAINT chk_listing_json CHECK (jsonb_typeof(bullet_points)='array' AND jsonb_typeof(image_urls)='array' AND jsonb_typeof(normalized_attributes)='object'),
  CONSTRAINT chk_listing_rank CHECK (rank_value IS NULL OR rank_category IS NOT NULL)
);
COMMENT ON TABLE market_listings IS 'Competitor listing snapshots; V2 listing_attributes are merged into normalized_attributes.';
COMMENT ON COLUMN market_listings.normalized_attributes IS 'Object keyed by attribute_code; each value includes value,unit,source_locator,confidence.';
CREATE INDEX idx_listing_dataset_price ON market_listings(dataset_id,currency,sale_price);
CREATE INDEX idx_listing_dataset_rating ON market_listings(dataset_id,rating,review_count);
CREATE INDEX idx_listing_normalized_attributes ON market_listings USING GIN(normalized_attributes);

CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  dataset_id BIGINT NOT NULL REFERENCES market_datasets(id) ON DELETE CASCADE,
  listing_id BIGINT NOT NULL REFERENCES market_listings(id) ON DELETE CASCADE,
  platform_review_id VARCHAR(200) NOT NULL,
  rating NUMERIC(3,2),
  title_original TEXT,
  content_original TEXT NOT NULL,
  language_code VARCHAR(16) NOT NULL DEFAULT 'und',
  reviewer_location VARCHAR(100),
  sentiment VARCHAR(16),
  title_translated TEXT,
  content_translated TEXT,
  reviewed_at TIMESTAMPTZ(3),
  verified_purchase BOOLEAN,
  helpful_count INTEGER,
  is_valid BOOLEAN NOT NULL DEFAULT TRUE,
  invalid_reason VARCHAR(100),
  content_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_review_dataset_platform_id UNIQUE(dataset_id,platform_review_id),
  CONSTRAINT uk_review_dataset_hash UNIQUE(dataset_id,content_hash),
  CONSTRAINT chk_review_rating CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
  CONSTRAINT chk_review_helpful CHECK (helpful_count IS NULL OR helpful_count>=0),
  CONSTRAINT chk_review_valid_reason CHECK (is_valid OR invalid_reason IS NOT NULL),
  CONSTRAINT chk_review_hash CHECK (content_hash ~ '^[0-9a-f]{64}$')
);
COMMENT ON TABLE reviews IS 'Immutable original competitor reviews; translations are stored separately.';
COMMENT ON COLUMN reviews.content_original IS 'Protected original text used for all evidence spans; never overwritten by translation or AI.';
CREATE INDEX idx_review_listing_valid_time ON reviews(listing_id,is_valid,reviewed_at);
CREATE INDEX idx_review_dataset_rating_valid ON reviews(dataset_id,rating,is_valid);

CREATE TABLE prompt_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  version VARCHAR(64) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  template_content TEXT NOT NULL,
  output_schema JSONB,
  status VARCHAR(16) NOT NULL DEFAULT 'draft',
  evaluation_set_version VARCHAR(64),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_prompt_version UNIQUE(code,version),
  CONSTRAINT chk_prompt_status CHECK (status IN ('draft','testing','active','retired')),
  CONSTRAINT chk_prompt_schema CHECK (output_schema IS NULL OR jsonb_typeof(output_schema)='object'),
  CONSTRAINT chk_prompt_active CHECK (status<>'active' OR evaluation_set_version IS NOT NULL)
);
COMMENT ON TABLE prompt_templates IS 'Immutable versioned prompts; credentials are never stored here.';

CREATE TABLE model_route_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(32) NOT NULL,
  config_version VARCHAR(64) NOT NULL,
  primary_model_id VARCHAR(200) NOT NULL,
  fallback_model_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  timeout_ms INTEGER NOT NULL,
  max_retries INTEGER NOT NULL,
  batch_size INTEGER,
  concurrency_limit INTEGER NOT NULL,
  compute_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_model_route_version UNIQUE(task_type,config_version),
  CONSTRAINT chk_model_route_json CHECK (jsonb_typeof(fallback_model_ids)='array' AND jsonb_typeof(compute_config)='object'),
  CONSTRAINT chk_model_route_timeout CHECK (timeout_ms>0),
  CONSTRAINT chk_model_route_retry CHECK (max_retries BETWEEN 0 AND 5),
  CONSTRAINT chk_model_route_batch CHECK (batch_size IS NULL OR batch_size>=1),
  CONSTRAINT chk_model_route_concurrency CHECK (concurrency_limit>=1)
);
CREATE UNIQUE INDEX uk_model_route_active ON model_route_configs(task_type) WHERE active;
COMMENT ON TABLE model_route_configs IS 'Admin-managed model and compute configuration; no API keys or secrets.';
COMMENT ON COLUMN model_route_configs.compute_config IS 'Schema: quota_unit,quota_total,warning_threshold,hard_limit; usage is aggregated from ai_model_runs.';

CREATE TABLE analysis_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  job_name VARCHAR(200) NOT NULL,
  job_type VARCHAR(32) NOT NULL DEFAULT 'product_market_fit',
  product_id BIGINT NOT NULL REFERENCES products(id),
  product_profile_version_id BIGINT NOT NULL REFERENCES product_profile_versions(id),
  dataset_id BIGINT NOT NULL REFERENCES market_datasets(id),
  target_country CHAR(2) NOT NULL,
  target_platform VARCHAR(32) NOT NULL,
  analysis_currency CHAR(3) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  external_stage VARCHAR(40) NOT NULL DEFAULT 'understanding_product',
  internal_stage VARCHAR(64) NOT NULL DEFAULT 'task_initializing',
  progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  checkpoint_stage VARCHAR(64),
  analysis_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  enterprise_profile_version INTEGER NOT NULL DEFAULT 0,
  enterprise_profile_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  ontology_version VARCHAR(64) NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  prompt_bundle_version VARCHAR(64) NOT NULL,
  model_route_version VARCHAR(64) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  started_at TIMESTAMPTZ(3), completed_at TIMESTAMPTZ(3),
  failure_code VARCHAR(100), failure_message TEXT,
  created_by BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_task_tenant_idem UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_task_type CHECK (job_type IN ('product_market_fit','product_improvement')),
  CONSTRAINT chk_task_status CHECK (status IN ('draft','queued','running','waiting_human','partial_succeeded','succeeded','failed','cancelled')),
  CONSTRAINT chk_task_external_stage CHECK (external_stage IN ('understanding_product','researching_market','evaluating_opportunity','generating_recommendation','completed')),
  CONSTRAINT chk_task_internal_stage CHECK (internal_stage IN ('task_initializing','preflight_check','context_loading','data_quality','competitor_filtering','competitor_embedding','competitor_reranking','user_confirmation','review_preprocessing','review_extracting','need_clustering','market_analytics','opportunity_scoring','strategy_generating','evidence_auditing','report_generating','persisting','completed')),
  CONSTRAINT chk_task_progress CHECK (progress_percent BETWEEN 0 AND 100),
  CONSTRAINT chk_task_config CHECK (jsonb_typeof(analysis_config)='object'),
  CONSTRAINT chk_task_enterprise_snapshot CHECK (jsonb_typeof(enterprise_profile_snapshot)='object' AND enterprise_profile_version>=0),
  CONSTRAINT chk_task_complete CHECK (status<>'succeeded' OR (external_stage='completed' AND progress_percent=100 AND completed_at IS NOT NULL))
);
COMMENT ON TABLE analysis_tasks IS 'Super AI employee analysis tasks with internal state and five-stage external projection.';
COMMENT ON COLUMN analysis_tasks.external_stage IS 'Only the five PRD V2 user-visible stages.';
COMMENT ON COLUMN analysis_tasks.internal_stage IS 'LangGraph internal stage; competitor_review/expert_review are forbidden.';
CREATE INDEX idx_task_tenant_status_time ON analysis_tasks(tenant_id,status,updated_at DESC);
CREATE INDEX idx_task_tenant_external_stage ON analysis_tasks(tenant_id,external_stage,status);
CREATE INDEX idx_task_product_time ON analysis_tasks(tenant_id,product_id,created_at DESC);

CREATE TABLE task_stage_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_code VARCHAR(64) NOT NULL,
  attempt_no INTEGER NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(128) NOT NULL UNIQUE,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  input_ref JSONB NOT NULL,
  output_ref JSONB,
  started_at TIMESTAMPTZ(3), ended_at TIMESTAMPTZ(3),
  error_code VARCHAR(100), error_message VARCHAR(1000),
  retryable BOOLEAN,
  retry_parent_run_id BIGINT REFERENCES task_stage_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_stage_task_attempt UNIQUE(task_id,stage_code,attempt_no),
  CONSTRAINT chk_stage_status CHECK (status IN ('queued','running','waiting_human','retry_scheduled','succeeded','partial_succeeded','failed','skipped','cancelled')),
  CONSTRAINT chk_stage_attempt CHECK (attempt_no>=1),
  CONSTRAINT chk_stage_refs CHECK (jsonb_typeof(input_ref)='object' AND (output_ref IS NULL OR jsonb_typeof(output_ref)='object')),
  CONSTRAINT chk_stage_time CHECK (ended_at IS NULL OR started_at IS NULL OR ended_at>=started_at),
  CONSTRAINT chk_stage_error CHECK (status NOT IN ('failed','retry_scheduled') OR error_code IS NOT NULL)
);
COMMENT ON TABLE task_stage_runs IS 'Immutable attempts for LangGraph internal stages; automatic retries create new attempts.';
CREATE INDEX idx_stage_task_status ON task_stage_runs(task_id,status,stage_code);

CREATE TABLE workflow_checkpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkpoint_id VARCHAR(128) NOT NULL UNIQUE,
  thread_id VARCHAR(128) NOT NULL,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_code VARCHAR(64) NOT NULL,
  checkpoint_version BIGINT NOT NULL,
  state_snapshot JSONB NOT NULL,
  state_hash CHAR(64) NOT NULL,
  is_safe_resume BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consumed_at TIMESTAMPTZ(3),
  CONSTRAINT uk_checkpoint_task_version UNIQUE(task_id,checkpoint_version),
  CONSTRAINT chk_checkpoint_state CHECK (jsonb_typeof(state_snapshot)='object'),
  CONSTRAINT chk_checkpoint_hash CHECK (state_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_checkpoint_status CHECK (status IN ('active','consumed','superseded','corrupted'))
);
COMMENT ON TABLE workflow_checkpoints IS 'Business-safe checkpoint projection; separate from LangGraph official checkpointer tables.';
COMMENT ON COLUMN workflow_checkpoints.state_snapshot IS 'Lightweight IDs, versions and references only; never review text, file bytes or vectors.';
CREATE INDEX idx_checkpoint_task_safe_version ON workflow_checkpoints(task_id,is_safe_resume,checkpoint_version DESC);

CREATE TABLE workflow_partial_failures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_run_id BIGINT NOT NULL REFERENCES task_stage_runs(id),
  stage_code VARCHAR(64) NOT NULL,
  unit_type VARCHAR(24) NOT NULL,
  failed_unit_ids JSONB NOT NULL,
  failed_count INTEGER NOT NULL,
  total_count INTEGER NOT NULL,
  impact VARCHAR(1000) NOT NULL,
  confidence_cap NUMERIC(5,4),
  retryable BOOLEAN NOT NULL,
  resolved_status VARCHAR(24) NOT NULL DEFAULT 'open',
  resolved_stage_run_id BIGINT REFERENCES task_stage_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMPTZ(3),
  CONSTRAINT chk_partial_unit CHECK (unit_type IN ('review_batch','opportunity','model_call','file','branch','other')),
  CONSTRAINT chk_partial_ids CHECK (jsonb_typeof(failed_unit_ids)='array' AND jsonb_array_length(failed_unit_ids)>0),
  CONSTRAINT chk_partial_count CHECK (failed_count>0 AND total_count>=failed_count),
  CONSTRAINT chk_partial_cap CHECK (confidence_cap IS NULL OR confidence_cap BETWEEN 0 AND 1),
  CONSTRAINT chk_partial_status CHECK (resolved_status IN ('open','retry_scheduled','resolved','accepted_limit'))
);
COMMENT ON TABLE workflow_partial_failures IS 'Persisted non-blocking batch or branch failures and their impact on confidence.';
CREATE INDEX idx_partial_failure_task_open ON workflow_partial_failures(task_id,resolved_status);

CREATE TABLE user_confirmations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  confirmation_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  confirmation_type VARCHAR(32) NOT NULL,
  question TEXT NOT NULL,
  recommended_option VARCHAR(100) NOT NULL,
  options JSONB NOT NULL,
  evidence_refs JSONB NOT NULL,
  impact JSONB NOT NULL,
  checkpoint_stage VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(3),
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  selected_option VARCHAR(100),
  user_input JSONB,
  responded_by BIGINT REFERENCES users(id),
  responded_at TIMESTAMPTZ(3),
  idempotency_key VARCHAR(128) NOT NULL,
  checkpoint_id VARCHAR(128) REFERENCES workflow_checkpoints(checkpoint_id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_confirmation_tenant_idem UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_confirmation_type CHECK (confirmation_type IN ('fact_conflict','insufficient_data','low_confidence','high_risk_recommendation')),
  CONSTRAINT chk_confirmation_json CHECK (jsonb_typeof(options)='array' AND jsonb_array_length(options)>0 AND jsonb_typeof(evidence_refs)='array' AND jsonb_array_length(evidence_refs)>0 AND jsonb_typeof(impact) IN ('object','string')),
  CONSTRAINT chk_confirmation_status CHECK (status IN ('pending','responded','expired','cancelled')),
  CONSTRAINT chk_confirmation_response CHECK ((status='responded')=(selected_option IS NOT NULL AND responded_by IS NOT NULL AND responded_at IS NOT NULL)),
  CONSTRAINT chk_confirmation_option CHECK (jsonb_option_has_code(options,recommended_option)),
  CONSTRAINT chk_confirmation_selected CHECK (selected_option IS NULL OR jsonb_option_has_code(options,selected_option))
);
CREATE UNIQUE INDEX uk_confirmation_pending_task ON user_confirmations(task_id) WHERE status='pending';
CREATE INDEX idx_confirmation_tenant_status_expire ON user_confirmations(tenant_id,status,expires_at);
COMMENT ON TABLE user_confirmations IS 'Single user_confirmation protocol replacing competitor review and expert review.';
COMMENT ON COLUMN user_confirmations.checkpoint_stage IS 'Internal safe stage used by Command(resume=...).';

CREATE TABLE workflow_control_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  event_type VARCHAR(32) NOT NULL,
  checkpoint_id VARCHAR(128) REFERENCES workflow_checkpoints(checkpoint_id),
  stage_code VARCHAR(64),
  payload JSONB NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  delivery_attempts INTEGER NOT NULL DEFAULT 0,
  enqueued_at TIMESTAMPTZ(3),
  requested_by BIGINT REFERENCES users(id),
  requested_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  consumed_at TIMESTAMPTZ(3),
  error_code VARCHAR(100),
  CONSTRAINT uk_control_tenant_idem UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_control_type CHECK (event_type IN ('resume_confirmation','auto_retry','safe_stop')),
  CONSTRAINT chk_control_payload CHECK (jsonb_typeof(payload)='object'),
  CONSTRAINT chk_control_status CHECK (status IN ('pending','enqueued','consumed','failed','cancelled')),
  CONSTRAINT chk_control_delivery CHECK(delivery_attempts>=0 AND (status<>'enqueued' OR enqueued_at IS NOT NULL)),
  CONSTRAINT chk_control_failure CHECK (status<>'failed' OR error_code IS NOT NULL)
);
COMMENT ON TABLE workflow_control_events IS 'Transactional outbox for supervisor-controlled resume, retry and safe stop.';
CREATE INDEX idx_control_status_time ON workflow_control_events(status,requested_at);

CREATE TABLE ai_model_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  stage_run_id BIGINT REFERENCES task_stage_runs(id),
  provider VARCHAR(100) NOT NULL DEFAULT 'aliyun_model_router',
  model_id VARCHAR(200) NOT NULL,
  task_type VARCHAR(32) NOT NULL,
  prompt_template_id BIGINT REFERENCES prompt_templates(id),
  prompt_version VARCHAR(64),
  input_hash CHAR(64) NOT NULL,
  output_schema_version VARCHAR(64),
  input_tokens INTEGER, output_tokens INTEGER,
  image_count INTEGER NOT NULL DEFAULT 0,
  latency_ms INTEGER NOT NULL DEFAULT 0,
  estimated_cost NUMERIC(18,8), cost_unit VARCHAR(16),
  status VARCHAR(24) NOT NULL,
  retry_count INTEGER NOT NULL DEFAULT 0,
  schema_valid BOOLEAN,
  error_code VARCHAR(100), error_message VARCHAR(1000),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_model_task_type CHECK (task_type IN ('vision_extract','text_extract','translate','embed','rerank','reason','report')),
  CONSTRAINT chk_model_status CHECK (status IN ('queued','running','succeeded','schema_failed','rate_limited','timeout','content_blocked','failed','cached')),
  CONSTRAINT chk_model_counts CHECK ((input_tokens IS NULL OR input_tokens>=0) AND (output_tokens IS NULL OR output_tokens>=0) AND image_count>=0 AND latency_ms>=0 AND retry_count>=0),
  CONSTRAINT chk_model_hash CHECK (input_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_model_cost CHECK ((estimated_cost IS NULL)=(cost_unit IS NULL))
);
COMMENT ON TABLE ai_model_runs IS 'Actual model, prompt, token, latency, cost, retry and schema trace for every AI call.';
CREATE INDEX idx_model_run_task_type_status ON ai_model_runs(task_id,task_type,status);

CREATE TABLE competitor_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  listing_id BIGINT NOT NULL REFERENCES market_listings(id),
  product_profile_version_id BIGINT NOT NULL REFERENCES product_profile_versions(id),
  competitor_type VARCHAR(16) NOT NULL,
  category_score NUMERIC(5,2) NOT NULL, function_score NUMERIC(5,2) NOT NULL,
  style_score NUMERIC(5,2) NOT NULL, price_score NUMERIC(5,2) NOT NULL,
  material_score NUMERIC(5,2) NOT NULL, scenario_score NUMERIC(5,2) NOT NULL,
  overall_score NUMERIC(5,2) NOT NULL, rerank_score NUMERIC(8,6),
  match_reasons JSONB NOT NULL,
  set_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_match_task_listing_version UNIQUE(analysis_job_id,listing_id,set_version),
  CONSTRAINT chk_match_type CHECK (competitor_type IN ('direct','benchmark','substitute','excluded')),
  CONSTRAINT chk_match_scores CHECK (category_score BETWEEN 0 AND 100 AND function_score BETWEEN 0 AND 100 AND style_score BETWEEN 0 AND 100 AND price_score BETWEEN 0 AND 100 AND material_score BETWEEN 0 AND 100 AND scenario_score BETWEEN 0 AND 100 AND overall_score BETWEEN 0 AND 100),
  CONSTRAINT chk_match_reasons CHECK (jsonb_typeof(match_reasons)='array')
);
COMMENT ON TABLE competitor_matches IS 'Versioned autonomous or user-confirmed competitor set; no role review fields.';
CREATE INDEX idx_match_task_type_score ON competitor_matches(analysis_job_id,competitor_type,overall_score DESC);

CREATE TABLE review_aspects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  review_id BIGINT NOT NULL REFERENCES reviews(id),
  aspect_index INTEGER NOT NULL,
  taxonomy_code VARCHAR(100) NOT NULL,
  sentiment VARCHAR(16) NOT NULL,
  severity VARCHAR(16),
  person_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  scenario_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  product_attribute_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  evidence_start INTEGER NOT NULL,
  evidence_end INTEGER NOT NULL,
  evidence_quote TEXT NOT NULL,
  extraction_confidence NUMERIC(5,4) NOT NULL,
  model_run_id BIGINT NOT NULL REFERENCES ai_model_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_aspect_task_review_index UNIQUE(analysis_job_id,review_id,aspect_index),
  CONSTRAINT chk_aspect_sentiment CHECK (sentiment IN ('positive','negative','neutral','mixed')),
  CONSTRAINT chk_aspect_json CHECK (jsonb_typeof(person_codes)='array' AND jsonb_typeof(scenario_codes)='array' AND jsonb_typeof(product_attribute_codes)='array'),
  CONSTRAINT chk_aspect_span CHECK (evidence_start>=0 AND evidence_end>evidence_start),
  CONSTRAINT chk_aspect_conf CHECK (extraction_confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE review_aspects IS 'Aspect-level demand, sentiment, context and immutable original-text evidence span.';
COMMENT ON COLUMN review_aspects.evidence_start IS 'Unicode character offset into reviews.content_original.';
COMMENT ON COLUMN review_aspects.evidence_end IS 'Exclusive Unicode character offset into reviews.content_original.';

CREATE OR REPLACE FUNCTION validate_review_aspect_span() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE source_text TEXT;
BEGIN
  SELECT content_original INTO source_text FROM furniscope.reviews WHERE id=NEW.review_id;
  IF source_text IS NULL OR NEW.evidence_end > char_length(source_text) OR
     substring(source_text FROM NEW.evidence_start+1 FOR NEW.evidence_end-NEW.evidence_start) <> NEW.evidence_quote THEN
    RAISE EXCEPTION 'evidence span/quote does not match protected review original';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_validate_review_aspect_span BEFORE INSERT OR UPDATE OF review_id,evidence_start,evidence_end,evidence_quote ON review_aspects FOR EACH ROW EXECUTE FUNCTION validate_review_aspect_span();
CREATE INDEX idx_aspect_task_taxonomy_sentiment ON review_aspects(analysis_job_id,taxonomy_code,sentiment);

CREATE TABLE insight_clusters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  cluster_code VARCHAR(64) NOT NULL,
  taxonomy_code VARCHAR(100) NOT NULL,
  name VARCHAR(200) NOT NULL,
  summary TEXT NOT NULL,
  sentiment_distribution JSONB NOT NULL,
  aspect_count INTEGER NOT NULL, review_count INTEGER NOT NULL, listing_count INTEGER NOT NULL,
  mention_rate NUMERIC(7,6) NOT NULL,
  importance_score NUMERIC(5,2) NOT NULL,
  cluster_confidence NUMERIC(5,4) NOT NULL,
  representative_aspect_ids JSONB NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_cluster_task_code UNIQUE(analysis_job_id,cluster_code),
  CONSTRAINT chk_cluster_counts CHECK (aspect_count>0 AND review_count>0 AND review_count<=aspect_count AND listing_count>0),
  CONSTRAINT chk_cluster_rates CHECK (mention_rate BETWEEN 0 AND 1 AND importance_score BETWEEN 0 AND 100 AND cluster_confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_cluster_json CHECK (jsonb_typeof(sentiment_distribution)='object' AND jsonb_typeof(representative_aspect_ids)='array' AND jsonb_array_length(representative_aspect_ids)>0)
);
COMMENT ON TABLE insight_clusters IS 'Cross-review and cross-listing furniture need clusters with representative evidence.';
CREATE INDEX idx_cluster_task_importance ON insight_clusters(analysis_job_id,importance_score DESC);

CREATE TABLE cluster_members (
  cluster_id BIGINT NOT NULL REFERENCES insight_clusters(id) ON DELETE CASCADE,
  review_aspect_id BIGINT NOT NULL REFERENCES review_aspects(id) ON DELETE CASCADE,
  similarity_score NUMERIC(8,6) NOT NULL,
  is_representative BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY(cluster_id,review_aspect_id),
  CONSTRAINT chk_cluster_member_score CHECK (similarity_score BETWEEN 0 AND 1)
);
COMMENT ON TABLE cluster_members IS 'Many-to-many membership between demand clusters and review aspects.';

CREATE TABLE market_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  metric_code VARCHAR(100) NOT NULL,
  dimension_type VARCHAR(64) NOT NULL,
  dimension_value VARCHAR(200),
  metric_value NUMERIC(24,8),
  metric_json JSONB,
  numerator NUMERIC(24,8), denominator NUMERIC(24,8),
  unit VARCHAR(32),
  period_start TIMESTAMPTZ(3), period_end TIMESTAMPTZ(3),
  sample_size INTEGER NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  formula_version VARCHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_metric_value CHECK (metric_value IS NOT NULL OR metric_json IS NOT NULL),
  CONSTRAINT chk_metric_json CHECK (metric_json IS NULL OR jsonb_typeof(metric_json) IN ('object','array')),
  CONSTRAINT chk_metric_denominator CHECK (denominator IS NULL OR denominator>0),
  CONSTRAINT chk_metric_period CHECK (period_end IS NULL OR period_start IS NULL OR period_end>=period_start),
  CONSTRAINT chk_metric_sample_conf CHECK (sample_size>=0 AND confidence BETWEEN 0 AND 1)
);
COMMENT ON TABLE market_metrics IS 'Deterministic versioned market, price, brand, feature, demand and time metrics.';
CREATE INDEX idx_metric_task_code_dimension ON market_metrics(analysis_job_id,metric_code,dimension_type);

CREATE TABLE price_bands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  band_code VARCHAR(50) NOT NULL,
  currency CHAR(3) NOT NULL,
  lower_bound NUMERIC(18,4) NOT NULL,
  upper_bound NUMERIC(18,4),
  listing_count INTEGER NOT NULL,
  median_rating NUMERIC(3,2),
  review_share NUMERIC(7,6),
  feature_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_price_band_task_code UNIQUE(analysis_job_id,band_code),
  CONSTRAINT chk_price_band_bounds CHECK (lower_bound>=0 AND (upper_bound IS NULL OR upper_bound>lower_bound)),
  CONSTRAINT chk_price_band_values CHECK (listing_count>=0 AND (median_rating IS NULL OR median_rating BETWEEN 0 AND 5) AND (review_share IS NULL OR review_share BETWEEN 0 AND 1)),
  CONSTRAINT chk_price_band_features CHECK (jsonb_typeof(feature_codes)='array')
);
COMMENT ON TABLE price_bands IS 'Task-scoped deterministic price buckets and feature penetration.';

CREATE TABLE market_opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  opportunity_code VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL, description TEXT NOT NULL,
  target_country CHAR(2) NOT NULL, target_platform VARCHAR(32) NOT NULL,
  target_user_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  usage_scenario_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  primary_cluster_ids JSONB NOT NULL,
  price_band_id BIGINT REFERENCES price_bands(id),
  status VARCHAR(24) NOT NULL DEFAULT 'generated',
  demand_heat_score NUMERIC(5,2) NOT NULL,
  demand_growth_score NUMERIC(5,2),
  unmet_need_score NUMERIC(5,2) NOT NULL,
  competition_space_score NUMERIC(5,2) NOT NULL,
  profit_space_score NUMERIC(5,2),
  enterprise_fit_score NUMERIC(5,2) NOT NULL,
  enterprise_fit_confidence NUMERIC(5,4) NOT NULL DEFAULT 0.4,
  base_score NUMERIC(5,2) NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  recommendation_level VARCHAR(32) NOT NULL,
  weight_config JSONB NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  manufacturing_fit JSONB NOT NULL DEFAULT '[]'::jsonb,
  calculated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_opportunity_task_code UNIQUE(analysis_job_id,opportunity_code),
  CONSTRAINT chk_opportunity_status CHECK (status IN ('generated','data_needed')),
  CONSTRAINT chk_opportunity_scores CHECK (demand_heat_score BETWEEN 0 AND 100 AND (demand_growth_score IS NULL OR demand_growth_score BETWEEN 0 AND 100) AND unmet_need_score BETWEEN 0 AND 100 AND competition_space_score BETWEEN 0 AND 100 AND (profit_space_score IS NULL OR profit_space_score BETWEEN 0 AND 100) AND enterprise_fit_score BETWEEN 0 AND 100 AND base_score BETWEEN 0 AND 100),
  CONSTRAINT chk_opportunity_conf CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_opportunity_fit_confidence CHECK (enterprise_fit_confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_opportunity_level CHECK (recommendation_level IN ('prioritize_validate','collect_more_data','capability_gap','limited_opportunity')),
  CONSTRAINT chk_opportunity_json CHECK (jsonb_typeof(target_user_codes)='array' AND jsonb_typeof(usage_scenario_codes)='array' AND jsonb_typeof(primary_cluster_ids)='array' AND jsonb_array_length(primary_cluster_ids)>0 AND jsonb_typeof(weight_config)='object' AND jsonb_typeof(manufacturing_fit)='array')
);
COMMENT ON TABLE market_opportunities IS 'Opportunity, six scores, independent confidence and merged manufacturing fit.';
COMMENT ON COLUMN market_opportunities.manufacturing_fit IS 'Array merging V2 manufacturing requirements and enterprise fit details; indexed fields remain top-level scores.';
CREATE INDEX idx_opportunity_task_score_conf ON market_opportunities(analysis_job_id,base_score DESC,confidence DESC);
CREATE INDEX idx_opportunity_manufacturing_fit ON market_opportunities USING GIN(manufacturing_fit);

CREATE TABLE product_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  opportunity_id BIGINT NOT NULL REFERENCES market_opportunities(id) ON DELETE CASCADE,
  recommendation_type VARCHAR(24) NOT NULL,
  problem_statement TEXT NOT NULL,
  root_cause_hypotheses JSONB NOT NULL,
  recommended_action TEXT NOT NULL,
  target_attribute_code VARCHAR(100), target_value JSONB,
  expected_benefit TEXT NOT NULL,
  impact_dimensions JSONB NOT NULL,
  cost_impact_min NUMERIC(18,4), cost_impact_max NUMERIC(18,4), cost_currency CHAR(3),
  priority VARCHAR(16) NOT NULL,
  confidence NUMERIC(5,4) NOT NULL,
  validation_method TEXT NOT NULL,
  evidence_cluster_ids JSONB NOT NULL,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'medium',
  model_run_id BIGINT NOT NULL REFERENCES ai_model_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_recommendation_type CHECK (recommendation_type IN ('dimension','material','structure','function','color','packaging','assembly','cost','testing','positioning')),
  CONSTRAINT chk_recommendation_json CHECK (jsonb_typeof(root_cause_hypotheses)='array' AND jsonb_array_length(root_cause_hypotheses)>0 AND jsonb_typeof(impact_dimensions)='array' AND jsonb_typeof(evidence_cluster_ids)='array' AND jsonb_array_length(evidence_cluster_ids)>0),
  CONSTRAINT chk_recommendation_cost CHECK (cost_impact_max IS NULL OR cost_impact_min IS NULL OR cost_impact_max>=cost_impact_min),
  CONSTRAINT chk_recommendation_conf CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_recommendation_priority CHECK (priority IN ('high','medium','low')),
  CONSTRAINT chk_recommendation_risk CHECK (risk_level IN ('high','medium','low'))
);
COMMENT ON TABLE product_recommendations IS 'Evidence-backed engineering suggestions; no expert-review workflow or validation task.';
CREATE INDEX idx_recommendation_opportunity_priority ON product_recommendations(opportunity_id,priority);

CREATE TABLE evidence_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  claim_type VARCHAR(32) NOT NULL,
  claim_id BIGINT NOT NULL,
  claim_path VARCHAR(500),
  claim_category VARCHAR(24) NOT NULL,
  evidence_type VARCHAR(32) NOT NULL,
  evidence_id BIGINT NOT NULL,
  support_type VARCHAR(16) NOT NULL DEFAULT 'supports',
  relevance_score NUMERIC(5,4) NOT NULL DEFAULT 1,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_evidence_claim_item UNIQUE(analysis_job_id,claim_type,claim_id,claim_path,evidence_type,evidence_id),
  CONSTRAINT chk_evidence_claim CHECK (claim_type IN ('report','opportunity','recommendation','score','manufacturing_fit')),
  CONSTRAINT chk_evidence_category CHECK (claim_category IN ('observation','inference','recommendation','validation_required')),
  CONSTRAINT chk_evidence_type CHECK (evidence_type IN ('review_aspect','listing','market_metric','product_attribute','capability','file','data_quality')),
  CONSTRAINT chk_evidence_support CHECK (support_type IN ('supports','contradicts','context','limitation')),
  CONSTRAINT chk_evidence_relevance CHECK (relevance_score BETWEEN 0 AND 1),
  CONSTRAINT chk_evidence_order CHECK (display_order>=1)
);
COMMENT ON TABLE evidence_links IS 'Polymorphic evidence chain for reports, scores, opportunities, recommendations and JSON claim paths.';
CREATE INDEX idx_evidence_task_claim ON evidence_links(analysis_job_id,claim_type,claim_id,display_order);

CREATE TABLE analysis_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  analysis_job_id BIGINT NOT NULL REFERENCES analysis_tasks(id),
  report_version INTEGER NOT NULL DEFAULT 1,
  title VARCHAR(300) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  executive_summary TEXT NOT NULL,
  decision_recommendation VARCHAR(32) NOT NULL,
  overall_opportunity_score NUMERIC(5,2) NOT NULL,
  overall_confidence NUMERIC(5,4) NOT NULL,
  data_scope_snapshot JSONB NOT NULL,
  product_profile_snapshot JSONB NOT NULL,
  enterprise_profile_snapshot JSONB NOT NULL,
  target_user_summary JSONB,
  price_summary JSONB,
  risk_summary JSONB NOT NULL,
  pending_validation_items JSONB NOT NULL DEFAULT '[]'::jsonb,
  sections JSONB NOT NULL,
  partial_failures_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
  version_bundle JSONB NOT NULL,
  generated_model_run_id BIGINT NOT NULL REFERENCES ai_model_runs(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_report_task_version UNIQUE(analysis_job_id,report_version),
  CONSTRAINT chk_report_status CHECK (status IN ('draft','superseded')),
  CONSTRAINT chk_report_scores CHECK (overall_opportunity_score BETWEEN 0 AND 100 AND overall_confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_report_json CHECK (jsonb_typeof(data_scope_snapshot)='object' AND jsonb_typeof(product_profile_snapshot)='object' AND jsonb_typeof(enterprise_profile_snapshot)='object' AND jsonb_typeof(risk_summary) IN ('object','array') AND jsonb_typeof(pending_validation_items)='array' AND jsonb_typeof(sections)='array' AND jsonb_array_length(sections)>0 AND jsonb_typeof(partial_failures_snapshot)='array' AND jsonb_typeof(version_bundle)='object')
);
COMMENT ON TABLE analysis_reports IS 'Directly viewable online decision report; no publication approval, review or file export workflow.';
COMMENT ON COLUMN analysis_reports.data_scope_snapshot IS 'Immutable platform,country,time,dataset version,listing/review counts,limitations and proxy-indicator scope.';
COMMENT ON COLUMN analysis_reports.sections IS 'Ordered section array merging V2 report_sections.';
CREATE INDEX idx_reports_tenant_status_time ON analysis_reports(tenant_id,status,created_at DESC);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT REFERENCES tenants(id),
  actor_user_id BIGINT REFERENCES users(id),
  action_code VARCHAR(100) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT,
  request_id VARCHAR(64),
  before_snapshot JSONB,
  after_snapshot JSONB,
  ip_address VARCHAR(45),
  user_agent VARCHAR(512),
  occurred_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_audit_snapshots CHECK ((before_snapshot IS NULL OR jsonb_typeof(before_snapshot)='object') AND (after_snapshot IS NULL OR jsonb_typeof(after_snapshot)='object'))
);
COMMENT ON TABLE audit_logs IS 'Privacy-safe audit trail; snapshots must be redacted and never contain secrets or full review text.';
CREATE INDEX idx_audit_tenant_time ON audit_logs(tenant_id,occurred_at DESC);
CREATE INDEX idx_audit_resource ON audit_logs(tenant_id,resource_type,resource_id);

-- Updated-at triggers.
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['tenants','users','enterprise_profiles','products','file_assets','manufacturing_capabilities','product_parse_jobs','product_parse_job_files','product_profile_versions','product_attributes','market_datasets','prompt_templates','model_route_configs','user_confirmations','competitor_matches','market_opportunities','product_recommendations','analysis_reports']
  LOOP
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()','trg_'||t||'_updated',t);
  END LOOP;
END $$;

COMMIT;

-- Additive Forecast V4 domain. Kept in a standalone migration so existing V3
-- databases and fresh installations execute the exact same contract.
\ir migrations/v3_forecast_integration.sql
\ir migrations/v3_5_admin_control_center.sql
\ir migrations/v3_6_registration_applications.sql
\ir migrations/v3_7_authorized_market_signals.sql
\ir migrations/v3_8_alert_notifications.sql
\ir migrations/v3_9_active_web_collection.sql
\ir migrations/v3_10_analysis_workspaces.sql
\ir migrations/v3_11_forecast_sku_aliases.sql
\ir migrations/v3_15_enterprise_data.sql
\ir migrations/v3_18_customer_memory.sql
\ir migrations/v3_16_tenant_boundaries.sql
\ir migrations/v3_17_opportunity_policy.sql
\ir migrations/v3_19_training_leases.sql
\ir migrations/v3_20_forecast_routing.sql
\ir migrations/v3_21_import_templates.sql
\ir migrations/v3_22_opportunity_outcomes.sql
\ir migrations/v3_23_context_lifecycle.sql
\ir migrations/v3_24_memory_agent_governance.sql
\ir migrations/v3_25_database_security_baseline.sql
\ir migrations/v3_26_competitor_watch_product_binding.sql
\ir migrations/v3_27_audit_rbac.sql
\ir migrations/v3_28_tenant_deletion_lifecycle.sql
\ir migrations/v3_29_tenant_cell_routing.sql
\ir migrations/v3_30_tenant_query_optimization.sql
\ir migrations/v3_31_controlled_data_query.sql
\ir migrations/v3_32_product_catalog_imports.sql
\ir migrations/v3_33_tenant_data_class.sql
\ir migrations/v3_34_sku_fact_identity.sql
\ir migrations/v3_35_agent_runtime.sql
\ir migrations/v3_36_market_intelligence_governance.sql
\ir migrations/v3_37_operational_outcomes.sql

-- Verification SQL (read-only; run after build).
SET search_path TO furniscope, public;
SELECT count(*) AS core_table_count
FROM information_schema.tables
WHERE table_schema='furniscope' AND table_type='BASE TABLE';

SELECT table_name
FROM information_schema.tables
WHERE table_schema='furniscope' AND table_type='BASE TABLE'
ORDER BY table_name;

SELECT conrelid::regclass AS table_name, conname, pg_get_constraintdef(oid) AS definition
FROM pg_constraint
WHERE connamespace='furniscope'::regnamespace
ORDER BY conrelid::regclass::text, conname;
