-- FurniScope V2.1 -> V3.0 migration
-- PostgreSQL 16+
-- The migration is transactional. Any failure rolls back data moves, table drops and constraints.
-- Run only after taking a physical backup and testing on a database copy.

\set ON_ERROR_STOP on
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '15min';
SET search_path TO furniscope, public;

-- Serialize schema migration.
SELECT pg_advisory_xact_lock(hashtext('furniscope:v2_1_to_v3'));

-- V2.1 attached this generic trigger to some tables without updated_at.
-- Remove legacy instances before rewrites; V3 recreates only valid instances.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT n.nspname,c.relname,t.tgname
    FROM pg_trigger t
    JOIN pg_class c ON c.oid=t.tgrelid
    JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN pg_proc p ON p.oid=t.tgfoid
    WHERE n.nspname='furniscope' AND NOT t.tgisinternal AND p.proname='set_updated_at'
  LOOP
    EXECUTE format('DROP TRIGGER %I ON %I.%I',r.tgname,r.nspname,r.relname);
  END LOOP;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='furniscope' AND table_name='roles') THEN
    RAISE EXCEPTION 'V2.1 baseline not detected: furniscope.roles is missing';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='furniscope' AND table_name='user_confirmations') THEN
    RAISE EXCEPTION 'V3 user_confirmations already exists; migration is not re-entrant';
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS furniscope_archive;
CREATE TABLE IF NOT EXISTS furniscope_archive.retired_entity_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_schema VARCHAR(64) NOT NULL,
  source_table VARCHAR(128) NOT NULL,
  source_pk TEXT,
  tenant_id BIGINT,
  row_data JSONB NOT NULL,
  archived_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  migration_version VARCHAR(32) NOT NULL DEFAULT 'v2_1_to_v3'
);
COMMENT ON TABLE furniscope_archive.retired_entity_rows IS 'Rollback-safe row archive for V2.1 entities removed from the V3 core schema.';
CREATE INDEX IF NOT EXISTS idx_retired_source ON furniscope_archive.retired_entity_rows(source_table,source_pk);

-- Archive every entity that will be removed or whose workflow-specific columns will be discarded.
CREATE OR REPLACE FUNCTION pg_temp.archive_table(p_table TEXT, p_pk TEXT, p_tenant_expr TEXT) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE sql_text TEXT;
BEGIN
  sql_text := format(
    'INSERT INTO furniscope_archive.retired_entity_rows(source_schema,source_table,source_pk,tenant_id,row_data) '
    || 'SELECT %L,%L,(%s)::text,(%s)::bigint,to_jsonb(t) FROM furniscope.%I t',
    'furniscope',p_table,p_pk,p_tenant_expr,p_table
  );
  EXECUTE sql_text;
END;
$$;

SELECT pg_temp.archive_table('roles','t.id','NULL');
SELECT pg_temp.archive_table('user_roles','t.user_id','(SELECT u.tenant_id FROM furniscope.users u WHERE u.id=t.user_id)');
SELECT pg_temp.archive_table('enterprise_constraints','t.id','t.tenant_id');
SELECT pg_temp.archive_table('dataset_field_mappings','t.id','(SELECT d.tenant_id FROM furniscope.market_datasets d WHERE d.id=t.dataset_id)');
SELECT pg_temp.archive_table('listing_attributes','t.id','(SELECT l.tenant_id FROM furniscope.competitor_listings l WHERE l.id=t.listing_id)');
SELECT pg_temp.archive_table('opportunity_scores','t.id','(SELECT a.tenant_id FROM furniscope.market_opportunities o JOIN furniscope.analysis_tasks a ON a.id=o.task_id WHERE o.id=t.opportunity_id)');
SELECT pg_temp.archive_table('manufacturing_requirements','t.id','(SELECT a.tenant_id FROM furniscope.market_opportunities o JOIN furniscope.analysis_tasks a ON a.id=o.task_id WHERE o.id=t.opportunity_id)');
SELECT pg_temp.archive_table('enterprise_fit_details','t.id','(SELECT a.tenant_id FROM furniscope.market_opportunities o JOIN furniscope.analysis_tasks a ON a.id=o.task_id WHERE o.id=t.opportunity_id)');
SELECT pg_temp.archive_table('validation_tasks','t.id','(SELECT a.tenant_id FROM furniscope.product_recommendations r JOIN furniscope.analysis_tasks a ON a.id=r.task_id WHERE r.id=t.recommendation_id)');
SELECT pg_temp.archive_table('report_sections','t.id','(SELECT r.tenant_id FROM furniscope.analysis_reports r WHERE r.id=t.report_id)');
SELECT pg_temp.archive_table('report_reviews','t.id','(SELECT r.tenant_id FROM furniscope.analysis_reports r WHERE r.id=t.report_id)');
SELECT pg_temp.archive_table('compute_quotas','t.id','t.tenant_id');
SELECT pg_temp.archive_table('product_events','t.id','t.tenant_id');
SELECT pg_temp.archive_table('listing_generation_records','t.id','t.tenant_id');
SELECT pg_temp.archive_table('report_exports','t.id','t.tenant_id');
SELECT pg_temp.archive_table('competitor_set_confirmations','t.id','t.tenant_id');

INSERT INTO furniscope_archive.retired_entity_rows(source_schema,source_table,source_pk,tenant_id,row_data)
SELECT 'furniscope','product_recommendations.review_fields',r.id::text,a.tenant_id,
       jsonb_build_object('expert_review_status',r.expert_review_status,'expert_review_note',r.expert_review_note,'reviewed_by',r.reviewed_by,'reviewed_at',r.reviewed_at)
FROM product_recommendations r JOIN analysis_tasks a ON a.id=r.task_id
WHERE r.expert_review_status IS DISTINCT FROM 'pending' OR r.expert_review_note IS NOT NULL OR r.reviewed_by IS NOT NULL;

-- Static two-role model. Legacy business roles are mapped to user; admin remains admin.
UPDATE users SET role_code=CASE WHEN role_code='admin' THEN 'admin' ELSE 'user' END;
DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM users GROUP BY lower(email) HAVING count(*)>1) THEN
    RAISE EXCEPTION 'duplicate login email prevents global identity migration';
  END IF;
END $$;
ALTER TABLE users DROP CONSTRAINT IF EXISTS uk_users_tenant_email;
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE(email);
ALTER TABLE users ALTER COLUMN role_code SET DEFAULT 'user';
ALTER TABLE users ADD CONSTRAINT chk_users_role_v3 CHECK(role_code IN ('user','admin'));

-- Normalize tenant and user names/status without creating credentials.
ALTER TABLE tenants RENAME COLUMN tenant_name TO name;
ALTER TABLE tenants ALTER COLUMN status DROP DEFAULT;
ALTER TABLE tenants ALTER COLUMN status TYPE VARCHAR(16)
USING CASE status WHEN 0 THEN 'closed' WHEN 1 THEN 'active' WHEN 2 THEN 'suspended' ELSE 'trial' END;
ALTER TABLE tenants ALTER COLUMN status SET DEFAULT 'trial';
ALTER TABLE tenants ADD CONSTRAINT chk_tenant_status_v3 CHECK(status IN ('trial','active','suspended','closed'));

ALTER TABLE users RENAME COLUMN user_name TO name;
ALTER TABLE users ALTER COLUMN status DROP DEFAULT;
ALTER TABLE users ALTER COLUMN status TYPE VARCHAR(16)
USING CASE status WHEN 0 THEN 'disabled' WHEN 1 THEN 'active' WHEN 2 THEN 'locked' ELSE 'invited' END;
ALTER TABLE users ALTER COLUMN status SET DEFAULT 'invited';
ALTER TABLE users ADD CONSTRAINT chk_users_status_v3 CHECK(status IN ('invited','active','disabled','locked'));

-- Authentication sessions are new in V3.1. Existing credentials are retained,
-- but no refresh token is synthesized during migration.
CREATE TABLE auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash CHAR(64) NOT NULL UNIQUE,
  token_family_uuid UUID NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  last_used_at TIMESTAMPTZ(3),
  revoked_at TIMESTAMPTZ(3),
  revoke_reason VARCHAR(64),
  replaced_by_session_uuid UUID,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_auth_token_hash CHECK(refresh_token_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_auth_expiry CHECK(expires_at>created_at),
  CONSTRAINT chk_auth_revoke CHECK((revoked_at IS NULL)=(revoke_reason IS NULL))
);
COMMENT ON TABLE auth_sessions IS 'Rotating refresh-token sessions; only SHA-256 token hashes are persisted.';
CREATE INDEX idx_auth_sessions_user_active ON auth_sessions(tenant_id,user_id,expires_at DESC) WHERE revoked_at IS NULL;
CREATE INDEX idx_auth_sessions_family ON auth_sessions(token_family_uuid,created_at);

CREATE TABLE api_idempotency_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  actor_user_id BIGINT NOT NULL REFERENCES users(id),
  route_code VARCHAR(32) NOT NULL,
  http_method VARCHAR(8) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'processing',
  resource_type VARCHAR(64),
  resource_public_id VARCHAR(128),
  response_status INTEGER,
  response_body JSONB,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_api_idempotency_scope UNIQUE(tenant_id,route_code,idempotency_key),
  CONSTRAINT chk_api_idempotency_method CHECK(http_method IN ('POST','PUT','PATCH','DELETE')),
  CONSTRAINT chk_api_idempotency_hash CHECK(request_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_api_idempotency_status CHECK(status IN ('processing','completed','failed')),
  CONSTRAINT chk_api_idempotency_response CHECK(
    (status='processing' AND response_status IS NULL AND response_body IS NULL)
    OR (status IN ('completed','failed') AND response_status BETWEEN 200 AND 599 AND response_body IS NOT NULL)
  ),
  CONSTRAINT chk_api_idempotency_expiry CHECK(expires_at>created_at)
);
COMMENT ON TABLE api_idempotency_records IS 'Tenant-scoped durable HTTP idempotency ledger; excludes authentication endpoints.';
CREATE INDEX idx_api_idempotency_expiry ON api_idempotency_records(expires_at);
CREATE INDEX idx_api_idempotency_resource ON api_idempotency_records(tenant_id,resource_type,resource_public_id);

-- Merge enterprise constraints.
ALTER TABLE enterprise_profiles RENAME COLUMN business_models TO business_model;
ALTER TABLE enterprise_profiles ADD COLUMN constraints JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE enterprise_profiles ep
SET constraints=COALESCE((
  SELECT jsonb_agg(jsonb_build_object(
    'constraint_type',ec.constraint_type,'operator',ec.operator,'value',ec.value,'unit',ec.unit,
    'hardness',ec.hardness,'effective_at',ec.effective_at,'expires_at',ec.expires_at,
    'sensitivity_level',ec.sensitivity_level) ORDER BY ec.id)
  FROM enterprise_constraints ec WHERE ec.tenant_id=ep.tenant_id
),'[]'::jsonb);
ALTER TABLE enterprise_profiles ADD CONSTRAINT chk_enterprise_constraints_v3 CHECK(jsonb_typeof(constraints)='array');

-- Bring product/file/profile naming into V3 without deleting business data.
ALTER TABLE products RENAME COLUMN product_name TO name;
ALTER TABLE products ADD COLUMN primary_image_id BIGINT REFERENCES file_assets(id);
ALTER TABLE products ADD COLUMN current_profile_version_id BIGINT;
ALTER TABLE product_profile_versions ADD COLUMN tenant_id BIGINT;
UPDATE product_profile_versions pv SET tenant_id=p.tenant_id FROM products p WHERE p.id=pv.product_id;
ALTER TABLE product_profile_versions ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE product_profile_versions ADD CONSTRAINT fk_profile_tenant_v3 FOREIGN KEY(tenant_id) REFERENCES tenants(id);
ALTER TABLE product_profile_versions ADD COLUMN source_summary JSONB NOT NULL DEFAULT '{}'::jsonb;
UPDATE products p SET current_profile_version_id=(SELECT pv.id FROM product_profile_versions pv WHERE pv.product_id=p.id ORDER BY pv.version_no DESC LIMIT 1);
ALTER TABLE products ADD CONSTRAINT fk_product_current_profile_v3 FOREIGN KEY(current_profile_version_id) REFERENCES product_profile_versions(id);

-- Merge field mappings and normalize dataset columns/default JSON.
ALTER TABLE market_datasets RENAME COLUMN dataset_name TO name;
ALTER TABLE market_datasets ADD COLUMN field_mapping JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE market_datasets d SET field_mapping=COALESCE((
  SELECT jsonb_agg(jsonb_build_object('source_field',m.source_field,'target_entity',m.target_entity,'target_field',m.target_field,'transform_rule',m.transform_rule,'mapping_status',m.mapping_status) ORDER BY m.id)
  FROM dataset_field_mappings m WHERE m.dataset_id=d.id
),'[]'::jsonb);
UPDATE market_datasets SET quality_report=COALESCE(quality_report,'{}'::jsonb), limitations=COALESCE(limitations,'[]'::jsonb);
ALTER TABLE market_datasets ALTER COLUMN quality_report SET DEFAULT '{}'::jsonb;
ALTER TABLE market_datasets ALTER COLUMN limitations SET DEFAULT '[]'::jsonb;
ALTER TABLE market_datasets ADD CONSTRAINT chk_dataset_field_mapping_v3 CHECK(jsonb_typeof(field_mapping)='array');

-- Merge listing attributes before renaming platform tables.
UPDATE competitor_listings l SET normalized_attributes=COALESCE(l.normalized_attributes,'{}'::jsonb) || COALESCE((
  SELECT jsonb_object_agg(a.attribute_code,jsonb_build_object('value',a.value,'unit',a.unit,'source_locator',a.source_locator,'confidence',a.confidence))
  FROM listing_attributes a WHERE a.listing_id=l.id
),'{}'::jsonb);
ALTER TABLE competitor_listings RENAME TO market_listings;
ALTER TABLE market_listings RENAME COLUMN coupon_info TO coupon_value;
ALTER TABLE market_listings RENAME COLUMN observed_at TO captured_at;
ALTER TABLE market_listings RENAME COLUMN first_available_at TO first_available_date_legacy;
ALTER TABLE market_listings ADD COLUMN first_available_date DATE;
UPDATE market_listings SET first_available_date=first_available_date_legacy::date;
ALTER TABLE market_listings ADD CONSTRAINT chk_listing_normalized_v3 CHECK(jsonb_typeof(COALESCE(normalized_attributes,'{}'::jsonb))='object');

ALTER TABLE competitor_reviews RENAME TO reviews;
ALTER TABLE reviews RENAME COLUMN review_title TO title_original;
ALTER TABLE reviews RENAME COLUMN body_original TO content_original;
ALTER TABLE reviews RENAME COLUMN language TO language_code;
ALTER TABLE reviews RENAME COLUMN body_translated_zh TO content_translated;
ALTER TABLE reviews RENAME COLUMN helpful_votes TO helpful_count;
ALTER TABLE reviews ADD COLUMN title_translated TEXT;
UPDATE reviews SET platform_review_id=COALESCE(platform_review_id,'legacy-'||id::text);
ALTER TABLE reviews ALTER COLUMN platform_review_id SET NOT NULL;
ALTER TABLE reviews ALTER COLUMN rating DROP NOT NULL;
ALTER TABLE reviews ADD CONSTRAINT uk_review_dataset_platform_v3 UNIQUE(dataset_id,platform_review_id);

-- Analysis task: split external five-stage projection from internal stage.
ALTER TABLE analysis_tasks RENAME COLUMN task_name TO job_name;
ALTER TABLE analysis_tasks RENAME COLUMN task_type TO job_type;
ALTER TABLE analysis_tasks ADD COLUMN product_profile_version_id BIGINT;
UPDATE analysis_tasks t SET product_profile_version_id=(
  SELECT pv.id FROM product_profile_versions pv
  WHERE pv.product_id=t.product_id AND pv.version_no=t.product_profile_version
  ORDER BY pv.id DESC LIMIT 1
);
UPDATE analysis_tasks t SET product_profile_version_id=(SELECT pv.id FROM product_profile_versions pv WHERE pv.product_id=t.product_id ORDER BY pv.version_no DESC LIMIT 1)
WHERE product_profile_version_id IS NULL;
DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM analysis_tasks WHERE product_profile_version_id IS NULL) THEN
    RAISE EXCEPTION 'analysis task profile migration left NULL references';
  END IF;
END $$;
ALTER TABLE analysis_tasks ALTER COLUMN product_profile_version_id SET NOT NULL;
ALTER TABLE analysis_tasks ADD CONSTRAINT fk_task_profile_v3 FOREIGN KEY(product_profile_version_id) REFERENCES product_profile_versions(id);
ALTER TABLE analysis_tasks DROP COLUMN product_profile_version;
ALTER TABLE analysis_tasks ADD COLUMN external_stage VARCHAR(40);
ALTER TABLE analysis_tasks ADD COLUMN internal_stage VARCHAR(64);
UPDATE analysis_tasks SET
  internal_stage=CASE current_stage
    WHEN 'draft' THEN 'task_initializing' WHEN 'competitor_review' THEN 'user_confirmation'
    WHEN 'expert_review' THEN 'user_confirmation' ELSE current_stage END,
  external_stage=CASE
    WHEN current_stage IN ('draft','preflight_check','context_loading') THEN 'understanding_product'
    WHEN current_stage IN ('data_quality','competitor_filtering','competitor_embedding','competitor_reranking','competitor_review','review_preprocessing','review_extracting','need_clustering','market_analytics') THEN 'researching_market'
    WHEN current_stage='opportunity_scoring' THEN 'evaluating_opportunity'
    WHEN current_stage IN ('strategy_generating','expert_review','evidence_auditing','report_generating','persisting') THEN 'generating_recommendation'
    WHEN current_stage='completed' THEN 'completed' ELSE 'understanding_product' END;
ALTER TABLE analysis_tasks ALTER COLUMN external_stage SET NOT NULL;
ALTER TABLE analysis_tasks ALTER COLUMN internal_stage SET NOT NULL;
ALTER TABLE analysis_tasks ADD COLUMN model_route_version VARCHAR(64) NOT NULL DEFAULT 'legacy-v2.1';
ALTER TABLE analysis_tasks ADD COLUMN idempotency_key VARCHAR(128);
UPDATE analysis_tasks SET idempotency_key='legacy-task-'||task_uuid::text;
ALTER TABLE analysis_tasks ALTER COLUMN idempotency_key SET NOT NULL;
ALTER TABLE analysis_tasks ADD CONSTRAINT uk_task_tenant_idem_v3 UNIQUE(tenant_id,idempotency_key);
UPDATE analysis_tasks SET analysis_config=COALESCE(analysis_config,'{}'::jsonb);
ALTER TABLE analysis_tasks ADD CONSTRAINT chk_task_external_stage_v3 CHECK(external_stage IN ('understanding_product','researching_market','evaluating_opportunity','generating_recommendation','completed'));
ALTER TABLE analysis_tasks ADD CONSTRAINT chk_task_internal_review_removed CHECK(internal_stage NOT IN ('competitor_review','expert_review'));

-- Stage, checkpoint and partial-failure tenant projections.
ALTER TABLE task_stage_runs ADD COLUMN tenant_id BIGINT;
UPDATE task_stage_runs s SET tenant_id=t.tenant_id FROM analysis_tasks t WHERE t.id=s.task_id;
ALTER TABLE task_stage_runs ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE task_stage_runs ADD CONSTRAINT fk_stage_tenant_v3 FOREIGN KEY(tenant_id) REFERENCES tenants(id);
UPDATE task_stage_runs SET stage_code='user_confirmation' WHERE stage_code IN ('competitor_review','expert_review');

-- Unified confirmations. V2 competitor confirmations become responded low-confidence confirmations.
CREATE OR REPLACE FUNCTION furniscope.jsonb_option_has_code(items JSONB, expected_code TEXT) RETURNS BOOLEAN
LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT EXISTS(SELECT 1 FROM jsonb_array_elements(items) i WHERE i->>'code'=expected_code) $$;

CREATE TABLE user_confirmations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  confirmation_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  task_id BIGINT NOT NULL REFERENCES analysis_tasks(id) ON DELETE CASCADE,
  confirmation_type VARCHAR(32) NOT NULL,
  question TEXT NOT NULL,
  recommended_option VARCHAR(100) NOT NULL,
  options JSONB NOT NULL,
  evidence_refs JSONB NOT NULL,
  impact JSONB NOT NULL,
  checkpoint_stage VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(3),
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  selected_option VARCHAR(100),
  user_input JSONB,
  responded_by BIGINT REFERENCES users(id),
  responded_at TIMESTAMPTZ(3),
  idempotency_key VARCHAR(128) NOT NULL,
  checkpoint_id VARCHAR(128) REFERENCES workflow_checkpoints(checkpoint_id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_confirmation_tenant_idem UNIQUE(tenant_id,idempotency_key),
  CONSTRAINT chk_confirmation_type CHECK(confirmation_type IN ('fact_conflict','insufficient_data','low_confidence','high_risk_recommendation')),
  CONSTRAINT chk_confirmation_json CHECK(jsonb_typeof(options)='array' AND jsonb_array_length(options)>0 AND jsonb_typeof(evidence_refs)='array' AND jsonb_array_length(evidence_refs)>0 AND jsonb_typeof(impact) IN ('object','string')),
  CONSTRAINT chk_confirmation_status CHECK(status IN ('pending','responded','expired','cancelled')),
  CONSTRAINT chk_confirmation_response CHECK((status='responded')=(selected_option IS NOT NULL AND responded_by IS NOT NULL AND responded_at IS NOT NULL)),
  CONSTRAINT chk_confirmation_option CHECK(furniscope.jsonb_option_has_code(options,recommended_option)),
  CONSTRAINT chk_confirmation_selected CHECK(selected_option IS NULL OR furniscope.jsonb_option_has_code(options,selected_option))
);
CREATE UNIQUE INDEX uk_confirmation_pending_task ON user_confirmations(task_id) WHERE status='pending';
CREATE INDEX idx_confirmation_tenant_status_expire ON user_confirmations(tenant_id,status,expires_at);

INSERT INTO user_confirmations(
  tenant_id,task_id,confirmation_type,question,recommended_option,options,evidence_refs,impact,
  checkpoint_stage,status,selected_option,user_input,responded_by,responded_at,idempotency_key,checkpoint_id,created_at
)
SELECT c.tenant_id,c.task_id,'low_confidence',
       '历史V2.1竞品集合已由user确认，是否沿用该样本范围？','confirmed_set',
       jsonb_build_array(jsonb_build_object('code','confirmed_set','label','沿用历史确认集合')),
       jsonb_build_array(jsonb_build_object('type','legacy_competitor_set_confirmation','id',c.id)),
       jsonb_build_object('confirmed_listing_count',c.direct_count+c.benchmark_count+c.substitute_count,'excluded_count',c.excluded_count),
       'competitor_reranking','responded','confirmed_set',
       jsonb_build_object('confirmed_listing_ids',c.confirmed_listing_ids,'legacy_version_no',c.version_no),
       c.confirmed_by,c.confirmed_at,'legacy-competitor-confirmation-'||c.id::text,
       (SELECT w.checkpoint_id FROM workflow_checkpoints w WHERE w.task_id=c.task_id ORDER BY w.checkpoint_version DESC LIMIT 1),
       c.confirmed_at
FROM competitor_set_confirmations c;

-- Normalize workflow control events to internal Supervisor semantics.
ALTER TABLE workflow_control_events DROP CONSTRAINT IF EXISTS chk_control_event_type;
UPDATE workflow_control_events SET event_type=CASE event_type
  WHEN 'resume_competitors' THEN 'resume_confirmation'
  WHEN 'resume_expert_review' THEN 'resume_confirmation'
  WHEN 'retry_stage' THEN 'auto_retry'
  WHEN 'cancel_task' THEN 'safe_stop'
  ELSE event_type END;
UPDATE workflow_control_events SET expected_checkpoint_stage='user_confirmation' WHERE expected_checkpoint_stage IN ('competitor_review','expert_review');
UPDATE workflow_control_events SET stage_code='user_confirmation' WHERE stage_code IN ('competitor_review','expert_review');
ALTER TABLE workflow_control_events ADD COLUMN delivery_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE workflow_control_events ADD COLUMN enqueued_at TIMESTAMPTZ(3);
UPDATE workflow_control_events SET enqueued_at=requested_at,delivery_attempts=1 WHERE status='enqueued';
ALTER TABLE workflow_control_events ADD CONSTRAINT chk_control_event_type_v3 CHECK(event_type IN ('resume_confirmation','auto_retry','safe_stop'));
ALTER TABLE workflow_control_events ADD CONSTRAINT chk_control_delivery_v3 CHECK(delivery_attempts>=0 AND (status<>'enqueued' OR enqueued_at IS NOT NULL));

-- Model and compute configuration; preserve all quota rows inside versioned admin config before dropping entity.
ALTER TABLE model_route_configs ADD COLUMN config_version VARCHAR(64);
UPDATE model_route_configs SET config_version='legacy-v2.1-'||id::text;
ALTER TABLE model_route_configs ALTER COLUMN config_version SET NOT NULL;
ALTER TABLE model_route_configs ADD COLUMN compute_config JSONB NOT NULL DEFAULT '{}'::jsonb;
UPDATE model_route_configs m SET compute_config=jsonb_build_object(
  'legacy_compute_quotas',COALESCE((SELECT jsonb_agg(to_jsonb(q) ORDER BY q.id) FROM compute_quotas q),'[]'::jsonb),
  'usage_source','ai_model_runs'
);
ALTER TABLE model_route_configs ADD CONSTRAINT uk_model_route_version_v3 UNIQUE(task_type,config_version);
ALTER TABLE ai_model_runs ADD COLUMN tenant_id BIGINT;
UPDATE ai_model_runs m SET tenant_id=t.tenant_id FROM analysis_tasks t WHERE t.id=m.task_id;
ALTER TABLE ai_model_runs ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE ai_model_runs ADD CONSTRAINT fk_model_tenant_v3 FOREIGN KEY(tenant_id) REFERENCES tenants(id);
UPDATE ai_model_runs SET status='succeeded' WHERE status='success';

-- Merge latest score version into the opportunity's indexed top-level fields.
WITH latest_score AS (
  SELECT DISTINCT ON (opportunity_id) * FROM opportunity_scores
  ORDER BY opportunity_id,calculated_at DESC,id DESC
)
UPDATE market_opportunities o SET
  demand_heat_score=s.demand_heat_score,demand_growth_score=s.demand_growth_score,
  unmet_need_score=s.unmet_need_score,competition_space_score=s.competition_space_score,
  profit_space_score=s.profit_space_score,enterprise_fit_score=s.enterprise_fit_score,
  overall_score=s.base_score,confidence=s.confidence,recommendation_level=s.recommendation_level,
  weight_config=s.weight_config,scoring_version=s.scoring_version
FROM latest_score s WHERE s.opportunity_id=o.id;
ALTER TABLE market_opportunities ADD COLUMN base_score NUMERIC(5,2);
UPDATE market_opportunities SET base_score=overall_score;
ALTER TABLE market_opportunities ADD COLUMN manufacturing_fit JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE market_opportunities o SET manufacturing_fit=COALESCE((
  SELECT jsonb_agg(jsonb_build_object(
    'requirement_type',r.requirement_type,'requirement_code',r.requirement_code,'description',r.description,
    'target_value',r.target_value,'unit',r.unit,'priority',r.priority,'evidence_cluster_ids',r.evidence_cluster_ids,
    'validation_required',r.validation_required,'capability_id',f.capability_id,'fit_status',COALESCE(f.fit_status,'unknown'),
    'fit_score',f.fit_score,'hard_constraint_breached',COALESCE(f.hard_constraint_breached,false),
    'explanation',COALESCE(f.explanation,'V2.1无适配明细'),'confidence',COALESCE(f.confidence,0)) ORDER BY r.id)
  FROM manufacturing_requirements r LEFT JOIN enterprise_fit_details f ON f.requirement_id=r.id
  WHERE r.opportunity_id=o.id
),'[]'::jsonb);

-- Recommendations retain AI output; removed expert fields are already archived.
ALTER TABLE product_recommendations ADD COLUMN tenant_id BIGINT;
UPDATE product_recommendations r SET tenant_id=t.tenant_id FROM analysis_tasks t WHERE t.id=r.task_id;
ALTER TABLE product_recommendations ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE product_recommendations ADD CONSTRAINT fk_recommendation_tenant_v3 FOREIGN KEY(tenant_id) REFERENCES tenants(id);
ALTER TABLE product_recommendations ADD COLUMN risk_level VARCHAR(16) NOT NULL DEFAULT 'medium';

-- Evidence references are remapped before report sections and score/fit tables are removed.
ALTER TABLE evidence_links ADD COLUMN tenant_id BIGINT;
UPDATE evidence_links e SET tenant_id=t.tenant_id FROM analysis_tasks t WHERE t.id=e.task_id;
ALTER TABLE evidence_links ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE evidence_links ADD CONSTRAINT fk_evidence_tenant_v3 FOREIGN KEY(tenant_id) REFERENCES tenants(id);
ALTER TABLE evidence_links ADD COLUMN claim_path VARCHAR(500);
UPDATE evidence_links e SET claim_path='sections[legacy_id='||s.id::text||']',claim_id=s.report_id,claim_type='report'
FROM report_sections s WHERE e.claim_type='report_section' AND e.claim_id=s.id;
UPDATE evidence_links e SET claim_path='score[legacy_id='||s.id::text||']',claim_id=s.opportunity_id
FROM opportunity_scores s WHERE e.claim_type='score' AND e.claim_id=s.id;
UPDATE evidence_links e SET claim_path='manufacturing_fit[legacy_id='||f.id::text||']',claim_id=f.opportunity_id,claim_type='manufacturing_fit'
FROM enterprise_fit_details f WHERE e.claim_type='fit_detail' AND e.claim_id=f.id;
ALTER TABLE evidence_links RENAME COLUMN task_id TO analysis_job_id;

-- Merge report sections and immutable scope/version snapshots.
ALTER TABLE analysis_reports RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE analysis_reports RENAME COLUMN data_scope_summary TO data_scope_snapshot;
ALTER TABLE analysis_reports ADD COLUMN enterprise_profile_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE analysis_reports ADD COLUMN target_user_summary JSONB;
UPDATE analysis_reports r SET enterprise_profile_snapshot=COALESCE((
  SELECT jsonb_build_object('profile',to_jsonb(ep),'capabilities',COALESCE((SELECT jsonb_agg(to_jsonb(mc)) FROM manufacturing_capabilities mc WHERE mc.tenant_id=r.tenant_id),'[]'::jsonb))
  FROM enterprise_profiles ep WHERE ep.tenant_id=r.tenant_id
),'{}'::jsonb);
ALTER TABLE analysis_reports ADD COLUMN sections JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE analysis_reports r SET sections=COALESCE((
  SELECT jsonb_agg(jsonb_build_object('section_code',s.section_code,'title',s.title,'sort_order',s.sort_order,'content_type',s.content_type,'structured_content',s.structured_content,'narrative_text',s.narrative_text,'chart_config',s.chart_config) ORDER BY s.sort_order)
  FROM report_sections s WHERE s.report_id=r.id
),jsonb_build_array(jsonb_build_object('section_code','scope','title','分析范围','sort_order',1,'content_type','structured','structured_content',r.data_scope_snapshot)));
ALTER TABLE analysis_reports ADD COLUMN partial_failures_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE analysis_reports r SET partial_failures_snapshot=COALESCE((SELECT jsonb_agg(to_jsonb(p)) FROM workflow_partial_failures p WHERE p.task_id=r.analysis_job_id),'[]'::jsonb);
ALTER TABLE analysis_reports ADD COLUMN version_bundle JSONB NOT NULL DEFAULT '{}'::jsonb;
UPDATE analysis_reports r SET version_bundle=jsonb_build_object('ontology_version',t.ontology_version,'scoring_version',t.scoring_version,'prompt_bundle_version',t.prompt_bundle_version,'model_route_version',t.model_route_version)
FROM analysis_tasks t WHERE t.id=r.analysis_job_id;
UPDATE analysis_reports SET status='draft' WHERE status IN ('human_review','published');
-- Retained V2 summary columns are compatibility-only and must not be required
-- from V3 report writers. Existing values remain available for historical reads.
ALTER TABLE analysis_reports ALTER COLUMN opportunity_summary DROP NOT NULL;
ALTER TABLE analysis_reports ALTER COLUMN recommendation_summary DROP NOT NULL;

-- Rename task foreign keys where V3 uses analysis_job_id; retain physical semantics.
ALTER TABLE competitor_matches RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE review_aspects RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE insight_clusters RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE market_metrics RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE price_bands RENAME COLUMN task_id TO analysis_job_id;
ALTER TABLE market_opportunities RENAME COLUMN task_id TO analysis_job_id;

-- Validate all merged row counts and JSON shapes BEFORE dropping source tables.
DO $$
DECLARE src BIGINT; dst BIGINT;
BEGIN
  SELECT count(*) INTO src FROM enterprise_constraints;
  SELECT COALESCE(sum(jsonb_array_length(constraints)),0) INTO dst FROM enterprise_profiles;
  IF src<>dst THEN RAISE EXCEPTION 'enterprise constraint migration mismatch: % <> %',src,dst; END IF;

  SELECT count(*) INTO src FROM dataset_field_mappings;
  SELECT COALESCE(sum(jsonb_array_length(field_mapping)),0) INTO dst FROM market_datasets;
  IF src<>dst THEN RAISE EXCEPTION 'field mapping migration mismatch: % <> %',src,dst; END IF;

  SELECT count(*) INTO src FROM listing_attributes;
  SELECT count(*) INTO dst FROM market_listings l CROSS JOIN LATERAL jsonb_object_keys(COALESCE(l.normalized_attributes,'{}'::jsonb)) k;
  IF dst<src THEN RAISE EXCEPTION 'listing attribute migration lost rows: % > %',src,dst; END IF;

  SELECT count(*) INTO src FROM competitor_set_confirmations;
  SELECT count(*) INTO dst FROM user_confirmations WHERE idempotency_key LIKE 'legacy-competitor-confirmation-%';
  IF src<>dst THEN RAISE EXCEPTION 'confirmation migration mismatch: % <> %',src,dst; END IF;

  IF EXISTS(SELECT 1 FROM users WHERE role_code NOT IN ('user','admin')) THEN RAISE EXCEPTION 'legacy role remains'; END IF;
  IF EXISTS(SELECT 1 FROM analysis_tasks WHERE external_stage IS NULL OR internal_stage IN ('competitor_review','expert_review')) THEN RAISE EXCEPTION 'task stage projection invalid'; END IF;
  IF EXISTS(SELECT 1 FROM analysis_reports WHERE jsonb_typeof(sections)<>'array' OR jsonb_array_length(sections)=0) THEN RAISE EXCEPTION 'report section merge invalid'; END IF;

  -- Fail inside the transaction if a legacy physical name survived. This prevents
  -- an apparently successful migration from exposing a schema that V3 code cannot query.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='furniscope'
      AND ((table_name='enterprise_profiles' AND column_name='business_models')
        OR (table_name='analysis_tasks' AND column_name='product_profile_version')
        OR (table_name IN ('competitor_matches','review_aspects','insight_clusters','market_metrics','price_bands','market_opportunities','evidence_links','analysis_reports') AND column_name='task_id'))
  ) THEN RAISE EXCEPTION 'legacy V2.1 physical column survived V3 migration'; END IF;
  IF (SELECT count(*) FROM information_schema.columns
      WHERE table_schema='furniscope'
        AND ((table_name='enterprise_profiles' AND column_name='business_model')
          OR (table_name IN ('competitor_matches','review_aspects','insight_clusters','market_metrics','price_bands','market_opportunities','evidence_links','analysis_reports') AND column_name='analysis_job_id'))) <> 9
  THEN RAISE EXCEPTION 'required V3 physical columns are incomplete'; END IF;
END $$;

-- Drops occur only after archive, transformation and validation. Any error rolls the transaction back.
DROP TABLE user_roles;
DROP TABLE roles;
DROP TABLE enterprise_constraints;
DROP TABLE dataset_field_mappings;
DROP TABLE listing_attributes;
DROP TABLE validation_tasks;
DROP TABLE report_reviews;
DROP TABLE report_sections;
DROP TABLE enterprise_fit_details;
DROP TABLE manufacturing_requirements;
DROP TABLE opportunity_scores;
DROP TABLE compute_quotas;
DROP TABLE product_events;
DROP TABLE listing_generation_records;
DROP TABLE report_exports;
DROP TABLE competitor_set_confirmations;

-- Drop workflow fields replaced by the unified model only after their contents are archived/migrated.
ALTER TABLE competitor_matches DROP CONSTRAINT IF EXISTS fk_match_reviewer;
ALTER TABLE competitor_matches DROP COLUMN review_status,DROP COLUMN review_note,DROP COLUMN reviewed_by,DROP COLUMN reviewed_at;
ALTER TABLE competitor_matches ADD COLUMN set_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE product_recommendations DROP CONSTRAINT IF EXISTS fk_recommendation_reviewer;
ALTER TABLE product_recommendations DROP COLUMN expert_review_status,DROP COLUMN expert_review_note,DROP COLUMN reviewed_by,DROP COLUMN reviewed_at;

-- Core V3 indexes.
CREATE INDEX IF NOT EXISTS idx_users_tenant_role_status ON users(tenant_id,role_code,status);
CREATE INDEX IF NOT EXISTS idx_dataset_tenant_market_status ON market_datasets(tenant_id,platform,market_country,status);
CREATE INDEX IF NOT EXISTS idx_listing_normalized_attributes ON market_listings USING GIN(normalized_attributes);
CREATE INDEX IF NOT EXISTS idx_task_tenant_external_stage ON analysis_tasks(tenant_id,external_stage,status);
CREATE INDEX IF NOT EXISTS idx_confirmation_tenant_status_expire ON user_confirmations(tenant_id,status,expires_at);
CREATE INDEX IF NOT EXISTS idx_match_task_type_score_v3 ON competitor_matches(analysis_job_id,competitor_type,overall_score DESC);
CREATE INDEX IF NOT EXISTS idx_aspect_task_taxonomy_sentiment_v3 ON review_aspects(analysis_job_id,taxonomy_code,sentiment);
CREATE INDEX IF NOT EXISTS idx_cluster_task_importance_v3 ON insight_clusters(analysis_job_id,importance_score DESC);
CREATE INDEX IF NOT EXISTS idx_metric_task_code_dimension_v3 ON market_metrics(analysis_job_id,metric_code,dimension_type);
CREATE INDEX IF NOT EXISTS idx_opportunity_task_score_conf ON market_opportunities(analysis_job_id,base_score DESC,confidence DESC);
CREATE INDEX IF NOT EXISTS idx_opportunity_manufacturing_fit ON market_opportunities USING GIN(manufacturing_fit);

-- Recreate timestamp triggers only for V3 tables that expose updated_at.
DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT DISTINCT table_name FROM information_schema.columns
    WHERE table_schema='furniscope' AND column_name='updated_at'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON furniscope.%I','trg_'||r.table_name||'_updated_at',r.table_name);
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON furniscope.%I FOR EACH ROW EXECUTE FUNCTION furniscope.set_updated_at()',
                   'trg_'||r.table_name||'_updated_at',r.table_name);
  END LOOP;
END $$;

COMMENT ON TABLE user_confirmations IS 'V3 single user_confirmation protocol replacing competitor and expert review.';
COMMENT ON COLUMN users.role_code IS 'Only user/admin; no dynamic RBAC.';
COMMENT ON COLUMN users.email IS 'Globally unique login identity; tenant_id is resolved by the server.';
COMMENT ON COLUMN enterprise_profiles.constraints IS 'Merged V2 enterprise_constraints with versioned item schema.';
COMMENT ON COLUMN market_datasets.field_mapping IS 'Merged V2 dataset_field_mappings.';
COMMENT ON COLUMN market_listings.normalized_attributes IS 'Merged V2 listing_attributes keyed by attribute_code.';
COMMENT ON COLUMN market_opportunities.manufacturing_fit IS 'Merged manufacturing requirements and enterprise fit details.';
COMMENT ON COLUMN analysis_reports.sections IS 'Merged ordered V2 report_sections.';
COMMENT ON TABLE workflow_checkpoints IS 'Business-safe projection only; LangGraph official checkpointer remains separate.';

COMMIT;

-- Post-migration verification (read-only).
SET search_path TO furniscope, public;
SELECT count(*) AS core_table_count FROM information_schema.tables WHERE table_schema='furniscope' AND table_type='BASE TABLE';
SELECT count(*) AS archived_removed_rows FROM furniscope_archive.retired_entity_rows WHERE migration_version='v2_1_to_v3';
SELECT role_code,count(*) FROM users GROUP BY role_code ORDER BY role_code;
SELECT count(*) AS invalid_roles FROM users WHERE role_code NOT IN ('user','admin');
SELECT count(*) AS invalid_external_stages FROM analysis_tasks WHERE external_stage NOT IN ('understanding_product','researching_market','evaluating_opportunity','generating_recommendation','completed');
SELECT count(*) AS legacy_review_stages FROM analysis_tasks WHERE internal_stage IN ('competitor_review','expert_review');
SELECT count(*) AS invalid_confirmations FROM user_confirmations
WHERE jsonb_typeof(options)<>'array' OR jsonb_array_length(options)=0 OR jsonb_typeof(evidence_refs)<>'array' OR jsonb_array_length(evidence_refs)=0;
SELECT count(*) AS reports_without_sections FROM analysis_reports WHERE jsonb_typeof(sections)<>'array' OR jsonb_array_length(sections)=0;
SELECT count(*) AS opportunities_without_fit_array FROM market_opportunities WHERE jsonb_typeof(manufacturing_fit)<>'array';
SELECT count(*) AS unsafe_checkpoint_refs FROM user_confirmations c LEFT JOIN workflow_checkpoints w ON w.checkpoint_id=c.checkpoint_id WHERE c.checkpoint_id IS NOT NULL AND (w.id IS NULL OR NOT w.is_safe_resume);
SELECT count(*) AS legacy_physical_columns FROM information_schema.columns
WHERE table_schema='furniscope'
  AND ((table_name='enterprise_profiles' AND column_name='business_models')
    OR (table_name='analysis_tasks' AND column_name='product_profile_version')
    OR (table_name IN ('competitor_matches','review_aspects','insight_clusters','market_metrics','price_bands','market_opportunities','evidence_links','analysis_reports') AND column_name='task_id'));
