\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS customer_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workspace_id BIGINT REFERENCES analysis_workspaces(id) ON DELETE CASCADE,
  memory_key VARCHAR(64) NOT NULL,
  memory_value JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(16) NOT NULL DEFAULT 'confirmed',
  confidence NUMERIC(5,4) NOT NULL DEFAULT 1,
  source_message_uuid UUID,
  expires_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_customer_memory_status CHECK (status IN ('candidate','confirmed','archived')),
  CONSTRAINT chk_customer_memory_json CHECK (jsonb_typeof(memory_value)='object'),
  CONSTRAINT uk_customer_memory_scope UNIQUE (tenant_id,user_id,workspace_id,memory_key)
);
CREATE INDEX IF NOT EXISTS idx_customer_memories_lookup
  ON customer_memories(tenant_id,user_id,status,updated_at DESC);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version TEXT PRIMARY KEY,applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),checksum TEXT
);
INSERT INTO schema_migrations(version) VALUES('v3_18_customer_memory') ON CONFLICT DO NOTHING;

COMMIT;
