\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

-- Conversation container for AI workbench. One workspace owns many analysis_tasks
-- (via analysis_config.workspace_uuid) and one ordered message log.
CREATE TABLE IF NOT EXISTS analysis_workspaces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_uuid UUID NOT NULL UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(200) NOT NULL,
  source VARCHAR(64) NOT NULL DEFAULT 'node_workflow_canvas',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  product_id BIGINT REFERENCES products(id),
  last_analysis_task_id BIGINT REFERENCES analysis_tasks(id),
  created_by BIGINT NOT NULL REFERENCES users(id),
  archived_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_workspace_tenant_uuid UNIQUE (tenant_id, workspace_uuid),
  CONSTRAINT chk_workspace_status CHECK (status IN ('active', 'archived')),
  CONSTRAINT chk_workspace_archive CHECK ((status = 'archived') = (archived_at IS NOT NULL))
);
COMMENT ON TABLE analysis_workspaces IS
  'AI workbench conversation container; work diary groups analysis_tasks that share this workspace_uuid.';
CREATE INDEX IF NOT EXISTS idx_workspace_tenant_updated
  ON analysis_workspaces(tenant_id, updated_at DESC)
  WHERE status = 'active';

CREATE TABLE IF NOT EXISTS analysis_workspace_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  workspace_id BIGINT NOT NULL REFERENCES analysis_workspaces(id) ON DELETE CASCADE,
  analysis_task_id BIGINT REFERENCES analysis_tasks(id) ON DELETE SET NULL,
  model_run_id BIGINT REFERENCES ai_model_runs(id) ON DELETE SET NULL,
  role VARCHAR(16) NOT NULL,
  message_kind VARCHAR(24) NOT NULL DEFAULT 'text',
  content TEXT NOT NULL,
  seq_no INTEGER NOT NULL,
  client_message_id VARCHAR(128),
  evidence_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_workspace_message_seq UNIQUE (workspace_id, seq_no),
  CONSTRAINT chk_workspace_message_role CHECK (role IN ('user', 'assistant', 'system')),
  CONSTRAINT chk_workspace_message_kind CHECK (message_kind IN (
    'greeting', 'text', 'run_event', 'task_chat', 'error', 'context'
  )),
  CONSTRAINT chk_workspace_message_content CHECK (char_length(content) BETWEEN 1 AND 20000),
  CONSTRAINT chk_workspace_message_seq CHECK (seq_no >= 1),
  CONSTRAINT chk_workspace_message_json CHECK (
    jsonb_typeof(evidence_refs) = 'array' AND jsonb_typeof(metadata) = 'object'
  )
);
COMMENT ON TABLE analysis_workspace_messages IS
  'Ordered workbench chat turns. Do not store model system prompts or full task-result JSON dumps.';
COMMENT ON COLUMN analysis_workspace_messages.analysis_task_id IS
  'Run this turn launched or asked about; null for greeting and workspace-only talk.';
COMMENT ON COLUMN analysis_workspace_messages.evidence_refs IS
  'Task-chat citation ids from API-INS-07; empty for ordinary UI event messages.';
CREATE INDEX IF NOT EXISTS idx_workspace_messages_workspace_time
  ON analysis_workspace_messages(workspace_id, seq_no);
CREATE INDEX IF NOT EXISTS idx_workspace_messages_tenant_time
  ON analysis_workspace_messages(tenant_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_message_client
  ON analysis_workspace_messages(tenant_id, client_message_id)
  WHERE client_message_id IS NOT NULL;

CREATE OR REPLACE FUNCTION furniscope.touch_analysis_workspaces() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_analysis_workspaces_updated ON analysis_workspaces;
CREATE TRIGGER trg_analysis_workspaces_updated
  BEFORE UPDATE ON analysis_workspaces
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();

INSERT INTO analysis_workspaces (
  workspace_uuid, tenant_id, name, source, status, product_id, last_analysis_task_id, created_by
)
SELECT DISTINCT ON (t.tenant_id, (t.analysis_config->>'workspace_uuid')::uuid)
  (t.analysis_config->>'workspace_uuid')::uuid,
  t.tenant_id,
  t.job_name,
  COALESCE(NULLIF(t.analysis_config->>'source',''), 'node_workflow_canvas'),
  'active',
  t.product_id,
  t.id,
  t.created_by
FROM analysis_tasks t
WHERE t.analysis_config ? 'workspace_uuid'
  AND t.analysis_config->>'workspace_uuid' ~ '^[0-9a-fA-F-]{36}$'
  AND t.created_by IS NOT NULL
ORDER BY t.tenant_id, (t.analysis_config->>'workspace_uuid')::uuid, t.updated_at DESC
ON CONFLICT (tenant_id, workspace_uuid) DO NOTHING;

COMMIT;
