\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

CREATE TABLE IF NOT EXISTS permission_catalog (
  permission_code VARCHAR(80) PRIMARY KEY,
  description VARCHAR(240) NOT NULL,
  risk_level VARCHAR(16) NOT NULL DEFAULT 'standard',
  CONSTRAINT chk_permission_risk CHECK(risk_level IN ('read','standard','high'))
);

INSERT INTO permission_catalog(permission_code,description,risk_level) VALUES
  ('tenant.members.manage','管理企业成员角色','high'),
  ('tenant.settings.write','修改企业级配置','high'),
  ('product.read','读取产品与产品画像','read'),
  ('product.write','创建或修改产品与产品画像','standard'),
  ('dataset.read','读取市场与经营数据','read'),
  ('dataset.write','上传、修改或删除数据','high'),
  ('forecast.read','读取预测结果和训练状态','read'),
  ('forecast.train','创建训练任务和修改训练配置','high'),
  ('forecast.publish','发布、替换或回滚模型','high'),
  ('analysis.read','读取分析任务、报告和证据','read'),
  ('analysis.execute','创建、启动或确认分析任务','standard'),
  ('knowledge.read','读取和检索企业知识库','read'),
  ('knowledge.write','维护知识库和文档','standard'),
  ('memory.read','读取企业记忆','read'),
  ('memory.write','确认、归档或删除企业记忆','high'),
  ('audit.read','读取并验证企业审计链','read')
ON CONFLICT(permission_code) DO UPDATE
SET description=EXCLUDED.description,risk_level=EXCLUDED.risk_level;

CREATE TABLE IF NOT EXISTS tenant_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  role_code VARCHAR(64) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  built_in BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_tenant_roles_boundary UNIQUE(id,tenant_id),
  CONSTRAINT uk_tenant_role_code UNIQUE(tenant_id,role_code),
  CONSTRAINT fk_tenant_roles_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT chk_tenant_role_code CHECK(role_code ~ '^[a-z][a-z0-9_]{1,63}$')
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  permission_code VARCHAR(80) NOT NULL REFERENCES permission_catalog(permission_code),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_role_permission UNIQUE(tenant_id,role_id,permission_code),
  CONSTRAINT uk_role_permissions_boundary UNIQUE(id,tenant_id),
  CONSTRAINT fk_role_permissions_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_role_permissions_role FOREIGN KEY(role_id,tenant_id)
    REFERENCES tenant_roles(id,tenant_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_role_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_by BIGINT,
  assigned_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ(3),
  CONSTRAINT uk_user_role_assignment UNIQUE(tenant_id,user_id,role_id),
  CONSTRAINT uk_user_role_assignments_boundary UNIQUE(id,tenant_id),
  CONSTRAINT fk_user_role_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_user_role_user FOREIGN KEY(user_id,tenant_id)
    REFERENCES users(id,tenant_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_role_role FOREIGN KEY(role_id,tenant_id)
    REFERENCES tenant_roles(id,tenant_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_role_assigner FOREIGN KEY(assigned_by,tenant_id)
    REFERENCES users(id,tenant_id) ON DELETE SET NULL (assigned_by),
  CONSTRAINT chk_user_role_expiry CHECK(expires_at IS NULL OR expires_at>assigned_at)
);

CREATE INDEX IF NOT EXISTS idx_tenant_roles_lookup
  ON tenant_roles(tenant_id,role_code);
CREATE INDEX IF NOT EXISTS idx_role_permissions_effective
  ON role_permissions(tenant_id,role_id,permission_code);
CREATE INDEX IF NOT EXISTS idx_user_role_effective
  ON user_role_assignments(tenant_id,user_id,expires_at,role_id);

CREATE OR REPLACE FUNCTION seed_tenant_builtin_roles(target_tenant_id BIGINT)
RETURNS void LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE role_spec record;
DECLARE permission text;
DECLARE target_role_id bigint;
BEGIN
  FOR role_spec IN
    SELECT * FROM (VALUES
      ('tenant_owner','企业所有者','企业全权限与成员管理',
       ARRAY['tenant.members.manage','tenant.settings.write','product.read','product.write',
             'dataset.read','dataset.write','forecast.read','forecast.train','forecast.publish',
             'analysis.read','analysis.execute','knowledge.read','knowledge.write',
             'memory.read','memory.write','audit.read']::text[]),
      ('data_admin','数据管理员','维护企业数据、知识和记忆',
       ARRAY['product.read','product.write','dataset.read','dataset.write','forecast.read',
             'forecast.train','analysis.read','analysis.execute','knowledge.read',
             'knowledge.write','memory.read','memory.write','audit.read']::text[]),
      ('analyst','分析师','执行分析与训练并维护业务事实',
       ARRAY['product.read','product.write','dataset.read','dataset.write','forecast.read',
             'forecast.train','analysis.read','analysis.execute','knowledge.read',
             'knowledge.write','memory.read','memory.write']::text[]),
      ('operator','运营人员','维护产品数据并执行分析',
       ARRAY['product.read','product.write','dataset.read','dataset.write','forecast.read',
             'analysis.read','analysis.execute','knowledge.read','memory.read']::text[]),
      ('auditor','审计员','只读业务数据和审计记录',
       ARRAY['product.read','dataset.read','forecast.read','analysis.read','knowledge.read',
             'memory.read','audit.read']::text[]),
      ('viewer','访客','只读企业业务数据',
       ARRAY['product.read','dataset.read','forecast.read','analysis.read','knowledge.read',
             'memory.read']::text[])
    ) AS roles(role_code,display_name,description,permissions)
  LOOP
    INSERT INTO tenant_roles(tenant_id,role_code,display_name,description,built_in)
    VALUES(target_tenant_id,role_spec.role_code,role_spec.display_name,role_spec.description,true)
    ON CONFLICT(tenant_id,role_code) DO UPDATE
      SET display_name=EXCLUDED.display_name,description=EXCLUDED.description,built_in=true
    RETURNING id INTO target_role_id;
    FOREACH permission IN ARRAY role_spec.permissions LOOP
      INSERT INTO role_permissions(tenant_id,role_id,permission_code)
      VALUES(target_tenant_id,target_role_id,permission)
      ON CONFLICT DO NOTHING;
    END LOOP;
  END LOOP;
END $$;

DO $$
DECLARE tenant_record record;
DECLARE owner_user_id bigint;
DECLARE owner_role_id bigint;
DECLARE user_record record;
DECLARE viewer_role_id bigint;
BEGIN
  FOR tenant_record IN SELECT id FROM tenants ORDER BY id LOOP
    PERFORM seed_tenant_builtin_roles(tenant_record.id);
    SELECT id INTO owner_role_id FROM tenant_roles
     WHERE tenant_id=tenant_record.id AND role_code='tenant_owner';
    SELECT id INTO viewer_role_id FROM tenant_roles
     WHERE tenant_id=tenant_record.id AND role_code='viewer';
    SELECT id INTO owner_user_id FROM users
     WHERE tenant_id=tenant_record.id AND role_code='user'
     ORDER BY created_at,id LIMIT 1;
    IF owner_user_id IS NOT NULL THEN
      INSERT INTO user_role_assignments(tenant_id,user_id,role_id)
      VALUES(tenant_record.id,owner_user_id,owner_role_id)
      ON CONFLICT DO NOTHING;
    END IF;
    FOR user_record IN
      SELECT id FROM users
       WHERE tenant_id=tenant_record.id AND role_code='user' AND id<>owner_user_id
    LOOP
      INSERT INTO user_role_assignments(tenant_id,user_id,role_id)
      VALUES(tenant_record.id,user_record.id,viewer_role_id)
      ON CONFLICT DO NOTHING;
    END LOOP;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION seed_roles_for_new_tenant()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
BEGIN
  PERFORM furniscope.seed_tenant_builtin_roles(NEW.id);
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_tenants_seed_roles ON tenants;
CREATE TRIGGER trg_tenants_seed_roles
AFTER INSERT ON tenants FOR EACH ROW EXECUTE FUNCTION seed_roles_for_new_tenant();

CREATE OR REPLACE FUNCTION assign_default_role_to_user()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE selected_role_id bigint;
BEGIN
  IF NEW.role_code<>'user' THEN
    RETURN NEW;
  END IF;
  SELECT id INTO selected_role_id FROM tenant_roles
   WHERE tenant_id=NEW.tenant_id
     AND role_code=CASE
       WHEN EXISTS(
         SELECT FROM user_role_assignments a
         JOIN tenant_roles r ON r.id=a.role_id AND r.tenant_id=a.tenant_id
        WHERE a.tenant_id=NEW.tenant_id AND r.role_code='tenant_owner'
       ) THEN 'viewer' ELSE 'tenant_owner' END;
  IF selected_role_id IS NOT NULL THEN
    INSERT INTO user_role_assignments(tenant_id,user_id,role_id)
    VALUES(NEW.tenant_id,NEW.id,selected_role_id)
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_users_default_role ON users;
CREATE TRIGGER trg_users_default_role
AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION assign_default_role_to_user();

ALTER TABLE tenant_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_roles FORCE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions FORCE ROW LEVEL SECURITY;
ALTER TABLE user_role_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_role_assignments FORCE ROW LEVEL SECURITY;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'tenant_roles','role_permissions','user_role_assignments'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS authenticator_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY authenticator_scope ON %I FOR SELECT TO furniscope_authenticator
       USING(true)',
      table_name
    );
  END LOOP;
END $$;

GRANT SELECT ON permission_catalog TO
  furniscope_authenticator,furniscope_tenant,furniscope_platform_admin;
GRANT SELECT ON tenant_roles,role_permissions,user_role_assignments TO furniscope_authenticator;
GRANT SELECT ON tenant_roles,role_permissions,user_role_assignments TO furniscope_tenant;
GRANT INSERT,UPDATE,DELETE ON tenant_roles,role_permissions,user_role_assignments
  TO furniscope_tenant;
GRANT SELECT,INSERT,UPDATE,DELETE ON tenant_roles,role_permissions,user_role_assignments
  TO furniscope_platform_admin;
GRANT USAGE,SELECT ON SEQUENCE
  tenant_roles_id_seq,role_permissions_id_seq,user_role_assignments_id_seq
  TO furniscope_tenant,furniscope_platform_admin;

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS event_uuid UUID;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS chain_sequence BIGINT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS previous_hash CHAR(64);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS event_hash CHAR(64);

CREATE OR REPLACE FUNCTION audit_event_hash(
  event_uuid UUID,
  tenant_id BIGINT,
  chain_sequence BIGINT,
  previous_hash TEXT,
  actor_user_id BIGINT,
  action_code TEXT,
  resource_type TEXT,
  resource_id BIGINT,
  request_id TEXT,
  before_snapshot JSONB,
  after_snapshot JSONB,
  ip_address TEXT,
  user_agent TEXT,
  occurred_at TIMESTAMPTZ
) RETURNS CHAR(64)
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
  SELECT encode(digest(convert_to(jsonb_build_object(
    'event_uuid',event_uuid::text,
    'tenant_id',tenant_id,
    'chain_sequence',chain_sequence,
    'previous_hash',previous_hash,
    'actor_user_id',actor_user_id,
    'action_code',action_code,
    'resource_type',resource_type,
    'resource_id',resource_id,
    'request_id',request_id,
    'before_snapshot',before_snapshot,
    'after_snapshot',after_snapshot,
    'ip_address',ip_address,
    'user_agent',user_agent,
    'occurred_at',to_char(occurred_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
  )::text,'UTF8'),'sha256'),'hex')::char(64)
$$;

DO $$
DECLARE audit_record record;
DECLARE next_sequence bigint;
DECLARE prior_hash char(64);
DECLARE calculated_hash char(64);
BEGIN
  FOR audit_record IN
    SELECT * FROM audit_logs
     WHERE chain_sequence IS NULL
     ORDER BY COALESCE(tenant_id,0),occurred_at,id FOR UPDATE
  LOOP
    SELECT COALESCE(max(chain_sequence),0)+1,event_hash
      INTO next_sequence,prior_hash
      FROM audit_logs
     WHERE COALESCE(tenant_id,0)=COALESCE(audit_record.tenant_id,0)
       AND chain_sequence IS NOT NULL
     GROUP BY event_hash,chain_sequence
     ORDER BY chain_sequence DESC LIMIT 1;
    next_sequence:=COALESCE(next_sequence,1);
    prior_hash:=COALESCE(prior_hash,repeat('0',64)::char(64));
    audit_record.event_uuid:=COALESCE(audit_record.event_uuid,gen_random_uuid());
    calculated_hash:=audit_event_hash(
      audit_record.event_uuid,audit_record.tenant_id,next_sequence,prior_hash,
      audit_record.actor_user_id,audit_record.action_code,audit_record.resource_type,
      audit_record.resource_id,audit_record.request_id,audit_record.before_snapshot,
      audit_record.after_snapshot,audit_record.ip_address,audit_record.user_agent,
      audit_record.occurred_at
    );
    UPDATE audit_logs SET event_uuid=audit_record.event_uuid,
      chain_sequence=next_sequence,previous_hash=prior_hash,event_hash=calculated_hash
     WHERE id=audit_record.id;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION prepare_audit_chain()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE prior audit_logs%ROWTYPE;
DECLARE chain_key bigint:=COALESCE(NEW.tenant_id,0);
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('furniscope.audit.'||chain_key::text,0));
  SELECT * INTO prior FROM audit_logs
   WHERE COALESCE(tenant_id,0)=chain_key
   ORDER BY chain_sequence DESC LIMIT 1;
  NEW.event_uuid:=COALESCE(NEW.event_uuid,gen_random_uuid());
  NEW.occurred_at:=COALESCE(NEW.occurred_at,CURRENT_TIMESTAMP);
  NEW.chain_sequence:=COALESCE(prior.chain_sequence,0)+1;
  NEW.previous_hash:=COALESCE(prior.event_hash,repeat('0',64)::char(64));
  NEW.event_hash:=audit_event_hash(
    NEW.event_uuid,NEW.tenant_id,NEW.chain_sequence,NEW.previous_hash,
    NEW.actor_user_id,NEW.action_code,NEW.resource_type,NEW.resource_id,
    NEW.request_id,NEW.before_snapshot,NEW.after_snapshot,NEW.ip_address,
    NEW.user_agent,NEW.occurred_at
  );
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_audit_chain_insert ON audit_logs;
CREATE TRIGGER trg_audit_chain_insert
BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION prepare_audit_chain();

CREATE OR REPLACE FUNCTION protect_audit_chain()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE table_owner text;
BEGIN
  SELECT owner.rolname INTO table_owner
    FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN pg_roles owner ON owner.oid=c.relowner
   WHERE n.nspname=TG_TABLE_SCHEMA AND c.relname=TG_TABLE_NAME;
  IF session_user=table_owner
     OR pg_has_role(session_user,'furniscope_migrator','MEMBER')
     OR pg_has_role(session_user,'furniscope_schema_owner','MEMBER') THEN
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
  END IF;
  RAISE EXCEPTION 'audit chain is append-only' USING ERRCODE='42501';
END $$;
DROP TRIGGER IF EXISTS trg_audit_chain_protect ON audit_logs;
CREATE TRIGGER trg_audit_chain_protect
BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION protect_audit_chain();

ALTER TABLE audit_logs ALTER COLUMN event_uuid SET NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN chain_sequence SET NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN previous_hash SET NOT NULL;
ALTER TABLE audit_logs ALTER COLUMN event_hash SET NOT NULL;
DO $$ BEGIN
  ALTER TABLE audit_logs ADD CONSTRAINT uk_audit_event_uuid UNIQUE(event_uuid);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_chain_sequence CHECK(chain_sequence>0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE audit_logs ADD CONSTRAINT chk_audit_hashes CHECK(
    previous_hash ~ '^[0-9a-f]{64}$' AND event_hash ~ '^[0-9a-f]{64}$'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_chain_sequence
  ON audit_logs(COALESCE(tenant_id,0),chain_sequence);
CREATE INDEX IF NOT EXISTS idx_audit_event_hash ON audit_logs(event_hash);

REVOKE UPDATE,DELETE,TRUNCATE ON audit_logs FROM
  PUBLIC,furniscope_tenant,furniscope_runtime,furniscope_platform_admin,
  furniscope_scheduler,furniscope_audit_writer;
GRANT SELECT,INSERT ON audit_logs TO
  furniscope_tenant,furniscope_platform_admin,furniscope_audit_writer;

INSERT INTO schema_migrations(version)
VALUES('v3_27_audit_rbac')
ON CONFLICT DO NOTHING;
COMMIT;
