\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

-- Customer memories are immutable versions. A candidate never overwrites a
-- confirmed value; confirmation supersedes the previous version explicitly.
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS memory_uuid UUID;
UPDATE customer_memories SET memory_uuid=gen_random_uuid() WHERE memory_uuid IS NULL;
ALTER TABLE customer_memories ALTER COLUMN memory_uuid SET DEFAULT gen_random_uuid();
ALTER TABLE customer_memories ALTER COLUMN memory_uuid SET NOT NULL;
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS memory_type VARCHAR(64) GENERATED ALWAYS AS (memory_key) STORED;
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS scope VARCHAR(16) NOT NULL DEFAULT 'user';
UPDATE customer_memories SET scope=CASE WHEN workspace_id IS NULL THEN 'user' ELSE 'workspace' END;
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS supersedes_memory_uuid UUID;
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ(3);
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ(3);
ALTER TABLE customer_memories ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE customer_memories DROP CONSTRAINT IF EXISTS uk_customer_memory_scope;
ALTER TABLE customer_memories DROP CONSTRAINT IF EXISTS chk_customer_memory_status;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_status
    CHECK(status IN ('candidate','confirmed','superseded','archived'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_scope
    CHECK(
      (scope='workspace' AND workspace_id IS NOT NULL AND user_id IS NOT NULL) OR
      (scope='user' AND workspace_id IS NULL AND user_id IS NOT NULL) OR
      (scope='tenant' AND workspace_id IS NULL AND user_id IS NULL)
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_metadata
    CHECK(jsonb_typeof(metadata)='object');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT uk_customer_memory_uuid_tenant
    UNIQUE(memory_uuid,tenant_id);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT fk_customer_memory_supersedes
    FOREIGN KEY(supersedes_memory_uuid,tenant_id)
    REFERENCES customer_memories(memory_uuid,tenant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

WITH ranked AS (
  SELECT id,row_number() OVER(
    PARTITION BY tenant_id,scope,user_id,workspace_id,memory_key
    ORDER BY updated_at DESC,id DESC
  ) AS position
  FROM customer_memories WHERE status='confirmed'
)
UPDATE customer_memories m
   SET status='archived',archived_at=COALESCE(m.archived_at,CURRENT_TIMESTAMP)
  FROM ranked r WHERE r.id=m.id AND r.position>1;
CREATE UNIQUE INDEX IF NOT EXISTS uk_customer_memory_confirmed_workspace
  ON customer_memories(tenant_id,user_id,workspace_id,memory_key)
  WHERE status='confirmed' AND scope='workspace';
CREATE UNIQUE INDEX IF NOT EXISTS uk_customer_memory_confirmed_user
  ON customer_memories(tenant_id,user_id,memory_key)
  WHERE status='confirmed' AND scope='user';
CREATE UNIQUE INDEX IF NOT EXISTS uk_customer_memory_confirmed_tenant
  ON customer_memories(tenant_id,memory_key)
  WHERE status='confirmed' AND scope='tenant';
CREATE INDEX IF NOT EXISTS idx_customer_memory_versions
  ON customer_memories(tenant_id,memory_key,created_at DESC);

CREATE TABLE IF NOT EXISTS customer_memory_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  policy_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT,
  auto_extract BOOLEAN NOT NULL DEFAULT TRUE,
  confirmation_required BOOLEAN NOT NULL DEFAULT TRUE,
  default_scope VARCHAR(16) NOT NULL DEFAULT 'workspace',
  retention_days INTEGER NOT NULL DEFAULT 365,
  allowed_types JSONB NOT NULL DEFAULT
    '["target_market","budget","unit_cost_limit","preferred_channel","customer_preference"]'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,user_id),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id,tenant_id) REFERENCES users(id,tenant_id) ON DELETE CASCADE,
  CHECK(default_scope IN ('workspace','user','tenant')),
  CHECK(retention_days BETWEEN 1 AND 3650),
  CHECK(jsonb_typeof(allowed_types)='array')
);

CREATE TABLE IF NOT EXISTS analysis_workspace_turns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turn_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  workspace_id BIGINT NOT NULL,
  client_turn_id UUID NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  task_id BIGINT,
  regenerated_from_turn_uuid UUID,
  user_message_uuid UUID,
  assistant_message_uuid UUID,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  request_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  response_payload JSONB,
  error_code VARCHAR(64),
  created_by BIGINT NOT NULL,
  started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ(3),
  cancelled_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,workspace_id,client_turn_id),
  UNIQUE(tenant_id,workspace_id,idempotency_key),
  UNIQUE(id,tenant_id),
  UNIQUE(turn_uuid,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(workspace_id,tenant_id) REFERENCES analysis_workspaces(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(task_id,tenant_id) REFERENCES analysis_tasks(id,tenant_id),
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  FOREIGN KEY(regenerated_from_turn_uuid) REFERENCES analysis_workspace_turns(turn_uuid),
  FOREIGN KEY(user_message_uuid) REFERENCES analysis_workspace_messages(message_uuid) ON DELETE SET NULL,
  FOREIGN KEY(assistant_message_uuid) REFERENCES analysis_workspace_messages(message_uuid) ON DELETE SET NULL,
  CHECK(status IN ('pending','completed','failed','cancelled')),
  CHECK(jsonb_typeof(request_payload)='object'),
  CHECK(response_payload IS NULL OR jsonb_typeof(response_payload)='object'),
  CHECK(
    (status='pending' AND completed_at IS NULL AND cancelled_at IS NULL) OR
    (status='completed' AND completed_at IS NOT NULL AND cancelled_at IS NULL) OR
    (status='failed' AND completed_at IS NOT NULL AND cancelled_at IS NULL) OR
    (status='cancelled' AND cancelled_at IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_workspace_turns_history
  ON analysis_workspace_turns(tenant_id,workspace_id,created_at DESC);
ALTER TABLE analysis_workspace_messages ADD COLUMN IF NOT EXISTS turn_uuid UUID;
ALTER TABLE analysis_workspace_messages ADD COLUMN IF NOT EXISTS message_version INTEGER NOT NULL DEFAULT 1;
DO $$ BEGIN
  ALTER TABLE analysis_workspace_messages ADD CONSTRAINT fk_workspace_message_turn
    FOREIGN KEY(turn_uuid,tenant_id)
    REFERENCES analysis_workspace_turns(turn_uuid,tenant_id)
    ON DELETE SET NULL (turn_uuid) DEFERRABLE INITIALLY DEFERRED;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE analysis_workspace_messages ADD CONSTRAINT chk_workspace_message_version
    CHECK(message_version>0);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_turn_role
  ON analysis_workspace_messages(tenant_id,turn_uuid,role)
  WHERE turn_uuid IS NOT NULL AND role IN ('user','assistant');

CREATE TABLE IF NOT EXISTS analysis_workspace_contexts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  workspace_id BIGINT NOT NULL,
  revision INTEGER NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,workspace_id,revision),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(workspace_id,tenant_id) REFERENCES analysis_workspaces(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(revision>0),
  CHECK(jsonb_typeof(configuration)='object')
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_context_current
  ON analysis_workspace_contexts(tenant_id,workspace_id) WHERE is_current;

CREATE TABLE IF NOT EXISTS analysis_context_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context_snapshot_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  workspace_id BIGINT NOT NULL,
  turn_uuid UUID,
  context_revision INTEGER,
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  estimated_tokens INTEGER NOT NULL DEFAULT 0,
  truncated_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  context_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  UNIQUE(tenant_id,turn_uuid),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(workspace_id,tenant_id) REFERENCES analysis_workspaces(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(turn_uuid,tenant_id) REFERENCES analysis_workspace_turns(turn_uuid,tenant_id) ON DELETE CASCADE,
  CHECK(jsonb_typeof(configuration)='object'),
  CHECK(jsonb_typeof(sources)='array'),
  CHECK(jsonb_typeof(truncated_sources)='array'),
  CHECK(estimated_tokens>=0)
);

CREATE TABLE IF NOT EXISTS citations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  citation_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  workspace_id BIGINT,
  turn_uuid UUID,
  assistant_message_uuid UUID,
  source_type VARCHAR(48) NOT NULL,
  source_id VARCHAR(200) NOT NULL,
  source_version VARCHAR(64),
  label VARCHAR(300) NOT NULL,
  locator JSONB NOT NULL DEFAULT '{}'::jsonb,
  excerpt TEXT,
  score NUMERIC(8,7),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(workspace_id,tenant_id) REFERENCES analysis_workspaces(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(turn_uuid,tenant_id) REFERENCES analysis_workspace_turns(turn_uuid,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(assistant_message_uuid) REFERENCES analysis_workspace_messages(message_uuid) ON DELETE SET NULL,
  CHECK(jsonb_typeof(locator)='object'),
  CHECK(score IS NULL OR score BETWEEN 0 AND 1)
);
CREATE INDEX IF NOT EXISTS idx_citations_turn
  ON citations(tenant_id,turn_uuid,created_at);

CREATE TABLE IF NOT EXISTS knowledge_bases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_base_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(2000),
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived_at TIMESTAMPTZ(3),
  UNIQUE(id,tenant_id),
  UNIQUE(tenant_id,name),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(status IN ('active','archived')),
  CHECK((status='archived')=(archived_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS knowledge_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  knowledge_base_id BIGINT NOT NULL,
  filename VARCHAR(500) NOT NULL,
  mime_type VARCHAR(200) NOT NULL,
  document_type VARCHAR(64),
  status VARCHAR(16) NOT NULL DEFAULT 'uploaded',
  current_version INTEGER NOT NULL DEFAULT 1,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_code VARCHAR(64),
  error_message VARCHAR(1000),
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3),
  UNIQUE(id,tenant_id),
  UNIQUE(document_uuid,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(knowledge_base_id,tenant_id) REFERENCES knowledge_bases(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(status IN ('uploaded','parsing','chunking','embedding','ready','failed','deleted')),
  CHECK(current_version>0),
  CHECK(jsonb_typeof(metadata)='object'),
  CHECK((status='deleted')=(deleted_at IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_knowledge_documents_base
  ON knowledge_documents(tenant_id,knowledge_base_id,created_at DESC);

CREATE TABLE IF NOT EXISTS knowledge_document_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_version_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  document_id BIGINT NOT NULL,
  version INTEGER NOT NULL,
  sha256 CHAR(64) NOT NULL,
  byte_size BIGINT NOT NULL,
  source_content BYTEA NOT NULL,
  extracted_text TEXT,
  extraction_method VARCHAR(64),
  page_or_sheet_count INTEGER,
  embedding_model VARCHAR(128),
  embedding_dimensions INTEGER,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,document_id,version),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(document_id,tenant_id) REFERENCES knowledge_documents(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(byte_size>0),
  CHECK(page_or_sheet_count IS NULL OR page_or_sheet_count>0),
  CHECK(embedding_dimensions IS NULL OR embedding_dimensions>0)
);

CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chunk_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  document_id BIGINT NOT NULL,
  document_version_id BIGINT NOT NULL,
  chunk_index INTEGER NOT NULL,
  page INTEGER,
  chunk_text TEXT NOT NULL,
  token_estimate INTEGER NOT NULL,
  embedding JSONB,
  search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple',chunk_text)) STORED,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,document_version_id,chunk_index),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(document_id,tenant_id) REFERENCES knowledge_documents(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(document_version_id,tenant_id)
    REFERENCES knowledge_document_versions(id,tenant_id) ON DELETE CASCADE,
  CHECK(chunk_index>=0),
  CHECK(page IS NULL OR page>0),
  CHECK(char_length(chunk_text)>0),
  CHECK(token_estimate>0),
  CHECK(embedding IS NULL OR jsonb_typeof(embedding)='array')
);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_search
  ON knowledge_chunks USING GIN(search_vector);

CREATE TABLE IF NOT EXISTS knowledge_index_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  index_job_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  document_id BIGINT NOT NULL,
  document_version_id BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'queued',
  attempt INTEGER NOT NULL DEFAULT 0,
  error_code VARCHAR(64),
  error_message VARCHAR(1000),
  queued_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMPTZ(3),
  finished_at TIMESTAMPTZ(3),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(document_id,tenant_id) REFERENCES knowledge_documents(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(document_version_id,tenant_id)
    REFERENCES knowledge_document_versions(id,tenant_id) ON DELETE CASCADE,
  CHECK(status IN ('queued','running','succeeded','failed','cancelled')),
  CHECK(attempt>=0)
);
CREATE INDEX IF NOT EXISTS idx_knowledge_jobs_queue
  ON knowledge_index_jobs(status,queued_at) WHERE status='queued';

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'customer_memories','customer_memory_policies','analysis_workspace_turns',
    'analysis_workspace_contexts','analysis_context_snapshots','citations',
    'knowledge_bases','knowledge_documents','knowledge_document_versions',
    'knowledge_chunks','knowledge_index_jobs'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',t);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',t
    );
    EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO furniscope_tenant',t);
  END LOOP;
END $$;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA furniscope TO furniscope_tenant;

DROP TRIGGER IF EXISTS trg_customer_memory_policies_updated ON customer_memory_policies;
CREATE TRIGGER trg_customer_memory_policies_updated BEFORE UPDATE ON customer_memory_policies
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();
DROP TRIGGER IF EXISTS trg_analysis_workspace_turns_updated ON analysis_workspace_turns;
CREATE TRIGGER trg_analysis_workspace_turns_updated BEFORE UPDATE ON analysis_workspace_turns
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();
DROP TRIGGER IF EXISTS trg_knowledge_bases_updated ON knowledge_bases;
CREATE TRIGGER trg_knowledge_bases_updated BEFORE UPDATE ON knowledge_bases
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();
DROP TRIGGER IF EXISTS trg_knowledge_documents_updated ON knowledge_documents;
CREATE TRIGGER trg_knowledge_documents_updated BEFORE UPDATE ON knowledge_documents
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();

INSERT INTO schema_migrations(version) VALUES('v3_23_context_lifecycle') ON CONFLICT DO NOTHING;
COMMIT;
