\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

CREATE TABLE IF NOT EXISTS deployment_cells (
  cell_code VARCHAR(64) PRIMARY KEY,
  display_name VARCHAR(160) NOT NULL,
  region_code VARCHAR(64) NOT NULL,
  cell_kind VARCHAR(16) NOT NULL DEFAULT 'shared',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  is_default BOOLEAN NOT NULL DEFAULT false,
  routing_endpoint VARCHAR(500),
  database_secret_ref VARCHAR(500),
  capacity_tenants INTEGER,
  safe_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_deployment_cell_code CHECK(cell_code ~ '^[a-z][a-z0-9-]{1,63}$'),
  CONSTRAINT chk_deployment_cell_region CHECK(region_code ~ '^[a-z][a-z0-9-]{1,63}$'),
  CONSTRAINT chk_deployment_cell_kind CHECK(cell_kind IN ('shared','dedicated')),
  CONSTRAINT chk_deployment_cell_status CHECK(
    status IN ('provisioning','active','draining','offline')
  ),
  CONSTRAINT chk_deployment_cell_capacity CHECK(
    capacity_tenants IS NULL OR capacity_tenants>0
  ),
  CONSTRAINT chk_deployment_cell_metadata CHECK(jsonb_typeof(safe_metadata)='object')
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_deployment_cell_default
  ON deployment_cells(is_default) WHERE is_default;
COMMENT ON TABLE deployment_cells IS
  'Credential-free control-plane directory. database_secret_ref names a secret; it never stores credentials.';

INSERT INTO deployment_cells(
  cell_code,display_name,region_code,cell_kind,status,is_default,safe_metadata
) VALUES(
  'cell-local','Local primary cell','local','shared','active',true,
  '{"bootstrap":"v3_29"}'::jsonb
) ON CONFLICT(cell_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS tenant_placements (
  tenant_id BIGINT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  cell_code VARCHAR(64) NOT NULL REFERENCES deployment_cells(cell_code),
  residency_region VARCHAR(64) NOT NULL,
  service_tier VARCHAR(24) NOT NULL DEFAULT 'standard',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  placement_version BIGINT NOT NULL DEFAULT 1,
  routing_generation BIGINT NOT NULL DEFAULT 1,
  migration_uuid UUID,
  placed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_tenant_placement_boundary UNIQUE(tenant_id,cell_code),
  CONSTRAINT chk_tenant_placement_region CHECK(
    residency_region ~ '^[a-z][a-z0-9-]{1,63}$'
  ),
  CONSTRAINT chk_tenant_placement_tier CHECK(
    service_tier IN ('standard','priority','dedicated','regulated')
  ),
  CONSTRAINT chk_tenant_placement_status CHECK(
    status IN ('active','migrating','frozen','validating','cutover','failed')
  ),
  CONSTRAINT chk_tenant_placement_versions CHECK(
    placement_version>0 AND routing_generation>0
  ),
  CONSTRAINT chk_tenant_placement_migration CHECK(
    (status='active' AND migration_uuid IS NULL)
    OR (status<>'active' AND migration_uuid IS NOT NULL)
  )
);
CREATE INDEX IF NOT EXISTS idx_tenant_placements_route
  ON tenant_placements(cell_code,status,tenant_id);

CREATE TABLE IF NOT EXISTS tenant_migration_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  source_cell_code VARCHAR(64) NOT NULL REFERENCES deployment_cells(cell_code),
  target_cell_code VARCHAR(64) NOT NULL REFERENCES deployment_cells(cell_code),
  status VARCHAR(20) NOT NULL DEFAULT 'planned',
  requested_by BIGINT REFERENCES users(id),
  package_sha256 CHAR(64),
  source_row_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  target_row_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  validation_hash CHAR(64),
  failure_code VARCHAR(100),
  failure_detail VARCHAR(2000),
  planned_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  frozen_at TIMESTAMPTZ(3),
  exported_at TIMESTAMPTZ(3),
  restored_at TIMESTAMPTZ(3),
  validated_at TIMESTAMPTZ(3),
  cutover_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_tenant_migration_boundary UNIQUE(id,tenant_id),
  CONSTRAINT chk_tenant_migration_cells CHECK(source_cell_code<>target_cell_code),
  CONSTRAINT chk_tenant_migration_status CHECK(
    status IN (
      'planned','freezing','exporting','restoring','validating',
      'cutover','completed','failed','rolled_back'
    )
  ),
  CONSTRAINT chk_tenant_migration_hashes CHECK(
    (package_sha256 IS NULL OR package_sha256 ~ '^[0-9a-f]{64}$')
    AND (validation_hash IS NULL OR validation_hash ~ '^[0-9a-f]{64}$')
  ),
  CONSTRAINT chk_tenant_migration_counts CHECK(
    jsonb_typeof(source_row_counts)='object'
    AND jsonb_typeof(target_row_counts)='object'
  )
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_tenant_migration_active
  ON tenant_migration_jobs(tenant_id)
  WHERE status IN (
    'planned','freezing','exporting','restoring','validating','cutover'
  );
CREATE INDEX IF NOT EXISTS idx_tenant_migration_status
  ON tenant_migration_jobs(status,updated_at,tenant_id);

INSERT INTO tenant_placements(
  tenant_id,cell_code,residency_region,service_tier,status
)
SELECT id,'cell-local','local','standard','active'
  FROM tenants
ON CONFLICT(tenant_id) DO NOTHING;

CREATE OR REPLACE FUNCTION seed_tenant_placement()
RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO furniscope,public AS $$
DECLARE configured_cell text;
DECLARE selected_cell deployment_cells%ROWTYPE;
BEGIN
  configured_cell := nullif(current_setting('furniscope.cell_code',true),'');
  SELECT * INTO selected_cell
    FROM deployment_cells
   WHERE status='active'
     AND (cell_code=configured_cell OR (configured_cell IS NULL AND is_default))
   ORDER BY (cell_code=configured_cell) DESC,is_default DESC,cell_code
   LIMIT 1;
  IF selected_cell.cell_code IS NULL THEN
    RAISE EXCEPTION 'no active deployment cell is configured'
      USING ERRCODE='55000';
  END IF;
  INSERT INTO tenant_placements(
    tenant_id,cell_code,residency_region,service_tier,status
  ) VALUES(
    NEW.id,selected_cell.cell_code,selected_cell.region_code,'standard','active'
  ) ON CONFLICT(tenant_id) DO NOTHING;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_tenants_seed_placement ON tenants;
CREATE TRIGGER trg_tenants_seed_placement
AFTER INSERT ON tenants FOR EACH ROW EXECUTE FUNCTION seed_tenant_placement();

CREATE OR REPLACE FUNCTION enforce_tenant_write_fence()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE target_tenant_id bigint;
DECLARE placement_status text;
DECLARE active_migration uuid;
DECLARE bypass_token text;
BEGIN
  IF TG_TABLE_NAME='tenants' THEN
    IF TG_OP='INSERT' THEN RETURN NEW; END IF;
    target_tenant_id := OLD.id;
  ELSIF TG_OP='DELETE' THEN
    target_tenant_id := OLD.tenant_id;
  ELSE
    target_tenant_id := NEW.tenant_id;
  END IF;
  IF target_tenant_id IS NULL THEN
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
  END IF;
  SELECT status,migration_uuid
    INTO placement_status,active_migration
    FROM tenant_placements
   WHERE tenant_id=target_tenant_id;
  IF placement_status IS NULL OR placement_status='active' THEN
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
  END IF;
  bypass_token := nullif(current_setting('furniscope.migration_bypass',true),'');
  IF active_migration IS NOT NULL
     AND bypass_token=active_migration::text
     AND (
       pg_has_role(session_user,'furniscope_migrator','MEMBER')
       OR EXISTS(SELECT FROM pg_roles WHERE rolname=session_user AND rolsuper)
     ) THEN
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
  END IF;
  RAISE EXCEPTION 'tenant % writes are fenced while placement status is %',
    target_tenant_id,placement_status
    USING ERRCODE='55000';
END $$;

DO $$
DECLARE table_name text;
BEGIN
  FOR table_name IN
    SELECT c.relname
      FROM pg_class c
      JOIN pg_namespace n ON n.oid=c.relnamespace
     WHERE n.nspname='furniscope' AND c.relkind IN ('r','p')
       AND NOT c.relispartition
       AND (
         c.relname='tenants'
         OR EXISTS(
           SELECT FROM pg_attribute a
            WHERE a.attrelid=c.oid AND a.attname='tenant_id'
              AND NOT a.attisdropped
         )
       )
       AND c.relname<>ALL(ARRAY[
         'tenant_placements','tenant_migration_jobs','audit_logs',
         'tenant_legal_holds','tenant_deletion_requests',
         'tenant_deletion_certificates'
       ])
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_tenant_write_fence ON %I',table_name);
    EXECUTE format(
      'CREATE TRIGGER trg_tenant_write_fence
       BEFORE INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW EXECUTE FUNCTION enforce_tenant_write_fence()',
      table_name
    );
  END LOOP;
END $$;

ALTER TABLE tenant_placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_placements FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_migration_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_migration_jobs FORCE ROW LEVEL SECURITY;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'tenant_placements','tenant_migration_jobs'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS routing_lookup ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY routing_lookup ON %I FOR SELECT
       TO furniscope_authenticator,furniscope_scheduler USING(true)',
      table_name
    );
  END LOOP;
END $$;

GRANT SELECT ON deployment_cells TO
  furniscope_authenticator,furniscope_tenant,furniscope_platform_admin,
  furniscope_scheduler,furniscope_monitor;
GRANT USAGE ON SCHEMA furniscope TO furniscope_tenant;
GRANT SELECT ON tenant_placements TO
  furniscope_authenticator,furniscope_tenant,furniscope_scheduler;
GRANT SELECT,INSERT,UPDATE,DELETE ON
  deployment_cells,tenant_placements,tenant_migration_jobs
  TO furniscope_platform_admin;
GRANT SELECT,INSERT,UPDATE ON tenant_migration_jobs TO furniscope_scheduler;
GRANT USAGE,SELECT ON SEQUENCE tenant_migration_jobs_id_seq
  TO furniscope_platform_admin,furniscope_scheduler;

INSERT INTO schema_migrations(version)
VALUES('v3_29_tenant_cell_routing')
ON CONFLICT DO NOTHING;
COMMIT;
