\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

CREATE TABLE IF NOT EXISTS tenant_legal_holds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hold_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  reason VARCHAR(1000) NOT NULL,
  reference_code VARCHAR(160) NOT NULL,
  placed_by BIGINT NOT NULL,
  placed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_by BIGINT,
  released_at TIMESTAMPTZ(3),
  release_reason VARCHAR(1000),
  CONSTRAINT uk_tenant_legal_holds_boundary UNIQUE(id,tenant_id),
  CONSTRAINT uk_tenant_legal_hold_reference UNIQUE(tenant_id,reference_code),
  CONSTRAINT fk_tenant_legal_hold_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_legal_hold_placer FOREIGN KEY(placed_by) REFERENCES users(id),
  CONSTRAINT fk_tenant_legal_hold_releaser FOREIGN KEY(released_by) REFERENCES users(id),
  CONSTRAINT chk_tenant_legal_hold_release CHECK(
    (released_at IS NULL AND released_by IS NULL AND release_reason IS NULL)
    OR (released_at IS NOT NULL AND released_by IS NOT NULL AND release_reason IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS tenant_deletion_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  tenant_code_snapshot VARCHAR(32) NOT NULL,
  tenant_name_snapshot VARCHAR(200) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled',
  reason VARCHAR(1000) NOT NULL,
  requested_by BIGINT NOT NULL,
  requested_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scheduled_for TIMESTAMPTZ(3) NOT NULL,
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  cancelled_at TIMESTAMPTZ(3),
  cancelled_by BIGINT,
  cancellation_reason VARCHAR(1000),
  failure_code VARCHAR(100),
  failure_detail VARCHAR(2000),
  inventory_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_tenant_deletion_boundary UNIQUE(id,tenant_id),
  CONSTRAINT fk_tenant_deletion_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),
  CONSTRAINT fk_tenant_deletion_requester FOREIGN KEY(requested_by) REFERENCES users(id),
  CONSTRAINT fk_tenant_deletion_canceller FOREIGN KEY(cancelled_by) REFERENCES users(id),
  CONSTRAINT chk_tenant_deletion_status CHECK(
    status IN ('scheduled','running','completed','cancelled','blocked','failed')
  ),
  CONSTRAINT chk_tenant_deletion_schedule CHECK(scheduled_for>=requested_at),
  CONSTRAINT chk_tenant_deletion_inventory CHECK(jsonb_typeof(inventory_snapshot)='object')
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_tenant_deletion_active
  ON tenant_deletion_requests(tenant_id)
  WHERE status IN ('scheduled','running','blocked');
CREATE INDEX IF NOT EXISTS idx_tenant_deletion_due
  ON tenant_deletion_requests(status,scheduled_for,tenant_id);

CREATE TABLE IF NOT EXISTS tenant_deletion_certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  certificate_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  request_uuid UUID NOT NULL UNIQUE,
  tenant_id BIGINT NOT NULL,
  tenant_code_digest CHAR(64) NOT NULL,
  started_at TIMESTAMPTZ(3) NOT NULL,
  completed_at TIMESTAMPTZ(3) NOT NULL,
  deleted_row_counts JSONB NOT NULL,
  retained_record_counts JSONB NOT NULL,
  deleted_object_manifest JSONB NOT NULL DEFAULT '[]'::jsonb,
  executor_identity VARCHAR(160) NOT NULL,
  evidence_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_tenant_deletion_cert_boundary UNIQUE(id,tenant_id),
  CONSTRAINT fk_tenant_deletion_cert_request FOREIGN KEY(request_uuid)
    REFERENCES tenant_deletion_requests(request_uuid),
  CONSTRAINT fk_tenant_deletion_cert_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),
  CONSTRAINT chk_tenant_deletion_cert_time CHECK(completed_at>=started_at),
  CONSTRAINT chk_tenant_deletion_cert_json CHECK(
    jsonb_typeof(deleted_row_counts)='object'
    AND jsonb_typeof(retained_record_counts)='object'
    AND jsonb_typeof(deleted_object_manifest)='array'
  ),
  CONSTRAINT chk_tenant_deletion_cert_hash CHECK(
    tenant_code_digest ~ '^[0-9a-f]{64}$' AND evidence_hash ~ '^[0-9a-f]{64}$'
  )
);

CREATE OR REPLACE FUNCTION protect_compliance_evidence()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
DECLARE table_owner text;
BEGIN
  SELECT owner.rolname INTO table_owner
    FROM pg_class c
    JOIN pg_namespace n ON n.oid=c.relnamespace
    JOIN pg_roles owner ON owner.oid=c.relowner
   WHERE n.nspname=TG_TABLE_SCHEMA AND c.relname=TG_TABLE_NAME;
  IF session_user=table_owner
     OR pg_has_role(session_user,'furniscope_migrator','MEMBER')
     OR pg_has_role(session_user,'furniscope_schema_owner','MEMBER') THEN
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
  END IF;
  RAISE EXCEPTION 'compliance evidence is append-only' USING ERRCODE='42501';
END $$;
DROP TRIGGER IF EXISTS trg_deletion_certificate_protect ON tenant_deletion_certificates;
CREATE TRIGGER trg_deletion_certificate_protect
BEFORE UPDATE OR DELETE ON tenant_deletion_certificates
FOR EACH ROW EXECUTE FUNCTION protect_compliance_evidence();

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'tenant_legal_holds','tenant_deletion_requests','tenant_deletion_certificates'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      table_name
    );
  END LOOP;
END $$;

GRANT SELECT ON tenant_legal_holds,tenant_deletion_requests,tenant_deletion_certificates
  TO furniscope_tenant;
GRANT SELECT,INSERT,UPDATE ON tenant_legal_holds,tenant_deletion_requests
  TO furniscope_platform_admin;
GRANT SELECT,INSERT ON tenant_deletion_certificates TO furniscope_platform_admin;
GRANT USAGE,SELECT ON SEQUENCE
  tenant_legal_holds_id_seq,tenant_deletion_requests_id_seq,
  tenant_deletion_certificates_id_seq
  TO furniscope_platform_admin;
REVOKE UPDATE,DELETE,TRUNCATE ON tenant_deletion_certificates FROM
  PUBLIC,furniscope_tenant,furniscope_runtime,furniscope_platform_admin,
  furniscope_scheduler,furniscope_audit_writer;

INSERT INTO schema_migrations(version)
VALUES('v3_28_tenant_deletion_lifecycle')
ON CONFLICT DO NOTHING;
COMMIT;
