\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

-- Deployment identities are LOGIN roles managed by the secret manager. These
-- NOLOGIN roles define capabilities without placing credentials in migrations.
DO $$
DECLARE role_name text;
BEGIN
  FOREACH role_name IN ARRAY ARRAY[
    'furniscope_schema_owner',
    'furniscope_migrator',
    'furniscope_authenticator',
    'furniscope_runtime',
    'furniscope_platform_admin',
    'furniscope_scheduler',
    'furniscope_audit_writer',
    'furniscope_backup',
    'furniscope_monitor'
  ] LOOP
    IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname=role_name) THEN
      EXECUTE format('CREATE ROLE %I NOLOGIN NOSUPERUSER NOBYPASSRLS',role_name);
    END IF;
    IF EXISTS(
      SELECT FROM pg_roles
       WHERE rolname=role_name AND (rolsuper OR rolbypassrls OR rolcanlogin)
    ) THEN
      RAISE EXCEPTION '% must be NOLOGIN NOSUPERUSER NOBYPASSRLS',role_name;
    END IF;
  END LOOP;
END $$;

GRANT furniscope_authenticator TO furniscope_runtime;
GRANT furniscope_tenant TO furniscope_runtime;
GRANT furniscope_platform_admin TO furniscope_scheduler;
GRANT pg_read_all_data TO furniscope_backup;
GRANT pg_monitor TO furniscope_monitor;

GRANT USAGE ON SCHEMA furniscope TO
  furniscope_authenticator,furniscope_runtime,furniscope_platform_admin,furniscope_scheduler,
  furniscope_audit_writer,furniscope_backup,furniscope_monitor;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA furniscope
  TO furniscope_platform_admin;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA furniscope
  TO furniscope_platform_admin,furniscope_scheduler,furniscope_audit_writer;
GRANT SELECT,INSERT ON audit_logs TO furniscope_audit_writer;
GRANT SELECT ON tenants TO furniscope_authenticator;
GRANT SELECT,UPDATE ON users TO furniscope_authenticator;
GRANT SELECT,INSERT,UPDATE,DELETE ON auth_sessions TO furniscope_authenticator;
GRANT SELECT,INSERT ON registration_applications TO furniscope_authenticator;
GRANT USAGE,SELECT ON SEQUENCE
  auth_sessions_id_seq,registration_applications_id_seq
  TO furniscope_authenticator;

-- A bound business transaction does not need to mutate authentication state.
REVOKE INSERT,UPDATE,DELETE ON users,auth_sessions FROM furniscope_tenant;

-- Runtime bootstrap used to create this table. It is now migration-owned so a
-- production application identity never needs CREATE or ALTER privileges.
CREATE TABLE IF NOT EXISTS password_reset_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  email VARCHAR(254) NOT NULL,
  code_hash CHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  consumed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_password_reset_hash CHECK (code_hash ~ '^[0-9a-f]{64}$')
);
CREATE INDEX IF NOT EXISTS idx_password_reset_user_active
  ON password_reset_requests(tenant_id,user_id,created_at DESC);
GRANT SELECT,INSERT,UPDATE,DELETE ON password_reset_requests
  TO furniscope_platform_admin;
GRANT SELECT,INSERT,UPDATE,DELETE ON password_reset_requests
  TO furniscope_authenticator;
GRANT USAGE,SELECT ON SEQUENCE password_reset_requests_id_seq
  TO furniscope_authenticator,furniscope_platform_admin,furniscope_audit_writer;
DO $$ BEGIN
  ALTER TABLE password_reset_requests ADD CONSTRAINT uk_password_reset_boundary
    UNIQUE(id,tenant_id);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE password_reset_requests ADD CONSTRAINT fk_password_reset_tenant
    FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE password_reset_requests ADD CONSTRAINT fk_password_reset_user
    FOREIGN KEY(user_id,tenant_id) REFERENCES users(id,tenant_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- These columns were also runtime-aligned before this migration.
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS reviewer_location VARCHAR(100);
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS sentiment VARCHAR(16);

-- Every ordinary tenant table has the same fail-closed user policy and a
-- separate explicit platform-admin policy. FORCE makes table ownership alone
-- insufficient to bypass RLS; superuser/BYPASSRLS credentials remain forbidden
-- for application processes.
DO $$
DECLARE item record;
BEGIN
  FOR item IN
    SELECT c.table_name
      FROM information_schema.columns c
      JOIN information_schema.tables t USING(table_schema,table_name)
     WHERE c.table_schema='furniscope'
       AND c.column_name='tenant_id'
       AND t.table_type='BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',item.table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',item.table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',item.table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      item.table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',item.table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      item.table_name
    );
  END LOOP;
END $$;

ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_scope ON tenants;
CREATE POLICY tenant_scope ON tenants TO furniscope_tenant
  USING(id=furniscope.current_tenant_id());
DROP POLICY IF EXISTS platform_admin_scope ON tenants;
CREATE POLICY platform_admin_scope ON tenants TO furniscope_platform_admin
  USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS authenticator_scope ON tenants;
CREATE POLICY authenticator_scope ON tenants FOR SELECT TO furniscope_authenticator
  USING(true);

DROP POLICY IF EXISTS authenticator_scope ON users;
CREATE POLICY authenticator_scope ON users TO furniscope_authenticator
  USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS authenticator_scope ON auth_sessions;
CREATE POLICY authenticator_scope ON auth_sessions TO furniscope_authenticator
  USING(true) WITH CHECK(true);
DROP POLICY IF EXISTS authenticator_scope ON password_reset_requests;
CREATE POLICY authenticator_scope ON password_reset_requests TO furniscope_authenticator
  USING(true) WITH CHECK(true);

ALTER TABLE cluster_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE cluster_members FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_scope ON cluster_members;
CREATE POLICY platform_admin_scope ON cluster_members TO furniscope_platform_admin
  USING(true) WITH CHECK(true);

ALTER TABLE forecast_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecast_models FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS platform_admin_scope ON forecast_models;
CREATE POLICY platform_admin_scope ON forecast_models TO furniscope_platform_admin
  USING(true) WITH CHECK(true);

-- A future table must receive explicit grants and policies in its migration.
ALTER DEFAULT PRIVILEGES IN SCHEMA furniscope
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA furniscope
  REVOKE ALL ON SEQUENCES FROM PUBLIC;

INSERT INTO schema_migrations(version)
VALUES('v3_25_database_security_baseline')
ON CONFLICT DO NOTHING;
COMMIT;
