\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

-- Memory validity is explicit. Preferences remain independent unless their
-- profile_dependencies opt in to invalidation on a source-profile change.
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS effective_at TIMESTAMPTZ(3);
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS confirmed_by BIGINT;
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS invalidated_at TIMESTAMPTZ(3);
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS invalidation_reason VARCHAR(200);
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS sensitivity VARCHAR(16) NOT NULL DEFAULT 'confidential';
ALTER TABLE customer_memories
  ADD COLUMN IF NOT EXISTS profile_dependencies JSONB NOT NULL DEFAULT '{}'::jsonb;

UPDATE customer_memories
   SET effective_at=COALESCE(effective_at,confirmed_at,created_at)
 WHERE effective_at IS NULL;
ALTER TABLE customer_memories ALTER COLUMN effective_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE customer_memories ALTER COLUMN effective_at SET NOT NULL;

ALTER TABLE customer_memories DROP CONSTRAINT IF EXISTS chk_customer_memory_status;
ALTER TABLE customer_memories
  ADD CONSTRAINT chk_customer_memory_status
  CHECK(status IN ('candidate','confirmed','superseded','archived','invalidated'));
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT fk_customer_memory_confirmed_by
    FOREIGN KEY(confirmed_by,tenant_id) REFERENCES users(id,tenant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_sensitivity
    CHECK(sensitivity IN ('internal','confidential','restricted'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_dependencies
    CHECK(jsonb_typeof(profile_dependencies)='object');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE customer_memories ADD CONSTRAINT chk_customer_memory_validity
    CHECK(
      (status='invalidated' AND invalidated_at IS NOT NULL AND invalidation_reason IS NOT NULL)
      OR
      (status<>'invalidated' AND invalidated_at IS NULL)
    );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS idx_customer_memory_active
  ON customer_memories(tenant_id,scope,user_id,workspace_id,memory_key,effective_at DESC)
  WHERE status='confirmed' AND invalidated_at IS NULL;

-- One durable, server-owned semantic state per workspace. Context snapshots
-- retain the historical state used by each completed turn.
CREATE TABLE IF NOT EXISTS analysis_workspace_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  workspace_id BIGINT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 0,
  current_product_id BIGINT,
  current_market VARCHAR(8),
  compared_markets JSONB NOT NULL DEFAULT '[]'::jsonb,
  current_dataset_id BIGINT,
  current_task_id BIGINT,
  current_analysis_stage VARCHAR(64),
  pending_confirmation JSONB,
  last_user_intent VARCHAR(64),
  resolved_references JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by_turn_uuid UUID,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,workspace_id),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(workspace_id,tenant_id)
    REFERENCES analysis_workspaces(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(current_product_id,tenant_id) REFERENCES products(id,tenant_id),
  FOREIGN KEY(current_dataset_id,tenant_id) REFERENCES market_datasets(id,tenant_id),
  FOREIGN KEY(current_task_id,tenant_id) REFERENCES analysis_tasks(id,tenant_id),
  CONSTRAINT fk_workspace_state_updated_turn
    FOREIGN KEY(updated_by_turn_uuid,tenant_id)
    REFERENCES analysis_workspace_turns(turn_uuid,tenant_id)
    ON DELETE SET NULL (updated_by_turn_uuid),
  CHECK(revision>=0),
  CHECK(current_market IS NULL OR current_market ~ '^[A-Z]{2}$'),
  CHECK(jsonb_typeof(compared_markets)='array'),
  CHECK(pending_confirmation IS NULL OR jsonb_typeof(pending_confirmation)='object'),
  CHECK(jsonb_typeof(resolved_references)='array')
);
ALTER TABLE analysis_workspace_states
  DROP CONSTRAINT IF EXISTS analysis_workspace_states_updated_by_turn_uuid_tenant_id_fkey;
DO $$ BEGIN
  ALTER TABLE analysis_workspace_states
    ADD CONSTRAINT fk_workspace_state_updated_turn
    FOREIGN KEY(updated_by_turn_uuid,tenant_id)
    REFERENCES analysis_workspace_turns(turn_uuid,tenant_id)
    ON DELETE SET NULL (updated_by_turn_uuid);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE analysis_workspace_turns ADD COLUMN IF NOT EXISTS sequence_no BIGINT;
WITH numbered AS (
  SELECT id,row_number() OVER(
    PARTITION BY tenant_id,workspace_id ORDER BY created_at,id
  ) AS sequence_no
  FROM analysis_workspace_turns
)
UPDATE analysis_workspace_turns t
   SET sequence_no=n.sequence_no
  FROM numbered n
 WHERE n.id=t.id AND t.sequence_no IS NULL;
ALTER TABLE analysis_workspace_turns ALTER COLUMN sequence_no SET NOT NULL;
DO $$ BEGIN
  ALTER TABLE analysis_workspace_turns ADD CONSTRAINT uk_workspace_turn_sequence
    UNIQUE(tenant_id,workspace_id,sequence_no);
EXCEPTION WHEN duplicate_object OR duplicate_table THEN NULL; END $$;

-- Preserve the oldest active turn and fail duplicate in-flight rows before
-- installing the serialization constraint on upgraded databases.
WITH pending AS (
  SELECT id,row_number() OVER(
    PARTITION BY tenant_id,workspace_id ORDER BY started_at,id
  ) AS position
  FROM analysis_workspace_turns
  WHERE status='pending'
)
UPDATE analysis_workspace_turns t
   SET status='failed',error_code='TURN_SUPERSEDED_BY_SERIALIZATION',
       completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP
  FROM pending p
 WHERE p.id=t.id AND p.position>1;
CREATE UNIQUE INDEX IF NOT EXISTS uk_workspace_single_pending_turn
  ON analysis_workspace_turns(tenant_id,workspace_id)
  WHERE status='pending';

ALTER TABLE analysis_context_snapshots
  ADD COLUMN IF NOT EXISTS state_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE analysis_context_snapshots
  ADD COLUMN IF NOT EXISTS resolution_log JSONB NOT NULL DEFAULT '[]'::jsonb;
DO $$ BEGIN
  ALTER TABLE analysis_context_snapshots ADD CONSTRAINT chk_context_snapshot_state
    CHECK(jsonb_typeof(state_snapshot)='object' AND jsonb_typeof(resolution_log)='array');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Knowledge content is tenant-visible by default. A user-private base can only
-- be listed, bound, or searched by its creator.
ALTER TABLE knowledge_bases
  ADD COLUMN IF NOT EXISTS visibility VARCHAR(16) NOT NULL DEFAULT 'tenant';
DO $$ BEGIN
  ALTER TABLE knowledge_bases ADD CONSTRAINT chk_knowledge_base_visibility
    CHECK(visibility IN ('tenant','user'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE OR REPLACE FUNCTION furniscope.invalidate_enterprise_dependent_memories()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
BEGIN
  IF NEW.profile_version IS DISTINCT FROM OLD.profile_version THEN
    UPDATE customer_memories
       SET status='invalidated',invalidated_at=CURRENT_TIMESTAMP,
           invalidation_reason='enterprise_profile_version_changed',
           updated_at=CURRENT_TIMESTAMP
     WHERE tenant_id=NEW.tenant_id AND status='confirmed'
       AND COALESCE((profile_dependencies->>'invalidate_on_profile_change')::boolean,FALSE)
       AND profile_dependencies->>'enterprise_profile_version'=OLD.profile_version::text;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_enterprise_memory_invalidation ON enterprise_profiles;
CREATE TRIGGER trg_enterprise_memory_invalidation
  AFTER UPDATE OF profile_version ON enterprise_profiles
  FOR EACH ROW EXECUTE FUNCTION furniscope.invalidate_enterprise_dependent_memories();

CREATE OR REPLACE FUNCTION furniscope.invalidate_product_dependent_memories()
RETURNS trigger LANGUAGE plpgsql
SET search_path TO furniscope,public AS $$
BEGIN
  IF NEW.current_profile_version_id IS DISTINCT FROM OLD.current_profile_version_id
     AND OLD.current_profile_version_id IS NOT NULL THEN
    UPDATE customer_memories
       SET status='invalidated',invalidated_at=CURRENT_TIMESTAMP,
           invalidation_reason='product_profile_version_changed',
           updated_at=CURRENT_TIMESTAMP
     WHERE tenant_id=NEW.tenant_id AND status='confirmed'
       AND COALESCE((profile_dependencies->>'invalidate_on_profile_change')::boolean,FALSE)
       AND profile_dependencies->>'product_id'=NEW.id::text
       AND profile_dependencies->>'product_profile_version_id'=OLD.current_profile_version_id::text;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_product_memory_invalidation ON products;
CREATE TRIGGER trg_product_memory_invalidation
  AFTER UPDATE OF current_profile_version_id ON products
  FOR EACH ROW EXECUTE FUNCTION furniscope.invalidate_product_dependent_memories();

ALTER TABLE analysis_workspace_states ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_scope ON analysis_workspace_states;
CREATE POLICY tenant_scope ON analysis_workspace_states TO furniscope_tenant
  USING(tenant_id=furniscope.current_tenant_id())
  WITH CHECK(tenant_id=furniscope.current_tenant_id());
GRANT SELECT,INSERT,UPDATE,DELETE ON analysis_workspace_states TO furniscope_tenant;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA furniscope TO furniscope_tenant;

DROP TRIGGER IF EXISTS trg_analysis_workspace_states_updated ON analysis_workspace_states;
CREATE TRIGGER trg_analysis_workspace_states_updated
  BEFORE UPDATE ON analysis_workspace_states
  FOR EACH ROW EXECUTE FUNCTION furniscope.touch_analysis_workspaces();

INSERT INTO schema_migrations(version)
VALUES('v3_24_memory_agent_governance')
ON CONFLICT DO NOTHING;
COMMIT;
