\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

CREATE TABLE IF NOT EXISTS market_intelligence_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  dataset_id BIGINT,
  product_id BIGINT,
  package_id VARCHAR(120) NOT NULL,
  package_version VARCHAR(40) NOT NULL,
  package_sha256 CHAR(64) NOT NULL,
  schema_version VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'staged',
  source_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  scope_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  imported_by BIGINT NOT NULL,
  imported_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activated_at TIMESTAMPTZ(3),
  superseded_at TIMESTAMPTZ(3),
  revoked_at TIMESTAMPTZ(3),
  revocation_reason TEXT,
  UNIQUE(id,tenant_id),
  UNIQUE(tenant_id,package_id,package_version),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(dataset_id,tenant_id)
    REFERENCES market_datasets(id,tenant_id) ON DELETE RESTRICT,
  FOREIGN KEY(product_id,tenant_id)
    REFERENCES products(id,tenant_id) ON DELETE RESTRICT,
  FOREIGN KEY(imported_by,tenant_id)
    REFERENCES users(id,tenant_id),
  CONSTRAINT chk_market_intelligence_batch_hash
    CHECK(package_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_market_intelligence_batch_status
    CHECK(status IN ('staged','active','superseded','revoked','failed')),
  CONSTRAINT chk_market_intelligence_batch_json
    CHECK(
      jsonb_typeof(source_summary)='object'
      AND jsonb_typeof(scope_snapshot)='object'
    ),
  CONSTRAINT chk_market_intelligence_batch_dates CHECK(
    (status<>'active' OR activated_at IS NOT NULL)
    AND (status<>'superseded' OR superseded_at IS NOT NULL)
    AND (status<>'revoked' OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL))
  )
);
CREATE INDEX IF NOT EXISTS idx_market_intelligence_batches_tenant_time
  ON market_intelligence_batches(tenant_id,imported_at DESC,id DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_market_intelligence_active_package
  ON market_intelligence_batches(tenant_id,package_id)
  WHERE status='active';

CREATE TABLE IF NOT EXISTS market_intelligence_lineage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  batch_id BIGINT NOT NULL,
  capability_code VARCHAR(40) NOT NULL,
  record_kind VARCHAR(80) NOT NULL,
  source_class VARCHAR(32) NOT NULL,
  target_table VARCHAR(80) NOT NULL,
  target_record_id BIGINT,
  natural_key VARCHAR(240) NOT NULL,
  source_locator JSONB NOT NULL DEFAULT '{}'::jsonb,
  derivation_rule TEXT,
  rule_version VARCHAR(64),
  input_sha256 CHAR(64) NOT NULL,
  payload_sha256 CHAR(64) NOT NULL,
  confidence NUMERIC(5,4),
  observed_at TIMESTAMPTZ(3),
  valid_from TIMESTAMPTZ(3),
  valid_until TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  UNIQUE(batch_id,target_table,natural_key),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(batch_id,tenant_id)
    REFERENCES market_intelligence_batches(id,tenant_id) ON DELETE CASCADE,
  CONSTRAINT chk_market_intelligence_capability CHECK(
    capability_code IN (
      'smart_selection','competitor_tracking','review_mining',
      'pricing','compliance'
    )
  ),
  CONSTRAINT chk_market_intelligence_source_class CHECK(
    source_class IN (
      'authorized_source_record','derived_result',
      'planning_assumption','official_source_registry'
    )
  ),
  CONSTRAINT chk_market_intelligence_lineage_hashes CHECK(
    input_sha256 ~ '^[0-9a-f]{64}$'
    AND payload_sha256 ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT chk_market_intelligence_lineage_json
    CHECK(jsonb_typeof(source_locator)='object'),
  CONSTRAINT chk_market_intelligence_lineage_confidence
    CHECK(confidence IS NULL OR confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_market_intelligence_lineage_dates
    CHECK(valid_until IS NULL OR valid_from IS NULL OR valid_until>=valid_from)
);
CREATE INDEX IF NOT EXISTS idx_market_intelligence_lineage_batch
  ON market_intelligence_lineage(tenant_id,batch_id,capability_code,id);
CREATE INDEX IF NOT EXISTS idx_market_intelligence_lineage_target
  ON market_intelligence_lineage(tenant_id,target_table,target_record_id);

COMMENT ON TABLE market_intelligence_batches IS
  'Versioned import batches for the five market decision capabilities; large source bodies remain in their authoritative domain tables or object storage.';
COMMENT ON TABLE market_intelligence_lineage IS
  'Immutable per-record provenance, calculation rule, hashes, confidence and validity for market decision data.';
COMMENT ON COLUMN market_intelligence_lineage.source_locator IS
  'Identifiers and offsets only; credentials and full review bodies are forbidden.';

CREATE OR REPLACE FUNCTION guard_market_intelligence_batch()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP='DELETE' THEN
    RAISE EXCEPTION 'Market intelligence batches cannot be deleted';
  END IF;
  IF (
    NEW.tenant_id,NEW.dataset_id,NEW.product_id,NEW.package_id,
    NEW.package_version,NEW.package_sha256,NEW.schema_version,
    NEW.source_summary,NEW.scope_snapshot,NEW.imported_by,NEW.imported_at
  ) IS DISTINCT FROM (
    OLD.tenant_id,OLD.dataset_id,OLD.product_id,OLD.package_id,
    OLD.package_version,OLD.package_sha256,OLD.schema_version,
    OLD.source_summary,OLD.scope_snapshot,OLD.imported_by,OLD.imported_at
  ) THEN
    RAISE EXCEPTION 'Market intelligence batch identity is immutable';
  END IF;
  IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
    (OLD.status='staged' AND NEW.status IN ('active','failed'))
    OR (OLD.status='active' AND NEW.status IN ('superseded','revoked'))
  ) THEN
    RAISE EXCEPTION 'Invalid market intelligence batch transition: % -> %',
      OLD.status,NEW.status;
  END IF;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_market_intelligence_batch_guard
  ON market_intelligence_batches;
CREATE TRIGGER trg_market_intelligence_batch_guard
  BEFORE UPDATE OR DELETE ON market_intelligence_batches
  FOR EACH ROW EXECUTE FUNCTION guard_market_intelligence_batch();

CREATE OR REPLACE FUNCTION guard_market_intelligence_lineage()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Market intelligence lineage is immutable';
END
$$;

DROP TRIGGER IF EXISTS trg_market_intelligence_lineage_guard
  ON market_intelligence_lineage;
CREATE TRIGGER trg_market_intelligence_lineage_guard
  BEFORE UPDATE OR DELETE ON market_intelligence_lineage
  FOR EACH ROW EXECUTE FUNCTION guard_market_intelligence_lineage();

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'market_intelligence_batches','market_intelligence_lineage'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      table_name
    );
    EXECUTE format('DROP TRIGGER IF EXISTS trg_tenant_write_fence ON %I',table_name);
    EXECUTE format(
      'CREATE TRIGGER trg_tenant_write_fence
       BEFORE INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW EXECUTE FUNCTION enforce_tenant_write_fence()',
      table_name
    );
  END LOOP;
END
$$;

GRANT SELECT,INSERT,UPDATE ON market_intelligence_batches
  TO furniscope_tenant,furniscope_platform_admin;
GRANT SELECT,INSERT ON market_intelligence_lineage
  TO furniscope_tenant,furniscope_platform_admin;
GRANT USAGE,SELECT ON SEQUENCE
  market_intelligence_batches_id_seq,market_intelligence_lineage_id_seq
  TO furniscope_tenant,furniscope_platform_admin;

INSERT INTO schema_migrations(version)
VALUES('v3_36_market_intelligence_governance')
ON CONFLICT DO NOTHING;

COMMIT;
