\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

CREATE TABLE IF NOT EXISTS ai_employee_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  display_name VARCHAR(100) NOT NULL DEFAULT '经营分析员工',
  role_title VARCHAR(120) NOT NULL DEFAULT '跨境家具经营分析',
  autonomy_level VARCHAR(8) NOT NULL DEFAULT 'L2',
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  enabled_skills JSONB NOT NULL DEFAULT
    '["market_entry_assessment@1","weekly_sales_review@1","data_readiness_check@1"]'::jsonb,
  default_budget JSONB NOT NULL DEFAULT
    '{"max_tool_calls":30,"max_replans":1}'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,user_id),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(user_id,tenant_id) REFERENCES users(id,tenant_id) ON DELETE CASCADE,
  CHECK(autonomy_level IN ('L0','L1','L2','L3')),
  CHECK(status IN ('active','paused','disabled')),
  CHECK(jsonb_typeof(enabled_skills)='array'),
  CHECK(jsonb_typeof(default_budget)='object')
);

CREATE TABLE IF NOT EXISTS agent_tool_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  capability_id VARCHAR(100) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  display_name VARCHAR(160) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  provider VARCHAR(80) NOT NULL,
  effect_level VARCHAR(4) NOT NULL,
  permission_code VARCHAR(80),
  input_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  verifier_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,capability_id,version),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(permission_code) REFERENCES permission_catalog(permission_code),
  CHECK(version>0),
  CHECK(effect_level IN ('R0','R1','R2','R3','R4')),
  CHECK(status IN ('active','disabled','deprecated')),
  CHECK(jsonb_typeof(input_schema)='object'),
  CHECK(jsonb_typeof(output_schema)='object'),
  CHECK(jsonb_typeof(verifier_config)='object')
);

CREATE TABLE IF NOT EXISTS agent_skill_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  skill_id VARCHAR(100) NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  display_name VARCHAR(160) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  objective_patterns JSONB NOT NULL DEFAULT '[]'::jsonb,
  plan_template JSONB NOT NULL,
  content_sha256 CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,skill_id,version),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CHECK(version>0),
  CHECK(status IN ('active','disabled','deprecated')),
  CHECK(jsonb_typeof(objective_patterns)='array'),
  CHECK(jsonb_typeof(plan_template)='object'),
  CHECK(content_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS agent_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  profile_id BIGINT NOT NULL,
  objective TEXT NOT NULL,
  expected_deliverables JSONB NOT NULL DEFAULT '[]'::jsonb,
  constraints JSONB NOT NULL DEFAULT '{}'::jsonb,
  acceptance_criteria JSONB NOT NULL DEFAULT '[]'::jsonb,
  autonomy_envelope JSONB NOT NULL DEFAULT '{}'::jsonb,
  deadline TIMESTAMPTZ(3),
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  trigger_type VARCHAR(32) NOT NULL DEFAULT 'user_delegate',
  source_mode VARCHAR(16) NOT NULL DEFAULT 'employee',
  return_href VARCHAR(1000),
  selected_skill_id VARCHAR(100) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  current_plan_id BIGINT,
  current_run_id BIGINT,
  request_hash CHAR(64) NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ(3),
  UNIQUE(tenant_id,idempotency_key),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  FOREIGN KEY(profile_id,tenant_id) REFERENCES ai_employee_profiles(id,tenant_id),
  CHECK(priority IN ('low','normal','high','urgent')),
  CHECK(trigger_type IN ('user_delegate','business_page','schedule','internal_event')),
  CHECK(source_mode IN ('employee','copilot')),
  CHECK(status IN (
    'draft','planning','plan_ready','queued','running','waiting_human',
    'verifying','delivering','succeeded','partial_succeeded','failed','cancelled','paused'
  )),
  CHECK(jsonb_typeof(expected_deliverables)='array'),
  CHECK(jsonb_typeof(constraints)='object'),
  CHECK(jsonb_typeof(acceptance_criteria)='array'),
  CHECK(jsonb_typeof(autonomy_envelope)='object'),
  CHECK(request_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS agent_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  version INTEGER NOT NULL,
  skill_id VARCHAR(100) NOT NULL,
  skill_version INTEGER NOT NULL,
  plan_sha256 CHAR(64) NOT NULL,
  risk_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(16) NOT NULL DEFAULT 'ready',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,goal_id,version),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(version>0),
  CHECK(skill_version>0),
  CHECK(status IN ('ready','active','superseded','cancelled')),
  CHECK(plan_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK(jsonb_typeof(risk_summary)='object')
);

CREATE TABLE IF NOT EXISTS agent_plan_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  ordinal INTEGER NOT NULL,
  title VARCHAR(200) NOT NULL,
  capability_id VARCHAR(100) NOT NULL,
  capability_version INTEGER NOT NULL DEFAULT 1,
  provider VARCHAR(80) NOT NULL,
  effect_level VARCHAR(4) NOT NULL,
  depends_on JSONB NOT NULL DEFAULT '[]'::jsonb,
  input_refs JSONB NOT NULL DEFAULT '{}'::jsonb,
  output_schema JSONB NOT NULL DEFAULT '{}'::jsonb,
  verifier_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,plan_id,ordinal),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(plan_id,tenant_id) REFERENCES agent_plans(id,tenant_id) ON DELETE CASCADE,
  CHECK(ordinal>0),
  CHECK(capability_version>0),
  CHECK(effect_level IN ('R0','R1','R2','R3','R4')),
  CHECK(status IN (
    'pending','ready','running','verifying','waiting_human',
    'retry_scheduled','succeeded','failed','skipped','rolled_back','cancelled'
  )),
  CHECK(jsonb_typeof(depends_on)='array'),
  CHECK(jsonb_typeof(input_refs)='object'),
  CHECK(jsonb_typeof(output_schema)='object'),
  CHECK(jsonb_typeof(verifier_config)='object')
);

CREATE TABLE IF NOT EXISTS agent_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  progress_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
  current_step_id BIGINT,
  pause_requested BOOLEAN NOT NULL DEFAULT FALSE,
  cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  checkpoint JSONB NOT NULL DEFAULT '{}'::jsonb,
  budget JSONB NOT NULL DEFAULT '{}'::jsonb,
  tool_call_count INTEGER NOT NULL DEFAULT 0,
  replan_count INTEGER NOT NULL DEFAULT 0,
  failure_code VARCHAR(100),
  failure_message VARCHAR(1000),
  created_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(plan_id,tenant_id) REFERENCES agent_plans(id,tenant_id),
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(status IN (
    'queued','running','waiting_human','verifying','delivering',
    'paused','succeeded','partial_succeeded','failed','cancelled'
  )),
  CHECK(progress_percent BETWEEN 0 AND 100),
  CHECK(tool_call_count>=0 AND replan_count>=0),
  CHECK(jsonb_typeof(checkpoint)='object'),
  CHECK(jsonb_typeof(budget)='object')
);

CREATE TABLE IF NOT EXISTS agent_step_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_run_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  step_id BIGINT NOT NULL,
  attempt_no INTEGER NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'running',
  input_sha256 CHAR(64) NOT NULL,
  output_data JSONB,
  output_sha256 CHAR(64),
  error_code VARCHAR(100),
  error_message VARCHAR(1000),
  started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ(3),
  UNIQUE(tenant_id,run_id,step_id,attempt_no),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(run_id,tenant_id) REFERENCES agent_runs(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(step_id,tenant_id) REFERENCES agent_plan_steps(id,tenant_id),
  CHECK(attempt_no>0),
  CHECK(status IN ('running','verifying','succeeded','failed','cancelled')),
  CHECK(input_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK(output_data IS NULL OR jsonb_typeof(output_data)='object'),
  CHECK(output_sha256 IS NULL OR output_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS agent_tool_invocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invocation_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  step_run_id BIGINT NOT NULL,
  capability_id VARCHAR(100) NOT NULL,
  capability_version INTEGER NOT NULL,
  policy_decision VARCHAR(32) NOT NULL,
  parameter_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
  result_summary JSONB,
  receipt_sha256 CHAR(64),
  duration_ms INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(run_id,tenant_id) REFERENCES agent_runs(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(step_run_id,tenant_id) REFERENCES agent_step_runs(id,tenant_id) ON DELETE CASCADE,
  CHECK(capability_version>0),
  CHECK(policy_decision IN ('allow','allow_with_constraints','require_confirmation','deny')),
  CHECK(jsonb_typeof(parameter_summary)='object'),
  CHECK(result_summary IS NULL OR jsonb_typeof(result_summary)='object'),
  CHECK(receipt_sha256 IS NULL OR receipt_sha256 ~ '^[0-9a-f]{64}$'),
  CHECK(duration_ms>=0)
);

CREATE TABLE IF NOT EXISTS agent_approvals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  step_id BIGINT,
  approval_type VARCHAR(64) NOT NULL,
  title VARCHAR(200) NOT NULL,
  question TEXT NOT NULL,
  reason TEXT NOT NULL,
  impact JSONB NOT NULL DEFAULT '{}'::jsonb,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  recommended_option VARCHAR(64),
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  response JSONB,
  expires_at TIMESTAMPTZ(3),
  responded_by BIGINT,
  responded_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(run_id,tenant_id) REFERENCES agent_runs(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(step_id,tenant_id) REFERENCES agent_plan_steps(id,tenant_id),
  FOREIGN KEY(responded_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(status IN ('pending','approved','rejected','expired','cancelled')),
  CHECK(jsonb_typeof(impact)='object'),
  CHECK(jsonb_typeof(options)='array'),
  CHECK(response IS NULL OR jsonb_typeof(response)='object')
);

CREATE TABLE IF NOT EXISTS agent_artifacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artifact_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  step_id BIGINT,
  artifact_type VARCHAR(64) NOT NULL,
  title VARCHAR(300) NOT NULL,
  summary TEXT,
  resource_type VARCHAR(80),
  resource_uuid UUID,
  resource_version INTEGER,
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  sha256 CHAR(64) NOT NULL,
  open_href VARCHAR(1000),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(run_id,tenant_id) REFERENCES agent_runs(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(step_id,tenant_id) REFERENCES agent_plan_steps(id,tenant_id),
  CHECK(resource_version IS NULL OR resource_version>0),
  CHECK(jsonb_typeof(content)='object'),
  CHECK(sha256 ~ '^[0-9a-f]{64}$')
);

CREATE TABLE IF NOT EXISTS agent_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  run_id BIGINT,
  sequence_no BIGINT NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id,goal_id,sequence_no),
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(run_id,tenant_id) REFERENCES agent_runs(id,tenant_id) ON DELETE CASCADE,
  CHECK(sequence_no>0),
  CHECK(jsonb_typeof(payload)='object')
);

CREATE TABLE IF NOT EXISTS agent_goal_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  goal_id BIGINT NOT NULL,
  role VARCHAR(16) NOT NULL,
  content TEXT NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(goal_id,tenant_id) REFERENCES agent_goals(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(role IN ('user','employee','system'))
);

CREATE TABLE IF NOT EXISTS agent_triggers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trigger_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL,
  created_by BIGINT NOT NULL,
  skill_id VARCHAR(100) NOT NULL,
  trigger_type VARCHAR(24) NOT NULL,
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(16) NOT NULL DEFAULT 'disabled',
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  FOREIGN KEY(tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CHECK(trigger_type IN ('schedule','business_event')),
  CHECK(status IN ('active','disabled')),
  CHECK(jsonb_typeof(configuration)='object')
);

DO $$ BEGIN
  ALTER TABLE agent_goals
    ADD CONSTRAINT fk_agent_goal_current_plan
    FOREIGN KEY(current_plan_id,tenant_id) REFERENCES agent_plans(id,tenant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE agent_goals
    ADD CONSTRAINT fk_agent_goal_current_run
    FOREIGN KEY(current_run_id,tenant_id) REFERENCES agent_runs(id,tenant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE agent_runs
    ADD CONSTRAINT fk_agent_run_current_step
    FOREIGN KEY(current_step_id,tenant_id) REFERENCES agent_plan_steps(id,tenant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_agent_goals_user_status
  ON agent_goals(tenant_id,created_by,status,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_plan_steps_status
  ON agent_plan_steps(tenant_id,plan_id,status,ordinal);
CREATE INDEX IF NOT EXISTS idx_agent_runs_status
  ON agent_runs(tenant_id,status,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_approvals_pending
  ON agent_approvals(tenant_id,status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_artifacts_recent
  ON agent_artifacts(tenant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_events_replay
  ON agent_events(tenant_id,run_id,sequence_no);

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'ai_employee_profiles','agent_tool_definitions','agent_skill_packages',
    'agent_goals','agent_plans','agent_plan_steps','agent_runs','agent_step_runs',
    'agent_tool_invocations','agent_approvals','agent_artifacts','agent_events',
    'agent_goal_messages','agent_triggers'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',table_name
    );
    EXECUTE format(
      'GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO furniscope_tenant',table_name
    );
    EXECUTE format(
      'GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO furniscope_platform_admin',table_name
    );
  END LOOP;
END $$;

GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA furniscope
  TO furniscope_tenant,furniscope_platform_admin;

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'ai_employee_profiles','agent_tool_definitions','agent_skill_packages',
    'agent_goals','agent_plan_steps','agent_runs','agent_approvals','agent_triggers'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I',
      'trg_'||table_name||'_updated',table_name);
    EXECUTE format(
      'CREATE TRIGGER %I BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE FUNCTION furniscope.set_updated_at()',
      'trg_'||table_name||'_updated',table_name
    );
  END LOOP;
END $$;

INSERT INTO schema_migrations(version)
VALUES('v3_35_agent_runtime')
ON CONFLICT DO NOTHING;

COMMIT;
