\set ON_ERROR_STOP on
BEGIN;
SET LOCAL search_path TO furniscope,public;

-- Product identity comparison is case-insensitive while the original SKU is
-- preserved for display, exports and external contracts.
ALTER TABLE products ADD COLUMN IF NOT EXISTS sku_compare_key TEXT
  GENERATED ALWAYS AS (upper(btrim(sku))) STORED;

DO $$
DECLARE collision RECORD;
BEGIN
  SELECT tenant_id,sku_compare_key,count(*) AS duplicate_count
    INTO collision
    FROM products
   GROUP BY tenant_id,sku_compare_key
  HAVING count(*)>1
   LIMIT 1;
  IF FOUND THEN
    RAISE EXCEPTION
      'SKU case collision exists for tenant %, key % (% rows). Reconcile before v3_32.',
      collision.tenant_id,collision.sku_compare_key,collision.duplicate_count;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uk_products_tenant_sku_compare
  ON products(tenant_id,sku_compare_key);

CREATE TABLE IF NOT EXISTS product_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  group_type VARCHAR(16) NOT NULL,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  UNIQUE(tenant_id,group_type,code),
  CONSTRAINT chk_product_group_type CHECK(group_type IN ('spu','variant','bundle','bom'))
);

CREATE TABLE IF NOT EXISTS product_group_members (
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  group_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  member_role VARCHAR(16) NOT NULL,
  quantity NUMERIC(18,6) NOT NULL DEFAULT 1,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(group_id,product_id,member_role),
  FOREIGN KEY(group_id,tenant_id)
    REFERENCES product_groups(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(product_id,tenant_id)
    REFERENCES products(id,tenant_id) ON DELETE CASCADE,
  CONSTRAINT chk_product_member_role CHECK(
    member_role IN ('parent','variant','component','item')
  ),
  CONSTRAINT chk_product_member_quantity CHECK(quantity>0)
);
CREATE INDEX IF NOT EXISTS idx_product_group_members_product
  ON product_group_members(tenant_id,product_id,group_id);

CREATE TABLE IF NOT EXISTS product_import_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  created_by BIGINT NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT NOT NULL,
  source_sha256 CHAR(64) NOT NULL,
  template_version VARCHAR(32),
  sheet_name VARCHAR(128) NOT NULL,
  available_sheets JSONB NOT NULL DEFAULT '[]'::jsonb,
  header_row INTEGER NOT NULL DEFAULT 1,
  field_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
  unit_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
  dictionary_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,
  import_mode VARCHAR(16) NOT NULL DEFAULT 'create_only',
  status VARCHAR(24) NOT NULL DEFAULT 'preflighting',
  preview_sha256 CHAR(64),
  total_rows INTEGER NOT NULL DEFAULT 0,
  valid_rows INTEGER NOT NULL DEFAULT 0,
  error_rows INTEGER NOT NULL DEFAULT 0,
  warning_rows INTEGER NOT NULL DEFAULT 0,
  imported_rows INTEGER NOT NULL DEFAULT 0,
  schema_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_message VARCHAR(1000),
  committed_at TIMESTAMPTZ(3),
  cancelled_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(id,tenant_id),
  UNIQUE(tenant_id,idempotency_key),
  FOREIGN KEY(created_by,tenant_id) REFERENCES users(id,tenant_id),
  CONSTRAINT chk_product_import_size CHECK(size_bytes>0 AND size_bytes<=20971520),
  CONSTRAINT chk_product_import_hash CHECK(source_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT chk_product_import_preview_hash CHECK(
    preview_sha256 IS NULL OR preview_sha256 ~ '^[0-9a-f]{64}$'
  ),
  CONSTRAINT chk_product_import_header CHECK(header_row BETWEEN 1 AND 100),
  CONSTRAINT chk_product_import_mode CHECK(import_mode IN ('create_only','upsert')),
  CONSTRAINT chk_product_import_status CHECK(status IN (
    'preflighting','ready','blocked','importing','completed','failed','cancelled'
  )),
  CONSTRAINT chk_product_import_counts CHECK(
    total_rows>=0 AND valid_rows>=0 AND error_rows>=0
    AND warning_rows>=0 AND imported_rows>=0
    AND valid_rows+error_rows=total_rows
    AND imported_rows<=valid_rows
  ),
  CONSTRAINT chk_product_import_json CHECK(
    jsonb_typeof(available_sheets)='array'
    AND jsonb_typeof(field_mapping)='object'
    AND jsonb_typeof(unit_mapping)='object'
    AND jsonb_typeof(dictionary_mapping)='object'
    AND jsonb_typeof(schema_snapshot)='object'
  )
);
CREATE INDEX IF NOT EXISTS idx_product_import_jobs_tenant_time
  ON product_import_jobs(tenant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_product_import_jobs_resumable
  ON product_import_jobs(tenant_id,updated_at DESC)
  WHERE status IN ('ready','blocked','failed');

CREATE TABLE IF NOT EXISTS product_import_rows (
  tenant_id BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  job_id BIGINT NOT NULL,
  source_row_number INTEGER NOT NULL,
  source_values JSONB NOT NULL,
  normalized_values JSONB NOT NULL DEFAULT '{}'::jsonb,
  validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  validation_warnings JSONB NOT NULL DEFAULT '[]'::jsonb,
  planned_action VARCHAR(16) NOT NULL,
  is_user_edited BOOLEAN NOT NULL DEFAULT FALSE,
  imported_product_id BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(job_id,source_row_number),
  FOREIGN KEY(job_id,tenant_id)
    REFERENCES product_import_jobs(id,tenant_id) ON DELETE CASCADE,
  FOREIGN KEY(imported_product_id,tenant_id)
    REFERENCES products(id,tenant_id) ON DELETE SET NULL (imported_product_id),
  CONSTRAINT chk_product_import_row_number CHECK(source_row_number>0),
  CONSTRAINT chk_product_import_action CHECK(
    planned_action IN ('create','update','skip','invalid')
  ),
  CONSTRAINT chk_product_import_row_json CHECK(
    jsonb_typeof(source_values)='object'
    AND jsonb_typeof(normalized_values)='object'
    AND jsonb_typeof(validation_errors)='array'
    AND jsonb_typeof(validation_warnings)='array'
  )
);
CREATE INDEX IF NOT EXISTS idx_product_import_rows_job_action
  ON product_import_rows(tenant_id,job_id,planned_action,source_row_number);

DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'product_groups','product_group_members','product_import_jobs','product_import_rows'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',table_name);
    EXECUTE format('DROP POLICY IF EXISTS tenant_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY tenant_scope ON %I TO furniscope_tenant
       USING(tenant_id=furniscope.current_tenant_id())
       WITH CHECK(tenant_id=furniscope.current_tenant_id())',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS platform_admin_scope ON %I',table_name);
    EXECUTE format(
      'CREATE POLICY platform_admin_scope ON %I TO furniscope_platform_admin
       USING(true) WITH CHECK(true)',
      table_name
    );
    EXECUTE format('DROP TRIGGER IF EXISTS trg_tenant_write_fence ON %I',table_name);
    EXECUTE format(
      'CREATE TRIGGER trg_tenant_write_fence
       BEFORE INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW EXECUTE FUNCTION enforce_tenant_write_fence()',
      table_name
    );
  END LOOP;
END $$;

DROP TRIGGER IF EXISTS trg_product_groups_updated ON product_groups;
CREATE TRIGGER trg_product_groups_updated BEFORE UPDATE ON product_groups
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_product_group_members_updated ON product_group_members;
CREATE TRIGGER trg_product_group_members_updated BEFORE UPDATE ON product_group_members
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_product_import_jobs_updated ON product_import_jobs;
CREATE TRIGGER trg_product_import_jobs_updated BEFORE UPDATE ON product_import_jobs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_product_import_rows_updated ON product_import_rows;
CREATE TRIGGER trg_product_import_rows_updated BEFORE UPDATE ON product_import_rows
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

GRANT SELECT,INSERT,UPDATE,DELETE ON
  product_groups,product_group_members,product_import_jobs,product_import_rows
  TO furniscope_tenant,furniscope_platform_admin;
GRANT USAGE,SELECT ON SEQUENCE
  product_groups_id_seq,product_import_jobs_id_seq
  TO furniscope_tenant,furniscope_platform_admin;

INSERT INTO schema_migrations(version)
VALUES('v3_32_product_catalog_imports')
ON CONFLICT DO NOTHING;
COMMIT;
