\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS competitor_watch_targets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  dataset_id BIGINT REFERENCES market_datasets(id) ON DELETE SET NULL,
  platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
  market_country CHAR(2) NOT NULL,
  asin VARCHAR(40) NOT NULL,
  title TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  compare_selected BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_watch_tenant_asin UNIQUE (tenant_id, platform, market_country, asin)
);

CREATE TABLE IF NOT EXISTS competitor_listing_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  dataset_id BIGINT REFERENCES market_datasets(id) ON DELETE SET NULL,
  watch_id BIGINT REFERENCES competitor_watch_targets(id) ON DELETE SET NULL,
  asin VARCHAR(40) NOT NULL,
  captured_at TIMESTAMPTZ(3) NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'dataset_import',
  title TEXT,
  sale_price NUMERIC(18,4),
  list_price NUMERIC(18,4),
  currency CHAR(3),
  rating NUMERIC(3,2),
  review_count INTEGER,
  image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  bullet_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  promo_label TEXT,
  first_available_date DATE,
  fingerprint VARCHAR(64) NOT NULL,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_comp_snap_asin_time
  ON competitor_listing_snapshots(tenant_id, asin, captured_at DESC);

CREATE TABLE IF NOT EXISTS competitor_change_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  watch_id BIGINT REFERENCES competitor_watch_targets(id) ON DELETE CASCADE,
  asin VARCHAR(40) NOT NULL,
  change_type VARCHAR(40) NOT NULL,
  summary TEXT NOT NULL,
  before_value JSONB,
  after_value JSONB,
  captured_at TIMESTAMPTZ(3) NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_comp_alert_tenant_time
  ON competitor_change_alerts(tenant_id, created_at DESC);

COMMIT;
