\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS registration_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  enterprise_name VARCHAR(200) NOT NULL,
  contact_name VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  suggested_tenant_code VARCHAR(32) NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  reject_reason VARCHAR(500),
  reviewed_by BIGINT REFERENCES users(id),
  reviewed_at TIMESTAMPTZ(3),
  approved_tenant_id BIGINT REFERENCES tenants(id),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_registration_status CHECK (status IN ('pending','approved','rejected')),
  CONSTRAINT chk_registration_email_lower CHECK (email = lower(email))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_registration_pending_email
  ON registration_applications(email) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_registration_status_created
  ON registration_applications(status, created_at DESC);

COMMENT ON TABLE registration_applications IS 'Public enterprise signup requests awaiting platform-admin approval.';
COMMENT ON COLUMN registration_applications.password_hash IS 'Applicant-chosen password hash; never returned by APIs.';

COMMIT;
