\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS authorized_collect_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(200) NOT NULL,
  source_kind VARCHAR(40) NOT NULL,
  endpoint_url TEXT NOT NULL,
  platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
  market_country CHAR(2) NOT NULL DEFAULT 'US',
  category_code VARCHAR(80) NOT NULL DEFAULT 'sofa',
  dataset_id BIGINT REFERENCES market_datasets(id) ON DELETE SET NULL,
  authorization_reference TEXT NOT NULL,
  auth_token_env VARCHAR(128),
  schedule_minutes INTEGER NOT NULL DEFAULT 1440,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_fetched_at TIMESTAMPTZ(3),
  last_status VARCHAR(20),
  last_error TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_collect_source_kind CHECK (source_kind IN (
    'authorized_market_json','authorized_review_stream','amazon_product_page',
    'amazon_review_page','web_review_page')),
  CONSTRAINT chk_collect_schedule CHECK (schedule_minutes BETWEEN 5 AND 10080),
  CONSTRAINT uk_collect_source_url UNIQUE (tenant_id, source_kind, endpoint_url)
);
COMMENT ON TABLE authorized_collect_sources IS 'Tenant-authorized API, push, Amazon and external review web collection sources.';

CREATE TABLE IF NOT EXISTS authorized_collect_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  source_id BIGINT NOT NULL REFERENCES authorized_collect_sources(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL,
  fetched_count INTEGER NOT NULL DEFAULT 0,
  inserted_count INTEGER NOT NULL DEFAULT 0,
  alert_count INTEGER NOT NULL DEFAULT 0,
  error_summary TEXT,
  started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at TIMESTAMPTZ(3)
);
CREATE INDEX IF NOT EXISTS idx_collect_runs_source_time ON authorized_collect_runs(tenant_id, source_id, started_at DESC);

CREATE TABLE IF NOT EXISTS sentiment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  source_id BIGINT REFERENCES authorized_collect_sources(id) ON DELETE SET NULL,
  external_id VARCHAR(200),
  platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
  market_country CHAR(2) NOT NULL DEFAULT 'US',
  asin VARCHAR(40),
  reviewer_location VARCHAR(80),
  language_code VARCHAR(16),
  rating NUMERIC(3,2),
  content_original TEXT NOT NULL,
  sentiment VARCHAR(16) NOT NULL,
  sentiment_score NUMERIC(5,4),
  reviewed_at TIMESTAMPTZ(3),
  received_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  content_hash CHAR(64) NOT NULL,
  raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT chk_sentiment_event CHECK (sentiment IN ('positive','neutral','negative')),
  CONSTRAINT uk_sentiment_event_hash UNIQUE (tenant_id, content_hash)
);
COMMENT ON TABLE sentiment_events IS 'Authorized review/opinion events pushed by connectors or fetched from authorized JSON exports.';
CREATE INDEX IF NOT EXISTS idx_sentiment_events_tenant_time ON sentiment_events(tenant_id, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_sentiment_events_tenant_sentiment ON sentiment_events(tenant_id, sentiment, received_at DESC);

CREATE TABLE IF NOT EXISTS policy_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(200) NOT NULL,
  source_type VARCHAR(40) NOT NULL,
  source_url TEXT NOT NULL,
  market_country CHAR(2),
  category_code VARCHAR(80),
  keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
  authorization_reference TEXT NOT NULL,
  schedule_minutes INTEGER NOT NULL DEFAULT 1440,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_fetched_at TIMESTAMPTZ(3),
  last_status VARCHAR(20),
  last_error TEXT,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_policy_source_type CHECK (source_type IN ('official_rss','official_json')),
  CONSTRAINT chk_policy_schedule CHECK (schedule_minutes BETWEEN 5 AND 10080),
  CONSTRAINT uk_policy_source_url UNIQUE (tenant_id, source_url)
);
COMMENT ON TABLE policy_sources IS 'Tenant-configured official policy RSS/JSON sources with explicit authorization reference.';

CREATE TABLE IF NOT EXISTS policy_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  source_id BIGINT REFERENCES policy_sources(id) ON DELETE SET NULL,
  external_id VARCHAR(300),
  title TEXT NOT NULL,
  summary TEXT,
  url TEXT,
  published_at TIMESTAMPTZ(3),
  severity VARCHAR(16) NOT NULL DEFAULT 'low',
  matched_keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  content_hash CHAR(64) NOT NULL,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_policy_alert_severity CHECK (severity IN ('low','medium','high')),
  CONSTRAINT uk_policy_alert_hash UNIQUE (tenant_id, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_policy_alerts_tenant_time ON policy_alerts(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_policy_alerts_tenant_unread ON policy_alerts(tenant_id, is_read, created_at DESC);

COMMIT;
