\set ON_ERROR_STOP on
BEGIN;
SET search_path TO furniscope, public;

CREATE TABLE IF NOT EXISTS notification_channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  name VARCHAR(200) NOT NULL,
  channel_type VARCHAR(40) NOT NULL,
  target_url TEXT NOT NULL,
  secret_env VARCHAR(128),
  events JSONB NOT NULL DEFAULT '[]'::jsonb,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_notification_channel_type CHECK (channel_type IN ('webhook','dingtalk','slack','email_gateway','sms_gateway')),
  CONSTRAINT uk_notification_channel_url UNIQUE (tenant_id, target_url)
);
COMMENT ON TABLE notification_channels IS 'Tenant-configured outbound webhook channels; secrets stay in environment variables.';

CREATE TABLE IF NOT EXISTS notification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id BIGINT NOT NULL REFERENCES tenants(id),
  channel_id BIGINT NOT NULL REFERENCES notification_channels(id) ON DELETE CASCADE,
  event_type VARCHAR(40) NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delivered_at TIMESTAMPTZ(3),
  CONSTRAINT chk_notification_event_type CHECK (event_type IN ('competitor_alert','policy_alert','test')),
  CONSTRAINT chk_notification_event_status CHECK (status IN ('pending','delivered','failed'))
);
CREATE INDEX IF NOT EXISTS idx_notification_events_pending
  ON notification_events(status, created_at) WHERE status='pending';
CREATE INDEX IF NOT EXISTS idx_notification_events_tenant_time
  ON notification_events(tenant_id, created_at DESC);

ALTER TABLE authorized_collect_sources ADD COLUMN IF NOT EXISTS last_queued_at TIMESTAMPTZ(3);
ALTER TABLE policy_sources ADD COLUMN IF NOT EXISTS last_queued_at TIMESTAMPTZ(3);

COMMIT;
