"""Authorized market signals from APIs, feeds, pushes, and active web crawlers."""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
import hashlib
import ipaddress
import json
import os
import re
import socket
from typing import Any
from urllib.parse import urlparse, urlunparse
from urllib.request import Request, urlopen
import xml.etree.ElementTree as ET

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from ..errors import BusinessError
from .competitor_tracking import CompetitorTrackingService, listing_fingerprint, promo_label
from .notifications import queue_alert_notifications
from .review_cleaning import REASON_LABELS, content_hash, infer_sentiment, review_invalid_reason, unique_invalid_hash
from .web_signal_parser import parse_html_signal_page

MAX_RESPONSE_BYTES = 2_000_000
CONNECTOR_UA = "FurniScope-AuthorizedCrawler/1.0 (+tenant-authorized-collection)"
AUTHORIZED_PACK_DIR = Path(__file__).resolve().parent.parent / "authorized_packs"
PACK_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,120}$")
SOURCE_KINDS = {
    "authorized_market_json", "authorized_review_stream", "amazon_product_page",
    "amazon_review_page", "web_review_page",
}
POLICY_SOURCE_TYPES = {"official_rss", "official_json"}
DEFAULT_POLICY_KEYWORDS = [
    "furniture", "sofa", "chair", "recliner", "跨境", "家具", "沙发", "召回", "recall",
    "safety", "cpsc", "tariff", "duty", "customs", "certification", "reach", "prop 65",
]
HIGH_RISK_TERMS = ("recall", "召回", "ban", "禁售", "injury", "伤亡", "tariff", "加征关税")
MEDIUM_RISK_TERMS = ("certification", "认证", "customs", "清关", "reach", "prop 65", "cpsc")
POSITIVE_TERMS = ("comfortable", "sturdy", "easy assembly", "perfect", "love", "舒服", "结实", "满意", "稳固")
NEGATIVE_TERMS = ("broken", "terrible", "awful", "smell", "mold", "refund", "collapsed", "squeak", "差", "破", "臭", "塌", "退")


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _jsonable(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Decimal):
        return float(value)
    return value


def _sha256(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _safe_error(exc: Exception) -> str:
    if isinstance(exc, BusinessError):
        return exc.message[:300]
    return type(exc).__name__[:120]


def finalize_collect_run(*, status: str, fetched: int, inserted: int,
                         listing_asins: list[str], error_summary: str | None) -> tuple[str, str | None]:
    """Zero-result collects must not be recorded as succeeded."""
    if status != "succeeded":
        return status, error_summary
    wrote_anything = inserted > 0 or bool(listing_asins)
    if fetched <= 0 or not wrote_anything:
        return "failed", error_summary or "来源未返回可写入的竞品或评论，零结果不记为成功"
    return status, error_summary


def _parse_datetime(value: Any) -> datetime | None:
    if value in (None, ""):
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


def _float(value: Any) -> float | None:
    try:
        return None if value in (None, "") else float(value)
    except (TypeError, ValueError):
        return None


def _int(value: Any) -> int | None:
    try:
        return None if value in (None, "") else int(float(value))
    except (TypeError, ValueError):
        return None


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1].lower()


def _child_text(element: ET.Element, names: set[str]) -> str | None:
    for child in list(element):
        if _local_name(child.tag) in names:
            if _local_name(child.tag) == "link" and child.attrib.get("href"):
                return child.attrib["href"]
            if child.text and child.text.strip():
                return child.text.strip()
    return None


class AuthorizedSignalService:
    def __init__(self, settings: Any | None = None) -> None:
        self.settings = settings
        self.tracking = CompetitorTrackingService()

    async def ensure_schema(self, session: AsyncSession) -> None:
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS authorized_collect_sources (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              name VARCHAR(200) NOT NULL,
              source_kind VARCHAR(40) NOT NULL,
              endpoint_url TEXT NOT NULL,
              platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
              market_country CHAR(2) NOT NULL DEFAULT 'US',
              category_code VARCHAR(80) NOT NULL DEFAULT 'sofa',
              dataset_id BIGINT,
              authorization_reference TEXT NOT NULL,
              auth_token_env VARCHAR(128),
              schedule_minutes INTEGER NOT NULL DEFAULT 1440,
              enabled BOOLEAN NOT NULL DEFAULT TRUE,
              last_fetched_at TIMESTAMPTZ(3),
              last_queued_at TIMESTAMPTZ(3),
              last_status VARCHAR(20),
              last_error TEXT,
              created_by BIGINT,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_collect_source_kind CHECK (source_kind IN (
                'authorized_market_json','authorized_review_stream','amazon_product_page',
                'amazon_review_page','web_review_page')),
              CONSTRAINT chk_collect_schedule CHECK (schedule_minutes BETWEEN 5 AND 10080),
              CONSTRAINT uk_collect_source_url UNIQUE (tenant_id, source_kind, endpoint_url)
            )
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS authorized_collect_runs (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              source_id BIGINT NOT NULL REFERENCES authorized_collect_sources(id) ON DELETE CASCADE,
              status VARCHAR(20) NOT NULL,
              fetched_count INTEGER NOT NULL DEFAULT 0,
              inserted_count INTEGER NOT NULL DEFAULT 0,
              alert_count INTEGER NOT NULL DEFAULT 0,
              error_summary TEXT,
              started_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              finished_at TIMESTAMPTZ(3)
            )
        """))
        await session.execute(text("""
            DO $$
            BEGIN
              IF EXISTS (
                SELECT 1 FROM pg_constraint
                 WHERE conrelid='authorized_collect_sources'::regclass
                   AND conname='chk_collect_source_kind'
                   AND pg_get_constraintdef(oid) NOT LIKE '%amazon_product_page%'
              ) THEN
                ALTER TABLE authorized_collect_sources DROP CONSTRAINT chk_collect_source_kind;
                ALTER TABLE authorized_collect_sources ADD CONSTRAINT chk_collect_source_kind CHECK (
                  source_kind IN ('authorized_market_json','authorized_review_stream','amazon_product_page',
                                  'amazon_review_page','web_review_page'));
              END IF;
            END $$
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS sentiment_events (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              source_id BIGINT REFERENCES authorized_collect_sources(id) ON DELETE SET NULL,
              external_id VARCHAR(200),
              platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
              market_country CHAR(2) NOT NULL DEFAULT 'US',
              asin VARCHAR(40),
              reviewer_location VARCHAR(80),
              language_code VARCHAR(16),
              rating NUMERIC(3,2),
              content_original TEXT NOT NULL,
              sentiment VARCHAR(16) NOT NULL,
              sentiment_score NUMERIC(5,4),
              reviewed_at TIMESTAMPTZ(3),
              received_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              content_hash CHAR(64) NOT NULL,
              raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
              CONSTRAINT chk_sentiment_event CHECK (sentiment IN ('positive','neutral','negative')),
              CONSTRAINT uk_sentiment_event_hash UNIQUE (tenant_id, content_hash)
            )
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_sentiment_events_tenant_time
              ON sentiment_events(tenant_id, received_at DESC)
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS policy_sources (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              name VARCHAR(200) NOT NULL,
              source_type VARCHAR(40) NOT NULL,
              source_url TEXT NOT NULL,
              market_country CHAR(2),
              category_code VARCHAR(80),
              keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
              authorization_reference TEXT NOT NULL,
              schedule_minutes INTEGER NOT NULL DEFAULT 1440,
              enabled BOOLEAN NOT NULL DEFAULT TRUE,
              last_fetched_at TIMESTAMPTZ(3),
              last_queued_at TIMESTAMPTZ(3),
              last_status VARCHAR(20),
              last_error TEXT,
              created_by BIGINT,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_policy_source_type CHECK (source_type IN ('official_rss','official_json')),
              CONSTRAINT chk_policy_schedule CHECK (schedule_minutes BETWEEN 5 AND 10080),
              CONSTRAINT uk_policy_source_url UNIQUE (tenant_id, source_url)
            )
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS policy_alerts (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              source_id BIGINT REFERENCES policy_sources(id) ON DELETE SET NULL,
              external_id VARCHAR(300),
              title TEXT NOT NULL,
              summary TEXT,
              url TEXT,
              published_at TIMESTAMPTZ(3),
              severity VARCHAR(16) NOT NULL DEFAULT 'low',
              matched_keywords JSONB NOT NULL DEFAULT '[]'::jsonb,
              is_read BOOLEAN NOT NULL DEFAULT FALSE,
              content_hash CHAR(64) NOT NULL,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_policy_alert_severity CHECK (severity IN ('low','medium','high')),
              CONSTRAINT uk_policy_alert_hash UNIQUE (tenant_id, content_hash)
            )
        """))
        await session.execute(text("""
            ALTER TABLE policy_sources ADD COLUMN IF NOT EXISTS schedule_minutes INTEGER NOT NULL DEFAULT 1440
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_policy_alerts_tenant_time
              ON policy_alerts(tenant_id, created_at DESC)
        """))

    def _pack_path(self, url: str) -> Path:
        parsed = urlparse(url.strip())
        if parsed.scheme != "pack" or (parsed.hostname or "").lower() != "authorized":
            raise BusinessError("SOURCE_URL_INVALID", "授权数据包地址必须使用 pack://authorized/<pack-id>", status_code=422)
        name = (parsed.path or "").strip("/")
        if not PACK_NAME.fullmatch(name):
            raise BusinessError("SOURCE_URL_INVALID", "授权数据包标识无效", status_code=422)
        root = AUTHORIZED_PACK_DIR.resolve()
        path = (root / f"{name}.json").resolve()
        if path.parent != root:
            raise BusinessError("SOURCE_URL_FORBIDDEN", "不允许访问授权数据包目录之外的文件", status_code=422)
        if not path.is_file():
            raise BusinessError("SOURCE_PACK_NOT_FOUND", "授权数据包不存在", status_code=404)
        return path

    def _validate_source_url(self, raw_url: str) -> str:
        parsed = urlparse(raw_url.strip())
        if parsed.scheme == "pack":
            path = self._pack_path(raw_url)
            return f"pack://authorized/{path.stem}"
        allow_http = getattr(self.settings, "app_env", "development") != "production"
        if parsed.scheme not in ({"https", "http"} if allow_http else {"https"}):
            raise BusinessError("SOURCE_URL_INVALID", "授权采集源必须使用 HTTPS URL，或 pack://authorized/<pack-id>", status_code=422)
        if parsed.username or parsed.password:
            raise BusinessError("SOURCE_URL_INVALID", "URL 不允许携带账号或密码", status_code=422)
        if not parsed.hostname:
            raise BusinessError("SOURCE_URL_INVALID", "URL 缺少主机名", status_code=422)
        try:
            literal_ip = ipaddress.ip_address(parsed.hostname)
        except ValueError:
            literal_ip = None
        if literal_ip and (literal_ip.is_private or literal_ip.is_loopback or literal_ip.is_link_local
                           or literal_ip.is_reserved or literal_ip.is_multicast or literal_ip.is_unspecified):
            raise BusinessError("SOURCE_URL_FORBIDDEN", "不允许访问内网或保留地址", status_code=422)
        return urlunparse(parsed._replace(fragment=""))

    def _assert_fetch_allowed(self, raw_url: str) -> None:
        if raw_url.startswith("pack://"):
            self._pack_path(raw_url)
            return
        parsed = urlparse(raw_url)
        host = (parsed.hostname or "").lower()
        if host in {"localhost", "localhost."}:
            raise BusinessError("SOURCE_URL_FORBIDDEN", "不允许访问本机地址", status_code=422)
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        try:
            infos = socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
        except socket.gaierror as exc:
            raise BusinessError("SOURCE_URL_UNREACHABLE", "授权源域名无法解析", status_code=422) from exc
        for info in infos:
            ip = ipaddress.ip_address(info[4][0])
            if (ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved
                    or ip.is_multicast or ip.is_unspecified):
                raise BusinessError("SOURCE_URL_FORBIDDEN", "授权源解析到内网或保留地址", status_code=422)

    def _read_url(self, url: str, auth_token_env: str | None) -> str:
        self._assert_fetch_allowed(url)
        if url.startswith("pack://"):
            return self._pack_path(url).read_text(encoding="utf-8")
        headers = {
            "User-Agent": CONNECTOR_UA,
            "Accept": "text/html,application/xhtml+xml,application/json,application/rss+xml,application/atom+xml,text/xml;q=0.8",
            "Accept-Language": "en-US,en;q=0.8",
        }
        if auth_token_env:
            token = os.getenv(auth_token_env)
            if token:
                headers["Authorization"] = f"Bearer {token}"
        request = Request(url, headers=headers)
        with urlopen(request, timeout=12) as response:  # noqa: S310 - URL/IP are validated before use.
            final_url = response.geturl() or url
            if final_url != url:
                self._assert_fetch_allowed(final_url)
            body = response.read(MAX_RESPONSE_BYTES + 1)
        if len(body) > MAX_RESPONSE_BYTES:
            raise BusinessError("SOURCE_PAYLOAD_TOO_LARGE", "授权源响应超过 2MiB 限制", status_code=422)
        return body.decode("utf-8", errors="replace")

    async def _fetch_text(self, url: str, auth_token_env: str | None) -> str:
        return await asyncio.to_thread(self._read_url, url, auth_token_env)

    async def create_source(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                            payload: dict[str, Any]) -> dict[str, Any]:
        endpoint_url = self._validate_source_url(payload["endpoint_url"])
        dataset_id = payload.get("dataset_id")
        if dataset_id is not None:
            dataset = await session.scalar(text("""
                SELECT id FROM market_datasets
                 WHERE id=:dataset AND tenant_id=:tenant AND deleted_at IS NULL
            """), {"dataset": dataset_id, "tenant": tenant_id})
            if not dataset:
                raise BusinessError("DATASET_NOT_FOUND", "绑定数据集不存在或不可访问", status_code=404)
        source_id = int(await session.scalar(text("""
            INSERT INTO authorized_collect_sources
              (tenant_id,name,source_kind,endpoint_url,platform,market_country,category_code,dataset_id,
               authorization_reference,auth_token_env,schedule_minutes,enabled,created_by)
            VALUES (:tenant,:name,:kind,:url,:platform,:country,:category,:dataset,:authorization,
                    :token_env,:schedule,:enabled,:user)
            RETURNING id
        """), {
            "tenant": tenant_id, "name": payload["name"], "kind": payload["source_kind"],
            "url": endpoint_url, "platform": payload.get("platform") or "amazon",
            "country": payload.get("market_country") or "US", "category": payload.get("category_code") or "sofa",
            "dataset": dataset_id, "authorization": payload["authorization_reference"],
            "token_env": payload.get("auth_token_env"), "schedule": payload.get("schedule_minutes") or 1440,
            "enabled": payload.get("enabled", True), "user": user_id,
        }))
        return await self.get_source(session, tenant_id=tenant_id, source_id=source_id)

    def infer_source_kind(self, url: str, requested: str | None = None) -> str:
        if requested:
            return requested
        parsed = urlparse(url)
        host = (parsed.hostname or "").lower()
        path = (parsed.path or "").lower()
        if "amazon." in host:
            if "product-reviews" in path or "/reviews" in path:
                return "amazon_review_page"
            return "amazon_product_page"
        return "web_review_page"

    async def collect_from_url(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                               payload: dict[str, Any]) -> dict[str, Any]:
        endpoint_url = self._validate_source_url(payload["endpoint_url"])
        source_kind = self.infer_source_kind(endpoint_url, payload.get("source_kind"))
        existing = (await session.execute(text("""
            SELECT id FROM authorized_collect_sources
             WHERE tenant_id=:tenant AND endpoint_url=:url
             ORDER BY id DESC LIMIT 1
        """), {"tenant": tenant_id, "url": endpoint_url})).scalar()
        if existing:
            source_id = int(existing)
            await session.execute(text("""
                UPDATE authorized_collect_sources
                   SET dataset_id=COALESCE(:dataset,dataset_id)
                 WHERE id=:id AND tenant_id=:tenant
            """), {"dataset": payload.get("dataset_id"), "id": source_id, "tenant": tenant_id})
        else:
            host = urlparse(endpoint_url).hostname or "网页"
            created = await self.create_source(session, tenant_id=tenant_id, user_id=user_id, payload={
                "name": f"采集 {host}"[:200],
                "source_kind": source_kind,
                "endpoint_url": endpoint_url,
                "platform": payload.get("platform") or "amazon",
                "market_country": (payload.get("market_country") or "US").upper(),
                "category_code": payload.get("category_code") or "sofa",
                "dataset_id": payload.get("dataset_id"),
                "authorization_reference": f"网页采集 {host}",
                "schedule_minutes": payload.get("schedule_minutes") or 1440,
                "enabled": False,
            })
            source_id = int(created["source_id"])
        return await self.fetch_source(session, tenant_id=tenant_id, source_id=source_id)

    async def get_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> dict[str, Any]:
        row = (await session.execute(text("""
            SELECT id AS source_id,name,source_kind,endpoint_url,platform,market_country,category_code,
                   dataset_id,authorization_reference,auth_token_env,schedule_minutes,enabled,
                   last_fetched_at,last_status,last_error,created_at
              FROM authorized_collect_sources
             WHERE id=:id AND tenant_id=:tenant
        """), {"id": source_id, "tenant": tenant_id})).mappings().one_or_none()
        if not row:
            raise BusinessError("SOURCE_NOT_FOUND", "授权采集源不存在或不可访问", status_code=404)
        return {key: _jsonable(value) for key, value in dict(row).items()}

    async def list_sources(self, session: AsyncSession, *, tenant_id: int) -> list[dict[str, Any]]:
        rows = (await session.execute(text("""
            SELECT id AS source_id,name,source_kind,endpoint_url,platform,market_country,category_code,
                   dataset_id,authorization_reference,auth_token_env,schedule_minutes,enabled,
                   last_fetched_at,last_status,last_error,created_at
              FROM authorized_collect_sources
             WHERE tenant_id=:tenant
             ORDER BY created_at DESC,id DESC
        """), {"tenant": tenant_id})).mappings().all()
        return [{key: _jsonable(value) for key, value in dict(row).items()} for row in rows]

    async def update_source(self, session: AsyncSession, *, tenant_id: int, source_id: int,
                            payload: dict[str, Any]) -> dict[str, Any]:
        current = await self.get_source(session, tenant_id=tenant_id, source_id=source_id)
        enabled = current["enabled"] if payload.get("enabled") is None else bool(payload["enabled"])
        schedule = payload.get("schedule_minutes") or current["schedule_minutes"]
        await session.execute(text("""
            UPDATE authorized_collect_sources
               SET enabled=:enabled,schedule_minutes=:schedule
             WHERE id=:id AND tenant_id=:tenant
        """), {"enabled": enabled, "schedule": schedule, "id": source_id, "tenant": tenant_id})
        return await self.get_source(session, tenant_id=tenant_id, source_id=source_id)

    async def delete_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> None:
        result = await session.execute(text("""
            DELETE FROM authorized_collect_sources WHERE id=:id AND tenant_id=:tenant
        """), {"id": source_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("SOURCE_NOT_FOUND", "授权采集源不存在或不可访问", status_code=404)

    async def fetch_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> dict[str, Any]:
        source = await self.get_source(session, tenant_id=tenant_id, source_id=source_id)
        run_id = int(await session.scalar(text("""
            INSERT INTO authorized_collect_runs(tenant_id,source_id,status)
            VALUES (:tenant,:source,'running') RETURNING id
        """), {"tenant": tenant_id, "source": source_id}))
        fetched = inserted = alerts = 0
        listing_asins: list[str] = []
        status = "succeeded"
        error_summary = None
        try:
            if source["source_kind"] == "authorized_review_stream":
                raise BusinessError("SOURCE_KIND_STREAM_ONLY", "评论流源请通过 sentiment-events 接口实时推送", status_code=422)
            text_body = await self._fetch_text(source["endpoint_url"], source.get("auth_token_env"))
            if source["source_kind"] == "authorized_market_json":
                payload = json.loads(text_body)
            else:
                payload = parse_html_signal_page(
                    text_body, page_url=source["endpoint_url"], source_kind=source["source_kind"],
                )
            listings = payload.get("listings") or []
            reviews = payload.get("reviews") or []
            if not listings and not reviews:
                lowered = text_body.lower()
                if source["source_kind"].startswith("amazon_") and any(marker in lowered for marker in (
                    "edgex/guard", "__rx_csd", "sign in or create account", "/ap/signin",
                )):
                    raise BusinessError(
                        "AMAZON_SESSION_REQUIRED",
                        "Amazon 返回了访问防护或登录页面，未获取到商品/评论；请使用可访问的授权 API，或配置带登录会话的浏览器采集器",
                        status_code=422,
                    )
                raise BusinessError(
                    "SOURCE_NO_RECORDS",
                    "来源响应成功，但未解析到任何竞品或评论，请检查地址、页面类型和返回格式",
                    status_code=422,
                )
            fetched = len(listings) + len(reviews)
            for item in listings:
                asin = str(item.get("platform_listing_id") or item.get("asin") or "").strip().upper()
                if not asin:
                    continue
                listing_asins.append(asin)
                await self._store_authorized_listing(session, tenant_id=tenant_id, source=source, item=item)
                inserted += 1
            for item in reviews:
                result = await self.ingest_sentiment_events(session, tenant_id=tenant_id, events=[item],
                                                            source_id=source_id,
                                                            authorization_reference=source["authorization_reference"],
                                                            defaults=source)
                inserted += result["inserted_count"]
                await self._store_dataset_review(session, tenant_id=tenant_id, source=source, item=item)
            if source.get("dataset_id"):
                await self._refresh_bound_dataset(session, tenant_id=tenant_id,
                                                  dataset_id=int(source["dataset_id"]), source=source)
            alerts = int(await session.scalar(text("""
                SELECT count(*) FROM competitor_change_alerts
                 WHERE tenant_id=:tenant AND captured_at >= (SELECT started_at FROM authorized_collect_runs WHERE id=:run)
            """), {"tenant": tenant_id, "run": run_id}) or 0)
        except Exception as exc:  # run is kept as the audit record; message is sanitized.
            status = "failed"
            error_summary = _safe_error(exc)
        status, error_summary = finalize_collect_run(
            status=status, fetched=fetched, inserted=inserted,
            listing_asins=listing_asins, error_summary=error_summary,
        )
        await session.execute(text("""
            UPDATE authorized_collect_runs
               SET status=:status,fetched_count=:fetched,inserted_count=:inserted,alert_count=:alerts,
                   error_summary=:error,finished_at=CURRENT_TIMESTAMP
             WHERE id=:run AND tenant_id=:tenant
        """), {"status": status, "fetched": fetched, "inserted": inserted, "alerts": alerts,
               "error": error_summary, "run": run_id, "tenant": tenant_id})
        await session.execute(text("""
            UPDATE authorized_collect_sources
               SET last_fetched_at=CURRENT_TIMESTAMP,last_status=:status,last_error=:error
             WHERE id=:source AND tenant_id=:tenant
        """), {"status": status, "error": error_summary, "source": source_id, "tenant": tenant_id})
        return {"run_id": run_id, "source_id": source_id, "status": status, "fetched_count": fetched,
                "inserted_count": inserted, "alert_count": alerts, "error_summary": error_summary,
                "listing_asins": listing_asins}

    async def _store_authorized_listing(self, session: AsyncSession, *, tenant_id: int,
                                        source: dict[str, Any], item: dict[str, Any]) -> int:
        asin = str(item.get("platform_listing_id") or item.get("asin") or "").strip().upper()
        if not asin:
            return 0
        payload = {
            "asin": asin,
            "title": item.get("title"),
            "sale_price": _float(item.get("sale_price")),
            "list_price": _float(item.get("list_price")),
            "currency": (item.get("currency") or "USD")[:3],
            "rating": _float(item.get("rating")),
            "review_count": _int(item.get("review_count")),
            "image_urls": item.get("image_urls") or [],
            "bullet_points": item.get("bullet_points") or [],
            "promo_label": promo_label(item.get("sale_price"), item.get("list_price"), item.get("promo_label")),
            "first_available_date": item.get("first_available_date"),
            "captured_at": _parse_datetime(item.get("captured_at")) or _now(),
            "market_country": source.get("market_country"),
            "platform": source.get("platform"),
            "dataset_id": source.get("dataset_id"),
        }
        payload["fingerprint"] = listing_fingerprint(payload)
        alert_count = await self.tracking._store_snapshot(  # noqa: SLF001 - shared snapshot/diff logic.
            session, tenant_id=tenant_id, dataset_id=source.get("dataset_id"),
            source=("authorized_api" if source.get("source_kind") == "authorized_market_json"
                    else "authorized_crawler"), payload=payload,
        )
        if source.get("dataset_id"):
            await self._upsert_dataset_listing(session, tenant_id=tenant_id, source=source, item=item)
        return alert_count

    async def _upsert_dataset_listing(self, session: AsyncSession, *, tenant_id: int,
                                      source: dict[str, Any], item: dict[str, Any]) -> int | None:
        """Keep the bound AI dataset's current listing row in sync with a live source.

        Full point-in-time history remains in competitor_listing_snapshots.  The market
        dataset deliberately stores one current row per platform listing so list counts,
        previews, and workflow inputs do not grow on every scheduled fetch.
        """
        dataset_id = source.get("dataset_id")
        asin = str(item.get("platform_listing_id") or item.get("asin") or "").strip().upper()
        if not dataset_id or not asin:
            return None
        captured_at = _parse_datetime(item.get("captured_at")) or _now()
        rating = _float(item.get("rating"))
        rating = rating if rating is None or 0 <= rating <= 5 else None
        sale_price = max(0.0, _float(item.get("sale_price")) or 0.0)
        list_price = _float(item.get("list_price"))
        list_price = max(0.0, list_price) if list_price is not None else None
        attributes = {
            **(item.get("normalized_attributes") or {}),
            "market_country": source.get("market_country") or "US",
            "collection_source_kind": source.get("source_kind"),
            "authorization_reference": source.get("authorization_reference"),
        }
        params = {
            "tenant": tenant_id, "dataset": int(dataset_id), "platform_id": asin,
            "url": item.get("source_url") or source.get("endpoint_url"),
            "title": str(item.get("title") or f"{source.get('platform', 'market')} {asin}"),
            "category": str(item.get("category_code") or source.get("category_code") or "uncategorized"),
            "currency": str(item.get("currency") or "USD")[:3].upper(),
            "list_price": list_price, "sale_price": sale_price, "brand": item.get("brand"),
            "rating": rating, "review_count": max(0, _int(item.get("review_count")) or 0),
            "captured": captured_at, "first_available": item.get("first_available_date"),
            "attrs": json.dumps(attributes, ensure_ascii=False, default=str),
            "images": json.dumps(item.get("image_urls") or [], ensure_ascii=False),
            "bullets": json.dumps(item.get("bullet_points") or [], ensure_ascii=False),
            "raw": json.dumps({**item, "authorization_reference": source.get("authorization_reference")},
                              ensure_ascii=False, default=str),
        }
        existing_id = await session.scalar(text("""
            SELECT id FROM market_listings
             WHERE tenant_id=:tenant AND dataset_id=:dataset AND platform_listing_id=:platform_id
             ORDER BY captured_at DESC,id DESC LIMIT 1
        """), params)
        if existing_id:
            params["listing"] = int(existing_id)
            await session.execute(text("""
                UPDATE market_listings
                   SET listing_url=:url,title=:title,category_code=:category,currency=:currency,
                       list_price=:list_price,sale_price=:sale_price,brand=:brand,rating=:rating,
                       review_count=:review_count,captured_at=:captured,first_available_date=:first_available,
                       normalized_attributes=CAST(:attrs AS jsonb),image_urls=CAST(:images AS jsonb),
                       bullet_points=CAST(:bullets AS jsonb),raw_payload=CAST(:raw AS jsonb)
                 WHERE id=:listing AND tenant_id=:tenant AND dataset_id=:dataset
            """), params)
            return int(existing_id)
        return int(await session.scalar(text("""
            INSERT INTO market_listings
              (tenant_id,dataset_id,platform_listing_id,listing_url,title,category_code,currency,
               list_price,sale_price,brand,rating,review_count,captured_at,first_available_date,
               normalized_attributes,image_urls,bullet_points,raw_payload)
            VALUES (:tenant,:dataset,:platform_id,:url,:title,:category,:currency,:list_price,:sale_price,
                    :brand,:rating,:review_count,:captured,:first_available,CAST(:attrs AS jsonb),
                    CAST(:images AS jsonb),CAST(:bullets AS jsonb),CAST(:raw AS jsonb))
            RETURNING id
        """), params))

    async def _store_dataset_review(self, session: AsyncSession, *, tenant_id: int,
                                    source: dict[str, Any], item: dict[str, Any]) -> int:
        dataset_id = source.get("dataset_id")
        content = str(item.get("content_original") or item.get("content") or "").strip()
        asin = str(item.get("platform_listing_id") or item.get("asin") or "").strip().upper()
        if not dataset_id or not content or not asin:
            return 0
        listing_id = await session.scalar(text("""
            SELECT id FROM market_listings
             WHERE tenant_id=:tenant AND dataset_id=:dataset AND platform_listing_id=:asin
             ORDER BY captured_at DESC,id DESC LIMIT 1
        """), {"tenant": tenant_id, "dataset": int(dataset_id), "asin": asin})
        if not listing_id:
            listing_id = await self._upsert_dataset_listing(
                session, tenant_id=tenant_id, source=source,
                item={"platform_listing_id": asin, "title": item.get("listing_title")},
            )
        if not listing_id:
            return 0
        review_id = str(item.get("platform_review_id") or item.get("external_id") or "").strip()
        review_id = (review_id or f"crawl-{content_hash(content)[:24]}")[:200]
        reason = review_invalid_reason(content, set())
        is_valid = reason is None
        digest = content_hash(content) if is_valid else unique_invalid_hash(review_id, content)
        rating = _float(item.get("rating"))
        rating = rating if rating is None or 0 <= rating <= 5 else None
        sentiment = str(item.get("sentiment") or "").lower()
        if sentiment not in {"positive", "neutral", "negative"}:
            sentiment = infer_sentiment(content, rating)
        row = await session.scalar(text("""
            INSERT INTO reviews
              (tenant_id,dataset_id,listing_id,platform_review_id,rating,title_original,content_original,
               language_code,reviewer_location,sentiment,reviewed_at,verified_purchase,helpful_count,
               is_valid,invalid_reason,content_hash)
            VALUES (:tenant,:dataset,:listing,:review_id,:rating,:title,:content,:language,:location,
                    :sentiment,:reviewed,:verified,:helpful,:is_valid,:invalid_reason,:hash)
            ON CONFLICT DO NOTHING RETURNING id
        """), {
            "tenant": tenant_id, "dataset": int(dataset_id), "listing": int(listing_id),
            "review_id": review_id, "rating": rating, "title": item.get("title_original"),
            "content": content, "language": (item.get("language_code") or "en")[:16],
            "location": item.get("reviewer_location") or item.get("user_location"),
            "sentiment": sentiment, "reviewed": _parse_datetime(item.get("reviewed_at") or item.get("created_at")),
            "verified": bool(item.get("verified_purchase", False)),
            "helpful": max(0, _int(item.get("helpful_count")) or 0), "is_valid": is_valid,
            "invalid_reason": None if is_valid else REASON_LABELS.get(reason, reason), "hash": digest,
        })
        return 1 if row else 0

    async def _refresh_bound_dataset(self, session: AsyncSession, *, tenant_id: int,
                                     dataset_id: int, source: dict[str, Any]) -> None:
        stats = (await session.execute(text("""
            SELECT count(DISTINCT l.platform_listing_id) AS listings,
                   count(r.id) AS reviews,
                   count(r.id) FILTER (WHERE r.is_valid) AS valid_reviews
              FROM market_listings l
              LEFT JOIN reviews r ON r.listing_id=l.id AND r.dataset_id=l.dataset_id AND r.tenant_id=l.tenant_id
             WHERE l.tenant_id=:tenant AND l.dataset_id=:dataset
        """), {"tenant": tenant_id, "dataset": dataset_id})).mappings().one()
        listings = int(stats["listings"] or 0)
        reviews = int(stats["reviews"] or 0)
        valid = int(stats["valid_reviews"] or 0)
        quality = min(100, round(20 + (valid / reviews if reviews else 1) * 80)) if listings else 0
        live_report = {
            "source_id": source.get("source_id"),
            "source_kind": source.get("source_kind"),
            "last_synced_at": _now().isoformat(),
            "listing_count": listings,
            "review_count": reviews,
            "valid_review_count": valid,
            "filtered_review_count": max(0, reviews - valid),
            "mode": "incremental_upsert",
        }
        await session.execute(text("""
            UPDATE market_datasets
               SET status='ready',listing_count=:listings,review_count=:reviews,
                   valid_review_count=:valid,quality_score=:quality,
                   quality_report=COALESCE(quality_report,'{}'::jsonb)
                     || jsonb_build_object('live_collection',CAST(:live_report AS jsonb)),
                   updated_at=CURRENT_TIMESTAMP
             WHERE id=:dataset AND tenant_id=:tenant AND deleted_at IS NULL
        """), {"tenant": tenant_id, "dataset": dataset_id, "listings": listings,
                 "reviews": reviews, "valid": valid, "quality": quality,
                 "live_report": json.dumps(live_report, ensure_ascii=False)})

    def _classify_sentiment(self, rating: float | None, content: str) -> tuple[str, float]:
        lowered = content.lower()
        if any(term in lowered for term in NEGATIVE_TERMS):
            return "negative", 0.9
        if any(term in lowered for term in POSITIVE_TERMS):
            return "positive", 0.85
        if rating is not None:
            if rating >= 4:
                return "positive", 0.75
            if rating <= 2:
                return "negative", 0.75
        return "neutral", 0.5

    async def ingest_sentiment_events(self, session: AsyncSession, *, tenant_id: int,
                                      events: list[dict[str, Any]], source_id: int | None,
                                      authorization_reference: str | None,
                                      defaults: dict[str, Any] | None = None) -> dict[str, Any]:
        if source_id is not None:
            source = await self.get_source(session, tenant_id=tenant_id, source_id=source_id)
            authorization_reference = source["authorization_reference"]
        if not authorization_reference:
            raise BusinessError("AUTHORIZATION_REQUIRED", "舆情事件必须提供授权依据或绑定授权源", status_code=422)
        inserted = 0
        items: list[dict[str, Any]] = []
        for event in events:
            content = str(event.get("content_original") or event.get("content") or "").strip()
            if not content:
                continue
            external_id = (event.get("external_id") or event.get("platform_review_id") or "")[:200] or None
            reviewed_at = _parse_datetime(event.get("reviewed_at") or event.get("created_at"))
            rating = _float(event.get("rating"))
            sentiment, score = self._classify_sentiment(rating, content)
            content_hash = _sha256(json.dumps({
                "source": source_id, "external_id": external_id, "content": content,
                "reviewed_at": reviewed_at.isoformat() if reviewed_at else None,
            }, ensure_ascii=False, sort_keys=True))
            row = (await session.execute(text("""
                INSERT INTO sentiment_events
                  (tenant_id,source_id,external_id,platform,market_country,asin,reviewer_location,language_code,
                   rating,content_original,sentiment,sentiment_score,reviewed_at,content_hash,raw_payload)
                VALUES (:tenant,:source,:external,:platform,:country,:asin,:location,:language,:rating,:content,
                        :sentiment,:score,:reviewed,:hash,CAST(:raw AS jsonb))
                ON CONFLICT (tenant_id, content_hash) DO NOTHING
                RETURNING id AS event_id,received_at
            """), {
                "tenant": tenant_id, "source": source_id, "external": external_id,
                "platform": (event.get("platform") or (defaults or {}).get("platform") or "amazon")[:40],
                "country": (event.get("market_country") or (defaults or {}).get("market_country") or "US")[:2].upper(),
                "asin": (event.get("asin") or event.get("platform_listing_id") or "")[:40].upper() or None,
                "location": event.get("reviewer_location") or event.get("user_location"),
                "language": (event.get("language_code") or "")[:16] or None,
                "rating": rating, "content": content, "sentiment": sentiment, "score": score,
                "reviewed": reviewed_at, "hash": content_hash,
                "raw": json.dumps({**event, "authorization_reference": authorization_reference},
                                  ensure_ascii=False, default=str),
            })).mappings().one_or_none()
            if row:
                inserted += 1
                items.append({"event_id": int(row["event_id"]), "sentiment": sentiment,
                              "sentiment_score": score, "received_at": _jsonable(row["received_at"])})
        return {"inserted_count": inserted, "items": items}

    async def list_sentiment_events(self, session: AsyncSession, *, tenant_id: int,
                                    sentiment: str | None, market_country: str | None,
                                    query: str | None, limit: int) -> list[dict[str, Any]]:
        clauses = ["tenant_id=:tenant"]
        params: dict[str, Any] = {"tenant": tenant_id, "limit": limit}
        if sentiment:
            clauses.append("sentiment=:sentiment")
            params["sentiment"] = sentiment
        if market_country:
            clauses.append("market_country=:country")
            params["country"] = market_country.upper()
        if query:
            clauses.append("(content_original ILIKE :q OR asin ILIKE :q OR external_id ILIKE :q)")
            params["q"] = f"%{query}%"
        rows = (await session.execute(text(f"""
            SELECT id AS event_id,source_id,external_id,platform,market_country,asin,reviewer_location,
                   language_code,rating,content_original,sentiment,sentiment_score,reviewed_at,received_at
              FROM sentiment_events
             WHERE {' AND '.join(clauses)}
             ORDER BY received_at DESC,id DESC LIMIT :limit
        """), params)).mappings().all()
        return [{key: _jsonable(value) for key, value in dict(row).items()} for row in rows]

    async def list_sentiment_feed(self, session: AsyncSession, *, tenant_id: int,
                                  sentiment: str | None, market_country: str | None,
                                  query: str | None, dataset_id: int | None,
                                  origin: str, offset: int, limit: int, page: int) -> dict[str, Any]:
        clauses = ["1=1"]
        params: dict[str, Any] = {"tenant": tenant_id, "offset": offset, "limit": limit}
        if dataset_id:
            clauses.append("(origin <> 'dataset' OR dataset_id=:dataset)")
            params["dataset"] = dataset_id
        if market_country:
            clauses.append("market_country=:country")
            params["country"] = market_country.upper()
        if query:
            clauses.append("(content_original ILIKE :q OR COALESCE(asin,'') ILIKE :q)")
            params["q"] = f"%{query}%"
        if sentiment:
            clauses.append("sentiment=:sentiment")
            params["sentiment"] = sentiment
        if origin in {"live", "dataset"}:
            clauses.append("origin=:origin")
            params["origin"] = origin
        where = " AND ".join(clauses)
        feed_sql = """
            SELECT * FROM (
              SELECT 'live:' || e.id::text AS item_id, 'live' AS origin,
                     NULL::bigint AS dataset_id, NULL::text AS dataset_name,
                     e.asin, e.platform, e.market_country, e.rating::float8 AS rating,
                     e.content_original, e.sentiment, e.sentiment_score::float8 AS sentiment_score,
                     e.reviewer_location, TRUE AS is_valid,
                     COALESCE(e.reviewed_at, e.received_at) AS occurred_at
                FROM sentiment_events e
               WHERE e.tenant_id=:tenant
              UNION ALL
              SELECT 'review:' || r.id::text, 'dataset',
                     r.dataset_id, d.name,
                     l.platform_listing_id, d.platform, d.market_country, r.rating::float8,
                     r.content_original,
                     CASE
                       WHEN lower(COALESCE(r.sentiment,'')) IN ('positive','negative','neutral')
                         THEN lower(r.sentiment)
                       WHEN r.rating >= 4 THEN 'positive'
                       WHEN r.rating IS NOT NULL AND r.rating <= 2 THEN 'negative'
                       ELSE 'neutral'
                     END,
                     NULL::float8, r.reviewer_location, r.is_valid,
                     COALESCE(r.reviewed_at, r.created_at)
                FROM reviews r
                JOIN market_datasets d ON d.id=r.dataset_id AND d.tenant_id=r.tenant_id AND d.deleted_at IS NULL
                JOIN market_listings l ON l.id=r.listing_id
               WHERE r.tenant_id=:tenant AND r.is_valid
            ) feed
        """
        stats_params = {key: value for key, value in params.items() if key not in {"offset", "limit"}}
        stats = (await session.execute(text(f"""
            SELECT count(*) AS total,
                   count(*) FILTER (WHERE sentiment='positive') AS positive_count,
                   count(*) FILTER (WHERE sentiment='negative') AS negative_count,
                   count(*) FILTER (WHERE sentiment='neutral') AS neutral_count,
                   count(*) FILTER (WHERE origin='live') AS live_count,
                   count(*) FILTER (WHERE origin='dataset') AS dataset_count
              FROM ({feed_sql}) scoped
             WHERE {where}
        """), stats_params)).mappings().one()
        rows = (await session.execute(text(f"""
            SELECT item_id,origin,dataset_id,dataset_name,asin,platform,market_country,rating,
                   content_original,sentiment,sentiment_score,reviewer_location,is_valid,occurred_at
              FROM ({feed_sql}) scoped
             WHERE {where}
             ORDER BY occurred_at DESC NULLS LAST, item_id DESC
             OFFSET :offset LIMIT :limit
        """), params)).mappings().all()
        total = int(stats["total"] or 0)
        return {
            "items": [{key: _jsonable(value) for key, value in dict(row).items()} for row in rows],
            "total": total,
            "page": page,
            "page_size": limit,
            "has_next": page * limit < total,
            "positive_count": int(stats["positive_count"] or 0),
            "negative_count": int(stats["negative_count"] or 0),
            "neutral_count": int(stats["neutral_count"] or 0),
            "live_count": int(stats["live_count"] or 0),
            "dataset_count": int(stats["dataset_count"] or 0),
        }

    async def create_policy_source(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                                   payload: dict[str, Any]) -> dict[str, Any]:
        source_url = self._validate_source_url(payload["source_url"])
        source_id = int(await session.scalar(text("""
            INSERT INTO policy_sources
              (tenant_id,name,source_type,source_url,market_country,category_code,keywords,
               authorization_reference,schedule_minutes,enabled,created_by)
            VALUES (:tenant,:name,:type,:url,:country,:category,CAST(:keywords AS jsonb),:authorization,
                    :schedule,:enabled,:user)
            RETURNING id
        """), {
            "tenant": tenant_id, "name": payload["name"], "type": payload["source_type"],
            "url": source_url, "country": payload.get("market_country"),
            "category": payload.get("category_code"),
            "keywords": json.dumps(payload.get("keywords") or [], ensure_ascii=False),
            "authorization": payload["authorization_reference"],
            "schedule": payload.get("schedule_minutes") or 1440,
            "enabled": payload.get("enabled", True), "user": user_id,
        }))
        return await self.get_policy_source(session, tenant_id=tenant_id, source_id=source_id)

    async def get_policy_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> dict[str, Any]:
        row = (await session.execute(text("""
            SELECT id AS source_id,name,source_type,source_url,market_country,category_code,keywords,
                   authorization_reference,schedule_minutes,enabled,last_fetched_at,last_status,last_error,created_at
              FROM policy_sources WHERE id=:id AND tenant_id=:tenant
        """), {"id": source_id, "tenant": tenant_id})).mappings().one_or_none()
        if not row:
            raise BusinessError("POLICY_SOURCE_NOT_FOUND", "政策源不存在或不可访问", status_code=404)
        item = dict(row)
        item["keywords"] = item.get("keywords") or []
        return {key: _jsonable(value) for key, value in item.items()}

    async def list_policy_sources(self, session: AsyncSession, *, tenant_id: int) -> list[dict[str, Any]]:
        rows = (await session.execute(text("""
            SELECT id AS source_id,name,source_type,source_url,market_country,category_code,keywords,
                   authorization_reference,schedule_minutes,enabled,last_fetched_at,last_status,last_error,created_at
              FROM policy_sources WHERE tenant_id=:tenant ORDER BY created_at DESC,id DESC
        """), {"tenant": tenant_id})).mappings().all()
        items = []
        for row in rows:
            item = dict(row)
            item["keywords"] = item.get("keywords") or []
            items.append({key: _jsonable(value) for key, value in item.items()})
        return items

    async def update_policy_source(self, session: AsyncSession, *, tenant_id: int, source_id: int,
                                   payload: dict[str, Any]) -> dict[str, Any]:
        current = await self.get_policy_source(session, tenant_id=tenant_id, source_id=source_id)
        enabled = current["enabled"] if payload.get("enabled") is None else bool(payload["enabled"])
        schedule = payload.get("schedule_minutes") or current["schedule_minutes"]
        await session.execute(text("""
            UPDATE policy_sources SET enabled=:enabled,schedule_minutes=:schedule
             WHERE id=:id AND tenant_id=:tenant
        """), {"enabled": enabled, "schedule": schedule, "id": source_id, "tenant": tenant_id})
        return await self.get_policy_source(session, tenant_id=tenant_id, source_id=source_id)

    async def delete_policy_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> None:
        result = await session.execute(text("""
            DELETE FROM policy_sources WHERE id=:id AND tenant_id=:tenant
        """), {"id": source_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("POLICY_SOURCE_NOT_FOUND", "政策源不存在或不可访问", status_code=404)

    def _parse_policy_payload(self, source: dict[str, Any], body: str) -> list[dict[str, Any]]:
        if source["source_type"] == "official_json":
            payload = json.loads(body)
            entries = payload if isinstance(payload, list) else payload.get("items") or payload.get("entries") or payload.get("alerts") or []
            return [{
                "external_id": str(item.get("id") or item.get("external_id") or item.get("url") or item.get("title") or "")[:300],
                "title": item.get("title") or item.get("name") or "未命名政策更新",
                "summary": item.get("summary") or item.get("description") or "",
                "url": item.get("url") or item.get("link"),
                "published_at": _parse_datetime(item.get("published_at") or item.get("published") or item.get("updated_at")),
            } for item in entries if isinstance(item, dict)]
        root = ET.fromstring(body)
        entries = [element for element in root.iter() if _local_name(element.tag) in {"item", "entry"}]
        parsed = []
        for element in entries:
            link = _child_text(element, {"link"})
            parsed.append({
                "external_id": (_child_text(element, {"guid", "id"}) or link or _child_text(element, {"title"}) or "")[:300],
                "title": _child_text(element, {"title"}) or "未命名政策更新",
                "summary": _child_text(element, {"summary", "description", "content"}) or "",
                "url": link,
                "published_at": _parse_datetime(_child_text(element, {"pubdate", "published", "updated", "date"})),
            })
        return parsed

    async def fetch_policy_source(self, session: AsyncSession, *, tenant_id: int, source_id: int) -> dict[str, Any]:
        source = await self.get_policy_source(session, tenant_id=tenant_id, source_id=source_id)
        if not source["enabled"]:
            raise BusinessError("POLICY_SOURCE_DISABLED", "政策源已停用", status_code=409)
        fetched = inserted = 0
        status = "succeeded"
        error_summary = None
        try:
            body = await self._fetch_text(source["source_url"], None)
            entries = self._parse_policy_payload(source, body)
            fetched = len(entries)
            keywords = [str(item) for item in (source.get("keywords") or []) if str(item).strip()] or DEFAULT_POLICY_KEYWORDS
            for entry in entries:
                haystack = f"{entry.get('title') or ''}\n{entry.get('summary') or ''}".lower()
                matched = [keyword for keyword in keywords if keyword.lower() in haystack]
                if not matched:
                    continue
                if any(term in haystack for term in HIGH_RISK_TERMS):
                    severity = "high"
                elif any(term in haystack for term in MEDIUM_RISK_TERMS):
                    severity = "medium"
                else:
                    severity = "low"
                content_hash = _sha256(json.dumps({
                    "source": source_id, "external_id": entry.get("external_id"),
                    "title": entry.get("title"), "published_at": entry.get("published_at").isoformat() if entry.get("published_at") else None,
                }, ensure_ascii=False, sort_keys=True))
                result = await session.execute(text("""
                    INSERT INTO policy_alerts
                      (tenant_id,source_id,external_id,title,summary,url,published_at,severity,matched_keywords,content_hash)
                    VALUES (:tenant,:source,:external,:title,:summary,:url,:published,:severity,
                            CAST(:matched AS jsonb),:hash)
                    ON CONFLICT (tenant_id, content_hash) DO NOTHING
                """), {
                    "tenant": tenant_id, "source": source_id, "external": entry.get("external_id"),
                    "title": entry.get("title"), "summary": entry.get("summary"), "url": entry.get("url"),
                    "published": entry.get("published_at"), "severity": severity,
                    "matched": json.dumps(matched, ensure_ascii=False), "hash": content_hash,
                })
                if result.rowcount:
                    inserted += result.rowcount or 0
                    await queue_alert_notifications(
                        session, tenant_id=tenant_id, event_type="policy_alert",
                        title=f"政策预警[{severity}]：{entry.get('title') or '未命名政策更新'}",
                        content=(entry.get("summary") or entry.get("title") or "命中政策关键词")[:3000],
                        payload={
                            "source_id": source_id, "external_id": entry.get("external_id"),
                            "url": entry.get("url"), "severity": severity, "matched_keywords": matched,
                            "published_at": entry.get("published_at").isoformat() if entry.get("published_at") else None,
                        },
                    )
        except Exception as exc:
            status = "failed"
            error_summary = _safe_error(exc)
        await session.execute(text("""
            UPDATE policy_sources
               SET last_fetched_at=CURRENT_TIMESTAMP,last_status=:status,last_error=:error
             WHERE id=:source AND tenant_id=:tenant
        """), {"status": status, "error": error_summary, "source": source_id, "tenant": tenant_id})
        return {"source_id": source_id, "status": status, "fetched_count": fetched,
                "inserted_count": inserted, "error_summary": error_summary}

    async def list_policy_alerts(self, session: AsyncSession, *, tenant_id: int,
                                 severity: str | None, unread_only: bool, limit: int) -> list[dict[str, Any]]:
        clauses = ["a.tenant_id=:tenant"]
        params: dict[str, Any] = {"tenant": tenant_id, "limit": limit}
        if severity:
            clauses.append("a.severity=:severity")
            params["severity"] = severity
        if unread_only:
            clauses.append("a.is_read=FALSE")
        rows = (await session.execute(text(f"""
            SELECT a.id AS alert_id,a.source_id,a.external_id,a.title,a.summary,a.url,a.published_at,
                   a.severity,a.matched_keywords,a.is_read,a.created_at,s.name AS source_name
              FROM policy_alerts a
              LEFT JOIN policy_sources s ON s.id=a.source_id AND s.tenant_id=a.tenant_id
             WHERE {' AND '.join(clauses)}
             ORDER BY a.created_at DESC,a.id DESC LIMIT :limit
        """), params)).mappings().all()
        items = []
        for row in rows:
            item = dict(row)
            item["matched_keywords"] = item.get("matched_keywords") or []
            items.append({key: _jsonable(value) for key, value in item.items()})
        return items

    async def mark_policy_alert_read(self, session: AsyncSession, *, tenant_id: int, alert_id: int) -> None:
        result = await session.execute(text("""
            UPDATE policy_alerts SET is_read=TRUE WHERE id=:id AND tenant_id=:tenant
        """), {"id": alert_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("POLICY_ALERT_NOT_FOUND", "政策预警不存在", status_code=404)

    async def overview(self, session: AsyncSession, *, tenant_id: int) -> dict[str, int]:
        row = (await session.execute(text("""
            SELECT
              (SELECT count(*) FROM authorized_collect_sources WHERE tenant_id=:tenant AND enabled) AS source_count,
              (SELECT count(*) FROM sentiment_events WHERE tenant_id=:tenant) AS sentiment_count,
              (SELECT count(*) FROM sentiment_events WHERE tenant_id=:tenant AND received_at >= CURRENT_TIMESTAMP - INTERVAL '24 hours') AS sentiment_24h,
              (SELECT count(*) FROM policy_sources WHERE tenant_id=:tenant AND enabled) AS policy_source_count,
              (SELECT count(*) FROM policy_alerts WHERE tenant_id=:tenant AND is_read=FALSE) AS unread_policy_alerts
        """), {"tenant": tenant_id})).mappings().one()
        return {key: int(value or 0) for key, value in dict(row).items()}
