"""Competitor watch board: snapshots come from authorized imported listings, not crawlers."""

from __future__ import annotations

from datetime import datetime, timezone
from decimal import Decimal
import hashlib
import json
import re
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from ..errors import BusinessError
from .notifications import queue_alert_notifications

ASIN_PATTERN = re.compile(r"^[A-Z0-9][A-Z0-9\-_.]{3,39}$", re.I)
TOKEN_PATTERN = re.compile(r"[a-z0-9]+|[\u4e00-\u9fff]")
CHANGE_LABELS = {
    "price": "价格变动",
    "title": "标题更新",
    "image": "主图更新",
    "bullets": "五点描述更新",
    "promo": "促销变动",
    "new_listing": "监控目标上新",
}


def _text_similarity(left: str, right: str) -> float:
    a = set(TOKEN_PATTERN.findall((left or "").lower()))
    b = set(TOKEN_PATTERN.findall((right or "").lower()))
    return len(a & b) / len(a | b) if a and b else 0.0


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _jsonable(value: Any) -> Any:
    if isinstance(value, datetime):
        return value.isoformat()
    if isinstance(value, Decimal):
        return float(value)
    return value


def promo_label(sale_price: Any, list_price: Any, coupon: Any = None) -> str | None:
    if coupon not in (None, "", [], {}):
        return str(coupon)[:120]
    try:
        sale = None if sale_price in (None, "") else float(sale_price)
        listed = None if list_price in (None, "") else float(list_price)
    except (TypeError, ValueError):
        return None
    if sale is None or listed is None or listed <= sale or listed <= 0:
        return None
    off = round((1 - sale / listed) * 100)
    return f"直降 {off}%"


def listing_fingerprint(payload: dict[str, Any]) -> str:
    material = json.dumps({
        "title": payload.get("title") or "",
        "sale_price": _jsonable(payload.get("sale_price")),
        "list_price": _jsonable(payload.get("list_price")),
        "image_urls": payload.get("image_urls") or [],
        "bullet_points": payload.get("bullet_points") or [],
        "promo_label": payload.get("promo_label") or "",
    }, ensure_ascii=False, sort_keys=True, default=str)
    return hashlib.sha256(material.encode("utf-8")).hexdigest()


def diff_snapshots(previous: dict[str, Any], current: dict[str, Any]) -> list[dict[str, Any]]:
    changes: list[dict[str, Any]] = []
    prev_sale = previous.get("sale_price")
    curr_sale = current.get("sale_price")
    if _jsonable(prev_sale) != _jsonable(curr_sale):
        changes.append({
            "change_type": "price",
            "summary": f"售价 {prev_sale} → {curr_sale}",
            "before_value": prev_sale, "after_value": curr_sale,
        })
    if (previous.get("title") or "") != (current.get("title") or ""):
        changes.append({
            "change_type": "title",
            "summary": "Listing 标题已更新",
            "before_value": previous.get("title"), "after_value": current.get("title"),
        })
    if json.dumps(previous.get("image_urls") or [], sort_keys=True) != json.dumps(current.get("image_urls") or [], sort_keys=True):
        changes.append({
            "change_type": "image",
            "summary": "主图或图片组已更新",
            "before_value": previous.get("image_urls") or [],
            "after_value": current.get("image_urls") or [],
        })
    if json.dumps(previous.get("bullet_points") or [], sort_keys=True) != json.dumps(current.get("bullet_points") or [], sort_keys=True):
        changes.append({
            "change_type": "bullets",
            "summary": "五点描述已更新",
            "before_value": previous.get("bullet_points") or [],
            "after_value": current.get("bullet_points") or [],
        })
    if (previous.get("promo_label") or "") != (current.get("promo_label") or ""):
        changes.append({
            "change_type": "promo",
            "summary": f"促销 {previous.get('promo_label') or '无'} → {current.get('promo_label') or '无'}",
            "before_value": previous.get("promo_label"),
            "after_value": current.get("promo_label"),
        })
    return changes


class CompetitorTrackingService:
    async def ensure_schema(self, session: AsyncSession) -> None:
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS competitor_watch_targets (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              dataset_id BIGINT,
              platform VARCHAR(40) NOT NULL DEFAULT 'amazon',
              market_country CHAR(2) NOT NULL,
              asin VARCHAR(40) NOT NULL,
              title TEXT,
              status VARCHAR(20) NOT NULL DEFAULT 'active',
              created_by BIGINT,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT uk_watch_tenant_asin UNIQUE (tenant_id, platform, market_country, asin)
            )
        """))
        await session.execute(text("""
            ALTER TABLE competitor_watch_targets ADD COLUMN IF NOT EXISTS product_id BIGINT
        """))
        await session.execute(text("""
            ALTER TABLE competitor_watch_targets ADD COLUMN IF NOT EXISTS match_score NUMERIC(6,4)
        """))
        await session.execute(text("""
            ALTER TABLE competitor_watch_targets
              ADD COLUMN IF NOT EXISTS compare_selected BOOLEAN NOT NULL DEFAULT TRUE
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS competitor_listing_snapshots (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              dataset_id BIGINT,
              watch_id BIGINT,
              asin VARCHAR(40) NOT NULL,
              captured_at TIMESTAMPTZ(3) NOT NULL,
              source VARCHAR(40) NOT NULL DEFAULT 'dataset_import',
              title TEXT,
              sale_price NUMERIC(18,4),
              list_price NUMERIC(18,4),
              currency CHAR(3),
              rating NUMERIC(3,2),
              review_count INTEGER,
              image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
              bullet_points JSONB NOT NULL DEFAULT '[]'::jsonb,
              promo_label TEXT,
              first_available_date DATE,
              fingerprint VARCHAR(64) NOT NULL,
              raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_comp_snap_asin_time
              ON competitor_listing_snapshots(tenant_id, asin, captured_at DESC)
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS competitor_change_alerts (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              watch_id BIGINT,
              asin VARCHAR(40) NOT NULL,
              change_type VARCHAR(40) NOT NULL,
              summary TEXT NOT NULL,
              before_value JSONB,
              after_value JSONB,
              captured_at TIMESTAMPTZ(3) NOT NULL,
              is_read BOOLEAN NOT NULL DEFAULT FALSE,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_comp_alert_tenant_time
              ON competitor_change_alerts(tenant_id, created_at DESC)
        """))

    async def capture_dataset(self, session: AsyncSession, *, tenant_id: int, dataset_id: int,
                              source: str = "dataset_import") -> dict[str, int]:
        rows = (await session.execute(text("""
            SELECT l.platform_listing_id AS asin,l.title,l.sale_price,l.list_price,l.currency,l.rating,
                   l.review_count,l.image_urls,l.bullet_points,l.coupon_value,l.first_available_date,
                   l.captured_at,d.market_country,d.platform
              FROM market_listings l
              JOIN market_datasets d ON d.id=l.dataset_id AND d.tenant_id=l.tenant_id
             WHERE l.tenant_id=:tenant AND l.dataset_id=:dataset
        """), {"tenant": tenant_id, "dataset": dataset_id})).mappings().all()
        captured = 0
        alerts = 0
        for row in rows:
            payload = self._row_payload(dict(row))
            if source != "dataset_import":
                payload["captured_at"] = _now()
            alerts += await self._store_snapshot(
                session, tenant_id=tenant_id, dataset_id=dataset_id, source=source, payload=payload,
            )
            captured += 1
        return {"snapshot_rows": captured, "alerts": alerts}

    async def add_watch(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                        asin: str, market_country: str, platform: str, dataset_id: int | None,
                        product_id: int | None = None, match_score: float | None = None) -> dict[str, Any]:
        asin = asin.strip().upper()
        if not ASIN_PATTERN.match(asin):
            raise BusinessError("WATCH_ASIN_INVALID", "请填写有效的 ASIN / 商品编号", status_code=422)
        market_country = market_country.upper()
        listing = await self._find_listing(session, tenant_id=tenant_id, asin=asin,
                                           dataset_id=dataset_id, market_country=market_country)
        title = listing["title"] if listing else None
        if await self._is_own_listing(session, tenant_id=tenant_id, asin=asin, title=title):
            raise BusinessError("WATCH_OWN_PRODUCT", "这是本企业产品，不能加入市场竞品对比", status_code=422)
        bound_dataset = int(listing["dataset_id"]) if listing and listing.get("dataset_id") else dataset_id
        if listing:
            market_country = listing.get("market_country") or market_country
            platform = listing.get("platform") or platform
        bound_product = product_id
        if bound_product:
            product = await self._get_product(session, tenant_id=tenant_id, product_id=bound_product)
            if not product:
                raise BusinessError("PRODUCT_NOT_FOUND", "本企业产品不存在", status_code=404)
            if match_score is None and title:
                match_score = round(_text_similarity(product["name"], title), 4)
        existing = (await session.execute(text("""
            SELECT id FROM competitor_watch_targets
             WHERE tenant_id=:tenant AND platform=:platform AND market_country=:country AND asin=:asin
        """), {"tenant": tenant_id, "platform": platform, "country": market_country, "asin": asin})).scalar()
        if existing:
            watch_id = int(existing)
            await session.execute(text("""
                UPDATE competitor_watch_targets
                   SET status='active',dataset_id=COALESCE(:dataset,dataset_id),title=COALESCE(:title,title),
                       product_id=COALESCE(:product,product_id),match_score=COALESCE(:score,match_score),
                       compare_selected=TRUE,updated_at=CURRENT_TIMESTAMP
                 WHERE id=:id AND tenant_id=:tenant
            """), {"dataset": bound_dataset, "title": title, "product": bound_product, "score": match_score,
                   "id": watch_id, "tenant": tenant_id})
        else:
            watch_id = int(await session.scalar(text("""
                INSERT INTO competitor_watch_targets
                  (tenant_id,dataset_id,platform,market_country,asin,title,created_by,product_id,match_score,compare_selected)
                VALUES (:tenant,:dataset,:platform,:country,:asin,:title,:user,:product,:score,TRUE)
                RETURNING id
            """), {"tenant": tenant_id, "dataset": bound_dataset, "platform": platform,
                   "country": market_country, "asin": asin, "title": title, "user": user_id,
                   "product": bound_product, "score": match_score}))
        if listing:
            await self._store_snapshot(session, tenant_id=tenant_id, dataset_id=bound_dataset,
                                       source="watch_create", payload=self._row_payload(listing),
                                       watch_id=watch_id)
        return await self.get_watch(session, tenant_id=tenant_id, watch_id=watch_id)

    async def add_from_dataset(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                               dataset_id: int, limit: int = 8, product_id: int | None = None) -> list[dict[str, Any]]:
        dataset = (await session.execute(text("""
            SELECT id,platform,market_country FROM market_datasets
             WHERE id=:dataset AND tenant_id=:tenant AND deleted_at IS NULL
        """), {"dataset": dataset_id, "tenant": tenant_id})).mappings().one_or_none()
        if not dataset:
            raise BusinessError("DATASET_NOT_FOUND", "数据集不存在或不可访问", status_code=404)
        own_catalog = await self._own_catalog(session, tenant_id=tenant_id)
        rows = (await session.execute(text("""
            SELECT platform_listing_id AS asin, title FROM market_listings
             WHERE tenant_id=:tenant AND dataset_id=:dataset
             ORDER BY COALESCE(review_count,0) DESC, id DESC LIMIT :limit
        """), {"tenant": tenant_id, "dataset": dataset_id, "limit": max(1, min(limit * 4, 80))})).mappings().all()
        created = []
        for row in rows:
            asin = str(row["asin"] or "").upper()
            if self._listing_is_own(own_catalog, asin, row["title"]):
                continue
            created.append(await self.add_watch(
                session, tenant_id=tenant_id, user_id=user_id, asin=asin,
                market_country=dataset["market_country"], platform=dataset["platform"] or "amazon",
                dataset_id=dataset_id, product_id=product_id,
            ))
            if len(created) >= max(1, min(limit, 20)):
                break
        if not created:
            raise BusinessError("NO_MARKET_COMPETITORS", "该数据集里没有可对比的外部竞品（已排除本企业 SKU）", status_code=422)
        await self.capture_dataset(session, tenant_id=tenant_id, dataset_id=dataset_id, source="watch_seed")
        return created

    async def match_from_product(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                                 product_id: int, dataset_id: int | None = None, limit: int = 8) -> list[dict[str, Any]]:
        product = await self._get_product(session, tenant_id=tenant_id, product_id=product_id)
        if not product:
            raise BusinessError("PRODUCT_NOT_FOUND", "请先在产品中心选择一个本企业产品", status_code=404)
        own_catalog = await self._own_catalog(session, tenant_id=tenant_id)
        params: dict[str, Any] = {"tenant": tenant_id}
        extra = ""
        if dataset_id:
            extra = " AND l.dataset_id=:dataset"
            params["dataset"] = dataset_id
        rows = (await session.execute(text(f"""
            SELECT l.platform_listing_id AS asin,l.title,l.dataset_id,d.market_country,d.platform
              FROM market_listings l
              JOIN market_datasets d ON d.id=l.dataset_id AND d.tenant_id=l.tenant_id
             WHERE l.tenant_id=:tenant AND d.deleted_at IS NULL {extra}
             ORDER BY COALESCE(l.review_count,0) DESC, l.id DESC
             LIMIT 200
        """), params)).mappings().all()
        ranked = []
        for row in rows:
            asin = str(row["asin"] or "").upper()
            if self._listing_is_own(own_catalog, asin, row["title"]):
                continue
            score = _text_similarity(product["name"], row["title"] or "")
            ranked.append((score, dict(row), asin))
        ranked.sort(key=lambda item: item[0], reverse=True)
        created = []
        for score, row, asin in ranked:
            if score <= 0 and created:
                continue
            try:
                created.append(await self.add_watch(
                    session, tenant_id=tenant_id, user_id=user_id, asin=asin,
                    market_country=row.get("market_country") or "US",
                    platform=row.get("platform") or "amazon",
                    dataset_id=row.get("dataset_id"), product_id=product_id,
                    match_score=round(float(score), 4),
                ))
            except BusinessError as exc:
                if exc.code == "WATCH_OWN_PRODUCT":
                    continue
                raise
            if len(created) >= max(1, min(limit, 20)):
                break
        if not created:
            raise BusinessError(
                "NO_SIMILAR_COMPETITORS",
                "没有找到与该产品相似的市场 Listing。请粘贴竞品商品页网址，或先导入/采集市场数据。",
                status_code=422,
            )
        return created

    async def delete_watch(self, session: AsyncSession, *, tenant_id: int, watch_id: int) -> None:
        result = await session.execute(text("""
            UPDATE competitor_watch_targets SET status='archived',updated_at=CURRENT_TIMESTAMP
             WHERE id=:id AND tenant_id=:tenant AND status<>'archived'
        """), {"id": watch_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("WATCH_NOT_FOUND", "监控目标不存在", status_code=404)

    async def patch_watch(self, session: AsyncSession, *, tenant_id: int, watch_id: int,
                          compare_selected: bool | None = None, product_id: int | None = None) -> dict[str, Any]:
        current = (await session.execute(text("""
            SELECT id FROM competitor_watch_targets
             WHERE id=:id AND tenant_id=:tenant AND status='active'
        """), {"id": watch_id, "tenant": tenant_id})).scalar()
        if not current:
            raise BusinessError("WATCH_NOT_FOUND", "竞品库中不存在该商品", status_code=404)
        if product_id is not None:
            product = await self._get_product(session, tenant_id=tenant_id, product_id=product_id)
            if not product:
                raise BusinessError("PRODUCT_NOT_FOUND", "本企业产品不存在", status_code=404)
        if compare_selected is None and product_id is None:
            return await self.get_watch(session, tenant_id=tenant_id, watch_id=watch_id)
        await session.execute(text("""
            UPDATE competitor_watch_targets
               SET compare_selected=COALESCE(:selected, compare_selected),
                   product_id=COALESCE(:product, product_id),
                   updated_at=CURRENT_TIMESTAMP
             WHERE id=:id AND tenant_id=:tenant
        """), {"selected": compare_selected, "product": product_id, "id": watch_id, "tenant": tenant_id})
        return await self.get_watch(session, tenant_id=tenant_id, watch_id=watch_id)

    async def list_catalog(self, session: AsyncSession, *, tenant_id: int, offset: int, limit: int,
                           query: str | None = None, dataset_id: int | None = None,
                           market_country: str | None = None, exclude_watched: bool = False) -> tuple[list[dict[str, Any]], int]:
        catalog = await self._own_catalog(session, tenant_id=tenant_id)
        filters = ["l.tenant_id=:tenant", "d.deleted_at IS NULL", "d.status='ready'"]
        params: dict[str, Any] = {"tenant": tenant_id}
        if dataset_id:
            filters.append("l.dataset_id=:dataset")
            params["dataset"] = dataset_id
        if market_country:
            filters.append("d.market_country=:country")
            params["country"] = market_country.upper()
        if query:
            filters.append("(l.title ILIKE :query OR l.platform_listing_id ILIKE :query OR COALESCE(l.brand,'') ILIKE :query)")
            params["query"] = f"%{query.strip()}%"
        if exclude_watched:
            filters.append("w.id IS NULL")
        where = " AND ".join(filters)
        join = """
            FROM market_listings l
            JOIN market_datasets d ON d.id=l.dataset_id AND d.tenant_id=l.tenant_id
            LEFT JOIN competitor_watch_targets w
              ON w.tenant_id=l.tenant_id AND w.status='active'
             AND w.asin=upper(l.platform_listing_id)
             AND w.platform=COALESCE(d.platform,'amazon')
             AND w.market_country=d.market_country
        """
        rows = (await session.execute(text(f"""
            SELECT l.id AS listing_id,l.dataset_id,d.name AS dataset_name,upper(l.platform_listing_id) AS asin,
                   l.title,l.brand,COALESCE(l.category_code,d.category_code) AS category_code,
                   l.sale_price,l.currency,l.rating,l.review_count,d.market_country,d.platform,
                   w.id AS watch_id
              {join}
             WHERE {where}
             ORDER BY COALESCE(l.review_count,0) DESC, l.captured_at DESC, l.id DESC
             LIMIT 400
        """), params)).mappings().all()
        items = []
        for row in rows:
            payload = dict(row)
            if self._listing_is_own(catalog, payload.get("asin"), payload.get("title")):
                continue
            payload["watched"] = payload.get("watch_id") is not None
            payload["sale_price"] = _jsonable(payload.get("sale_price"))
            payload["rating"] = _jsonable(payload.get("rating"))
            items.append(payload)
        total = len(items)
        return items[offset:offset + limit], total

    async def archive_own_product_watches(self, session: AsyncSession, *, tenant_id: int) -> None:
        catalog = await self._own_catalog(session, tenant_id=tenant_id)
        rows = (await session.execute(text("""
            SELECT id, asin, title FROM competitor_watch_targets
             WHERE tenant_id=:tenant AND status='active'
        """), {"tenant": tenant_id})).mappings().all()
        ids = [int(row["id"]) for row in rows if self._listing_is_own(catalog, row["asin"], row["title"])]
        if ids:
            for watch_id in ids:
                await session.execute(text("""
                    UPDATE competitor_watch_targets
                       SET status='archived', updated_at=CURRENT_TIMESTAMP
                     WHERE tenant_id=:tenant AND id=:id
                """), {"tenant": tenant_id, "id": watch_id})

    async def refresh(self, session: AsyncSession, *, tenant_id: int) -> dict[str, int]:
        datasets = (await session.execute(text("""
            SELECT DISTINCT dataset_id FROM competitor_watch_targets
             WHERE tenant_id=:tenant AND status='active' AND dataset_id IS NOT NULL
        """), {"tenant": tenant_id})).scalars().all()
        totals = {"snapshot_rows": 0, "alerts": 0}
        for dataset_id in datasets:
            result = await self.capture_dataset(
                session, tenant_id=tenant_id, dataset_id=int(dataset_id), source="manual_refresh",
            )
            totals["snapshot_rows"] += result["snapshot_rows"]
            totals["alerts"] += result["alerts"]
        watches = (await session.execute(text("""
            SELECT id,asin,dataset_id,market_country FROM competitor_watch_targets
             WHERE tenant_id=:tenant AND status='active'
        """), {"tenant": tenant_id})).mappings().all()
        for watch in watches:
            listing = await self._find_listing(
                session, tenant_id=tenant_id, asin=watch["asin"],
                dataset_id=watch["dataset_id"], market_country=watch["market_country"],
            )
            if listing:
                totals["alerts"] += await self._store_snapshot(
                    session, tenant_id=tenant_id, dataset_id=listing.get("dataset_id"),
                    source="manual_refresh", payload={**self._row_payload(listing), "captured_at": _now()},
                    watch_id=watch["id"],
                )
        return totals

    async def overview(self, session: AsyncSession, *, tenant_id: int, product_id: int | None = None) -> dict[str, Any]:
        await self.archive_own_product_watches(session, tenant_id=tenant_id)
        watches = await self.list_watches(session, tenant_id=tenant_id, product_id=product_id)
        alerts = await self.list_alerts(session, tenant_id=tenant_id, limit=20)
        unread = int(await session.scalar(text("""
            SELECT count(*) FROM competitor_change_alerts a
              JOIN competitor_watch_targets w ON w.id=a.watch_id
             WHERE a.tenant_id=:tenant AND w.status='active' AND a.is_read=FALSE
        """), {"tenant": tenant_id}) or 0)
        selected = [item for item in watches if item.get("compare_selected")]
        primary = (selected or watches)[0]["watch_id"] if watches else None
        prices = await self.price_series(session, tenant_id=tenant_id, watch_id=primary) if primary else []
        snapshots = await self.list_snapshots(session, tenant_id=tenant_id, watch_id=primary) if primary else []
        return {
            "watch_count": len(watches),
            "unread_alerts": unread,
            "watches": watches,
            "alerts": alerts,
            "rhythm": await self.rhythm(session, tenant_id=tenant_id),
            "selected_watch_id": primary,
            "price_series": prices,
            "snapshots": snapshots,
        }

    async def list_watches(self, session: AsyncSession, *, tenant_id: int,
                           product_id: int | None = None) -> list[dict[str, Any]]:
        params: dict[str, Any] = {"tenant": tenant_id}
        extra = ""
        if product_id:
            extra = " AND (w.product_id=:product OR w.product_id IS NULL)"
            params["product"] = product_id
        rows = (await session.execute(text(f"""
            SELECT w.id AS watch_id,w.asin,COALESCE(w.title, latest.title) AS title,w.platform,w.market_country,w.dataset_id,w.status,
                   w.product_id,w.match_score,COALESCE(w.compare_selected, TRUE) AS compare_selected,w.created_at,w.updated_at,
                   p.sku AS product_sku,p.name AS product_name,
                   COALESCE(listing.category_code, dataset.category_code) AS category_code,
                   latest.sale_price,latest.list_price,latest.currency,latest.promo_label,latest.captured_at,
                   latest.rating,latest.review_count,prev.sale_price AS previous_price
              FROM competitor_watch_targets w
              LEFT JOIN products p ON p.id=w.product_id AND p.tenant_id=w.tenant_id AND p.deleted_at IS NULL
              LEFT JOIN market_datasets dataset ON dataset.id=w.dataset_id AND dataset.tenant_id=w.tenant_id
              LEFT JOIN LATERAL (
                SELECT category_code FROM market_listings l
                 WHERE l.tenant_id=w.tenant_id AND upper(l.platform_listing_id)=w.asin
                 ORDER BY l.captured_at DESC,l.id DESC LIMIT 1
              ) listing ON true
              LEFT JOIN LATERAL (
                SELECT sale_price,list_price,currency,promo_label,captured_at,rating,review_count,title
                  FROM competitor_listing_snapshots s
                 WHERE s.tenant_id=w.tenant_id AND s.asin=w.asin
                 ORDER BY s.captured_at DESC,s.id DESC LIMIT 1
              ) latest ON true
              LEFT JOIN LATERAL (
                SELECT sale_price FROM competitor_listing_snapshots s
                 WHERE s.tenant_id=w.tenant_id AND s.asin=w.asin
                 ORDER BY s.captured_at DESC,s.id DESC OFFSET 1 LIMIT 1
              ) prev ON true
             WHERE w.tenant_id=:tenant AND w.status='active' {extra}
             ORDER BY COALESCE(w.compare_selected, TRUE) DESC, COALESCE(w.match_score,0) DESC, w.updated_at DESC, w.id DESC
        """), params)).mappings().all()
        catalog = await self._own_catalog(session, tenant_id=tenant_id)
        items = []
        for row in rows:
            item = {key: _jsonable(value) if not isinstance(value, (dict, list)) else value for key, value in dict(row).items()}
            if self._listing_is_own(catalog, item.get("asin"), item.get("title")):
                continue
            curr = item.get("sale_price")
            prev = item.get("previous_price")
            item["price_delta"] = None if curr is None or prev is None else round(float(curr) - float(prev), 2)
            if item.get("match_score") is not None:
                item["match_score"] = float(item["match_score"])
            item["compare_selected"] = bool(item.get("compare_selected", True))
            items.append(item)
        return items

    async def get_watch(self, session: AsyncSession, *, tenant_id: int, watch_id: int) -> dict[str, Any]:
        items = await self.list_watches(session, tenant_id=tenant_id)
        for item in items:
            if item["watch_id"] == watch_id:
                return item
        raise BusinessError("WATCH_NOT_FOUND", "监控目标不存在", status_code=404)

    async def price_series(self, session: AsyncSession, *, tenant_id: int, watch_id: int) -> list[dict[str, Any]]:
        watch = (await session.execute(text("""
            SELECT asin FROM competitor_watch_targets WHERE id=:id AND tenant_id=:tenant AND status='active'
        """), {"id": watch_id, "tenant": tenant_id})).scalar()
        if not watch:
            raise BusinessError("WATCH_NOT_FOUND", "监控目标不存在", status_code=404)
        rows = (await session.execute(text("""
            SELECT captured_at,sale_price,list_price,currency,promo_label
              FROM competitor_listing_snapshots
             WHERE tenant_id=:tenant AND asin=:asin
             ORDER BY captured_at ASC,id ASC
        """), {"tenant": tenant_id, "asin": watch})).mappings().all()
        return [{key: _jsonable(value) for key, value in dict(row).items()} for row in rows]

    async def list_snapshots(self, session: AsyncSession, *, tenant_id: int, watch_id: int) -> list[dict[str, Any]]:
        watch = (await session.execute(text("""
            SELECT asin FROM competitor_watch_targets WHERE id=:id AND tenant_id=:tenant AND status='active'
        """), {"id": watch_id, "tenant": tenant_id})).scalar()
        if not watch:
            raise BusinessError("WATCH_NOT_FOUND", "监控目标不存在", status_code=404)
        rows = (await session.execute(text("""
            SELECT id AS snapshot_id,captured_at,source,title,sale_price,list_price,currency,rating,
                   review_count,image_urls,bullet_points,promo_label,first_available_date,fingerprint
              FROM competitor_listing_snapshots
             WHERE tenant_id=:tenant AND asin=:asin
             ORDER BY captured_at DESC,id DESC LIMIT 40
        """), {"tenant": tenant_id, "asin": watch})).mappings().all()
        return [{key: _jsonable(value) if key not in {"image_urls", "bullet_points"} else (value or [])
                 for key, value in dict(row).items()} for row in rows]

    async def list_alerts(self, session: AsyncSession, *, tenant_id: int, limit: int = 50,
                          unread_only: bool = False) -> list[dict[str, Any]]:
        filters = "a.tenant_id=:tenant AND w.status='active'"
        if unread_only:
            filters += " AND a.is_read=FALSE"
        rows = (await session.execute(text(f"""
            SELECT a.id AS alert_id,a.watch_id,a.asin,a.change_type,a.summary,a.before_value,a.after_value,
                   a.captured_at,a.is_read,w.title
              FROM competitor_change_alerts a
              JOIN competitor_watch_targets w ON w.id=a.watch_id
             WHERE {filters}
             ORDER BY a.captured_at DESC,a.id DESC LIMIT :limit
        """), {"tenant": tenant_id, "limit": limit})).mappings().all()
        items = []
        for row in rows:
            item = {key: _jsonable(value) if key not in {"before_value", "after_value"} else value
                    for key, value in dict(row).items()}
            item["change_label"] = CHANGE_LABELS.get(item["change_type"], item["change_type"])
            items.append(item)
        return items

    async def mark_alert_read(self, session: AsyncSession, *, tenant_id: int, alert_id: int) -> None:
        result = await session.execute(text("""
            UPDATE competitor_change_alerts SET is_read=TRUE
             WHERE id=:id AND tenant_id=:tenant
        """), {"id": alert_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("ALERT_NOT_FOUND", "告警不存在", status_code=404)

    async def rhythm(self, session: AsyncSession, *, tenant_id: int) -> dict[str, Any]:
        dataset_ids = (await session.execute(text("""
            SELECT DISTINCT dataset_id FROM competitor_watch_targets
             WHERE tenant_id=:tenant AND status='active' AND dataset_id IS NOT NULL
        """), {"tenant": tenant_id})).scalars().all()
        if not dataset_ids:
            ready = (await session.execute(text("""
                SELECT id FROM market_datasets
                 WHERE tenant_id=:tenant AND deleted_at IS NULL AND status='ready'
                 ORDER BY updated_at DESC LIMIT 1
            """), {"tenant": tenant_id})).scalar()
            dataset_ids = [ready] if ready else []
        if not dataset_ids:
            return {"launches": [], "promos": []}
        launches = (await session.execute(text("""
            SELECT to_char(date_trunc('month', COALESCE(first_available_date, captured_at::date)), 'YYYY-MM') AS month,
                   count(*) AS listing_count
              FROM market_listings
             WHERE tenant_id=:tenant AND dataset_id = ANY(CAST(:datasets AS bigint[]))
             GROUP BY 1 ORDER BY 1 DESC LIMIT 12
        """), {"tenant": tenant_id, "datasets": list(dataset_ids)})).mappings().all()
        promos = (await session.execute(text("""
            SELECT to_char(date_trunc('month', captured_at), 'YYYY-MM') AS month,
                   count(*) FILTER (WHERE list_price IS NOT NULL AND list_price > sale_price) AS promo_count,
                   count(*) AS listing_count
              FROM market_listings
             WHERE tenant_id=:tenant AND dataset_id = ANY(CAST(:datasets AS bigint[]))
             GROUP BY 1 ORDER BY 1 DESC LIMIT 12
        """), {"tenant": tenant_id, "datasets": list(dataset_ids)})).mappings().all()
        return {
            "launches": [dict(row) for row in launches],
            "promos": [dict(row) for row in promos],
        }

    def _row_payload(self, row: dict[str, Any]) -> dict[str, Any]:
        images = row.get("image_urls") or []
        bullets = row.get("bullet_points") or []
        if isinstance(images, str):
            images = json.loads(images)
        if isinstance(bullets, str):
            bullets = json.loads(bullets)
        payload = {
            "asin": str(row.get("asin") or row.get("platform_listing_id") or "").upper(),
            "title": row.get("title"),
            "sale_price": row.get("sale_price"),
            "list_price": row.get("list_price"),
            "currency": row.get("currency"),
            "rating": row.get("rating"),
            "review_count": row.get("review_count"),
            "image_urls": images,
            "bullet_points": bullets,
            "promo_label": promo_label(row.get("sale_price"), row.get("list_price"), row.get("coupon_value")),
            "first_available_date": row.get("first_available_date"),
            "captured_at": row.get("captured_at") or _now(),
            "market_country": row.get("market_country"),
            "platform": row.get("platform"),
            "dataset_id": row.get("dataset_id"),
        }
        payload["fingerprint"] = listing_fingerprint(payload)
        return payload

    async def _find_listing(self, session: AsyncSession, *, tenant_id: int, asin: str,
                            dataset_id: int | None, market_country: str | None) -> dict[str, Any] | None:
        params: dict[str, Any] = {"tenant": tenant_id, "asin": asin}
        extra = ""
        if dataset_id:
            extra += " AND l.dataset_id=:dataset"
            params["dataset"] = dataset_id
        if market_country:
            extra += " AND d.market_country=:country"
            params["country"] = market_country
        row = (await session.execute(text(f"""
            SELECT l.platform_listing_id AS asin,l.title,l.sale_price,l.list_price,l.currency,l.rating,
                   l.review_count,l.image_urls,l.bullet_points,l.coupon_value,l.first_available_date,
                   l.captured_at,l.dataset_id,d.market_country,d.platform
              FROM market_listings l
              JOIN market_datasets d ON d.id=l.dataset_id AND d.tenant_id=l.tenant_id
             WHERE l.tenant_id=:tenant AND upper(l.platform_listing_id)=:asin {extra}
               AND d.deleted_at IS NULL
             ORDER BY l.captured_at DESC,l.id DESC LIMIT 1
        """), params)).mappings().one_or_none()
        return dict(row) if row else None

    async def _own_catalog(self, session: AsyncSession, *, tenant_id: int) -> list[dict[str, Any]]:
        rows = (await session.execute(text("""
            SELECT sku, name FROM products WHERE tenant_id=:tenant AND deleted_at IS NULL
        """), {"tenant": tenant_id})).mappings().all()
        return [dict(row) for row in rows]

    def _listing_is_own(self, catalog: list[dict[str, Any]], asin: Any, title: Any) -> bool:
        listing_id = str(asin or "").strip().upper()
        if not listing_id:
            return False
        for product in catalog:
            sku = str(product.get("sku") or "").strip().upper()
            if sku and listing_id == sku:
                return True
        return False

    async def _is_own_listing(self, session: AsyncSession, *, tenant_id: int, asin: str,
                              title: str | None) -> bool:
        catalog = await self._own_catalog(session, tenant_id=tenant_id)
        return self._listing_is_own(catalog, asin, title)

    async def _get_product(self, session: AsyncSession, *, tenant_id: int, product_id: int) -> dict[str, Any] | None:
        row = (await session.execute(text("""
            SELECT id AS product_id,sku,name,category_code
              FROM products
             WHERE id=:id AND tenant_id=:tenant AND deleted_at IS NULL
        """), {"id": product_id, "tenant": tenant_id})).mappings().one_or_none()
        return dict(row) if row else None

    async def _store_snapshot(self, session: AsyncSession, *, tenant_id: int, dataset_id: int | None,
                              source: str, payload: dict[str, Any], watch_id: int | None = None) -> int:
        asin = payload["asin"]
        last = (await session.execute(text("""
            SELECT fingerprint,sale_price,list_price,title,image_urls,bullet_points,promo_label
              FROM competitor_listing_snapshots
             WHERE tenant_id=:tenant AND asin=:asin
             ORDER BY captured_at DESC,id DESC LIMIT 1
        """), {"tenant": tenant_id, "asin": asin})).mappings().one_or_none()
        fingerprint = payload["fingerprint"]
        if last and last["fingerprint"] == fingerprint:
            return 0
        if watch_id is None:
            watch_id = await session.scalar(text("""
                SELECT id FROM competitor_watch_targets
                 WHERE tenant_id=:tenant AND asin=:asin AND status='active'
                 ORDER BY id DESC LIMIT 1
            """), {"tenant": tenant_id, "asin": asin})
        captured_at = payload.get("captured_at") or _now()
        if isinstance(captured_at, str):
            captured_at = datetime.fromisoformat(captured_at.replace("Z", "+00:00"))
        await session.execute(text("""
            INSERT INTO competitor_listing_snapshots
              (tenant_id,dataset_id,watch_id,asin,captured_at,source,title,sale_price,list_price,currency,
               rating,review_count,image_urls,bullet_points,promo_label,first_available_date,fingerprint,raw_payload)
            VALUES (:tenant,:dataset,:watch,:asin,:captured,:source,:title,:sale,:listed,:currency,:rating,
                    :reviews,CAST(:images AS jsonb),CAST(:bullets AS jsonb),:promo,:available,:fingerprint,
                    CAST(:raw AS jsonb))
        """), {
            "tenant": tenant_id, "dataset": dataset_id, "watch": watch_id, "asin": asin,
            "captured": captured_at, "source": source, "title": payload.get("title"),
            "sale": payload.get("sale_price"), "listed": payload.get("list_price"),
            "currency": payload.get("currency"), "rating": payload.get("rating"),
            "reviews": payload.get("review_count"),
            "images": json.dumps(payload.get("image_urls") or [], ensure_ascii=False),
            "bullets": json.dumps(payload.get("bullet_points") or [], ensure_ascii=False),
            "promo": payload.get("promo_label"), "available": payload.get("first_available_date"),
            "fingerprint": fingerprint,
            "raw": json.dumps({k: _jsonable(v) for k, v in payload.items() if k != "fingerprint"},
                              ensure_ascii=False, default=str),
        })
        if not last or not watch_id:
            if watch_id and not last:
                await session.execute(text("""
                    INSERT INTO competitor_change_alerts
                      (tenant_id,watch_id,asin,change_type,summary,after_value,captured_at)
                    VALUES (:tenant,:watch,:asin,'new_listing',:summary,CAST(:after AS jsonb),:captured)
                """), {"tenant": tenant_id, "watch": watch_id, "asin": asin,
                       "summary": f"开始监控 {asin}", "after": json.dumps({"title": payload.get("title")}),
                       "captured": captured_at})
                await queue_alert_notifications(
                    session, tenant_id=tenant_id, event_type="competitor_alert",
                    title=f"竞品监控上新：{asin}",
                    content=f"开始监控 {asin}：{payload.get('title') or '未命名商品'}",
                    payload={"asin": asin, "watch_id": watch_id, "change_type": "new_listing", "source": source},
                )
                return 1
            return 0
        created = 0
        for change in diff_snapshots(dict(last), payload):
            await session.execute(text("""
                INSERT INTO competitor_change_alerts
                  (tenant_id,watch_id,asin,change_type,summary,before_value,after_value,captured_at)
                VALUES (:tenant,:watch,:asin,:type,:summary,CAST(:before AS jsonb),CAST(:after AS jsonb),:captured)
            """), {"tenant": tenant_id, "watch": watch_id, "asin": asin, "type": change["change_type"],
                   "summary": change["summary"],
                   "before": json.dumps(change["before_value"], ensure_ascii=False, default=str),
                   "after": json.dumps(change["after_value"], ensure_ascii=False, default=str),
                   "captured": captured_at})
            await queue_alert_notifications(
                session, tenant_id=tenant_id, event_type="competitor_alert",
                title=f"竞品变动：{asin}",
                content=change["summary"],
                payload={"asin": asin, "watch_id": watch_id, "source": source, **change},
            )
            created += 1
        return created
