"""Outbound alert notifications through explicit webhook channels."""

from __future__ import annotations

import asyncio
import base64
from datetime import datetime, timezone
import hashlib
import hmac
import ipaddress
import json
import os
import socket
from typing import Any
from urllib.parse import quote, urlencode, urlparse, urlunparse
from urllib.request import Request, urlopen

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from ..errors import BusinessError

MAX_NOTIFICATION_BYTES = 65_536
CHANNEL_TYPES = {"webhook", "dingtalk", "slack", "email_gateway", "sms_gateway"}
ALERT_EVENT_TYPES = {"competitor_alert", "policy_alert", "test"}


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _safe_error(exc: Exception) -> str:
    if isinstance(exc, BusinessError):
        return exc.message[:300]
    return type(exc).__name__[:120]


class NotificationService:
    def __init__(self, settings: Any | None = None) -> None:
        self.settings = settings

    async def ensure_schema(self, session: AsyncSession) -> None:
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS notification_channels (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              name VARCHAR(200) NOT NULL,
              channel_type VARCHAR(40) NOT NULL,
              target_url TEXT NOT NULL,
              secret_env VARCHAR(128),
              events JSONB NOT NULL DEFAULT '[]'::jsonb,
              enabled BOOLEAN NOT NULL DEFAULT TRUE,
              created_by BIGINT,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_notification_channel_type CHECK (channel_type IN ('webhook','dingtalk','slack','email_gateway','sms_gateway')),
              CONSTRAINT uk_notification_channel_url UNIQUE (tenant_id, target_url)
            )
        """))
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS notification_events (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              channel_id BIGINT NOT NULL REFERENCES notification_channels(id) ON DELETE CASCADE,
              event_type VARCHAR(40) NOT NULL,
              title TEXT NOT NULL,
              content TEXT NOT NULL,
              payload JSONB NOT NULL DEFAULT '{}'::jsonb,
              status VARCHAR(20) NOT NULL DEFAULT 'pending',
              attempts INTEGER NOT NULL DEFAULT 0,
              last_error TEXT,
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              delivered_at TIMESTAMPTZ(3),
              CONSTRAINT chk_notification_event_type CHECK (event_type IN ('competitor_alert','policy_alert','test')),
              CONSTRAINT chk_notification_event_status CHECK (status IN ('pending','delivered','failed'))
            )
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_notification_events_pending
              ON notification_events(status, created_at) WHERE status='pending'
        """))

    def _validate_target_url(self, raw_url: str) -> str:
        parsed = urlparse(raw_url.strip())
        allow_http = getattr(self.settings, "app_env", "development") != "production"
        if parsed.scheme not in ({"https", "http"} if allow_http else {"https"}):
            raise BusinessError("NOTIFICATION_URL_INVALID", "通知地址必须使用 HTTPS Webhook", status_code=422)
        if parsed.username or parsed.password or not parsed.hostname:
            raise BusinessError("NOTIFICATION_URL_INVALID", "通知地址不允许携带账号密码且必须包含主机名", status_code=422)
        try:
            literal_ip = ipaddress.ip_address(parsed.hostname)
        except ValueError:
            literal_ip = None
        if literal_ip and (literal_ip.is_private or literal_ip.is_loopback or literal_ip.is_link_local
                           or literal_ip.is_reserved or literal_ip.is_multicast or literal_ip.is_unspecified):
            raise BusinessError("NOTIFICATION_URL_FORBIDDEN", "不允许向内网或保留地址发送通知", status_code=422)
        return urlunparse(parsed._replace(fragment=""))

    def _assert_send_allowed(self, raw_url: str) -> None:
        parsed = urlparse(raw_url)
        host = (parsed.hostname or "").lower()
        if host in {"localhost", "localhost."}:
            raise BusinessError("NOTIFICATION_URL_FORBIDDEN", "不允许向本机地址发送通知", status_code=422)
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        try:
            infos = socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
        except socket.gaierror as exc:
            raise BusinessError("NOTIFICATION_URL_UNREACHABLE", "通知地址域名无法解析", status_code=422) from exc
        for info in infos:
            ip = ipaddress.ip_address(info[4][0])
            if (ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved
                    or ip.is_multicast or ip.is_unspecified):
                raise BusinessError("NOTIFICATION_URL_FORBIDDEN", "通知地址解析到内网或保留地址", status_code=422)

    async def create_channel(self, session: AsyncSession, *, tenant_id: int, user_id: int,
                             payload: dict[str, Any]) -> dict[str, Any]:
        target_url = self._validate_target_url(payload["target_url"])
        events = payload.get("events") or ["competitor_alert", "policy_alert"]
        channel_id = int(await session.scalar(text("""
            INSERT INTO notification_channels
              (tenant_id,name,channel_type,target_url,secret_env,events,enabled,created_by)
            VALUES (:tenant,:name,:type,:url,:secret,CAST(:events AS jsonb),:enabled,:user)
            RETURNING id
        """), {
            "tenant": tenant_id, "name": payload["name"], "type": payload["channel_type"],
            "url": target_url, "secret": payload.get("secret_env"),
            "events": json.dumps(events, ensure_ascii=False), "enabled": payload.get("enabled", True),
            "user": user_id,
        }))
        return await self.get_channel(session, tenant_id=tenant_id, channel_id=channel_id)

    async def get_channel(self, session: AsyncSession, *, tenant_id: int, channel_id: int) -> dict[str, Any]:
        row = (await session.execute(text("""
            SELECT id AS channel_id,name,channel_type,target_url,secret_env,events,enabled,created_at
              FROM notification_channels WHERE id=:id AND tenant_id=:tenant
        """), {"id": channel_id, "tenant": tenant_id})).mappings().one_or_none()
        if not row:
            raise BusinessError("NOTIFICATION_CHANNEL_NOT_FOUND", "通知渠道不存在或不可访问", status_code=404)
        item = dict(row)
        item["events"] = item.get("events") or []
        return item

    async def list_channels(self, session: AsyncSession, *, tenant_id: int) -> list[dict[str, Any]]:
        rows = (await session.execute(text("""
            SELECT id AS channel_id,name,channel_type,target_url,secret_env,events,enabled,created_at
              FROM notification_channels WHERE tenant_id=:tenant ORDER BY created_at DESC,id DESC
        """), {"tenant": tenant_id})).mappings().all()
        items = []
        for row in rows:
            item = dict(row)
            item["events"] = item.get("events") or []
            items.append(item)
        return items

    async def update_channel(self, session: AsyncSession, *, tenant_id: int, channel_id: int,
                             payload: dict[str, Any]) -> dict[str, Any]:
        current = await self.get_channel(session, tenant_id=tenant_id, channel_id=channel_id)
        enabled = current["enabled"] if payload.get("enabled") is None else bool(payload["enabled"])
        await session.execute(text("""
            UPDATE notification_channels SET enabled=:enabled WHERE id=:id AND tenant_id=:tenant
        """), {"enabled": enabled, "id": channel_id, "tenant": tenant_id})
        return await self.get_channel(session, tenant_id=tenant_id, channel_id=channel_id)

    async def delete_channel(self, session: AsyncSession, *, tenant_id: int, channel_id: int) -> None:
        result = await session.execute(text("""
            DELETE FROM notification_channels WHERE id=:id AND tenant_id=:tenant
        """), {"id": channel_id, "tenant": tenant_id})
        if not result.rowcount:
            raise BusinessError("NOTIFICATION_CHANNEL_NOT_FOUND", "通知渠道不存在或不可访问", status_code=404)

    async def queue_alert(self, session: AsyncSession, *, tenant_id: int, event_type: str,
                          title: str, content: str, payload: dict[str, Any] | None = None) -> int:
        channels = (await session.execute(text("""
            SELECT id FROM notification_channels
             WHERE tenant_id=:tenant AND enabled=TRUE
               AND (jsonb_array_length(events)=0 OR events @> CAST(:event AS jsonb))
        """), {"tenant": tenant_id, "event": json.dumps([event_type])})).scalars().all()
        queued = 0
        for channel_id in channels:
            await session.execute(text("""
                INSERT INTO notification_events(tenant_id,channel_id,event_type,title,content,payload)
                VALUES (:tenant,:channel,:type,:title,:content,CAST(:payload AS jsonb))
            """), {
                "tenant": tenant_id, "channel": int(channel_id), "type": event_type,
                "title": title[:500], "content": content[:4000],
                "payload": json.dumps(payload or {}, ensure_ascii=False, default=str),
            })
            queued += 1
        return queued

    async def queue_test(self, session: AsyncSession, *, tenant_id: int, channel_id: int) -> dict[str, Any]:
        channel = await self.get_channel(session, tenant_id=tenant_id, channel_id=channel_id)
        event_id = int(await session.scalar(text("""
            INSERT INTO notification_events(tenant_id,channel_id,event_type,title,content,payload)
            VALUES (:tenant,:channel,'test',:title,:content,'{}'::jsonb) RETURNING id
        """), {"tenant": tenant_id, "channel": channel_id,
               "title": f"FurniScope 通知测试：{channel['name']}",
               "content": "这是一条用于验证通知渠道连通性的测试消息。"}))
        return {"event_id": event_id, "channel_id": channel_id, "status": "pending"}

    async def list_events(self, session: AsyncSession, *, tenant_id: int, limit: int = 50) -> list[dict[str, Any]]:
        rows = (await session.execute(text("""
            SELECT e.id AS event_id,e.channel_id,e.event_type,e.title,e.content,e.status,e.attempts,
                   e.last_error,e.created_at,e.delivered_at,c.name AS channel_name,c.channel_type
              FROM notification_events e
              JOIN notification_channels c ON c.id=e.channel_id AND c.tenant_id=e.tenant_id
             WHERE e.tenant_id=:tenant ORDER BY e.created_at DESC,e.id DESC LIMIT :limit
        """), {"tenant": tenant_id, "limit": limit})).mappings().all()
        return [dict(row) for row in rows]

    def _signed_url(self, channel: dict[str, Any]) -> str:
        if channel["channel_type"] != "dingtalk" or not channel.get("secret_env"):
            return channel["target_url"]
        secret = os.getenv(channel["secret_env"])
        if not secret:
            return channel["target_url"]
        timestamp = str(int(_now().timestamp() * 1000))
        sign = quote(base64.b64encode(hmac.new(
            secret.encode("utf-8"), f"{timestamp}\n{secret}".encode("utf-8"), hashlib.sha256,
        ).digest()).decode("utf-8"))
        separator = "&" if urlparse(channel["target_url"]).query else "?"
        return f"{channel['target_url']}{separator}{urlencode({'timestamp': timestamp, 'sign': sign})}"

    def _payload(self, channel: dict[str, Any], event: dict[str, Any]) -> bytes:
        text_body = f"{event['title']}\n\n{event['content']}"
        if channel["channel_type"] == "dingtalk":
            body = {"msgtype": "markdown", "markdown": {"title": event["title"][:100], "text": text_body}}
        elif channel["channel_type"] == "slack":
            body = {"text": text_body}
        elif channel["channel_type"] == "email_gateway":
            body = {"subject": event["title"], "text": event["content"],
                    "event_type": event["event_type"], "data": event.get("payload") or {}}
        elif channel["channel_type"] == "sms_gateway":
            body = {"message": text_body[:1000], "event_type": event["event_type"],
                    "data": event.get("payload") or {}}
        else:
            body = {"event_type": event["event_type"], "title": event["title"],
                    "content": event["content"], "payload": event.get("payload") or {}}
        return json.dumps(body, ensure_ascii=False).encode("utf-8")

    def _post(self, channel: dict[str, Any], event: dict[str, Any]) -> None:
        url = self._signed_url(channel)
        self._assert_send_allowed(url)
        request = Request(url, data=self._payload(channel, event), method="POST", headers={
            "Content-Type": "application/json; charset=utf-8",
            "User-Agent": "FurniScope-Notification/0.1",
        })
        with urlopen(request, timeout=10) as response:  # noqa: S310 - target URL/IP are validated first.
            response.read(MAX_NOTIFICATION_BYTES)

    async def deliver_pending(self, session: AsyncSession, *, limit: int = 20) -> dict[str, int]:
        rows = (await session.execute(text("""
            SELECT e.id AS event_id,e.tenant_id,e.event_type,e.title,e.content,e.payload,e.attempts,
                   c.id AS channel_id,c.name,c.channel_type,c.target_url,c.secret_env
              FROM notification_events e
              JOIN notification_channels c ON c.id=e.channel_id AND c.tenant_id=e.tenant_id
             WHERE e.status='pending' AND e.attempts<5 AND c.enabled=TRUE
             ORDER BY e.created_at ASC,e.id ASC LIMIT :limit
             FOR UPDATE OF e SKIP LOCKED
        """), {"limit": limit})).mappings().all()
        delivered = failed = 0
        for row in rows:
            event = dict(row)
            channel = dict(row)
            try:
                await asyncio.to_thread(self._post, channel, event)
            except Exception as exc:
                attempts = int(event["attempts"] or 0) + 1
                await session.execute(text("""
                    UPDATE notification_events
                       SET attempts=:attempts,status=:status,last_error=:error
                     WHERE id=:id AND tenant_id=:tenant
                """), {"attempts": attempts, "status": "failed" if attempts >= 5 else "pending",
                       "error": _safe_error(exc), "id": event["event_id"], "tenant": event["tenant_id"]})
                failed += 1
            else:
                await session.execute(text("""
                    UPDATE notification_events
                       SET status='delivered',attempts=attempts+1,last_error=NULL,delivered_at=CURRENT_TIMESTAMP
                     WHERE id=:id AND tenant_id=:tenant
                """), {"id": event["event_id"], "tenant": event["tenant_id"]})
                delivered += 1
        return {"delivered": delivered, "failed": failed, "picked": len(rows)}


async def queue_alert_notifications(session: AsyncSession, *, tenant_id: int, event_type: str,
                                    title: str, content: str,
                                    payload: dict[str, Any] | None = None) -> int:
    return await NotificationService().queue_alert(
        session, tenant_id=tenant_id, event_type=event_type, title=title, content=content, payload=payload,
    )
