"""Self-service password reset for enterprise users."""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from ..errors import BusinessError
from ..repositories.auth_repository import AuthRepository
from ..security.password import PasswordService

RESET_TTL = timedelta(minutes=30)
RESET_THROTTLE = timedelta(seconds=60)
CODE_DIGITS = 6


class PasswordResetService:
    def __init__(
        self,
        repository: AuthRepository | None = None,
        password_service: PasswordService | None = None,
    ) -> None:
        self.repository = repository or AuthRepository()
        self.password_service = password_service or PasswordService()

    async def ensure_schema(self, session: AsyncSession) -> None:
        await session.execute(text("""
            CREATE TABLE IF NOT EXISTS password_reset_requests (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              tenant_id BIGINT NOT NULL,
              user_id BIGINT NOT NULL,
              email VARCHAR(254) NOT NULL,
              code_hash CHAR(64) NOT NULL,
              expires_at TIMESTAMPTZ(3) NOT NULL,
              consumed_at TIMESTAMPTZ(3),
              created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_password_reset_hash CHECK (code_hash ~ '^[0-9a-f]{64}$')
            )
        """))
        await session.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_password_reset_user_active
              ON password_reset_requests(user_id, created_at DESC)
        """))

    @staticmethod
    def hash_code(email: str, code: str) -> str:
        material = f"{email.strip().lower()}:{code}".encode("utf-8")
        return hashlib.sha256(material).hexdigest()

    async def request_reset(self, session: AsyncSession, *, email: str) -> dict[str, Any]:
        identity = await self.repository.find_by_email(session, email)
        if identity is None:
            raise BusinessError("AUTH_ACCOUNT_NOT_FOUND", "该邮箱尚未注册企业账号", status_code=404)
        if identity.role_code != "user":
            raise BusinessError(
                "AUTH_ADMIN_PORTAL_REQUIRED",
                "平台管理员请从独立管理入口联系维护人员重置密码",
                status_code=403,
            )
        if identity.tenant_status != "active":
            raise BusinessError("TENANT_SUSPENDED", "租户当前不可用", status_code=403)
        if identity.user_status != "active":
            raise BusinessError("USER_DISABLED", "用户当前不可用", status_code=403)

        latest = (
            await session.execute(
                text(
                    """
                    SELECT created_at FROM password_reset_requests
                     WHERE user_id=:user_id
                     ORDER BY created_at DESC LIMIT 1
                    """
                ),
                {"user_id": identity.user_id},
            )
        ).one_or_none()
        now = datetime.now(timezone.utc)
        if latest is not None:
            created = latest[0]
            if created.tzinfo is None:
                created = created.replace(tzinfo=timezone.utc)
            if now - created < RESET_THROTTLE:
                raise BusinessError("AUTH_RATE_LIMITED", "校验码请求过于频繁，请稍后再试", status_code=429)

        await session.execute(
            text(
                """
                UPDATE password_reset_requests
                   SET consumed_at=COALESCE(consumed_at, CURRENT_TIMESTAMP)
                 WHERE user_id=:user_id AND consumed_at IS NULL
                """
            ),
            {"user_id": identity.user_id},
        )

        code = f"{secrets.randbelow(10 ** CODE_DIGITS):0{CODE_DIGITS}d}"
        await session.execute(
            text(
                """
                INSERT INTO password_reset_requests
                  (tenant_id, user_id, email, code_hash, expires_at)
                VALUES (:tenant_id, :user_id, :email, :code_hash, :expires_at)
                """
            ),
            {
                "tenant_id": identity.tenant_id,
                "user_id": identity.user_id,
                "email": identity.email,
                "code_hash": self.hash_code(identity.email, code),
                "expires_at": now + RESET_TTL,
            },
        )
        return {
            "delivery": "on_screen",
            "reset_code": code,
            "expires_in_seconds": int(RESET_TTL.total_seconds()),
            "email": identity.email,
        }

    async def confirm_reset(
        self, session: AsyncSession, *, email: str, reset_code: str, new_password: str
    ) -> dict[str, Any]:
        identity = await self.repository.find_by_email(session, email)
        dummy_hash = self.hash_code(email, "000000")
        row = None
        if identity is not None and identity.role_code == "user":
            row = (
                await session.execute(
                    text(
                        """
                        SELECT id, code_hash, expires_at, consumed_at
                          FROM password_reset_requests
                         WHERE user_id=:user_id AND consumed_at IS NULL
                         ORDER BY created_at DESC
                         LIMIT 1
                         FOR UPDATE
                        """
                    ),
                    {"user_id": identity.user_id},
                )
            ).mappings().one_or_none()

        candidate = row["code_hash"] if row is not None else dummy_hash
        matched = secrets.compare_digest(
            candidate, self.hash_code(identity.email if identity else email, reset_code)
        )
        now = datetime.now(timezone.utc)
        expired = True
        if row is not None:
            expires = row["expires_at"]
            if expires.tzinfo is None:
                expires = expires.replace(tzinfo=timezone.utc)
            expired = expires <= now
        if identity is None or identity.role_code != "user" or row is None or not matched or expired:
            raise BusinessError("AUTH_RESET_CODE_INVALID", "校验码无效或已过期", status_code=401)

        await session.execute(
            text("UPDATE password_reset_requests SET consumed_at=CURRENT_TIMESTAMP WHERE id=:id"),
            {"id": row["id"]},
        )
        await self.repository.update_password_hash(
            session,
            user_id=identity.user_id,
            password_hash=self.password_service.hash(new_password),
        )
        await self.repository.revoke_user_sessions(
            session, user_id=identity.user_id, reason="password_reset"
        )
        return {"reset": True, "email": identity.email}

    async def admin_set_password(
        self, session: AsyncSession, *, user_id: int, new_password: str
    ) -> None:
        await self.repository.update_password_hash(
            session,
            user_id=user_id,
            password_hash=self.password_service.hash(new_password),
        )
        await self.repository.revoke_user_sessions(
            session, user_id=user_id, reason="admin_password_reset"
        )
