-- FurniScope MySQL Database Schema V1.0
-- Target: MySQL 8.0+
-- Charset: utf8mb4

CREATE DATABASE IF NOT EXISTS furniscope
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE furniscope;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =========================================================
-- A. Business master data
-- =========================================================

CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Tenant primary key',
  tenant_code VARCHAR(32) NOT NULL COMMENT 'Globally unique tenant code',
  tenant_name VARCHAR(200) NOT NULL COMMENT 'Enterprise legal/display name',
  display_name VARCHAR(100) DEFAULT NULL COMMENT 'Enterprise short name',
  industry VARCHAR(64) NOT NULL DEFAULT 'furniture_manufacturing' COMMENT 'Industry code',
  default_timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT 'IANA timezone',
  default_currency CHAR(3) NOT NULL DEFAULT 'CNY' COMMENT 'ISO 4217 currency',
  status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '0 disabled, 1 active, 2 suspended',
  data_retention_days INT UNSIGNED NOT NULL DEFAULT 365 COMMENT 'Default data retention days',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenants_code (tenant_code),
  KEY idx_tenants_status (status)
) ENGINE=InnoDB COMMENT='Enterprise tenants';

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'User primary key',
  tenant_id BIGINT UNSIGNED NOT NULL COMMENT 'Tenant ID',
  email VARCHAR(254) NOT NULL COMMENT 'Login email, normalized lowercase',
  password_hash VARCHAR(255) NOT NULL COMMENT 'Password hash; never plaintext',
  user_name VARCHAR(100) NOT NULL COMMENT 'User display name',
  phone VARCHAR(32) DEFAULT NULL COMMENT 'Phone in E.164 format',
  department VARCHAR(100) DEFAULT NULL COMMENT 'Department',
  job_title VARCHAR(100) DEFAULT NULL COMMENT 'Job title',
  role_code VARCHAR(32) NOT NULL DEFAULT 'market_ops' COMMENT 'owner/product_rd/market_ops/sales/admin',
  locale VARCHAR(16) NOT NULL DEFAULT 'zh-CN' COMMENT 'BCP 47 locale',
  timezone VARCHAR(64) DEFAULT NULL COMMENT 'IANA timezone; null inherits tenant',
  status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '0 disabled, 1 active, 2 invited, 3 locked',
  last_login_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_tenant_email (tenant_id, email),
  KEY idx_users_tenant_role_status (tenant_id, role_code, status),
  CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id)
) ENGINE=InnoDB COMMENT='System users';

CREATE TABLE IF NOT EXISTS enterprise_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  business_models JSON NOT NULL COMMENT 'B2B/B2C/OEM/ODM/brand array',
  primary_categories JSON NOT NULL COMMENT 'Primary category code array',
  export_markets JSON DEFAULT NULL COMMENT 'ISO country code array',
  sales_channels JSON DEFAULT NULL COMMENT 'Existing sales channels',
  annual_capacity_note VARCHAR(1000) DEFAULT NULL,
  profile_completeness DECIMAL(5,4) NOT NULL DEFAULT 0.0000 COMMENT '0-1',
  confirmed_by BIGINT UNSIGNED DEFAULT NULL,
  confirmed_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_enterprise_profiles_tenant (tenant_id),
  CONSTRAINT fk_enterprise_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_enterprise_profiles_confirmer FOREIGN KEY (confirmed_by) REFERENCES users (id)
) ENGINE=InnoDB COMMENT='Enterprise business profile';

CREATE TABLE IF NOT EXISTS manufacturing_capabilities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  capability_type VARCHAR(32) NOT NULL COMMENT 'category/material/process/customization/packaging/certification/delivery/equipment',
  capability_code VARCHAR(100) NOT NULL,
  capability_name VARCHAR(200) NOT NULL,
  availability TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '0 no, 1 yes, 2 unknown',
  min_value DECIMAL(18,4) DEFAULT NULL,
  max_value DECIMAL(18,4) DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  valid_from DATE DEFAULT NULL,
  valid_until DATE DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL DEFAULT 'confirmed_user',
  confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000 COMMENT '0-1',
  evidence_url VARCHAR(1000) DEFAULT NULL COMMENT 'Authorized evidence object URL/key',
  notes VARCHAR(1000) DEFAULT NULL,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_capability_tenant_type_code (tenant_id, capability_type, capability_code),
  KEY idx_capability_tenant_available (tenant_id, availability, capability_type),
  KEY idx_capability_valid_until (tenant_id, valid_until),
  CONSTRAINT fk_capability_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_capability_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_capability_range CHECK (max_value IS NULL OR min_value IS NULL OR max_value >= min_value),
  CONSTRAINT chk_capability_confidence CHECK (confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Enterprise manufacturing capabilities';

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(100) NOT NULL COMMENT 'Enterprise SKU',
  product_name VARCHAR(200) NOT NULL,
  category_code VARCHAR(100) NOT NULL DEFAULT 'sofa',
  sofa_type VARCHAR(32) DEFAULT NULL COMMENT 'standard/sectional/modular/sleeper/loveseat/recliner/other',
  lifecycle_status VARCHAR(24) NOT NULL DEFAULT 'active' COMMENT 'concept/sample/active/discontinued',
  analysis_status VARCHAR(24) NOT NULL DEFAULT 'draft' COMMENT 'draft/profile_pending/ready/archived',
  description TEXT DEFAULT NULL,
  primary_image_url VARCHAR(1000) DEFAULT NULL,
  image_urls JSON DEFAULT NULL,
  source_files JSON DEFAULT NULL COMMENT 'Authorized object keys for PDF/XLSX/images',
  factory_price DECIMAL(18,4) DEFAULT NULL COMMENT 'Sensitive factory quotation',
  factory_price_currency CHAR(3) DEFAULT NULL,
  price_term VARCHAR(16) DEFAULT NULL COMMENT 'EXW/FOB/CIF/DDP/other',
  moq INT UNSIGNED DEFAULT NULL,
  moq_unit VARCHAR(32) DEFAULT 'piece',
  lead_time_days INT UNSIGNED DEFAULT NULL,
  profile_version INT UNSIGNED NOT NULL DEFAULT 1,
  profile_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed' COMMENT 'unreviewed/confirmed/needs_fix',
  profile_completeness DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  profile_confirmed_by BIGINT UNSIGNED DEFAULT NULL,
  profile_confirmed_at DATETIME(3) DEFAULT NULL,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_products_tenant_sku (tenant_id, sku),
  KEY idx_products_tenant_category_status (tenant_id, category_code, lifecycle_status),
  KEY idx_products_tenant_analysis_status (tenant_id, analysis_status, updated_at),
  CONSTRAINT fk_products_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_products_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT fk_products_confirmer FOREIGN KEY (profile_confirmed_by) REFERENCES users (id),
  CONSTRAINT chk_products_profile_complete CHECK (profile_completeness BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Enterprise product master';

CREATE TABLE IF NOT EXISTS product_attributes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  profile_version INT UNSIGNED NOT NULL,
  attribute_code VARCHAR(100) NOT NULL,
  attribute_name VARCHAR(100) NOT NULL,
  value_type VARCHAR(16) NOT NULL COMMENT 'string/number/boolean/enum/array/range',
  attribute_value JSON DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  raw_value VARCHAR(1000) DEFAULT NULL,
  source_type VARCHAR(32) NOT NULL COMMENT 'structured_file/user_input/pdf/vision/model_inference',
  source_locator JSON DEFAULT NULL,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  confirmation_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
  is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_attr_version_code (product_id, profile_version, attribute_code),
  KEY idx_product_attr_tenant_code (tenant_id, attribute_code),
  KEY idx_product_attr_product_status (product_id, confirmation_status),
  CONSTRAINT fk_product_attr_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_product_attr_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT chk_product_attr_confidence CHECK (confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Versioned normalized product attributes';

-- =========================================================
-- B. Market and competitor business data
-- =========================================================

CREATE TABLE IF NOT EXISTS market_datasets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  dataset_name VARCHAR(200) NOT NULL,
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  platform VARCHAR(32) NOT NULL COMMENT 'amazon/wayfair/walmart/other',
  market_country CHAR(2) NOT NULL,
  marketplace_code VARCHAR(50) DEFAULT NULL,
  category_code VARCHAR(100) NOT NULL,
  data_start_date DATE DEFAULT NULL,
  data_end_date DATE NOT NULL,
  source_type VARCHAR(32) NOT NULL COMMENT 'enterprise_export/licensed_provider/public_authorized/demo_synthetic',
  source_name VARCHAR(200) NOT NULL,
  authorization_reference VARCHAR(1000) DEFAULT NULL,
  import_file_url VARCHAR(1000) DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'uploaded' COMMENT 'uploaded/validating/ready/rejected/archived',
  listing_count INT UNSIGNED NOT NULL DEFAULT 0,
  review_count INT UNSIGNED NOT NULL DEFAULT 0,
  valid_review_count INT UNSIGNED NOT NULL DEFAULT 0,
  quality_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  quality_report JSON DEFAULT NULL,
  limitations JSON DEFAULT NULL,
  created_by BIGINT UNSIGNED DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_dataset_tenant_name_version (tenant_id, dataset_name, version_no),
  KEY idx_dataset_tenant_market_status (tenant_id, platform, market_country, status),
  KEY idx_dataset_category_date (tenant_id, category_code, data_end_date),
  CONSTRAINT fk_dataset_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_dataset_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_dataset_quality CHECK (quality_score BETWEEN 0 AND 100),
  CONSTRAINT chk_dataset_counts CHECK (valid_review_count <= review_count)
) ENGINE=InnoDB COMMENT='Versioned market data imports';

CREATE TABLE IF NOT EXISTS competitor_listings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  dataset_id BIGINT UNSIGNED NOT NULL,
  platform_listing_id VARCHAR(200) NOT NULL COMMENT 'ASIN or platform item ID',
  listing_url VARCHAR(1000) DEFAULT NULL,
  brand VARCHAR(200) DEFAULT NULL,
  seller_name VARCHAR(200) DEFAULT NULL,
  title TEXT NOT NULL,
  description MEDIUMTEXT DEFAULT NULL,
  bullet_points JSON DEFAULT NULL,
  category_raw VARCHAR(300) DEFAULT NULL,
  category_code VARCHAR(100) NOT NULL,
  image_urls JSON DEFAULT NULL,
  normalized_attributes JSON DEFAULT NULL COMMENT 'Denormalized attributes for Demo queries',
  feature_codes JSON DEFAULT NULL COMMENT 'Normalized selling point codes',
  currency CHAR(3) NOT NULL,
  list_price DECIMAL(18,4) DEFAULT NULL,
  sale_price DECIMAL(18,4) NOT NULL,
  coupon_info JSON DEFAULT NULL,
  rating DECIMAL(3,2) DEFAULT NULL,
  rating_count INT UNSIGNED DEFAULT NULL,
  review_count INT UNSIGNED DEFAULT NULL,
  rank_value INT UNSIGNED DEFAULT NULL,
  rank_category VARCHAR(300) DEFAULT NULL,
  sales_value DECIMAL(18,4) DEFAULT NULL,
  sales_value_type VARCHAR(16) DEFAULT NULL COMMENT 'actual/estimated/proxy',
  sales_period VARCHAR(16) DEFAULT NULL,
  first_available_at DATETIME(3) DEFAULT NULL,
  availability_status VARCHAR(24) DEFAULT 'unknown',
  observed_at DATETIME(3) NOT NULL,
  raw_payload JSON DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_listing_dataset_platform_observed (dataset_id, platform_listing_id, observed_at),
  KEY idx_listing_dataset_price (dataset_id, sale_price),
  KEY idx_listing_dataset_brand (dataset_id, brand),
  KEY idx_listing_dataset_rating (dataset_id, rating, review_count),
  KEY idx_listing_tenant_category_time (tenant_id, category_code, observed_at),
  CONSTRAINT fk_listing_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_listing_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT chk_listing_price CHECK (sale_price >= 0),
  CONSTRAINT chk_listing_rating CHECK (rating IS NULL OR rating BETWEEN 0 AND 5)
) ENGINE=InnoDB COMMENT='Competitor platform listing snapshots';

CREATE TABLE IF NOT EXISTS competitor_reviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  dataset_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  platform_review_id VARCHAR(200) DEFAULT NULL,
  rating DECIMAL(3,2) NOT NULL,
  review_title TEXT DEFAULT NULL,
  body_original MEDIUMTEXT NOT NULL,
  language VARCHAR(16) NOT NULL DEFAULT 'und',
  body_translated_zh MEDIUMTEXT DEFAULT NULL,
  reviewed_at DATETIME(3) DEFAULT NULL,
  verified_purchase TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '0 no, 1 yes, 2 unknown',
  helpful_votes INT UNSIGNED DEFAULT NULL,
  variant_info JSON DEFAULT NULL,
  is_duplicate TINYINT(1) NOT NULL DEFAULT 0,
  is_spam TINYINT(1) NOT NULL DEFAULT 0,
  is_valid TINYINT(1) NOT NULL DEFAULT 1,
  invalid_reason VARCHAR(64) DEFAULT NULL,
  content_hash CHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_review_dataset_hash (dataset_id, content_hash),
  KEY idx_review_listing_valid_time (listing_id, is_valid, reviewed_at),
  KEY idx_review_dataset_rating_valid (dataset_id, rating, is_valid),
  KEY idx_review_tenant_language (tenant_id, language),
  CONSTRAINT fk_review_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_review_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT fk_review_listing FOREIGN KEY (listing_id) REFERENCES competitor_listings (id),
  CONSTRAINT chk_review_rating CHECK (rating BETWEEN 0 AND 5)
) ENGINE=InnoDB COMMENT='Competitor customer reviews';

-- =========================================================
-- C. Task and AI intermediate data
-- =========================================================

CREATE TABLE IF NOT EXISTS analysis_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_uuid CHAR(36) NOT NULL COMMENT 'Externally exposed task UUID',
  tenant_id BIGINT UNSIGNED NOT NULL,
  task_name VARCHAR(200) NOT NULL,
  task_type VARCHAR(32) NOT NULL DEFAULT 'product_market_fit',
  product_id BIGINT UNSIGNED NOT NULL,
  product_profile_version INT UNSIGNED NOT NULL,
  dataset_id BIGINT UNSIGNED NOT NULL,
  target_country CHAR(2) NOT NULL,
  target_platform VARCHAR(32) NOT NULL,
  analysis_currency CHAR(3) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  current_stage VARCHAR(32) NOT NULL DEFAULT 'draft',
  progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  ontology_version VARCHAR(64) NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  prompt_bundle_version VARCHAR(64) NOT NULL,
  analysis_config JSON DEFAULT NULL COMMENT 'Frozen thresholds and filters',
  sample_listing_count INT UNSIGNED NOT NULL DEFAULT 0,
  sample_review_count INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME(3) DEFAULT NULL,
  completed_at DATETIME(3) DEFAULT NULL,
  failure_code VARCHAR(100) DEFAULT NULL,
  failure_message VARCHAR(1000) DEFAULT NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_analysis_tasks_uuid (task_uuid),
  KEY idx_task_tenant_status_created (tenant_id, status, created_at),
  KEY idx_task_product_created (tenant_id, product_id, created_at),
  KEY idx_task_dataset_status (dataset_id, status),
  CONSTRAINT fk_task_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_task_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_task_dataset FOREIGN KEY (dataset_id) REFERENCES market_datasets (id),
  CONSTRAINT fk_task_creator FOREIGN KEY (created_by) REFERENCES users (id),
  CONSTRAINT chk_task_progress CHECK (progress_percent BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='Market AI analysis tasks';

CREATE TABLE IF NOT EXISTS task_stage_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  stage_code VARCHAR(32) NOT NULL,
  attempt_no INT UNSIGNED NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued',
  input_ref JSON NOT NULL,
  output_ref JSON DEFAULT NULL,
  started_at DATETIME(3) DEFAULT NULL,
  ended_at DATETIME(3) DEFAULT NULL,
  error_code VARCHAR(100) DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  retryable TINYINT(1) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_stage_idempotency (idempotency_key),
  UNIQUE KEY uk_stage_task_code_attempt (task_id, stage_code, attempt_no),
  KEY idx_stage_task_status (task_id, status, stage_code),
  CONSTRAINT fk_stage_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id)
) ENGINE=InnoDB COMMENT='Analysis task workflow stage runs';

CREATE TABLE IF NOT EXISTS ai_model_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  stage_run_id BIGINT UNSIGNED DEFAULT NULL,
  provider VARCHAR(100) NOT NULL DEFAULT 'aliyun_model_router',
  model_id VARCHAR(200) NOT NULL,
  task_type VARCHAR(32) NOT NULL COMMENT 'vision_extract/text_extract/translate/embed/rerank/reason/report',
  prompt_code VARCHAR(100) DEFAULT NULL,
  prompt_version VARCHAR(64) DEFAULT NULL,
  input_hash CHAR(64) NOT NULL,
  output_schema_version VARCHAR(64) DEFAULT NULL,
  input_tokens INT UNSIGNED DEFAULT NULL,
  output_tokens INT UNSIGNED DEFAULT NULL,
  image_count INT UNSIGNED NOT NULL DEFAULT 0,
  latency_ms INT UNSIGNED NOT NULL DEFAULT 0,
  estimated_cost DECIMAL(18,8) DEFAULT NULL,
  cost_unit VARCHAR(16) DEFAULT NULL COMMENT 'CNY/USD/credit',
  status VARCHAR(24) NOT NULL,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  schema_valid TINYINT(1) DEFAULT NULL,
  error_code VARCHAR(100) DEFAULT NULL,
  error_message VARCHAR(1000) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_model_run_task_type (task_id, task_type, status),
  KEY idx_model_run_model_time (model_id, created_at),
  KEY idx_model_run_stage (stage_run_id),
  CONSTRAINT fk_model_run_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_model_run_stage FOREIGN KEY (stage_run_id) REFERENCES task_stage_runs (id)
) ENGINE=InnoDB COMMENT='AI model invocation logs and cost metrics';

CREATE TABLE IF NOT EXISTS competitor_matches (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  listing_id BIGINT UNSIGNED NOT NULL,
  competitor_type VARCHAR(16) NOT NULL DEFAULT 'direct' COMMENT 'direct/benchmark/substitute/excluded',
  category_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  function_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  style_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  price_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  material_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  scenario_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  overall_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  rerank_score DECIMAL(10,8) DEFAULT NULL,
  match_reasons JSON NOT NULL,
  review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  review_note VARCHAR(1000) DEFAULT NULL,
  reviewed_by BIGINT UNSIGNED DEFAULT NULL,
  reviewed_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_match_task_listing (task_id, listing_id),
  KEY idx_match_task_type_score (task_id, competitor_type, overall_score),
  KEY idx_match_task_review (task_id, review_status),
  CONSTRAINT fk_match_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_match_listing FOREIGN KEY (listing_id) REFERENCES competitor_listings (id),
  CONSTRAINT fk_match_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
) ENGINE=InnoDB COMMENT='Task-specific competitor matching and human review';

CREATE TABLE IF NOT EXISTS review_aspects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  review_id BIGINT UNSIGNED NOT NULL,
  aspect_index INT UNSIGNED NOT NULL,
  taxonomy_code VARCHAR(150) NOT NULL,
  product_attribute_code VARCHAR(100) DEFAULT NULL,
  opinion_text VARCHAR(1000) NOT NULL,
  sentiment VARCHAR(16) NOT NULL COMMENT 'positive/negative/neutral/mixed',
  severity TINYINT UNSIGNED DEFAULT NULL COMMENT '1-5 for negative aspects',
  user_profile_codes JSON DEFAULT NULL,
  usage_scenario_codes JSON DEFAULT NULL,
  purchase_driver TINYINT(1) NOT NULL DEFAULT 0,
  evidence_start INT UNSIGNED NOT NULL,
  evidence_end INT UNSIGNED NOT NULL,
  evidence_quote VARCHAR(2000) NOT NULL,
  extraction_confidence DECIMAL(5,4) NOT NULL,
  embedding JSON DEFAULT NULL COMMENT 'Demo storage; production may use vector DB',
  model_run_id BIGINT UNSIGNED NOT NULL,
  validation_status VARCHAR(24) NOT NULL DEFAULT 'unreviewed',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_aspect_task_review_index (task_id, review_id, aspect_index),
  KEY idx_aspect_task_taxonomy_sentiment (task_id, taxonomy_code, sentiment),
  KEY idx_aspect_task_severity (task_id, sentiment, severity),
  KEY idx_aspect_review (review_id),
  CONSTRAINT fk_aspect_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_aspect_review FOREIGN KEY (review_id) REFERENCES competitor_reviews (id),
  CONSTRAINT fk_aspect_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT chk_aspect_confidence CHECK (extraction_confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_aspect_severity CHECK (severity IS NULL OR severity BETWEEN 1 AND 5),
  CONSTRAINT chk_aspect_span CHECK (evidence_end > evidence_start)
) ENGINE=InnoDB COMMENT='Aspect-level AI extraction from competitor reviews';

CREATE TABLE IF NOT EXISTS insight_clusters (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  cluster_no INT UNSIGNED NOT NULL,
  cluster_name VARCHAR(200) NOT NULL,
  taxonomy_code VARCHAR(150) NOT NULL,
  sentiment VARCHAR(16) NOT NULL,
  aspect_count INT UNSIGNED NOT NULL,
  review_count INT UNSIGNED NOT NULL,
  listing_count INT UNSIGNED NOT NULL,
  mention_rate DECIMAL(7,6) NOT NULL,
  mention_denominator_type VARCHAR(32) NOT NULL COMMENT 'valid_reviews/negative_aspects/all_aspects',
  cross_listing_rate DECIMAL(7,6) NOT NULL,
  avg_severity DECIMAL(4,2) DEFAULT NULL,
  freshness_score DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  importance_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  cluster_confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  representative_aspect_ids JSON DEFAULT NULL,
  algorithm_version VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_cluster_task_no (task_id, cluster_no),
  KEY idx_cluster_task_importance (task_id, importance_score),
  KEY idx_cluster_task_taxonomy (task_id, taxonomy_code, sentiment),
  CONSTRAINT fk_cluster_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_cluster_mention_rate CHECK (mention_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_cluster_cross_rate CHECK (cross_listing_rate BETWEEN 0 AND 1),
  CONSTRAINT chk_cluster_confidence CHECK (cluster_confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Aggregated user need and pain-point clusters';

CREATE TABLE IF NOT EXISTS cluster_members (
  cluster_id BIGINT UNSIGNED NOT NULL,
  aspect_id BIGINT UNSIGNED NOT NULL,
  distance DECIMAL(12,10) NOT NULL DEFAULT 0.0000000000,
  is_representative TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (cluster_id, aspect_id),
  KEY idx_cluster_members_aspect (aspect_id),
  CONSTRAINT fk_cluster_member_cluster FOREIGN KEY (cluster_id) REFERENCES insight_clusters (id),
  CONSTRAINT fk_cluster_member_aspect FOREIGN KEY (aspect_id) REFERENCES review_aspects (id)
) ENGINE=InnoDB COMMENT='Membership between insight clusters and review aspects';

-- =========================================================
-- D. Result and output data
-- =========================================================

CREATE TABLE IF NOT EXISTS market_opportunities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  opportunity_code VARCHAR(50) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  target_country CHAR(2) NOT NULL,
  target_platform VARCHAR(32) NOT NULL,
  target_user_codes JSON DEFAULT NULL,
  usage_scenario_codes JSON DEFAULT NULL,
  primary_cluster_ids JSON NOT NULL,
  price_band_min DECIMAL(18,4) DEFAULT NULL,
  price_band_max DECIMAL(18,4) DEFAULT NULL,
  price_currency CHAR(3) DEFAULT NULL,
  demand_heat_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  demand_growth_score DECIMAL(5,2) DEFAULT NULL,
  unmet_need_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  competition_space_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  profit_space_score DECIMAL(5,2) DEFAULT NULL,
  enterprise_fit_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  overall_score DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  recommendation_level VARCHAR(32) NOT NULL,
  capability_gaps JSON DEFAULT NULL,
  weight_config JSON NOT NULL,
  scoring_version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'generated',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_opportunity_task_code (task_id, opportunity_code),
  KEY idx_opportunity_task_score (task_id, overall_score, confidence),
  KEY idx_opportunity_task_status (task_id, status),
  CONSTRAINT fk_opportunity_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_opportunity_score CHECK (overall_score BETWEEN 0 AND 100),
  CONSTRAINT chk_opportunity_confidence CHECK (confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Market opportunities with denormalized six-dimension scores';

CREATE TABLE IF NOT EXISTS product_recommendations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  opportunity_id BIGINT UNSIGNED NOT NULL,
  recommendation_type VARCHAR(24) NOT NULL,
  problem_statement TEXT NOT NULL,
  root_cause_hypotheses JSON NOT NULL,
  recommended_action TEXT NOT NULL,
  target_attribute_code VARCHAR(100) DEFAULT NULL,
  target_value JSON DEFAULT NULL,
  expected_benefit TEXT NOT NULL,
  impact_dimensions JSON NOT NULL,
  cost_impact_min DECIMAL(18,4) DEFAULT NULL,
  cost_impact_max DECIMAL(18,4) DEFAULT NULL,
  cost_currency CHAR(3) DEFAULT NULL,
  priority VARCHAR(16) NOT NULL COMMENT 'high/medium/low',
  confidence DECIMAL(5,4) NOT NULL,
  validation_method TEXT NOT NULL,
  evidence_cluster_ids JSON NOT NULL,
  expert_review_status VARCHAR(24) NOT NULL DEFAULT 'pending',
  expert_review_note VARCHAR(2000) DEFAULT NULL,
  reviewed_by BIGINT UNSIGNED DEFAULT NULL,
  reviewed_at DATETIME(3) DEFAULT NULL,
  model_run_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_recommendation_task_priority (task_id, priority, expert_review_status),
  KEY idx_recommendation_opportunity (opportunity_id),
  CONSTRAINT fk_recommendation_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_recommendation_opportunity FOREIGN KEY (opportunity_id) REFERENCES market_opportunities (id),
  CONSTRAINT fk_recommendation_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id),
  CONSTRAINT fk_recommendation_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT chk_recommendation_confidence CHECK (confidence BETWEEN 0 AND 1),
  CONSTRAINT chk_recommendation_cost CHECK (cost_impact_max IS NULL OR cost_impact_min IS NULL OR cost_impact_max >= cost_impact_min)
) ENGINE=InnoDB COMMENT='AI product improvement recommendations with expert review';

CREATE TABLE IF NOT EXISTS evidence_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_id BIGINT UNSIGNED NOT NULL,
  claim_type VARCHAR(32) NOT NULL COMMENT 'opportunity/recommendation/report/score',
  claim_id BIGINT UNSIGNED NOT NULL,
  claim_category VARCHAR(24) NOT NULL COMMENT 'observation/inference/recommendation/validation_required',
  evidence_type VARCHAR(32) NOT NULL COMMENT 'review_aspect/listing/cluster/metric/product_attribute/capability/expert_feedback',
  evidence_id BIGINT UNSIGNED NOT NULL,
  support_type VARCHAR(16) NOT NULL DEFAULT 'supports' COMMENT 'supports/contradicts/context/limitation',
  relevance_score DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  display_order INT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_evidence_claim_item (claim_type, claim_id, evidence_type, evidence_id),
  KEY idx_evidence_task_claim (task_id, claim_type, claim_id, display_order),
  KEY idx_evidence_reverse (evidence_type, evidence_id),
  CONSTRAINT fk_evidence_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT chk_evidence_relevance CHECK (relevance_score BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Polymorphic evidence chain for all AI conclusions';

CREATE TABLE IF NOT EXISTS analysis_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_uuid CHAR(36) NOT NULL,
  tenant_id BIGINT UNSIGNED NOT NULL,
  task_id BIGINT UNSIGNED NOT NULL,
  report_version INT UNSIGNED NOT NULL DEFAULT 1,
  title VARCHAR(300) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft' COMMENT 'draft/human_review/published/superseded',
  executive_summary MEDIUMTEXT NOT NULL,
  decision_recommendation VARCHAR(32) NOT NULL,
  overall_opportunity_score DECIMAL(5,2) NOT NULL,
  overall_confidence DECIMAL(5,4) NOT NULL,
  data_scope_summary JSON NOT NULL,
  product_profile_snapshot JSON NOT NULL,
  competitor_summary JSON DEFAULT NULL,
  user_need_summary JSON DEFAULT NULL,
  price_summary JSON DEFAULT NULL,
  opportunity_summary JSON NOT NULL,
  recommendation_summary JSON NOT NULL,
  risk_summary JSON NOT NULL,
  pending_validation_items JSON NOT NULL,
  generated_model_run_id BIGINT UNSIGNED NOT NULL,
  published_by BIGINT UNSIGNED DEFAULT NULL,
  published_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_reports_uuid (report_uuid),
  UNIQUE KEY uk_reports_task_version (task_id, report_version),
  KEY idx_reports_tenant_status_time (tenant_id, status, created_at),
  KEY idx_reports_task_status (task_id, status),
  CONSTRAINT fk_report_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_report_task FOREIGN KEY (task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_report_model_run FOREIGN KEY (generated_model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT fk_report_publisher FOREIGN KEY (published_by) REFERENCES users (id),
  CONSTRAINT chk_report_score CHECK (overall_opportunity_score BETWEEN 0 AND 100),
  CONSTRAINT chk_report_confidence CHECK (overall_confidence BETWEEN 0 AND 1)
) ENGINE=InnoDB COMMENT='Versioned market opportunity reports';

CREATE TABLE IF NOT EXISTS listing_generation_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  source_task_id BIGINT UNSIGNED DEFAULT NULL COMMENT 'Optional market insight task source',
  target_platform VARCHAR(32) NOT NULL,
  target_country CHAR(2) NOT NULL,
  language VARCHAR(16) NOT NULL,
  generation_type VARCHAR(32) NOT NULL COMMENT 'title/bullets/description/keywords/full_listing',
  input_snapshot JSON NOT NULL,
  generated_title TEXT DEFAULT NULL,
  generated_bullets JSON DEFAULT NULL,
  generated_description MEDIUMTEXT DEFAULT NULL,
  generated_keywords JSON DEFAULT NULL,
  compliance_warnings JSON DEFAULT NULL,
  model_run_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'generated' COMMENT 'generated/reviewed/approved/rejected',
  reviewed_by BIGINT UNSIGNED DEFAULT NULL,
  reviewed_at DATETIME(3) DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_listing_gen_product_time (tenant_id, product_id, created_at),
  KEY idx_listing_gen_task (source_task_id),
  KEY idx_listing_gen_status (tenant_id, status, target_platform),
  CONSTRAINT fk_listing_gen_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_listing_gen_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT fk_listing_gen_task FOREIGN KEY (source_task_id) REFERENCES analysis_tasks (id),
  CONSTRAINT fk_listing_gen_model_run FOREIGN KEY (model_run_id) REFERENCES ai_model_runs (id),
  CONSTRAINT fk_listing_gen_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id)
) ENGINE=InnoDB COMMENT='Optional generated listing records; post-MVP extension';

CREATE TABLE IF NOT EXISTS report_exports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  report_id BIGINT UNSIGNED NOT NULL,
  export_format VARCHAR(16) NOT NULL COMMENT 'pdf/docx/xlsx/json',
  file_url VARCHAR(1000) DEFAULT NULL COMMENT 'Authorized object key or URL',
  file_size_bytes BIGINT UNSIGNED DEFAULT NULL,
  file_hash CHAR(64) DEFAULT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'queued' COMMENT 'queued/generating/succeeded/failed/expired',
  error_message VARCHAR(1000) DEFAULT NULL,
  requested_by BIGINT UNSIGNED NOT NULL,
  requested_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at DATETIME(3) DEFAULT NULL,
  expires_at DATETIME(3) DEFAULT NULL,
  download_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_downloaded_at DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_export_report_status (report_id, status, requested_at),
  KEY idx_export_tenant_time (tenant_id, requested_at),
  CONSTRAINT fk_export_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_export_report FOREIGN KEY (report_id) REFERENCES analysis_reports (id),
  CONSTRAINT fk_export_requester FOREIGN KEY (requested_by) REFERENCES users (id)
) ENGINE=InnoDB COMMENT='Asynchronous report export records';

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED DEFAULT NULL,
  actor_id BIGINT UNSIGNED DEFAULT NULL,
  action VARCHAR(32) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id BIGINT UNSIGNED DEFAULT NULL,
  before_snapshot JSON DEFAULT NULL,
  after_snapshot JSON DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  user_agent VARCHAR(512) DEFAULT NULL,
  occurred_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_audit_tenant_time (tenant_id, occurred_at),
  KEY idx_audit_resource (resource_type, resource_id, occurred_at),
  KEY idx_audit_actor_time (actor_id, occurred_at),
  CONSTRAINT fk_audit_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id),
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users (id)
) ENGINE=InnoDB COMMENT='Sensitive operation audit trail';

SET FOREIGN_KEY_CHECKS = 1;
